### ISSUE TITLE
Use of MA_RESERVED1 breaks on recent Solaris builds

### ISSUE THREAD

**Issue by dhduvall** [giampaolo/psutil#1002]
This is against internal-to-Oracle Solaris, but recently `MA_RESERVED1` was renamed to `MA_CORE_NODATA`, as that value was given a specific use.  Currently, psutil translates that flag to `*`, but I can't find any documentation on what that's supposed to mean.  The documentation for the perms field in /proc/pid/maps in proc(5) only talks about `r`, `w`, `x`, `s`, and `p`, and not `R` and `*` as are also used in `_psutil_sunos.c`.  Since `MA_RESERVED1` was never used for anything (at least, not in recent memory), it's not clear that the `*` meant anything either, and it probably should just be dropped.  I can whip up a pull request for that, if desired.

**Comment by giampaolo** [comment]
What are you talking about? lol

**Comment by dhduvall** [comment]
`_psutil_sunos.c` references the macro `MA_RESERVED1`, which is going away in the next release of Solaris (and has already gone away in our internal builds).  The symbol it maps to isn't, to my knowledge, documented anywhere with any meaning, and I wanted to be sure of that before submitting a pull request to remove the reference to that macro.

**Comment by giampaolo** [comment]
Oh I get it now. Yeah, I think you can freely remove both "R" and "*". I don't remember where I got that from.
