### ISSUE TITLE
Can't compile on macOs because of 'features.h' file not found

### ISSUE THREAD

**Issue by leftis** [giampaolo/psutil#1005]
`os: macOs Sierra`
`python: 2.7 from homebrew`

Tried 

`pip install psutil` & `make install` from source result is the same 

https://gist.github.com/leftis/55766dc90bcb21aa6a98e04e7a998285

Any help appreciated thanks.

**Comment by leftis** [comment]
Actually utmpx.h is missing from my mac that calls features.h

**Comment by giampaolo** [comment]
Not sure why that happens but it looks like you're not alone: https://www.google.it/search?sourceid=chrome-psyapi2&ion=1&espv=2&ie=UTF-8&q=osx%20utmpx%20fatal%20error%3A%20%27features.h%27%20file%20not%20found&oq=osx%20utmpx%20fatal%20error%3A%20%27features.h%27%20file%20not%20found&aqs=chrome..69i57.3661j0j7
