### ISSUE TITLE
include pid entry into psutil.users()

### ISSUE THREAD

**Issue by alexanha** [giampaolo/psutil#1022]
Hi,

I need to have another entry ``'pid'=...`` in the output of ``psutil.users()``. As a proposal I uploaded a patch to [users_pid.txt](https://github.com/giampaolo/psutil/files/956232/users_pid.txt) with a solution I tested under Linux.

Cheers,
Alex

**Comment by giampaolo** [comment]
Oh nice, this looks useful. Patch does not apply cleanly though. 
Could you either provide an updated patch or a PR?
