### ISSUE TITLE
psutil doesn’t build on FreeBSD 11

### ISSUE THREAD

**Issue by interkosmos** [giampaolo/psutil#1045]
Trying `pypy3 -m pip install psutil`:

```
    [...]
    running build_ext
    building 'psutil._psutil_bsd' extension
    creating build/temp.freebsd-11.0-RELEASE-p8-amd64-3.5
    creating build/temp.freebsd-11.0-RELEASE-p8-amd64-3.5/psutil
    creating build/temp.freebsd-11.0-RELEASE-p8-amd64-3.5/psutil/arch
    creating build/temp.freebsd-11.0-RELEASE-p8-amd64-3.5/psutil/arch/bsd
    gcc -pthread -DNDEBUG -O2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_BSD=1 -DPSUTIL_VERSION=522 -DPSUTIL_FREEBSD=1 -I/usr/local/pypy3-5.7/include -c psutil/_psutil_bsd.c -o build/temp.freebsd-11.0-RELEASE-p8-amd64-3.5/psutil/_psutil_bsd.o
    psutil/_psutil_bsd.c: In function 'psutil_proc_oneshot_info':
    psutil/_psutil_bsd.c:289:9: internal compiler error: Illegal instruction
             PSUTIL_TV2DOUBLE(kp.ki_start),   // (double) create time
             ^
    no stack trace because unwind library not available
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <http://gcc.gnu.org/bugs.html> for instructions.
    error: command 'gcc' failed with exit status 1  
```

I used GCC 4.9 as well as 5.4.

**Comment by interkosmos** [comment]
I have tried it again with GCC 4.6 – and now it works.

**Comment by giampaolo** [comment]
Wow that's fu**ed up. A compiler not providing a stack trace?

**Comment by interkosmos** [comment]
See next error above.

**Comment by giampaolo** [comment]
That means you need to install Python headers. Perhaps `pkg install python-dev`?

**Comment by interkosmos** [comment]
It seems that there are no Python headers for PyPy 5.7 available for FreeBSD. At least, they are not installed to `/usr/local/include/`.

**Comment by interkosmos** [comment]
The header files are stored in `/usr/local/pypy3-5.7/include`. So, yeah, I have them.

**Comment by giampaolo** [comment]
Mmm that says `pypy` though, not `python`.

**Comment by interkosmos** [comment]
Yes, as I have written in the original post. On Python 3.6, `psutils` just works without any problems on FreeBSD 11. These errors only encounter with PyPy 5.7.

**Comment by giampaolo** [comment]
Ah sorry, I didn't notice you were using pypy. Then this is a duplicate of #853. psutil does not work on pypy3 because pypy3 does not implement `PyModule_GetState`.

**Comment by interkosmos** [comment]
Ok, thank you very much for this notice.

**Comment by giampaolo** [comment]
https://mail.python.org/pipermail/pypy-dev/2017-May/015135.html
