### ISSUE TITLE
Drop Python 2.6 support in unit tests and scripts, deprecate it in psutil

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#1053]
Maintaining Python 2.6 support is a pain in the butt from a CI / testing perspective for a variety of reason (unittest2, a specific version of mock, setuptools, etc.). Also, both [pip](https://github.com/pypa/pip/issues/3955) and [setuptools](https://github.com/pypa/setuptools/issues/878) dropped support for 2.6, so installing psutil on 2.6 is becoming harder (although still possible). For these reasons I would like to drop python 2.6 for tests only.

There is an argument for **not** dropping 2.6 support in psutil "as a lib" (so excluding tests) yet: CentOS 6. CentOS 6 still ships 2.6 by default and AFAIK it is still in use on a non negligible number of servers (unfortunately). Being psutil a "system library" I am kind of worried about that so I think it'd be nice to keep support for a little while longer and just deprecate it by issuing a warning on import. 

CentOS 6 EOL is scheduled for November 2020. I am not sure I want to maintain support 'till then, but the point is that there currently are no 2.7-only features such as set literals, set/dict comprehensions, multiple ctx managers or OrderedDict which I may want to use in psutil code, so why break it? 

On the other hand, some of those 2.7-only features may be used in the test suite (e.g. replace `contextlib.nexted` with multiple ctx managers). As far as 2.6 goes I would still like travis to test it by installing psutil on 2.6 and import it (that's it), but the test suite will not be run. 
At the same time, `setup.py` may print a warning telling that 2.6 is supported but not testable.

As for scripts (/scripts dir): we can also drop support (and e.g. be free to use the `argparse` module).

TODOs:

* drop 2.6 support in unit tests and scritps
* deprecate 2.6 support in psutil by issuing a deprecation warning

**Comment by hugovk** [comment]
Here's the pip installs for psutil from PyPI for the last month, showing relatively low numbers for 2.6.

```
$ pypinfo --percent --pip psutil pyversion
python_version percent download_count
-------------- ------- --------------
2.7              87.1%      2,389,860
3.5               5.9%        161,854
3.6               4.1%        113,205
3.4               1.7%         47,173
2.6               1.1%         30,921
3.3               0.0%          1,240
3.7               0.0%            573
3.2               0.0%             40
None              0.0%             13
2.8               0.0%             11

```

Python 3.3 also went EOL and has even lower numbers, so you could consider dropping that too. However, there's not as great a benefit as in dropping 2.6.

**Comment by giampaolo** [comment]
Thanks a lot for this. I will definitively drop support for 3.3 as well then. I had no idea download numbers were so big.

**Comment by hugovk** [comment]
psutil was the 42nd most-pip-installed from PyPI over the last month!

```
$ pypinfo --limit 50 "" project
project         download_count
--------------- --------------
simplejson          23,078,938
six                 19,041,813
botocore            15,899,209
python-dateutil     15,430,094
setuptools          14,958,714
pip                 14,831,254
pyyaml              13,845,784
pyasn1              13,394,480
s3transfer          13,238,510
requests            13,192,679
futures             13,108,981
docutils            13,098,192
jmespath            12,148,874
awscli              11,265,646
wheel               11,065,452
rsa                 10,926,175
colorama            10,395,206
idna                 8,962,018
certifi              8,434,862
urllib3              7,975,828
chardet              7,069,936
awscli-cwlogs        6,730,363
cffi                 5,673,479
pbr                  5,630,646
virtualenv           5,384,684
pytz                 4,874,941
boto3                4,746,767
markupsafe           4,739,582
jinja2               4,735,081
pycparser            4,699,732
cryptography         4,364,089
setuptools-scm       4,297,094
enum34               4,212,387
asn1crypto           3,523,116
ipaddress            3,431,710
boto                 3,399,856
decorator            3,065,377
lxml                 3,039,605
pytest-runner        3,000,335
numpy                2,920,002
pyparsing            2,902,246
psutil               2,892,245
click                2,834,914
pyopenssl            2,709,848
argparse             2,658,687
flask                2,553,760
future               2,494,573
werkzeug             2,418,321
tornado              2,354,768
mock                 2,306,457
```

**Comment by mayeut** [comment]
Stats from last month:
```
$ pypinfo --percent psutil pyversion
| python_version | percent | download_count |
| -------------- | ------- | -------------- |
| 3.7            |  30.58% |      6,453,415 |
| 3.8            |  28.27% |      5,965,917 |
| 3.6            |  24.25% |      5,118,593 |
| 2.7            |   9.41% |      1,985,177 |
| 3.9            |   4.35% |        918,440 |
| 3.5            |   3.07% |        647,434 |
| 3.4            |   0.04% |          8,518 |
| 2.6            |   0.02% |          3,904 |
| 3.10           |   0.01% |          2,384 |
| 3.3            |   0.00% |             64 |
| Total          |         |     21,103,846 |
```
