### ISSUE TITLE
proc.as_dict() memory leak

### ISSUE THREAD

**Issue by tomasrasymas** [giampaolo/psutil#1054]
I have script that runs every few seconds, and noticed that after 24 hours of work python script uses +- 470 mb of ram. Created sample script (below) and on script start memory usage +-6.5 mb, after 5 min of work memory usage rises up to +- 9 mb, after 5 min. rises to 12 mb and so on...

OS: Windows 10 HOME, 64 bit.
psutil: 5.3.0 version (just yesterday pulled from github)
python: 2.7

```
import psutil

while True:
    for proc in psutil.process_iter():
        try:
            proc.as_dict()
        except psutil.NoSuchProcess:
            print "error"

    print "iteration"
```

**Comment by giampaolo** [comment]
`as_dict` retrieves all process info so it really doesn't tell which function exactly has the memory leak. You should try with individual functions such as `proc.connections()`, `proc.exe()` and so on.

**Comment by giampaolo** [comment]
Also ,you could try to get latest version from GIT then run "`make test-memleaks"` and see what happens. I currently don't get failures on Windows 10, Python 2.7. Sometimes it can give false positives though, but it doesn't mean there's a leak.

**Comment by tomasrasymas** [comment]
test-memleaks shows that everything is fine. Will try to look for a function that might leak memory manually.

**Comment by giampaolo** [comment]
Closing this out for now. I believe there is no memory leak.
