### ISSUE TITLE
MANIFEST.in wisely include only revisioned files

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#1060]
MANIFEST.in controls what files will end up in the source tar.gz distribution on `python setup.py sdist`. Right now MANIFEST.in is a static file edited manually which doesn't take into account about whether files are added, removed or moved via GIT. It also doesn't take into account files which may be in the working dir but are not under revision control. As such it'd be better to have a dynamic `make generate-manifest` command which uses `git ls-files` to get a list of all files under revision control and writes them in MANIFEST.in.
This way we'll be certain the tar.gz distribution has no extraneous or missing files.

**Comment by SethMichaelLarson** [comment]
You could also check out [this project](https://pypi.python.org/pypi/check-manifest) which compares your MANIFEST.in against your VCS.

**Comment by giampaolo** [comment]
Yup, I already use it in psutil but thanks anyway.
