### ISSUE TITLE
Slow response time of psutil Process Iter

### ISSUE THREAD

**Issue by ajikumarmp** [giampaolo/psutil#1061]
Hi, 

I have used PSUTIL for solving a problem where I wanted to check if my application is already running on windows. I used the code below and that works but I see that I get response almost a minute or mote later, this I felt is too much time, are there any other methods by which this can be done faster or any other suggestions to get a faster result?

```
def listprocessRunning():
    for proc in psutil.process_iter():
        try:
            #print "Process Names", proc.name()
            if proc.name() == "MY APP":
                print "My APP is running"
        except (psutil.NoSuchProcess, psutil.AccessDenied) as e:
            print " Permission error and cannot access"
```

**Comment by giampaolo** [comment]
1 minute? That's very weird by just getting the process name(), unless you have milions of processes running.

**Comment by ajikumarmp** [comment]
That is true, I just used a stop watch to verify that and I clocked 58
seconds, this was run on PC that had multiple users accounts.
I did try to run this on my laptop which is a single user and to my
surprise I got results in 2 seconds.

I then checked the no of process running and found that multi user PC only
had 11 more process running. Can you think of any potential causes because
of the need to run through multiple user accounts? Having to run my tool on
multiple account PC's is a valid scenario.

regards
Aji/

**Comment by giampaolo** [comment]
What is it that takes so much time? `name()`? or `process_iter()`?
Here, try this:

```python

import psutil, time, contextlib


@contextlib.contextmanager
def timeit(what):
    t = time.time()
    yield
    print("%-30s: %f secs" % (what, time.time() - t))


def main():
    ls = psutil.process_iter()
    while 1:
        with timeit("process_iter next()"):
            try:
                proc = next(ls)
            except StopIteration:
                break
        with timeit("name()"):
            proc.name()


main()
```

**Comment by ajikumarmp** [comment]
Hi,

Both are taking time, this is on the remote PC where I am running.

process_iter next()           : 0.896000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.300000 secs
name()                        : 0.364000 secs
process_iter next()           : 0.180000 secs
name()                        : 0.201000 secs
process_iter next()           : 0.164000 secs
name()                        : 0.214000 secs
process_iter next()           : 0.205000 secs
name()                        : 0.194000 secs
process_iter next()           : 0.214000 secs
name()                        : 0.201000 secs
process_iter next()           : 0.225000 secs
name()                        : 0.194000 secs
process_iter next()           : 0.155000 secs
name()                        : 0.195000 secs
process_iter next()           : 0.156000 secs
name()                        : 0.156000 secs
process_iter next()           : 0.192000 secs
name()                        : 0.195000 secs
process_iter next()           : 0.167000 secs
name()                        : 0.204000 secs
process_iter next()           : 0.177000 secs
name()                        : 0.193000 secs
process_iter next()           : 0.200000 secs
name()                        : 0.178000 secs
process_iter next()           : 0.228000 secs
name()                        : 0.168000 secs
process_iter next()           : 0.152000 secs
name()                        : 0.193000 secs
process_iter next()           : 0.190000 secs
name()                        : 0.155000 secs
process_iter next()           : 0.192000 secs
name()                        : 0.155000 secs
process_iter next()           : 0.164000 secs
name()                        : 0.190000 secs
process_iter next()           : 0.181000 secs
name()                        : 0.158000 secs
process_iter next()           : 0.195000 secs
name()                        : 0.180000 secs
process_iter next()           : 0.185000 secs
name()                        : 0.193000 secs
process_iter next()           : 0.155000 secs
name()                        : 0.188000 secs
process_iter next()           : 0.164000 secs
name()                        : 0.194000 secs
process_iter next()           : 0.201000 secs
name()                        : 0.193000 secs
process_iter next()           : 0.154000 secs
name()                        : 0.199000 secs
process_iter next()           : 0.153000 secs
name()                        : 0.177000 secs
process_iter next()           : 0.192000 secs
name()                        : 0.196000 secs
process_iter next()           : 0.204000 secs
name()                        : 0.167000 secs
process_iter next()           : 0.173000 secs
name()                        : 0.198000 secs
process_iter next()           : 0.318000 secs
name()                        : 0.391000 secs
process_iter next()           : 0.397000 secs
name()                        : 0.367000 secs
process_iter next()           : 0.171000 secs
name()                        : 0.160000 secs
process_iter next()           : 0.197000 secs
name()                        : 0.229000 secs
process_iter next()           : 0.183000 secs
name()                        : 0.199000 secs
process_iter next()           : 0.180000 secs
name()                        : 0.197000 secs
process_iter next()           : 0.205000 secs
name()                        : 0.160000 secs
process_iter next()           : 0.202000 secs
name()                        : 0.168000 secs
process_iter next()           : 0.168000 secs
name()                        : 0.193000 secs
process_iter next()           : 0.198000 secs
name()                        : 0.179000 secs
process_iter next()           : 0.189000 secs
name()                        : 0.179000 secs
process_iter next()           : 0.196000 secs
name()                        : 0.200000 secs
process_iter next()           : 0.195000 secs
name()                        : 0.229000 secs
process_iter next()           : 0.189000 secs
name()                        : 0.195000 secs
process_iter next()           : 0.192000 secs
name()                        : 0.177000 secs
process_iter next()           : 0.192000 secs
name()                        : 0.156000 secs
process_iter next()           : 0.154000 secs
name()                        : 0.234000 secs
process_iter next()           : 0.192000 secs
name()                        : 0.155000 secs
process_iter next()           : 0.190000 secs
name()                        : 0.157000 secs
process_iter next()           : 0.169000 secs
name()                        : 0.194000 secs
process_iter next()           : 0.171000 secs
name()                        : 0.165000 secs
process_iter next()           : 0.180000 secs
name()                        : 0.222000 secs
process_iter next()           : 0.209000 secs
name()                        : 0.197000 secs
process_iter next()           : 0.158000 secs
name()                        : 0.200000 secs
process_iter next()           : 0.189000 secs
name()                        : 0.193000 secs
process_iter next()           : 0.192000 secs
name()                        : 0.161000 secs
process_iter next()           : 0.191000 secs
name()                        : 0.160000 secs
process_iter next()           : 0.162000 secs
name()                        : 0.195000 secs
process_iter next()           : 0.190000 secs
name()                        : 0.204000 secs
process_iter next()           : 0.353000 secs
name()                        : 0.406000 secs
process_iter next()           : 0.403000 secs
name()                        : 0.228000 secs
process_iter next()           : 0.182000 secs
name()                        : 0.200000 secs
process_iter next()           : 0.167000 secs
name()                        : 0.201000 secs
process_iter next()           : 0.174000 secs
name()                        : 0.178000 secs
process_iter next()           : 0.192000 secs
name()                        : 0.187000 secs
process_iter next()           : 0.183000 secs
name()                        : 0.193000 secs
process_iter next()           : 0.162000 secs
name()                        : 0.186000 secs
process_iter next()           : 0.195000 secs
name()                        : 0.209000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.197000 secs
name()                        : 0.155000 secs
process_iter next()           : 0.180000 secs
name()                        : 0.196000 secs
process_iter next()           : 0.196000 secs
name()                        : 0.162000 secs
process_iter next()           : 0.190000 secs
name()                        : 0.171000 secs
process_iter next()           : 0.202000 secs
name()                        : 0.185000 secs
process_iter next()           : 0.180000 secs
name()                        : 0.225000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.165000 secs
name()                        : 0.187000 secs
process_iter next()           : 0.198000 secs
name()                        : 0.196000 secs
process_iter next()           : 0.190000 secs
name()                        : 0.175000 secs
process_iter next()           : 0.166000 secs
name()                        : 0.190000 secs
process_iter next()           : 0.194000 secs
name()                        : 0.155000 secs
process_iter next()           : 0.191000 secs
name()                        : 0.154000 secs
process_iter next()           : 0.152000 secs
name()                        : 0.193000 secs
process_iter next()           : 0.192000 secs
name()                        : 0.156000 secs
process_iter next()           : 0.187000 secs
name()                        : 0.155000 secs
process_iter next()           : 0.155000 secs
name()                        : 0.190000 secs
process_iter next()           : 0.196000 secs
name()                        : 0.158000 secs
process_iter next()           : 0.202000 secs
name()                        : 0.201000 secs
process_iter next()           : 0.199000 secs
name()                        : 0.199000 secs
process_iter next()           : 0.177000 secs
name()                        : 0.210000 secs
process_iter next()           : 0.342000 secs
name()                        : 0.432000 secs
process_iter next()           : 0.367000 secs
name()                        : 0.217000 secs
process_iter next()           : 0.198000 secs
name()                        : 0.174000 secs
process_iter next()           : 0.163000 secs
name()                        : 0.182000 secs
process_iter next()           : 0.156000 secs
name()                        : 0.194000 secs
process_iter next()           : 0.190000 secs
name()                        : 0.165000 secs
process_iter next()           : 0.185000 secs
name()                        : 0.162000 secs
process_iter next()           : 0.152000 secs
name()                        : 0.188000 secs
process_iter next()           : 0.194000 secs
name()                        : 0.164000 secs
process_iter next()           : 0.235000 secs
name()                        : 0.179000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.182000 secs
name()                        : 0.198000 secs
process_iter next()           : 0.165000 secs
name()                        : 0.168000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.001000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.173000 secs
name()                        : 0.193000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.188000 secs
name()                        : 0.191000 secs
process_iter next()           : 0.152000 secs
name()                        : 0.194000 secs
process_iter next()           : 0.163000 secs
name()                        : 0.172000 secs
process_iter next()           : 0.215000 secs
name()                        : 0.189000 secs
process_iter next()           : 0.207000 secs
name()                        : 0.199000 secs
process_iter next()           : 0.173000 secs
name()                        : 0.192000 secs
process_iter next()           : 0.199000 secs
name()                        : 0.166000 secs
process_iter next()           : 0.197000 secs
name()                        : 0.175000 secs
process_iter next()           : 0.227000 secs
name()                        : 0.193000 secs
process_iter next()           : 0.152000 secs
name()                        : 0.181000 secs
process_iter next()           : 0.186000 secs
name()                        : 0.246000 secs
process_iter next()           : 0.202000 secs
name()                        : 0.188000 secs
process_iter next()           : 0.197000 secs
name()                        : 0.164000 secs
process_iter next()           : 0.153000 secs
name()                        : 0.190000 secs
process_iter next()           : 0.204000 secs
name()                        : 0.174000 secs
process_iter next()           : 0.207000 secs
name()                        : 0.295000 secs
process_iter next()           : 0.372000 secs
name()                        : 0.321000 secs
process_iter next()           : 0.303000 secs
name()                        : 0.193000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.198000 secs
name()                        : 0.176000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.191000 secs
name()                        : 0.187000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.198000 secs
name()                        : 0.187000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.171000 secs
name()                        : 0.206000 secs
process_iter next()           : 0.176000 secs
name()                        : 0.185000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.206000 secs
name()                        : 0.186000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.001000 secs
process_iter next()           : 0.181000 secs
name()                        : 0.200000 secs
process_iter next()           : 0.177000 secs
name()                        : 0.202000 secs
process_iter next()           : 0.245000 secs
name()                        : 0.207000 secs
process_iter next()           : 0.251000 secs
name()                        : 0.189000 secs
process_iter next()           : 0.216000 secs
name()                        : 0.209000 secs
process_iter next()           : 0.192000 secs
name()                        : 0.176000 secs
process_iter next()           : 0.175000 secs
name()                        : 0.202000 secs
process_iter next()           : 0.199000 secs
name()                        : 0.166000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.198000 secs
name()                        : 0.185000 secs
process_iter next()           : 0.205000 secs
name()                        : 0.209000 secs
process_iter next()           : 0.191000 secs
name()                        : 0.202000 secs
process_iter next()           : 0.187000 secs
name()                        : 0.205000 secs
process_iter next()           : 0.189000 secs
name()                        : 0.166000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.203000 secs
name()                        : 0.177000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.198000 secs
name()                        : 0.206000 secs
process_iter next()           : 0.179000 secs
name()                        : 0.180000 secs
process_iter next()           : 0.203000 secs
name()                        : 0.191000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.204000 secs
name()                        : 0.201000 secs
process_iter next()           : 0.174000 secs
name()                        : 0.195000 secs
process_iter next()           : 0.000000 secs

Process finished with exit code 0

compare this with the output on my laptop

process_iter next()           : 0.005000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.001000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.001000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.004000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.001000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.003000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.004000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.004000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.005000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.003000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.003000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.005000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.001000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.003000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.002000 secs
process_iter next()           : 0.003000 secs
name()                        : 0.004000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.001000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.003000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.001000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.005000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.005000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.004000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.002000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.001000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.001000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.001000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.004000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.001000 secs
name()                        : 0.003000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs
name()                        : 0.000000 secs
process_iter next()           : 0.000000 secs

Process finished with exit code 0

Huge differerence,

regards
Aji.

**Comment by giampaolo** [comment]
It looks like the first output was run on a Pentium 1 as both `process_iter()` (which internally calls `create_time()` and `name()` are unbelievably slow. Is this an old PC?

**Comment by ajikumarmp** [comment]
I would not call that a old PC, it has a manufacturing date in 2014 and
also has high end hardware

[image: Inline image 1]

It is a Xeon processor though and run Windows 7, thanks I will try this on
other PC's where multiple logons exist and verify the behaviour.

regards
Aji.

**Comment by giampaolo** [comment]
I doubt it has to do with multiple users connected.

**Comment by ajikumarmp** [comment]
Thanks, will come back to you if I find anything unusual in my testing
