### ISSUE TITLE
psutil.cpu_count(logical=False) returns None on arm

### ISSUE THREAD

**Issue by fake-name** [giampaolo/psutil#1078]
Basically, `psutil.cpu_count()` returns the correct number of cores (4, on a raspberry pi 3), but `psutil.cpu_count(logical=False)` returns nothing at all.

**Comment by giampaolo** [comment]
That is by design, meaning (also the doc states it) that if physical CPUs cannot be determined the function will return `None`, similarly to `os.cpu_count()` and `multiprocessing.cpu_count()`.
With that said, please paste the output of `cat /proc/cpuinfo`. I assume on raspberry it's either empty or has a different format (in which case we may adjust the parsing logic and fix this issue).

**Comment by fake-name** [comment]
Huh, I thought I didn't actually open this issue, because I wound up discovering that it intentionally returns `None`. As a result, I actually fixed it upstream in the package that uses cpuinfo (I'm doing stupid stuff with a pi, see https://github.com/gprMax/gprMax/issues/111 ).

Anyways, sorry for the issue clutter, and I'll get you the contents of `/proc/cpuinfo` on monday, when I'm at work again.

**Comment by giampaolo** [comment]
It's OK. =)

**Comment by fake-name** [comment]
Ok, the Pi's `/proc/cpuinfo`


```
130 pi@testpi:~$ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : BCM2835
Revision        : a22042
Serial          : 00000000f4e64924


```

**Comment by giampaolo** [comment]
Yeah, the format is just different. It's better not to try to guess it and just return None.
