### ISSUE TITLE
CPU_PERCENT always returns zero

### ISSUE THREAD

**Issue by bearrito** [giampaolo/psutil#1095]
The below snippet will always show 0.0 for cpu_percent.

version: 5.2.2
OS: Ubuntu 14.04 LTS

I am running the `Stress` application and  `top` shows the  process at 100.00%

```
for proc in psutil.process_iter():
            with proc.oneshot():

                ct = proc.cpu_times()
                cp = proc.cpu_percent()

                print proc.name()

                if "stress" in proc.name():
                    print "CPU: " + str(proc.cpu_percent())
```

**Comment by giampaolo** [comment]
That's by design. The first call to cpu_percent() always returns `0.0` (unless you specify a timeout).
Read the doc: https://pythonhosted.org/psutil/#psutil.Process.cpu_percent
