### ISSUE TITLE
`used memory`  not match free command on centos7

### ISSUE THREAD

**Issue by wanghaiqing2015** [giampaolo/psutil#1107]
os: centos 7.1 
psutil version : psutil (5.2.2)

--------------------------------------------------------------------------------

[root@test sysmon-1.0.1]# free -b
              total        used        free      shared  buff/cache   available
Mem:     1018978304   578482176   101789696     9592832   338706432   264282112
Swap:    4095733760   348106752  3747627008

[root@test sysmon-1.0.1]# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.virtual_memory()
svmem(total=1018978304, available=257376256, percent=74.7, used=613167104, free=94851072, active=335736832, inactive=399966208, buffers=0, cached=310960128, shared=9592832)

**Comment by wanghaiqing2015** [comment]
578482176 
and
613167104

**Comment by wanghaiqing2015** [comment]
？？？

**Comment by giampaolo** [comment]
What's the output of `free -V`?

**Comment by giampaolo** [comment]
Bump?

**Comment by giampaolo** [comment]
Closing as outdated.
