### ISSUE TITLE
sensors_temperatures()  not support  Double CPU 

### ISSUE THREAD

**Issue by wanghaiqing2015** [giampaolo/psutil#1108]
error message:
No such file or directory: '/sys/class/hwmon/hwmon0/device/name'

use lm_sensors is ok, show:

       coretemp-isa-0000
       coretemp-isa-0001

**Comment by giampaolo** [comment]
Please paste the output of `ls /sys/class/hwmon/hwmon*/temp*_*` and `/sys/class/hwmon/hwmon*/device/temp*_*`.

**Comment by giampaolo** [comment]
This should be a duplicate of https://github.com/giampaolo/psutil/issues/1129. Closing.
