### ISSUE TITLE
wrong (zero) read counts 

### ISSUE THREAD

**Issue by lzhengchun** [giampaolo/psutil#1128]
Unsure why, the file /proc/[pid]/io of my system "_Linux smart-dtn 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux_" always reports **read_bytes** as zero. 

So, _psutil.disk_io_counters().read_count_ always reports 0, as well as the _p.io_counters()_ where p is the process. 

update: Well the read counter is not always zero, but just does not change.

An example of my /proc/[pid]/io file:

rchar: 97640349
wchar: 93615
syscr: 1027662
syscw: 1123
read_bytes: 0
write_bytes: 225280
cancelled_write_bytes: 0

**Comment by giampaolo** [comment]
If it doesn't change and psutil reports it as is then it's not a psutil bug. Closing.
