### ISSUE TITLE
AIX: pid_exists() is broken?

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#1136]
```
test_pid_exists_2: there are pids in /proc that don't really exist
```

@wiggin15 I forgot about this. Does it mean `pid_exists()` is broken? Does AIX have /proc/{pid}/status? Linux uses a specific logic for pid_exists() as it takes the Tid (thread ID) into account. I wonder if AIX does the same. If we can't rely on `os.kill` then I suggest to implement pid_exists() like this:

```
def pid_exists(pid):
     return pid in pids()
```

It's slow but at least it's correct. What do you think?

**Comment by wiggin15** [comment]
You're right, I forgot about it too. I opened a PR. Let me know what you think.
