### ISSUE TITLE
OK to add stubs for psutil to typeshed?

### ISSUE THREAD

**Issue by gvanrossum** [giampaolo/psutil#1147]
Hey Giampaolo,

Would you be okay if someone added typing stubs for psutil to [typeshed](https://github.com/python/typeshed)? This will enable users of [mypy](https://github.com/python/mypy) to type-check code that uses psutil reliably.

--Guido

**Comment by giampaolo** [comment]
Hey Guido! Of course, no problem at all.

**Comment by gvanrossum** [comment]
Thank you! I'll close this issue.
