### ISSUE TITLE
I just found psutil support aix, when I installed, there are some errors

### ISSUE THREAD

**Issue by zixiliuyue** [giampaolo/psutil#1154]
util/_psutil_posix.c -o build/temp.aix-6.1-2.7/psutil/_psutil_posix.o
xlc_r -g -DNDEBUG -O -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=540 -DPSUTIL_AIX=1 -I/home/genius/python27/include/python2.7 -c psutil/_psutil_aix.c -o build/temp.aix-6.1-2.7/psutil/_psutil_aix.o
"psutil/_psutil_aix.c", line 169.5: 1506-045 (S) Undeclared identifier perfstat_thread_t.
"psutil/_psutil_aix.c", line 169.24: 1506-045 (S) Undeclared identifier threadt.
"psutil/_psutil_aix.c", line 169.32: 1506-277 (S) Syntax error: possible missing ';' or ','?
"psutil/_psutil_aix.c", line 186.35: 1506-275 (S) Unexpected text ')' encountered.
"psutil/_psutil_aix.c", line 187.35: 1506-277 (S) Syntax error: possible missing ')' or ','?
error: command 'xlc_r' failed with exit status 1

I am using the operating system:
# oslevel
6.1.0.0

**Comment by giampaolo** [comment]
@wiggin15 any idea?

**Comment by wiggin15** [comment]
That's strange. `perfstat_thread_t` et al exist in the documentation of AIX 6.1 (https://www.ibm.com/support/knowledgecenter/en/ssw_aix_61/com.ibm.aix.prftools/idprftools_perfstat_thread.htm) but apparently the pefrstat thread API is missing in some old (end-of-service) AIX versions. We'll have to dynamically check whether that API exists and disable `Process.threads` if it doesn't. I'll see what I can do.

**Comment by wiggin15** [comment]
It's not even in the [changelog](https://www.ibm.com/support/knowledgecenter/ssw_aix_72/com.ibm.aix.prftools/ch_history.htm) :angry:

**Comment by zixiliuyue** [comment]
Oh thank you, I can help you test aix6 as soon as possible.
