### ISSUE TITLE
'nice' is cached by 'oneshot'?

### ISSUE THREAD

**Issue by wiggin15** [giampaolo/psutil#1157]
The docs have a list of methods boosted by the "oneshot" context (in the table under the "oneshot" documentation).
The table lists `nice` and `ionice` under Windows and `nice` under SunOS, but I couldn't find a speedup for these methods in the code itself. Am I missing something or is it a problem with the documentation?

**Comment by giampaolo** [comment]
I would say you spotted a very hard to find documentation bug. =)

**Comment by wiggin15** [comment]
Thanks. I'll fix it along with other updates to that table.
