### ISSUE TITLE
Incorrect code snippet for "Terminate my children"

### ISSUE THREAD

**Issue by makalaaneesh** [giampaolo/psutil#1166]
in reference to this http://psutil.readthedocs.io/en/latest/#terminate-my-children

```
gone, alive = psutil.wait_procs(procs, timeout=timeout, callback=on_terminate)
    if not alive:
        # send SIGKILL
```

alive will have the processes that are still alive after having sent SIGTERM.
So the check should be ``` if alive ``` rather than ``` if not alive ```

**Comment by giampaolo** [comment]
Fixed thanks.
