### ISSUE TITLE
AttributeError with PsUtil on FreeBSD

### ISSUE THREAD

**Issue by nicolargo** [giampaolo/psutil#1195]
On a FreeBSD system with the system blackhole option enable (see detail here: https://github.com/nicolargo/glances/issues/1202).

            import psutil
            psutil.sensors_temperatures()
            Traceback (most recent call last):
            File "", line 1, in
            AttributeError: 'module' object has no attribute 'sensors_temperatures'
            psutil.sensors_fans()
            Traceback (most recent call last):
            File "", line 1, in
            AttributeError: 'module' object has no attribute 'sensors_fans'
            psutil.sensors_battery()

**Comment by giampaolo** [comment]
`sensors_battery()` is the only sensors API available on FreeBSD.
