### ISSUE TITLE
cpu_percent gives off wrong values on VM's

### ISSUE THREAD

**Issue by lorddusk** [giampaolo/psutil#1196]
hi,

I'm creating a specialized monitor with this tool, locally it runs perfect. But as soon as I migrate the tool to a VM (both Windows and Linux) I get wrongly stated values.

These VM's all have 16 logical cores, and cpu load for some are at 100%, and some are at 0%. Adding them all together, and dividing them by the same number (16) does NOT give the right percentage of usage.

Am I doing something wrong? Or is the tool not usable on VM's?

Tried running in both py 2.7.14 and 3.6.4, on Windows Server 2016.

**Comment by giampaolo** [comment]
What API are you talking about? `psutil.cpu_percent(percpu=True)`? Are you running it in a loop? Please show some actual code and results.

**Comment by lorddusk** [comment]
Ah, excuse me, forgot the actual code...

`import psutil as os

for x in range(3):
    CPU = os.cpu_times_percent(interval=1, percpu=False)
    print(CPU)
    print(os.cpu_percent(interval=1, percpu=True))`

this returns the following : 
![image](https://user-images.githubusercontent.com/425207/34259474-a726dda4-e662-11e7-8cc0-42ffa8f74aea.png)

while the Taskmanager shows this :
![image](https://user-images.githubusercontent.com/425207/34259488-bcc9450c-e662-11e7-92f8-6473785b50ce.png)

**Comment by giampaolo** [comment]
`100 / 16` is equal to 6.25% (total CPU usage), not so distant from the 4% reported by the task manager. 
`cpu_percent` is not supposed to return the exact same numbers as the task manager. CPU percent calculation *in general* is an approximation.
