### ISSUE TITLE
p.cpu_percent() returns over 100% per core

### ISSUE THREAD

**Issue by Jonaus** [giampaolo/psutil#1198]
Windows 10
Python 2.7.14

Code snippet:

```
import psutil
import time

PROCESS = filter(lambda p: p.name() == "Syncplicity.exe", psutil.process_iter())[0]

while True:
    with PROCESS.oneshot():
        print "%d - PID:%d - CPU:%f - tc:%d" % (
              time.time()*1000,
              PROCESS.pid,
              PROCESS.cpu_percent(interval=0.0) / psutil.cpu_count(),
              PROCESS.num_threads())
```

sample output with CPU over 100%:

```
1514377548358 - PID:10804 - CPU:0.000000 - tc:45
1514377548358 - PID:10804 - CPU:0.000000 - tc:45
1514377548358 - PID:10804 - CPU:0.000000 - tc:45
1514377548358 - PID:10804 - CPU:0.000000 - tc:45
1514377548358 - PID:10804 - CPU:0.000000 - tc:45
1514377548358 - PID:10804 - CPU:0.000000 - tc:45
1514377548374 - PID:10804 - CPU:0.000000 - tc:45
1514377548374 - PID:10804 - CPU:0.000000 - tc:45
1514377548374 - PID:10804 - CPU:0.000000 - tc:45
1514377548374 - PID:10804 - CPU:0.000000 - tc:45
1514377548374 - PID:10804 - CPU:0.000000 - tc:45
1514377548374 - PID:10804 - CPU:0.000000 - tc:45
1514377548390 - PID:10804 - CPU:0.000000 - tc:45
1514377548390 - PID:10804 - CPU:0.000000 - tc:45
1514377548390 - PID:10804 - CPU:0.000000 - tc:45
1514377548390 - PID:10804 - CPU:0.000000 - tc:45
1514377548402 - PID:10804 - CPU:0.000000 - tc:45
1514377548405 - PID:10804 - CPU:0.000000 - tc:45
1514377548407 - PID:10804 - CPU:0.000000 - tc:45
1514377548410 - PID:10804 - CPU:0.000000 - tc:45
1514377548411 - PID:10804 - CPU:195.325000 - tc:45
1514377548411 - PID:10804 - CPU:0.000000 - tc:45
1514377548411 - PID:10804 - CPU:0.000000 - tc:45
1514377548411 - PID:10804 - CPU:0.000000 - tc:45
1514377548411 - PID:10804 - CPU:0.000000 - tc:45
1514377548411 - PID:10804 - CPU:0.000000 - tc:45
1514377548427 - PID:10804 - CPU:0.000000 - tc:45
1514377548427 - PID:10804 - CPU:0.000000 - tc:45
1514377548427 - PID:10804 - CPU:0.000000 - tc:45
1514377548427 - PID:10804 - CPU:0.000000 - tc:45
1514377548427 - PID:10804 - CPU:0.000000 - tc:45
1514377548427 - PID:10804 - CPU:0.000000 - tc:45
1514377548427 - PID:10804 - CPU:0.000000 - tc:45
1514377548443 - PID:10804 - CPU:0.000000 - tc:45
1514377548443 - PID:10804 - CPU:0.000000 - tc:45
1514377548443 - PID:10804 - CPU:0.000000 - tc:45
1514377548443 - PID:10804 - CPU:0.000000 - tc:45
1514377548443 - PID:10804 - CPU:0.000000 - tc:45
1514377548443 - PID:10804 - CPU:0.000000 - tc:45
1514377548443 - PID:10804 - CPU:0.000000 - tc:45
1514377548443 - PID:10804 - CPU:0.000000 - tc:45
1514377548458 - PID:10804 - CPU:0.000000 - tc:45
1514377548458 - PID:10804 - CPU:0.000000 - tc:45
1514377548458 - PID:10804 - CPU:0.000000 - tc:45
```

psutil.cpu_count() correctly returns 8 every time. 

Only had this happen when interval is 0.
I looked through the documentation and could not figure out what could be causing this. As far as I understand the expected behavior would obviously be to have < 100% CPU usage per logical processor.

**Comment by giampaolo** [comment]
Not sure I understand. You're doing a busy loop (hence the high CPU usage) plus you're using `interval=0.0`, which is bad as it doesn't provide accurate results. What are you trying to achieve exactly?
Also, please read `cpu_percent` doc:
http://psutil.readthedocs.io/en/latest/#psutil.cpu_percent

**Comment by Jonaus** [comment]
I'm monitoring a process (in given example "Syncplicity") CPU usage using **cpu_percent() / psutil.cpu_count()**. My goal is to get a CPU usage per core (0-100 range, as in Windows `taskmgr.exe`) for that process as frequently as possible (that's why I'm using `interval=0`).

https://psutil.readthedocs.io/en/latest/#psutil.Process.cpu_percent

> Return a float representing the process CPU utilization as a percentage which can also be > 100.0 in case of a process running multiple threads on different CPUs.

If I understand this correctly, that means the result divided by number of logical processors should always be in range of 0-100 and I'm getting percentages higher than 100.

**Comment by giampaolo** [comment]
You will not get a meaningful result by using such a short interval. CPU usage is something which should be monitored over time, so you should give it some... time (e.g. 1 second). =)

> If I understand this correctly, that means the result divided by number of logical processors should 
> always be in range of 0-100 and I'm getting percentages higher than 100.

Correct. See this paragraph:

> Note the returned value is explicitly not split evenly between all available CPUs (differently from psutil.cpu_percent()). This means that a busy loop process running on a system with 2 logical CPUs will be reported as having 100% CPU utilization instead of 50%. This was done in order to be consistent with top UNIX utility and also to make it easier to identify processes hogging CPU resources independently from the number of CPUs. It must be noted that taskmgr.exe on Windows does not behave like this (it would report 50% usage instead). To emulate Windows taskmgr.exe behavior you can do: p.cpu_percent() / psutil.cpu_count().

**Comment by Jonaus** [comment]
Alright, I will increase the interval.

But this still does not answer why the result jumps above 100% when I'm diving the usage percentage by cores count like in documentation. `p.cpu_percent() / psutil.cpu_count()`

**Comment by giampaolo** [comment]
I'm not sure why that happens.

**Comment by Jonaus** [comment]
OK. Thank you for answering :)
