### ISSUE TITLE
cpu_count returns wrong results in the case of dynamically enabled CPU cores

### ISSUE THREAD

**Issue by KOLANICH** [giampaolo/psutil#1200]
Some systems allow to disable CPU cores to save power. On these systems cpu_count usually returns the count of cores less than the available one, for example on 4 core cpu it usually returns 2 (unless something heavy is not started in background or the cores are not manually brought up).

**Comment by giampaolo** [comment]
See https://github.com/giampaolo/psutil/issues/1122
Closing this one as duplicate.
