### ISSUE TITLE
Install psutil failed on Mac due to "cannot import name '_psutil_osx'"issue

### ISSUE THREAD

**Issue by wshandao** [giampaolo/psutil#1206]
Dear,
I have installed python3 eariler before，recently we have a requirement to build dynamic deploy spring boot applicaion via python, and need to use psutil accordingly.

All steps I have executed were followed by install instruction, but when import psutil, the python raise the error as below
<img width="680" alt="default" src="https://user-images.githubusercontent.com/16696624/34665551-96f76542-f49b-11e7-8a0f-c0060627bccd.png">

Have no idea how to fix this issue, could you help to review and share me the solution? thanks!

**Comment by giampaolo** [comment]
You should try to reinstall psutil.
I would try:
```
pip uninstall psutil
rm -rf /Users/wangshd/pythonProjects/psutil*
 # make sure the error above changes so there are zero references to psutil
python -c "import psutil" 
# finally reinstall
pip install psutil
```

**Comment by wshandao** [comment]
Thanks for your support on this, now the psutil is working on my laptop!
