### ISSUE TITLE
boot_time() returns incorrect value on XP

### ISSUE THREAD

**Issue by xiaolingbao** [giampaolo/psutil#1223]
Build _pswindows.pyd with _WIN32_WINNT set to '0x501' and PSAPI_VERSION=1, and run:

c:\window> python -c "import psutil; print psutil.boot_time()"
4.74414813e+18

Cause:
uptime is defined as double with the above settings (https://github.com/giampaolo/psutil/blob/dd19ba7b5bbf5ea67a4d386baa3fabd13b118533/psutil/_psutil_windows.c#L216), Py_BuildValue() later on expects either ULONGLONG or LONGLONG. There is memory layout mismatch between the expected value format and the supplied.

This is a regression as the previous version uses double in both places.

**Comment by giampaolo** [comment]
Can you submit a PR?
