### ISSUE TITLE
Windows 10 send_signal on child process fails with [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by ericgj** [giampaolo/psutil#1227]
I am sending a CTRL_BREAK_EVENT to all the child processes and then to the parent as part of a Windows service shutdown.  As outlined in the answer [here](https://stackoverflow.com/questions/1230669/subprocess-deleting-child-processes-in-windows), except sending CTRL_BREAK_EVENT instead of `child.kill()`.

I have not seen this error running the same code on Windows 7.

**Comment by giampaolo** [comment]
Can you paste the traceback?

**Comment by giampaolo** [comment]
Closing out as no response was given.
