### ISSUE TITLE
decoupled C library, without python

### ISSUE THREAD

**Issue by justinmk** [giampaolo/psutil#1247]
The code in https://github.com/giampaolo/psutil/blob/master/psutil/arch/ is quite a trove of useful cross-platform voodoo.  It's the most comprehensive that I've found.  Projects like [libuv](https://github.com/libuv/) are more conservative.

Has there been discussion about pulling the psutil C source into a separate project which could be included by other non-python C projects? Or, do you know of any efforts to do so? Or projects with similar goals?

How much effort would you estimate for this task?  I would guess it's "just" a matter of removing the python bits. 

I also wondered if https://github.com/micropython/micropython could be used as a bridge somehow, for projects that don't want to depend on the python universe, but I didn't check if that project is compatible with the python C API.

**Comment by giampaolo** [comment]
Yes, that is something I've been thinking about for a long time. One project I'm aware of which provides a "pure" C layer with on top the bindings for other languages is [sigar](https://github.com/hyperic/sigar/tree/master/bindings).
psutil is getting to a point which is pretty much feature-complete. The next more logical step in terms of new functionality would be adding support for some exotic platform (e.g. [cygwin](https://github.com/giampaolo/psutil/pull/998)) or start porting it to other languages (which [is already happening](https://github.com/giampaolo/psutil#portings) BTW).
That's not a simple task though:
- cPython API is used extensively throughout all C code
- the C code should return basic C types instead
- the implementation for platforms such as [Linux](https://github.com/giampaolo/psutil/blob/master/psutil/_pslinux.py) is 80% Python. That would have to be rewritten from scratch in C.
- Other platforms such as [Windows](https://github.com/giampaolo/psutil/blob/master/psutil/_pswindows.py) also have a non-negligible amount of Python logic which would have to be rewritten in C.

> How much effort would you estimate for this task? 

A lot. I imagine this as a 3-step process:
1) implement the pure C layer meaning getting rid of the cPython API and moving the Python logic to C. This may be a separate `psutil-lib` project or it may grow inside psutil itself.
2) add a Python wrapper on top of it
3) gradually add wrappers for other languages
I'm not sure how long this would take but it's surely in the order of *months* assuming a full-time investment.

**Comment by justinmk** [comment]
Thanks for the detailed answer!

> implement the pure C layer meaning getting rid of the cPython API and moving the Python logic to 

Ok, I didn't realize that python was used in the `arch/` layer for more than passing around data. 

I agree a big refactoring sounds horrible. Using https://github.com/micropython/micropython could be a very interesting hack, though maybe a different type of unpleasant (build-system) work.
