### ISSUE TITLE
swap_memory is not in bytes on FreeBSD

### ISSUE THREAD

**Issue by href** [giampaolo/psutil#1255]
Running `psutil.swap_memory` on FreeBSD 10.3 I gives me the following output:

    sswap(total=2097088, used=17347, free=2079741, percent=0.8, sin=53145, sout=76176)

Running `swapinfo` at the same time returns with the following output:

```bash
Device          1K-blocks     Used    Avail Capacity
/dev/gpt/swap0    4194304    34308  4159996     1%
/dev/gpt/swap1    4194304    35080  4159224     1%
Total             8388608    69388  8319220     1%
```

In other words, psutil thinks I got `2'097'088` bytes of swap, even though I actually have `8'388'608'000` bytes. Since the answer is off by a factor of almost exactly 4000, I assume that psutil doesn't really return bytes here.

Am I missing something? These values should be in bytes, right?

**Comment by giampaolo** [comment]
Yes all values are supposed to be expressed in bytes.
This is how it's done on FreeBSD:
https://github.com/giampaolo/psutil/blob/master/psutil/arch/freebsd/specific.c#L501
The C type is an `int`, which indeed makes me thing we're not dealing with bytes (`int` is too small).
I searched a bit and in here:
https://github.com/KDE/ksysguard/blob/master/ksysguardd/FreeBSD/Memory.c#L159
...they convert it as `swap_total * pagesize / 1024`.
I currently don't have a FreeBSD to test against (have to reinstall it on VirtualBox) and I'll travelling to China on Saturday. Maybe you can try doing the change yourself, re-compile and test?

**Comment by href** [comment]
Sure. Not sure if I can get to it this week, but I don't mind tackling this.

**Comment by giampaolo** [comment]
Take a look at:
https://github.com/giampaolo/psutil/blob/master/DEVGUIDE.rst
There are also a bunch unit tests for this:
https://github.com/giampaolo/psutil/blob/master/psutil/tests/test_bsd.py#L451-L463
I suppose they never failed for me 'cause I never had a swap > 0.

**Comment by giampaolo** [comment]
Forget about it, it's for NetBSD. =)

**Comment by href** [comment]
I fixed it locally, hopefully I did this the right way. My C is *way* rusty ;)

**Comment by href** [comment]
Within what time frame can I expect a release of psutil with this fix in it?

**Comment by giampaolo** [comment]
It's out. Enjoy!

**Comment by href** [comment]
Awesome, thank you 🎉
