### ISSUE TITLE
fail to build a wheel for psutil

### ISSUE THREAD

**Issue by djaffarou** [giampaolo/psutil#1261]
I have tried to install psutil on termux(android nougat) but when i write 
pip install psutil it send me this error on red 
```
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-alehd4ez/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-7kvh5ilb-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-alehd4ez/psu
```
What surprised is thad I used to install it but this time it doesn't work o don't know why !!!

**Comment by djaffarou** [comment]
If there some one who can help me

**Comment by nstr10** [comment]
The package `arm-linux-androideabi-clang` seems to be the source of this error, implying you need clang installed. Once you resolve that, you will find that some source files like `crypt.h` are not present. 

The following resolved this issue for me:
```bash
apt install python-dev clang libcrypt-dev```

**Comment by runthee** [comment]
its work.. thks
