### ISSUE TITLE
Windows - add info to error message when syscall fails

### ISSUE THREAD

**Issue by ewedlund** [giampaolo/psutil#1263]
On Windows, psutil.net_if_addrs() sometimes fails with "GetAdaptersAddresses() syscall failed." 

Typically this has happened when a py2exe executable created on an older version of Windows is used on an updated one, but sometimes it seems to fail for some other (unknown) reason. So it would be useful if it was possible to get more information on the error when it happens.

Looking at the code in _psutil_windows.c, it should be possible to use the return value dwRetVal in order to give a more detailed error message. 

Return code | Description
-- | --
ERROR_ADDRESS_NOT_ASSOCIATED | An address has not yet been associated with the network endpoint. DHCP lease information was available.
ERROR_BUFFER_OVERFLOW | The buffer size indicated by the SizePointer parameter is too small to hold the adapter information or the AdapterAddresses parameter is NULL. The SizePointer parameter returned points to the required size of the buffer to hold the adapter information.
ERROR_INVALID_PARAMETER | One of the parameters is invalid. This error is returned for any of the following conditions: the SizePointer parameter is NULL, the Address parameter is not AF_INET, AF_INET6, or AF_UNSPEC, or the address information for the parameters requested is greater than ULONG_MAX.
ERROR_NOT_ENOUGH_MEMORY | Insufficient memory resources are available to complete the operation.
ERROR_NO_DATA | No addresses were found for the requested parameters.
Other | Use FormatMessage to obtain the message string for the returned error.

For instance, here is a snippet from the example C++ code on https://msdn.microsoft.com/en-us/library/windows/desktop/aa365915(v=vs.85).aspx

```
        printf("Call to GetAdaptersAddresses failed with error: %d\n",
               dwRetVal);
        if (dwRetVal == ERROR_NO_DATA)
            printf("\tNo addresses were found for the requested parameters\n");
        else {

            if (FormatMessage(FORMAT_MESSAGE_ALLOCATE_BUFFER |
                    FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS, 
                    NULL, dwRetVal, MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),   
                    // Default language
                    (LPTSTR) & lpMsgBuf, 0, NULL)) {
                printf("\tError: %s", lpMsgBuf);
                LocalFree(lpMsgBuf);
                if (pAddresses)
                    FREE(pAddresses);
                exit(1);
            }
        }
```

The same applies for instance to net_if_stats.

If you agree, I could give it a try.

**Comment by giampaolo** [comment]
Sure, just make a PR.

**Comment by giampaolo** [comment]
Closing out as outdated.
