### ISSUE TITLE
Windows 10 AccessDenied: psutil.AccessDenied

### ISSUE THREAD

**Issue by nikitaverbis** [giampaolo/psutil#1264]
Hi found a bug (from ver 5.1) which in 5.4.3 still exist. 

**OS:** Windows 10 x64.
**Python version(s):** Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32 ; Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32.
**Module version(s):** psutil-5.1.x, psutil-5.4.3.
**Run:** cmd.exe as admin, then run python script. User in Admin group.
 
**Example code:**
import psutil
...
ps_process = psutil.Process(pid=nv_process.pid)
process['username'] = ps_process.username() **# See Error 1 Output**
_cmdline = ps_process.cmdline() **# See Error 2 Output**

**Error 1 Output:**
>File "C:\Python27\lib\site-packages\psutil\__init__.py", line 691, in username
>    return self._proc.username()
>  File "C:\Python27\lib\site-packages\psutil\_pswindows.py", line 638, in wrapper
>    raise AccessDenied(self.pid, self._name)
>AccessDenied: psutil.AccessDenied (pid=1144)

**Error 2 Output:**
> _cmdline = ps_process.cmdline()
>      File "C:\Python27\lib\site-packages\psutil\__init__.py", line 666, in cmdline
>    return self._proc.cmdline()
>     File "C:\Python27\lib\site-packages\psutil\_pswindows.py", line 638, in wrapper
>    raise AccessDenied(self.pid, self._name)
>AccessDenied: psutil.AccessDenied (pid=1144)

**Comment by giampaolo** [comment]
That's not a bug. From doc FAQs:
http://psutil.readthedocs.io/en/latest/#faqs

Q: Why do I get AccessDenied for certain processes?
A: This may happen when you query processess owned by another user, especially on OSX and Windows. Unfortunately there’s not much you can do about this except running the Python process with higher privileges. On Unix you may run the the Python process as root or use the SUID bit (this is the trick used by tools such as ps and netstat). On Windows you may run the Python process as NT AUTHORITY\SYSTEM or install the Python script as a Windows service (this is the trick used by tools such as ProcessHacker).
