### ISSUE TITLE
Docs: What is "snic"

### ISSUE THREAD

**Issue by guettli** [giampaolo/psutil#1273]
Please explain what "snic" means in the context of psutil.

Up to now I could not find a glossary in the docs.

**Comment by giampaolo** [comment]
I suppose you refer to the namedtuple name of `net_if_addrs` and `net_if_stats` functions. It stands for "system network interface card". With that said, nameduple names are not really important. They are there only because namedtuple construction requires them.

**Comment by guettli** [comment]
I am not the first person who has this question: https://stackoverflow.com/questions/45024490/what-is-a-snic-in-the-python-psutil-module

But I don't want to make more noise then necessary. If someone searches for "snic psutil" will find this issue and will find what he searched for.

Thank you for your answer.

**Comment by giampaolo** [comment]
In case of `net_if_stats()` the `snic` name is correct as it refers to a single entity (the network interface).
In case of `net_if_addrs()` it's indeed a bit misleading. It's probably better to rename it to `snicaddr`.

**Comment by giampaolo** [comment]
I see. I agree the name is a bit misleading indeed. It should be `snicaddr`.

**Comment by giampaolo** [comment]
Done.
