### ISSUE TITLE
MacOS thread times are incorrect since they only consider microseconds

### ISSUE THREAD

**Issue by nikhilm** [giampaolo/psutil#1278]
On MacOS, psutil uses only the microseconds field here https://github.com/giampaolo/psutil/blob/master/psutil/_psutil_osx.c#L1072. 

The struct also has a seconds field, which should be added to the return value.

**Comment by giampaolo** [comment]
It's too specific and only OSX has it. I prefer not to.

**Comment by nikhilm** [comment]
I don't understand why this was closed. The `threads()` function is supported on all platforms, but on MacOS it is returning incorrect values for the thread run times. This issue is a request to fix that by returning

```
basic_info_th->user_time.seconds + (float)basic_info_th->user_time.microseconds / 1000000.0,
```
instead of
```
 (float)basic_info_th->user_time.microseconds / 1000000.0,
```

and similar for the system time.

**Comment by giampaolo** [comment]
Oh, sorry, I thought the request was to add "microseconds" as a new field for the returned namedtuple.
