### ISSUE TITLE
linux service

### ISSUE THREAD

**Issue by DickLicha** [giampaolo/psutil#1282]
Hello, does this version support the view of Linux service? I have the need to use python to get services under Linux and to control it.

**Comment by giampaolo** [comment]
No, and I'm not sure how would you expect this to work. I don't think there's a practical use for a Python wrapper in this sense, or at least not as much as in Windows.

**Comment by giampaolo** [comment]
Are you on Ubuntu? In that case the cmdline utiilty to deal with service is... `service`. =)
You can invoke it from python via a subprocess.
