### ISSUE TITLE
feature request: cached Process object

### ISSUE THREAD

**Issue by lightydo** [giampaolo/psutil#1283]
It would be nice if Process object can be returned as cached, so that if the process no longer exist I can access all the functions which will returned the cached values.

e.g.:
p = psutil.Process(1, cached=True)

.....process died

p.cmdline() returns cached value

**Comment by giampaolo** [comment]
-1. Most methods of `Process` class are supposed to return fresh data, including `cmdline()` which on UNIX it can be changed after the process is created. There are a few other methods which never change and which are already cached: `pid`, `name()` (Windows only), `exe()`, `create_time()` and `ppid()` (Windows only). All the others can be altered after process creation.
