### ISSUE TITLE
Rename OSX to Darwin/macOS

### ISSUE THREAD

**Issue by JMY1000** [giampaolo/psutil#1286]
OSX is no longer the appropriate term for the OS. Things should be renamed to Darwin and macOS as appropriate.

<sup>Not exactly a high priority issue, but I thought it'd be worth putting into writing.</sup>

**Comment by giampaolo** [comment]
Mmm yeah. There are two things involved here. The "OSX" occurrences in code comments, docstrings and doc (and that's easy to change) and the `psutil.OSX` constant which is more debatable.
We either add `psutil.MACOS` and deprecate `psutil.OSX` or don't do anything. Maybe I'm a little bit more keen on not doing anything.

**Comment by giampaolo** [comment]
Note: https://www.apple.com/osx redirects to https://www.apple.com/macos/high-sierra/ so they're pretty serious about it.

**Comment by giampaolo** [comment]
OK, I changed my mind and decided to rename everything (including source files) in PR #1298 which introduces `psutil.MACOS` and deprecates `psutil.OSX`. If "macOS" really is the future I suppose "OSX" will gradually be forgotten. Even if it's gonna take years maybe it makes more sense to just be done with it immediately.
