### ISSUE TITLE
How to resolve ImportError: cannot import name '_psutil_linux'

### ISSUE THREAD

**Issue by pandyakavi** [giampaolo/psutil#1288]
I am installing apache airflow as per the installation steps provided at https://airflow.apache.org/start.html#quick-start

First Step - export AIRFLOW_HOME=~/airflow (No error)
Second Step - pip install apache-airflow (No error)
Third Step - airflow initdb ( Error - ImportError: cannot import name '_psutil_linux')

Detailed of error is on url - https://i.stack.imgur.com/3kxBY.png

Environment detail is as below- 
Python Version - Python 3.6.3 :: Anaconda custom (32-bit) 
Pip Version - 10.0.1 
Ubuntu Version - 14.04 LTS 
OS Type - 32 bits

How should I go on resolving it? I have already tried updating pip but that does not work.

**Comment by giampaolo** [comment]
Hello, sorry for the delay. That looks like a broken psutil installation. Try to `pip uninstall psutil`. Also, I wrote this script which should help solve this kind of situations:
https://github.com/giampaolo/psutil/blob/master/scripts/internal/purge_installation.py
Hope this helps.

**Comment by hongjin95** [comment]
> I am installing apache airflow as per the installation steps provided at https://airflow.apache.org/start.html#quick-start
> 
> First Step - export AIRFLOW_HOME=~/airflow (No error)
> Second Step - pip install apache-airflow (No error)
> Third Step - airflow initdb ( Error - ImportError: cannot import name '_psutil_linux')
> 
> Detailed of error is on url - https://i.stack.imgur.com/3kxBY.png
> 
> Environment detail is as below-
> Python Version - Python 3.6.3 :: Anaconda custom (32-bit)
> Pip Version - 10.0.1
> Ubuntu Version - 14.04 LTS
> OS Type - 32 bits
> 
> How should I go on resolving it? I have already tried updating pip but that does not work.
install the latest version module "aniso8601"

**Comment by tommydino93** [comment]
Upgrading psutil worked for me!
