### ISSUE TITLE
pip will not install psutil on windows 10, python37-32

### ISSUE THREAD

**Issue by dseaton216** [giampaolo/psutil#1297]
I believe the issue is another missing building wheel, similar to [this] (https://github.com/giampaolo/psutil/issues/706) thread. Please help.

**Comment by giampaolo** [comment]
Appveyor doesn't yet provide Python 3.7 so there aren't wheels for psutil+python3.7 on PYPI yet, hence pip attempts to use to compile psutil from sources.

**Comment by pfmoore** [comment]
For info, Appveyor now has Python 3.7. See https://www.appveyor.com/docs/build-environment/#python

**Comment by giampaolo** [comment]
I uploaded 3.7 wheels and also updated appveyor.yml which now builds wheels for 3.7
