### ISSUE TITLE
PROCFS_PATH for disk_partitions not functioning as expected.

### ISSUE THREAD

**Issue by srivignessh** [giampaolo/psutil#1307]
The disk_partitions function in _pslinux.py uses the C executable _psutil_linux.so.

The PROCFS_PATH parameter is unused in C executable and hence I still get the default disk_partitions for the path '/proc' instead of '/host/proc'.

```
from . import _psutil_linux as cext
def disk_partitions(all=False):
    """Return mounted disk partitions as a list of namedtuples."""
    .....
    .....
    retlist = []
    partitions = cext.disk_partitions()
    for partition in partitions:
        device, mountpoint, fstype, opts = partition
        .....
        ntuple = _common.sdiskpart(device, mountpoint, fstype, opts)
        retlist.append(ntuple)
    return retlist 
```

**Comment by srivignessh** [comment]
The '/etc/mtab' is a symbolic link to '/proc/mounts' so I get receive the metrics from '/proc' instead of modified PROCFS_PATH='/host/proc'.

**Comment by giampaolo** [comment]
Fixed.

**Comment by srivignessh** [comment]
Thanks

**Comment by Create-python** [comment]
/etc/matb 里面的字段都是什么含义？

**Comment by Create-python** [comment]
The fields in /etc/matb is what means？
