### ISSUE TITLE
No Sensor Information Available using a Raspberry Pi

### ISSUE THREAD

**Issue by PolynomialDivision** [giampaolo/psutil#1310]
Hi,
if I call

    psutil.sensors_temperatures()

on a raspberry pi 3, the result is always

    {}

Is there no information about CPU temperature?

**Comment by giampaolo** [comment]
Probably not due to `/sys/class/hwmon/hwmon*` directory structure not existing on raspberrypy (try to check)

**Comment by vzorglub** [comment]
The directory structure '/sys/class/hwmon/hwmon*` does not exits on the raspberry pi.
The processor temperature can be obtained with:

`cat /sys/class/thermal/thermal_zone0/temp` in mC

I don't have a Pi2 or Pi3 to test multicore

**Comment by giampaolo** [comment]
Re-opening. The goal should be to inspect `/sys/class/thermal/` tree in case `/sys/class/hwmon` does not exist.

**Comment by amanusk** [comment]
@giampaolo I tried looking into this a few days ago.
There was a discussion about this in `lm-sensors`: [#30](https://github.com/lm-sensors/lm-sensors/issues/30), that can be used as a reference. 
Also:
* I could not find a way to obtain `high` and `critical` temperatures from `/sys/class/thermal/`
* Although raspberry-pi has 4 cores reported by `psutil.cpu_count()`, there is only a file for `sys/class/thermal/thermal_zone0/`

Other than that, I could give this a try :)

**Comment by giampaolo** [comment]
Please do. If there's no way to obtain `high` and `critical` just set them to `None`.
