### ISSUE TITLE
Try use /sys/block/*/stat for disk_io_counters if /process/diskstats doesn't exist

### ISSUE THREAD

**Issue by LEAFERx** [giampaolo/psutil#1321]
For some VPS such as OPENVZ based, there is no /proc/diskstats, then psutil.disk_io_counters will fail.
But io Info's can still be collected by looking through /sys/block/*/stat. iostat has done that. Would you nicely add this feature for us who don't have /proc/diskstats? Really appreciate it :)

**Comment by giampaolo** [comment]
Why don't you make a PR instead? This is open source, you know... ;-)

**Comment by LEAFERx** [comment]
Yeah I know but I'm lack of coding experience especially those with Linux system stuff. Sure I will try, but I'm still hoping you could make elegant solution for us.
