### ISSUE TITLE
bogus create_time in LXC containers

### ISSUE THREAD

**Issue by mbanck** [giampaolo/psutil#1344]
The patroni acceptance tests fail under LXC cause patroni checks the (process start) timestamp in a pid file against `self.create_time`, and the latter is reported as several days in the future (note that the two timestamps are swapped by error, I opened an issue for that):

```
2018-09-26 05:20:50,478 INFO: Process 7166 is not postmaster, too much difference between PID file start time 1538286721.13 and process start time 1537939195
```

Some digging and the fact that the autopkgtest on ci.debian.net is run in LXC containers turned up https://github.com/lxc/lxcfs/issues/164 ("btime is not virtualized in /proc/stat") which sure sounds like the culprit, i.e. the `btime` that `create_time` uses as boot time/uptime for process creation time computation in https://github.com/giampaolo/psutil/blob/master/psutil/_pslinux.py#L1631 is bogus in this case.

**Comment by giampaolo** [comment]
Please try to be more clear about what the problem is and what you think psutil should do about it. Your bug report is confusing.

**Comment by mbanck** [comment]
Actually, there's already a comment about this here:

https://github.com/giampaolo/psutil/blob/master/psutil/_psutil_linux.c#L262

**Comment by giampaolo** [comment]
Clear. Sounds reasonable.

**Comment by wiggin15** [comment]
You mentioned https://github.com/lxc/lxcfs/issues/164, but it says there that they reverted btime virtualization in /proc/stat for exactly this reason (reverted in https://github.com/lxc/lxcfs/commit/72dd97f7ecfa1e118f4b33b3d694694fcf6fd120). Only LXC 2.0.7 seems to be affected by incorrect btime.

**Comment by mbanck** [comment]
Right, I digged a bit deeper and found that in the meantime as well. Problem is that 2.0.7 got shipped in Debian stable (and so far has not been fixed, although I am working on it), so maybe it is still worth fixing? But it's true that this needs some backtracking.
