### ISSUE TITLE
_common.py import issue due to conflict with other package.

### ISSUE THREAD

**Issue by inferno-chromium** [giampaolo/psutil#1348]
_common.py conflict with Google's grpc's _common.py when both of these packages are installed in a custom directory.
this causes an import error, is it possible to rename _common.py to something else to avoid conflicts. otherwise we have to install psutil system wide, which we want to avoid.

ImportError: cannot import name _common
at <module> (/b/clusterfuzz/src/third_party/psutil/__init__.py:41)

**Comment by inferno-chromium** [comment]
looks like other people hit this too, e.g. https://community.hortonworks.com/questions/77111/from-psutil-import-common-importerror-cannot-impor.html

**Comment by inferno-chromium** [comment]
or if we can remove https://github.com/giampaolo/psutil/blob/master/psutil/__init__.py#L40

**Comment by giampaolo** [comment]
Please paste the full traceback

**Comment by inferno-chromium** [comment]
I will see if i can create a reduced repro, otherwise stack is just internal code frames.
