### ISSUE TITLE
Get CPU frequency on FreeBSD 

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#1352]
It appears it's possible:
- https://github.com/netdata/netdata/blob/545d07eb78222a80124e9187e88921013ee403ea/collectors/freebsd.plugin/freebsd_sysctl.c#L538
- https://lists.freebsd.org/pipermail/freebsd-stable/2015-March/082042.html

On my virtualized FreeBSD 11 box though it appears the frequency metrics are not available:

```
vagrant@freebsd11~$  sysctl dev.cpu
dev.cpu.1.cx_method: C1/hlt
dev.cpu.1.cx_usage_counters: 9540
dev.cpu.1.cx_usage: 100.00% last 33074us
dev.cpu.1.cx_lowest: C2
dev.cpu.1.cx_supported: C1/1/0
dev.cpu.1.%parent: acpi0
dev.cpu.1.%pnpinfo: _HID=none _UID=0
dev.cpu.1.%location: handle=\_PR_.CPU1
dev.cpu.1.%driver: cpu
dev.cpu.1.%desc: ACPI CPU
dev.cpu.0.cx_method: C1/hlt
dev.cpu.0.cx_usage_counters: 17748
dev.cpu.0.cx_usage: 100.00% last 17867us
dev.cpu.0.cx_lowest: C2
dev.cpu.0.cx_supported: C1/1/0
dev.cpu.0.%parent: acpi0
dev.cpu.0.%pnpinfo: _HID=none _UID=0
dev.cpu.0.%location: handle=\_PR_.CPU0
dev.cpu.0.%driver: cpu
dev.cpu.0.%desc: ACPI CPU
dev.cpu.%parent: 
```

Not sure if I have to enable them similarly to CPU temperatures (https://www.cyberciti.biz/faq/freebsd-determine-processor-cpu-temperature-command/). @glebius, @sunpoet, @kostikbel  any idea? I'm also CC-ing @amanusk in case you want to give this a try.

**Comment by amanusk** [comment]
I can give this a try. From the code on `netdata` and this answer: https://stackoverflow.com/questions/9941664/how-to-get-real-cpu-frequency-while-system-running, it appears that only the information for cpu 0 is available, and it must by the same frequency for all CPUs.

This can also be enabled, similar to temperatures.

**Comment by giampaolo** [comment]
Nice. How do you enable it?

**Comment by amanusk** [comment]
According to this, https://forums.freebsd.org/threads/howto-freebsd-cpu-scaling-and-power-saving.172/ and other sources

You need to add `powerd_enable="YES"` to `/etc/rc.conf` 
I have tested this on my Thinkpad.
It would be great one of the FreeBSD experts can confirm this.
