### ISSUE TITLE
Two issues with secsleft.

### ISSUE THREAD

**Issue by NeuroAssassin** [giampaolo/psutil#1355]
For some reason, when I have a popup message saying my "computer is unplugged", it says that I have -2 seconds remaining until my computer dies.
![image](https://user-images.githubusercontent.com/42872277/47808928-ee7cad00-dd15-11e8-97ac-3fdd2f9a0aa2.png)
Also, when it is being put in the logs, it has this:
![image](https://user-images.githubusercontent.com/42872277/47808967-123ff300-dd16-11e8-9f59-ea8098f2ce55.png)
It keeps saying I have that many seconds left, even though google says that's over a century.
![image](https://user-images.githubusercontent.com/42872277/47809034-43b8be80-dd16-11e8-9baf-518160542d89.png)
Why is it doing this?

**Comment by giampaolo** [comment]
...and what does this have to do with psutil exactly? :D

**Comment by NeuroAssassin** [comment]
I'm getting the battery by psutil, by using psutil.sensors_battery() @giampaolo

**Comment by giampaolo** [comment]
Ah I get what you mean now. The number of seconds is too high.

**Comment by NeuroAssassin** [comment]
Closing issue because found source of problem; needed to enable bios in pre-boot menu of computer.
