### ISSUE TITLE
failed to build on MacOS Mojave

### ISSUE THREAD

**Issue by jesusch** [giampaolo/psutil#1361]
it seems MacOS Mojave did some changes on the /Lib Folder which causes the following compile error:

```
    clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=546 -DPSUTIL_OSX=1 -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c psutil/_psutil_common.c -o build/temp.macosx-10.13-x86_64-2.7/psutil/_psutil_common.o
    psutil/_psutil_common.c:9:10: fatal error: 'Python.h' file not found
    #include <Python.h>
             ^~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
```
Python.h can be found here: /System/Library/Frameworks/Python.framework//Versions/2.7/include/python2.7/Python.h

**Comment by giampaolo** [comment]
did you install Xcode?

**Comment by jesusch** [comment]
yes

**Comment by wiggin15** [comment]
@FelipeFrazao Looks like you encountered the following issue: https://apple.stackexchange.com/questions/254380/macos-mojave-invalid-active-developer-path
You need to _rerun_ `xcode-select --install`

@jesusch can you try the suggested follow-on fix in this link to "reset the path to Xcode"?

**Comment by giampaolo** [comment]
macOS wheels are now available. Closing.
