### ISSUE TITLE
threading.stack_size change not reflected in psutil.Process.memory_maps

### ISSUE THREAD

**Issue by Darkonaut** [giampaolo/psutil#1362]
Change for `threading.stack_size` doesn't seem to get detected by `psutil.Process.memory_maps`.
I'm on Ubuntu 18.04 with Python 3.6 and running the code below I would expect that `pmmap_grouped` would show `size=139264`, but it still shows `size=135168`. Using the process-id instead of the thread-id gives the same result. Is this a bug or am I missing something here?

```python
import ctypes
import threading

import psutil


def get_linux_tid():
    """System call gettid on Linux, returning thread-id."""
    return ctypes.CDLL('libc.so.6').syscall(186)


def print_info():
    print(
        [info for info
         in psutil.Process(pid=get_linux_tid()).memory_maps(grouped=True)
         if info.path == '[stack]']
    )


if __name__ == '__main__':

    threading.stack_size(139264)
    print(f'threading.stack_size(): {threading.stack_size()}')

    t = threading.Thread(target=print_info)
    t.start()
    t.join()
```

Output:
```
threading.stack_size(): 139264
[pmmap_grouped(path='[stack]', rss=98304, size=135168, pss=98304, shared_clean=0, shared_dirty=0, private_clean=0, private_dirty=98304, referenced=98304, anonymous=98304, swap=0)]
```

**Comment by giampaolo** [comment]
Mmm I'm not sure how to interpret that result as I've never used `threading.stack_size` (I'm curious: what is your use case?). My best guess is that `threading.stack_size(139264)` does not immediately reserve all the stack space. As far as psutil is concerned, it just parses what's inside `/proc/{PID}/smaps` and returns it. Try to `cat /proc/{PID}/smaps` and see if psutil report is correct. If it is then it's a question related to the Linux kernel.

**Comment by giampaolo** [comment]
I don't know, sorry. Judging from the output you pasted psutil correctly reports 274432 bytes (== 268KB) so I assume all is good on the psutil side of things. Thanks for the report though.
