### ISSUE TITLE
OSX psutil.disk_usage confusion

### ISSUE THREAD

**Issue by febalci** [giampaolo/psutil#1363]
macOS mojave 10.14:
Python 3.6.5
psutil 5.4.8

When using psutil.disk_usage i get the following from a network SMB mount to Synology NAS:

```
>>> psutil.disk_usage('/Volumes/music')
sdiskusage(total=1348853272576, used=-2783315886080, free=4132169158656, percent=-206.3)
```

The df gives the following for the same mount:

```
//xxxxxx@SYNOSERVER._smb._tcp.local/music    11224413640 3154137584 8070276056    29% 1577068790          4035138028   28%   /Volumes/music
```

As you can see, psutil is giving "-206.3 %" whereas it should be "28%". Is this a known bug??

**Comment by febalci** [comment]
'/Volumes/music' is a network fs from a Synology NAS, shared as SMB and mounted on OSX as SMB. Btw, the file system on Synology is "**btrfs**".

`>>> psutil.disk_usage('/Volumes/music')
sdiskusage(total=1348853272576, used=-2685843148800, free=4034696421376, percent=-199.1)`

And trying statvfs command:
`print (os.statvfs('/Volumes/music'))
os.statvfs_result(f_bsize=3670016, f_frsize=1024, f_blocks=1317239524, f_bfree=3939987400, f_bavail=3939987400, f_files=1317239522, f_ffree=3939987400, f_favail=3939987400, f_flag=2, f_namemax=255)`

The same negative results are valid for every SMB share i mount from the same Synology.

**Comment by giampaolo** [comment]
OK, so the problem here is that  `f_blocks=1317239524`, which is the total space, is lower than `f_ffree=3939987400`, which is the free space. Since `used` is calculated as `total - free` the value of `used` is negative.

**Comment by giampaolo** [comment]
> When using psutil.disk_usage i get the following from a network SMB mount to Synology NAS

I'm gonna close this out as this seems a bug with (or related to) macOS's SMB mount implementation. Unfortunately psutil cannot do anything about it.

**Comment by giampaolo** [comment]
@roachcord3  interesting. This seems unrelated with this ticket though. Can you please open a new ticket?

CC @mayeut : this seems somewhat related with https://github.com/giampaolo/psutil/pull/2152.

**Comment by giampaolo** [comment]
@roachcord3 can you please file a new issue? This seems important.
