### ISSUE TITLE
The children processes not shown

### ISSUE THREAD

**Issue by serser** [giampaolo/psutil#1367]
On ubuntu 14.04, children processes created with multiprocessing module are not listed using`psutil`, as well as `ps` command, but via `pstree` it is listed. However, children's PIDs found by `pstree -p` can be accessed from `psutil`. Could you fix this?

**Comment by giampaolo** [comment]
You should provide more info or a test script which reproduces the issue.

**Comment by giampaolo** [comment]
Closing out as outdated.
