### ISSUE TITLE
(Windows) CloseHandle() can override GetLastError()

### ISSUE THREAD

**Issue by ReneGrellert** [giampaolo/psutil#1370]
Hi,

we've disvovered the following behaviour in the following code of psutil_proc_create_time:

    if (! GetProcessTimes(hProcess, &ftCreate, &ftExit, &ftKernel, &ftUser)) {
        CloseHandle(hProcess);
        if (GetLastError() == ERROR_ACCESS_DENIED) {
            // usually means the process has died so we throw a
            // NoSuchProcess here
            return NoSuchProcess("");
        }
        else {
            return PyErr_SetFromWindowsErr(0);
        }
    }

We think, that CloseHandle resets the error stored in "GetLastError". This leads to "return PyErr_SetFromWindowsErr(0)" returning the Error raised in CloseHandle instead of the one of "GetProcessTimes".

We got there from another error, we could not understand:

    File "psutil\__init__.pyo" line 1440, in process_iter
    File "psutil\__init__.pyo" line 569, in is_running
    File "psutil\__init__.pyo" line 340, in __init__
    File "psutil\__init__.pyo" line 367, in _init
    File "psutil\__init__.pyo" line 698, in wrapper
    File "psutil\__init__.pyo" line 846, in create_time
    WindowsError: [Error 0]

Sometimes, there is an Error 2 instead. Maybe this comes from CloseHandle, since the handle might not 
be valid any more.

This problem occures with
python 2.7
pyutil 5.4.5
On Windows 7, 64 bit

Best regards,
René

**Comment by giampaolo** [comment]
It appears you're right. `CloseHandle` doc indeed states that. Good catch.

**Comment by giampaolo** [comment]
Also, there are other places with the same issue.

**Comment by giampaolo** [comment]
This is supposed to be fixed by c9988242c7138802e48ecd09837e95a06096aae6. Please let me know / reopen if you still think there's a problem.
