### ISSUE TITLE
process.children(recursive=True) should safely ignore some exited process in enumerate?

### ISSUE THREAD

**Issue by congzhangzh** [giampaolo/psutil#1381]
Hi Devs,

As title,  process.children(recursive=True)  should really be a nothrow behavior,  It's very strange that it throws a NoSuchProcess exception when I what to get all children but some process exist in the enumerate. 

As the next logical need children result to do more things, but itself throw an exception directly interrupt control flow? do children is just a reading behavior,  should be safe to call.
 
Maybe a more option can be added that ignore NoSuchProcess exception when do enumerate?

Tks,
Cong

**Comment by giampaolo** [comment]
What do you mean? `children()` is not supposed to raise `NoSuchProcess`. I can't see anything in the code which suggests that (`NoSuchProcess` is always catched and ignored).

**Comment by congzhangzh** [comment]
Hi @giampaolo 

I am sure it will throw this exception, I will give a stack trace later time.

Tks,
Cong

**Comment by giampaolo** [comment]
Closing this out as outdated.
