### ISSUE TITLE
how to diasable debug msg

### ISSUE THREAD

**Issue by Ratgor** [giampaolo/psutil#1385]
how to disable psutil debug messages?

I'm using psutil 5.4.7 with python 3.4 on winXP

and getting a lot of
"psutil-debug> GetActiveProcessorCount() not available;
usingGetNativeSystemInfo()"

I'm looking for python command (better) or environment variable, 
but can't find a solution,
not in docs https://psutil.readthedocs.io/en/latest/index.html#,
nor in notes https://github.com/giampaolo/psutil/issues/1173

e.g., this doesn't help (and, maybe, shouldn't):

in script.py:
...
try: print("PSUTIL_DEBUG = {}".format(os.environ["PSUTIL_DEBUG"]))
except Exception as e: print(e)

os.environ["PSUTIL_DEBUG"] = "0"
print("PSUTIL_DEBUG = {}".format(os.environ["PSUTIL_DEBUG"]))
...

in win powerShell:
PS ... > cmd /c "set PSUTIL_DEBUG=0 && python .\script.py"
PSUTIL_DEBUG = 0
PSUTIL_DEBUG = 0

**Comment by giampaolo** [comment]
Mmm this is weird. I think I already fixed this. Can you try upgrading to 5.4.8?

**Comment by Ratgor** [comment]
Thanks! 
I have upgraded to 5.4.8, that fix my problem.

With 5.4.8, if environ var PSUTIL_DEBUG doesn't exist or empty before first psutil import, 
there are no debug msgs.
To re-enable them I should create and set the var to a non-empty value.

**Comment by giampaolo** [comment]
Good. ;)
