### ISSUE TITLE
MacOS 10.14.1 - top.py script fails if a zombie process is present

### ISSUE THREAD

**Issue by aditisrinivas97** [giampaolo/psutil#1390]
For a zombie process, these are the fields : 

```
{'cpu_percent': None, 'cpu_times': None, 'username': 'aditisrinivas', 'memory_info': None, 'status': 'zombie', 'nice': None, 'memory_percent': None, 'name': 'a.out'}
```

The following line sorts based on `cpu_times` which is None in the case of a zombie process causing it to fail.

`processes = sorted(procs, key=lambda p: p.dict['cpu_percent'],reverse=True)`

**Comment by giampaolo** [comment]
Sorry this slipped under my radar. I guess you don't have the traceback right? =)

**Comment by giampaolo** [comment]
Closing as outdated / no response.
