### ISSUE TITLE
psutil.Process objects not pickle-able in 5.5.0

### ISSUE THREAD

**Issue by chrahunt** [giampaolo/psutil#1396]
In psutil 5.4.8 `psutil.Process` objects could be pickled. In 5.5.0 an error is raised:

```
[/tmp/psutil-test]$ python -V
Python 3.7.1
[/tmp/psutil-test]$ python -m venv .venv
[/tmp/psutil-test]$ . .venv/bin/activate
(.venv) [/tmp/psutil-test]$ pip install psutil
...
Successfully installed psutil-5.5.0
(.venv) [/tmp/psutil-test]$ python -c 'import psutil; import os; import pickle; pickle.dumps(psutil.Process(os.getpid()))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: can't pickle _thread.RLock objects
(.venv) [/tmp/psutil-test]$ pip install psutil==5.4.8
...
Successfully installed psutil-5.4.8
(.venv) [/tmp/psutil-test]$ python -c 'import psutil; import os; import pickle; pickle.dumps(
psutil.Process(os.getpid()))'
(.venv) [/tmp/psutil-test]$
```

**Comment by giampaolo** [comment]
Uhm... I get a different exception:

```
~/svn/psutil {master}$ python -c 'import psutil; import os; import pickle; pickle.dumps(psutil.Process(os.getpid()))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/pickle.py", line 1380, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "/usr/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "/usr/lib/python2.7/copy_reg.py", line 77, in _reduce_ex
    raise TypeError("a class that defines __slots__ without "
TypeError: a class that defines __slots__ without defining __getstate__ cannot be pickled
```

**Comment by chrahunt** [comment]
As mentioned [above](#issuecomment-457442739), my use case has (imo) a cleaner alternative so I'm not personally interested in a fix. If there doesn't appear to be general desire for this behavior then we can consider it as a documentation issue.

**Comment by giampaolo** [comment]
After thinking about it I am still of the opinion that `Process` objects should not be pickleable. Closing.

**Comment by giampaolo** [comment]
Also don't think it deserves a doc update. =)

**Comment by chrahunt** [comment]
Agreed, this issue should be enough.

**Comment by User087** [comment]
> In general terms, I'm not sure if pickling a Process instance is a good idea or should be supported. I think it's saner to serialize the process data instead (e.g. `pickle.dumps(Process().as_dict())`) and then re-create a brand new `Process` instance by using the PID. It is true that psutil 5.5.0 introduced a regression though. Point is I never considered supporting the pickling of a Process instance in the first place, so there were no tests for this (and hence the regression).

Is it guaranteed that `Process().as_dict()` would be picklable though, especially where `attrs` isn't specified and hence the dictionary includes all available attributes? Looking through the types of the attributes stored in the dict, there are a lot that are particular to `psutil`.

Also, one of the issues at hand is if you want to preserve the info about a currently existing process, whereas there's no guarantee if you only store the pid and then try to recreate the `Process` object that the process will still exist then for you to do so.

**Comment by giampaolo** [comment]
as_dict() returns python default standard types (int, list, etc.) plus namedtuples, which if I remember correctly are turned into standard tuples when serialized. So I see no problem there. 

I am not sure I understand your second paragraph. If you want to preserve process info as_dict() is what you want. You should not store the PID since it can disappear at any time on your platform, and is meaningless if you serialize it and send it to another platform to recreate a Process object.

**Comment by User087** [comment]
> as_dict() returns all standard types (int, list, etc.) plus namedtuples, which if I remember correctly are turned into plain tuples when serialized. So I see no problem there.
Okay, I was just wondering as I saw e.g. the `uids` attribute is of type `psutil._common.puids`, `cpu_times` is of type `psutil._pslinux.pcputimes`, etc, wasn't sure what sort of classes those were and hence whether they too were picklable.

> I am not sure I understand your second paragraph. If you want to preserve process info as_dict() is what you want. You probably should not trust the PID too much since it can disappear at any time on your platform, and is meaningless if you serialize it and send it to another platform to recreate a Process object.
That was just in reference to relying on the pid to reconstruct the `Process` which I thought was alluded to in your post.
