### ISSUE TITLE
Unable to install within a Conda env with python7

### ISSUE THREAD

**Issue by vlavorini** [giampaolo/psutil#1399]
Hi, 

   As in the title, if I run `pip install` within the virtual env I get this error:

    /usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin16.7.0/8.2.0/include-fixed/limits.h:194:15: fatal error: limits.h: No such file or directory

And if I exit the virtualenv, and install via conda: `conda install psutil` I see that conda try to downgrade Python:

    The following packages will be DOWNGRADED:

    python:                             3.7.0-hc167b69_0        --> 3.6.8-haf84260_0       
    twisted:                            18.7.0-py37h1de35cc_1   --> 17.5.0-py36_0          
    xlwt:                               1.3.0-py37_0            --> 1.2.0-py36h5ad1178_0   

Any way to solve this?

**Comment by giampaolo** [comment]
Never used conda but it looks like you're missing some system files. Does it work with plain Python + gcc (no conda)?

**Comment by vlavorini** [comment]
Hi, thank you for the reply!
Actually I found the issue is with a version of gcc installed with homebrew. I just deleted it and gone back to the gcc of the system, and everything worked.
Sorry for having forgot to update this issue!
