### ISSUE TITLE
is there a way to improve memory usage of psutil module?

### ISSUE THREAD

**Issue by AnkurTank** [giampaolo/psutil#1403]
We are using beaglebone black based custom board with 256MB RAM and 4GB eMMC.
We are running python2.7 on it.
We cross compiled and added psutil package, When I started checking memory usage it is very high for psutil, I checked as follows,
**1. On interactive terminal**
When interactive terminal is started without loading any module I checked memory usage of python process and it is as follows
```
# cat /proc/20748/status | grep -i "vmrss\|vmpeak"
VmPeak:     5452 kB
VmRSS:      4164 kB `
```
After that  I loaded psutil and checked memory usage as follows
```>>> import psutil
```
```
# cat /proc/20748/status | grep -i "vmrss\|vmpeak"
VmPeak:     8596 kB
VmRSS:      6416 kB`
```

So increase in memory is usage is ~2MiB which is high considering embedded linux environment.

Same thing I tested with following script

```import os
import subprocess


pid = os.getpid()
ps = subprocess.Popen(('cat', '/proc/%s/status' % pid), stdout=subprocess.PIPE)
vmrss_output = subprocess.check_output(('grep', 'VmRSS'), stdin=ps.stdout)
ps = subprocess.Popen(('cat', '/proc/%s/status' % pid), stdout=subprocess.PIPE)
vmpeak_output = subprocess.check_output(('grep', 'VmPeak'), stdin=ps.stdout)
print("Before import psutil {} {}".format(vmrss_output, vmpeak_output ))


import psutil

ps = subprocess.Popen(('cat', '/proc/%s/status' % pid), stdout=subprocess.PIPE)
vmrss_output = subprocess.check_output(('grep', 'VmRSS'), stdin=ps.stdout)
ps = subprocess.Popen(('cat', '/proc/%s/status' % pid), stdout=subprocess.PIPE)
vmpeak_output = subprocess.check_output(('grep', 'VmPeak'), stdin=ps.stdout)
print("After import psutil {} {}".format(vmrss_output, vmpeak_output ))`
```

And outtput is as follows,

```
# python non_interfactive_psutil_memusage.py 
Before import psutil VmRSS:         4504 kB
 VmPeak:            7224 kB

After import psutil VmRSS:          6352 kB
 VmPeak:            9612 kB
```

And as shown above memory usage increases ~2MiB.

Is it possible to configure psutil module and add whatever part is required e.g. networking, process etc?
is it possible to trim the module somehow ?

I had put-up question in [stakeoverflow](https://stackoverflow.com/questions/54485218/how-to-reduce-memory-usage-of-psutil-package)  and other developers marked it as duplicate. 

Please close issue if it is not valid question.

**Comment by AnkurTank** [comment]
Also is there a any way to find out stable tag ? or latest tag is always stable ?

**Comment by giampaolo** [comment]
Mmm... no, I can't think of any way to reduce the 2MB of psutil. I suppose most of that is due to shared libraries or other stuff which sums up when importing other stdlib which psutil necessarily has to depend on. 

What do you mean about tags? GIT tags? Those are pushed on every new release (see `git tags`). As for PYPI, psutil of course has a specific version number on each new release, which you can retrieve when e.g. installing psutil via pip (e.g. `pip install psutil==5.5.0`).

Hope this helps.

**Comment by AnkurTank** [comment]
Thank you for looking into issue.
Alright, we will try to limit `psutil  usage in our board so that memory usage is not of that much impact.

Yup I meant GIT Tags,
We are not installing psutil through pip, we are cloning the repo and cross compiling it for our platform. 
So we were wondering what would be the stable branch/tag we should be using. Currently we pulled `release-5.5.0` tag and using it.

**Comment by giampaolo** [comment]
Yes, if you retrieve/install psutil via GIT, tags are the correct way to pin-point a specific version. Hope you'll solve the memory issue. Closing this out for now. Be good. ;-)
