### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/anaconda3/lib/python3.6/site-packages/psutil-5.4.8.dist-info/METADATA'

### ISSUE THREAD

**Issue by jwfu** [giampaolo/psutil#1406]
Issue discovered in conda 3.6 installation.

When running Jupyter Notebook, following error prevented kernel starting:

```
ModuleNotFoundError: No module named 'prompt_toolkit.formatted_text'
```
Based on [this](https://github.com/jupyter/notebook/issues/4070), I tried to `pip install -U jupyter_console`.  This failed, giving 

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/anaconda3/lib/python3.6/site-packages/psutil-5.4.8.dist-info/METADATA'
```

Upon further investigation, the reason for this is that there was as subfolder created with another `psutil-5.4.8.dist-info` created.  Thus, by moving the files out of this nested subfolder, everything worked again.

KO: `/home/user/anaconda3/lib/python3.6/site-packages/psutil-5.4.8.dist-info/psutil-5.4.8.dist-info/METADATA`

OK: `/home/user/anaconda3/lib/python3.6/site-packages/psutil-5.4.8.dist-info/METADATA`

I wasn't manually doing anything in these package folders; any idea what automatic process (suspect `pip`-related) could have caused this?

**Comment by giampaolo** [comment]
Mmm not sure what to think of this. METADATA file is not part of psutil source code.

**Comment by jwfu** [comment]
I'll file with `pip`.
