### ISSUE TITLE
Trying to start a new process crashes the Python interpreter on FreeBSD 12

### ISSUE THREAD

**Issue by TiberiuD** [giampaolo/psutil#1411]
Software versions:
Python: **3.7.2**
FreeBSD: **12.0-RELEASE r341666**
Psutil: **5.5.0**

Trying to use psutil.Popen() leads to the Python interpreter crashing on FreeBSD 12.

For example, trying to start the **echo** executable leads to the result below:
![image](https://user-images.githubusercontent.com/10258201/52842481-e94a3f00-3107-11e9-957d-411196f8c4a5.png)

If I try to start **wget**, the interpreter doesn't crash right away sometimes. A stack trace is also sometimes printed (I had to try this on Python 3.6 to trigger it):
![image](https://user-images.githubusercontent.com/10258201/52842661-7a211a80-3108-11e9-9c67-d14c0b61832c.png)

**Comment by giampaolo** [comment]
Interesting. As for the first issue, what happens if you use `subprocess.Popen("echo")` instead?

**Comment by TiberiuD** [comment]
Sorry for the late reply...

It works as it should!
![image](https://user-images.githubusercontent.com/10258201/53047306-cbc7fd00-349a-11e9-89cc-f20dd2e1f194.png)

**Comment by giampaolo** [comment]
@TiberiuD I pushed https://github.com/giampaolo/psutil/commit/842a50538fb518291079ab5f245cca4c63813cb2 which I think it should fix the problem. Could you please give it a try?

**Comment by giampaolo** [comment]
I assume this is fixed. Closing.
