### ISSUE TITLE
[SunOS] AttributeError: 'Process' object has no attribute 'ionice'

### ISSUE THREAD

**Issue by Mno-hime** [giampaolo/psutil#1502]
**Platform**
* OpenIndiana 2018.10 (`illumos-e742aada08`) in Global Zone
`uname -a`: `SunOS lenovo 5.11 illumos-e742aada08 i86pc i386 i86pc`
* library/python/psutil@5.6.0-2018.0.0.0

**Bug description**

`ntpviz` from ntpsec 1.1.3 fail to start with:

```
{global} newman@lenovo:~ $ ntpviz 
Traceback (most recent call last):
  File "/usr/bin/ntpviz", line 1557, in <module>
    p.ionice(psutil.IOPRIO_CLASS_IDLE)
AttributeError: 'Process' object has no attribute 'ionice'
```
Reproducer:

```python
import os
import psutil
p = psutil.Process(os.getpid())
p.ionice(psutil.IOPRIO_CLASS_IDLE)
```

Could be just a wrong assumption in ntpsec? And it should be tested for `ionice()` first?

I tested the very same code on openSUSE Leap 15.0 and it worked.

**Comment by giampaolo** [comment]
ionice() is Linux and Windows Vista+ only
