### ISSUE TITLE
[MAC OS] virtual memory

### ISSUE THREAD

**Issue by kkfeng10** [giampaolo/psutil#1503]
**Platform**
* MAC OS
* psutil 5.6.2

**Bug description**
When I using ```psutil.virtual_memory()``` to get the used memory value, I print the value like this
```
svmem(total=8589934592, available=2204819456, percent=74.3, used=4809887744, free=14966784, active=2187837440, inactive=2189017088, wired=2622050304)
```
The description of this function is 
```
     - used:
        memory used, calculated differently depending on the platform and
        designed for informational purposes only:
        macOS: active + inactive + wired
        BSD: active + wired + cached
        Linux: total - free
```
But the value of real used seems like ```active+wired```, don't you think so?
This is a nice tool, thank you very much!

```python
code to reproduce the problem (if any)
```

**Test results**
```
output of `python -c psutil.tests` (failures only, not full result)
```
{ you may want to do this in order to discover other issues affecting your platform }
{ if failures look unrelated with the issue at hand open another ticket }

**Comment by giampaolo** [comment]
Mmm.. where did you get that from? Doc doesn't state that.

**Comment by kkfeng10** [comment]
psutil/__init__.py
Line 2056 state this

**Comment by giampaolo** [comment]
OK, a docstring bug then. I'll fix it. =)
