### ISSUE TITLE
[Windows] cpu_count(logical=False) can lead to Access Violation (Segfault)

### ISSUE THREAD

**Issue by tcm-marcel** [giampaolo/psutil#1506]
**Platform**
* Windows Server 2008 R2, version 6.1
* Windows Server 2016 Standard, version 10.0.14
* psutil 5.4.7

**Bug description**
Segfault when calling `psutil.cpu_count(logical=False)` This happened several times in our environment, but still super rare (a few out of hundreds). 

Unfortunately I can't provide any repro. Feel free to close the issue if there are no obvious problems in the c code. 

```
Windows fatal exception: access violation

Current thread 0x00001b10 (most recent call first):
  <venv>\lib\site-packages\psutil\_pswindows.py", line 292 in cpu_count_physical
  <venv>\lib\site-packages\psutil\__init__.py", line 1573 in cpu_count
```

```python
psutil.cpu_count(logical=False)
```

**Comment by giampaolo** [comment]
This may be related to https://github.com/giampaolo/psutil/pull/1480.
CC-ing @samertm in case he wants to take a look at this.

**Comment by tcm-marcel** [comment]
#1480 should be part of psutil 5.6.2, is this correct? I can update psutil and wait if we hit it again.

**Comment by giampaolo** [comment]
Correct. You should try if you can reproduce it with 5.6.1.

**Comment by tcm-marcel** [comment]
It didn't appear again after updating to psutil 5.6.2 so far, so I guess it was the problem solved by @samertm. Thanks you!
