### ISSUE TITLE
getloadavg() from psutil 5.6.2 crashes on Windows 10 with python 3.7.x 

### ISSUE THREAD

**Issue by bmxp** [giampaolo/psutil#1510]
**Platform**
* psutil 5.6.2
* Python 3.7.1 x32 or Python 3.7.3 x32
* Operating System Windows 10 Pro Build 1809 (Build 17763.437) German Languange

**Bug description**
Using the function psutil.getloadavg() introduced here https://github.com/giampaolo/psutil/pull/1485 kills the interpreter:

```
import psutil
a = psutil.getloadavg()
```
Wait a couple of seconds and Python will say quietly good bye

The problem does not show 
* on Windows Server 2012 R2 using either Python 3.5.2 and 3.6.6 
* Windows 10 build 1607 with Python 3.6.6 and even 3.7.3 x64

I think it's a combination between Windows 10 Build 1809 (German language) and Python 3.7.x

**Comment by AgainCrazyCode** [comment]
Yeah , me too

**Comment by giampaolo** [comment]
@ammaraskar could you take a look at this? I can't reproduce.

**Comment by bmxp** [comment]
I have checked again after three updates to Windows 10: In the meantime the following updates were applied to the test computer:

* 16.5.2019 KB4495590
* 16.5.2019 KB40

**Comment by HyroKayaa** [comment]
Hello,
Same bug, except i made the windows update 2 days ago (haven't tested .getloadavg() before update).
Seems like after executing getloadavg() i have 5 seconds before windows throw me a "Python has stopped working".
As if (excerpt from psutil.getloadavg() docs) "On Windows this is emulated by using a Windows API that spawns a thread which updates the average every 5 seconds" was a part of the problem.

**Comment by ammaraskar** [comment]
Could you try the command:

`typeperf "System\Processor Queue Length" -si 5` in cmd.exe and report back what the output is?

**Comment by HyroKayaa** [comment]
Output : 

"(PDH-CSV 4.0)","\\TOXICITY-LAPTOP\System\Processor Queue Length"
"06/15/2019 00:59:20.599","0.000000"
"06/15/2019 00:59:25.609","0.000000"
"06/15/2019 00:59:30.621","0.000000"
"06/15/2019 00:59:35.631","0.000000"
"06/15/2019 00:59:40.645","0.000000"
"06/15/2019 00:59:45.652","0.000000"
"06/15/2019 00:59:50.665","0.000000"
Exiting, please wait...                         
The command completed successfully.

getloadavg() launched near 00:59:30 and crashed near 00:59:35.
getloadavg() worked one time while i was running the command (one time for 20+ test) tried to reproduce what i did, but couldn't achieve it again.

**Comment by ammaraskar** [comment]
If you've still got this behavior, could you follow the instructions here https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a#method2 to have Python spit out a dump file when it crashes? Please try that and upload the dump that gets created.

**Comment by ammaraskar** [comment]
If you've still got this bug, could you please have Windows create a dump file for the Python crash following the instructions here https://helgeklein.com/blog/2018/10/creating-an-application-crash-dump/

Please upload the dump after it crashes.

**Comment by Braj-120** [comment]
I am also facing the same issue.

OS Name	Microsoft Windows 10 Enterprise x64
Version	10.0.17763 Build 17763
Python 3.7.4 
psutil 5.7.0

The process silently exits without error. It seems to be working for about 10 seconds and then the entire process stops.

**Comment by ammaraskar** [comment]
Could you try following the instructions above and see if it produces a crash dump?

**Comment by Braj-120** [comment]
Sorry. It is a secured system and I cannot take out dumps from it.

**Comment by sisalik** [comment]
Hi there, I'm experiencing the same issue in a very similar environment. Here's a [crash dump](https://github.com/giampaolo/psutil/files/4833268/python.exe.11072.zip), I hope that helps!

**Comment by ammaraskar** [comment]
Thank you so much for the crash dump @sisalik, would you mind giving the latest release a shot and see if the problem is gone? https://pypi.org/project/psutil/#history

**Comment by sisalik** [comment]
Wow yes, looks like it is! Thanks a lot, you guys are doing a great job :)
