### ISSUE TITLE
[MacOS] psutil.net_connections() Operation not supported on socket

### ISSUE THREAD

**Issue by rtkaratekid** [giampaolo/psutil#1512]
**Platform**
* MacOS X - Mojave
* psutil version - 5.6.1

**Bug description**
Running psutil.net_connections() a few thousand times while monitoring the machine leads to this error message. It looks like there is an issue in the _psosx.py file that is trying to run cext.proc_connections() on a socket

```
traceback message (

  File "macos_agent.py", line 86, in ip_receive
    connections = psutil.net_connections()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psutil/__init__.py", line 2248, in net_connections
    return _psplatform.net_connections(kind)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psutil/_psosx.py", line 252, in net_connections
    cons = Process(pid).connections(kind)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psutil/_psosx.py", line 339, in wrapper
    return fun(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psutil/_psosx.py", line 528, in connections
    rawlist = cext.proc_connections(self.pid, families, types)
OSError: [Errno 102] Operation not supported on socket

)
```

```python3
connections = psutil.net_connections()
```

**Test results**
```
# No failures
```

**Comment by giampaolo** [comment]
Hard to tell where this comes from as the C function implementing it is quite big. My best guess is that it originates either from here:
https://github.com/giampaolo/psutil/blob/b31f3bf778004f1eae6ac552dd8eb8419664ac73/psutil/_psutil_osx.c#L1106-L1108
...or here:
https://github.com/giampaolo/psutil/blob/b31f3bf778004f1eae6ac552dd8eb8419664ac73/psutil/_psutil_osx.c#L1116-L1119
You should `git clone` psutil repo, add a `printf()` statement, recompile (`make install`) and try it yourself though 'cause I can't reproduce it.

**Comment by electrozen** [comment]
I confirm the behavior still exists with ps_util 5.7.0 and macOS 10.15.3 when looping a thousand times over this:
`            for proc in psutil.process_iter():
                info = proc.as_dict(attrs=['pid', 'name', 'username', 'connections'])`

> Operation not supported on socket
