### ISSUE TITLE
Provide a public method for getting a list of valid process attributes

### ISSUE THREAD

**Issue by orodbhen** [giampaolo/psutil#1515]
Currently, the only way to determine if an attribute is valid is by triggering a `ValueError` and parsing the error string for the attribute name. As the string could change, this isn't a good option. 

Alternatively, it would be better to provide a public method of the Process class that, for example, returns the value of `_as_dict_attrnames`.

Otherwise, when using the module in a larger program, you either have to provide your own list of allowable attributes to query for, or let your user figure it out through trial and error. What I'd like to be able to do in my program, is simply ignore the invalid attributes, and print a warning.

**Comment by giampaolo** [comment]
Are you talking about getting a list of strings to pass to `Process.as_dict(attrs=[...])`? For the record, right now you can get that via:
```python
>>> list(psutil.Process().as_dict().keys())
['status', 'cpu_num', 'num_ctx_switches', 'pid', 'memory_full_info', 'connections', 'cmdline', 'create_time', 'ionice', 'num_fds', 'memory_maps', 'cpu_percent', 'terminal', 'ppid', 'cwd', 'nice', 'username', 'cpu_times', 'io_counters', 'memory_info', 'threads', 'open_files', 'name', 'num_threads', 'exe', 'uids', 'gids', 'cpu_affinity', 'memory_percent', 'environ']
>>> 
```

**Comment by orodbhen** [comment]
An intuitively named method would be great, but that will work. Thank!

**Comment by giampaolo** [comment]
I think a brand new method is too much. The use case is legitimate though so I mentioned this in the doc though: 9d5ee03b5a0a088ce0e1426ad59137466116a895.
