### ISSUE TITLE
[CentOS 7] psutil.Popen issue, can't run scripts

### ISSUE THREAD

**Issue by AgainCrazyCode** [giampaolo/psutil#1522]
p = psutil.Popen(["cat /proc/cpuinfo | grep 'name' | cut -f2 -d: | uniq -c"], stdout=PIPE)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3/lib/python3.7/site-packages/psutil/__init__.py", line 1431, in __init__
    self.__subproc = subprocess.Popen(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/python3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: "cat /proc/cpuinfo | grep 'name' | cut -f2 -d: | uniq -c": "cat /proc/cpuinfo | grep 'name' | cut -f2 -d: | uniq -c"

**Comment by giampaolo** [comment]
You should add the source code but I suspect the problem here is you should have passed `shell=True`

**Comment by AgainCrazyCode** [comment]
> You should add the source code but I suspect the problem here is you should have passed `shell=True`

 p = psutil.Popen( [ "cat /proc/cpuinfo | grep 'name' | cut -f2 -d: | uniq -c": "cat /proc/cpuinfo | grep 'name' | cut -f2 -d: | uniq -c", vFilePathSrc ] , stdout=PIPE )

Thank you 

how to fix ?

**Comment by giampaolo** [comment]
It should be:
```python
p = psutil.Popen("cat /proc/cpuinfo | grep 'name' | cut -f2 -d: | uniq -c", shell=True, stdout=PIPE )
```

**Comment by AgainCrazyCode** [comment]
Thnak you 

psutil good for use
