### ISSUE TITLE
[Win 7] memory_full_info() throw Permission denied Error in 5.6.3

### ISSUE THREAD

**Issue by zhaozhongyu** [giampaolo/psutil#1537]
**Platform**
* Windows 7 professional service pack 1  
* 5.6.2 and 5.6.3

**Bug description**
```
>>> import psutil
>>> print(psutil.__version__)
5.6.3
>>> p = psutil.Process(2176)
>>> p.memory_full_info()
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\psutil\_pswindows.py", line 716, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\psutil\_pswindows.py", line 851, in memory_full_info
    uss = cext.proc_memory_uss(self.pid)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    p.memory_full_info()
  File "C:\Program Files\Python37\lib\site-packages\psutil\__init__.py", line 1190, in memory_full_info
    return self._proc.memory_full_info()
  File "C:\Program Files\Python37\lib\site-packages\psutil\_pswindows.py", line 718, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=2176)
```
```
traceback message (if any)
```

```python
code to reproduce the problem (if any)
```
>>> import psutil
>>> p = psutil.Process(2176)
>>> p.memory_full_info()

**Test results**
```
output of `python -c psutil.tests` (failures only, not full result)
```
{ you may want to do this in order to discover other issues affecting your platform }
{ if failures look unrelated with the issue at hand open another ticket }

**Comment by giampaolo** [comment]
That means you don't have permission to query that process. There is nothing you can do about it except perhaps using a user with more privilges.

**Comment by zhaozhongyu** [comment]
> That means you don't have permission to query that process. There is nothing you can do about it except perhaps using a user with more privilges.

![image](https://user-images.githubusercontent.com/8148957/59502517-89ef1680-8ed0-11e9-904d-b5c709e36d57.png)
i run it with admin user, and memory_info() works well.  permission is not problem.

**Comment by giampaolo** [comment]
I know. It happens also with Administrator.

**Comment by zhaozhongyu** [comment]
but i can't get chrome process memory_full_info, and cmd.exe memory_full_info..
do you mean microsoft have different user permission policy on win 7? because my win10 computer works well.

**Comment by giampaolo** [comment]
memory_full_info() inspects and walks through process virtual memory pages, which is something which requires requiring high privileges on any OS. It is possible that win 7 and 10 have different security policies, yes.

**Comment by zhaozhongyu** [comment]
![image](https://user-images.githubusercontent.com/8148957/59510553-91b9b580-8ee6-11e9-8a6c-af2c41c709a7.png)
it can work in 5.4.8...

**Comment by bulgunduz** [comment]
Hi haozhongyu,
wonder if you were able to find the solution please?
I am getting the same error for process.memory,exe,open_files,memory_info queries.
I am using MacOSx and Python 3.10.4
