### ISSUE TITLE
cannot install pip

### ISSUE THREAD

**Issue by 648643579** [giampaolo/psutil#1548]
OS: Linux Mint v19.1 Mate
Hi, cannot install pip,
ERROR: https://pastebin.com/raw/F8r6f37R
what is the correct procedure for installing pip?

**Comment by giampaolo** [comment]
You need to use higher privileges (sudo).

**Comment by 648643579** [comment]
@giampaolo still the same problem: https://pastebin.com/raw/E29vZYYe

**Comment by giampaolo** [comment]
``` wget https://bootstrap.pypa.io/get-pip.py -O - | sudo python```
