### ISSUE TITLE
Include scripts in PyPI packages

### ISSUE THREAD

**Issue by itamarst** [giampaolo/psutil#1560]
The scripts/ directory is full of tools that are very useful—but they're not included in what gets installed via `pip`. It would be great if they were, probably with names like `psutil-top` so they don't conflict.

If you're interested I can probably do a PR.

**Comment by giampaolo** [comment]
Those scripts didn't receive enough love so that they can be installed. For instance, most of them don't even have a cmdline parser. I don't think it's worth it, sorry.
