### ISSUE TITLE
[windows] 获取系统磁盘信息

### ISSUE THREAD

**Issue by navysummer** [giampaolo/psutil#1577]
1.获取磁盘的平均队列长度
2.磁盘I/O使用率
3.平均I/O服务时长
4.读操作平均耗时
5.写操作平均耗时
6.平均读操作大小
7.平均写操作大小

**Comment by navysummer** [comment]
能添加以上信息的获取或者间接提供计算的相关参数吗？

**Comment by navysummer** [comment]
![image](https://user-images.githubusercontent.com/17807236/64140860-941e1280-ce38-11e9-8781-8b4dded50df8.png)

**Comment by giampaolo** [comment]
Not sure what you're asking here, sorry.
