### ISSUE TITLE
[OS] title

### ISSUE THREAD

**Issue by FrankUnlimited** [giampaolo/psutil#1593]
**Platform**
* { windows 10 }     (import ( windows, ...))
* { psutil 5.6.3}  (use "pip 10.0.1")

**Bug description**
{ Successfully Installed in the command prompt. However will not import in Python Idle 3.7.0 } Do i have to go to an earlier version of Python?

```
traceback message (if any)
```

```python
code to reproduce the problem (if any)
```

**Test results**
```
output of `python -c psutil.tests` (failures only, not full result)
```
{ you may want to do this in order to discover other issues affecting your platform }
{ if failures look unrelated with the issue at hand open another ticket }

**Comment by giampaolo** [comment]
Looks like a problem with your environment, not psutil. Closing.
