### ISSUE TITLE
[Windows] disk_partitions(all=True) only returns mountpoints on drives where it first finds one

### ISSUE THREAD

**Issue by ian28223** [giampaolo/psutil#1598]
**Platform**
* detected on Windows Server 2019 but may not be isolated to that version
* psutil 5.6.3

**Bug description**

Somewhat related to https://github.com/giampaolo/psutil/pull/1192
Above works but once it finds a mountpoint on a drive letter, it will not look for mountpoints on next drive letters.

Example:
Given 3 drive letters, `C:`, `D:`, `Z:`.

- case 1: mountpoints on C, D and Z
  - mount `C:/mnt1/` - detected/returned by psutil
  - mount `C:/mnt2/` - detected/returned by psutil
  - mount `D:/mnt3/` - not returned
  - mount `Z:/mnt4/` - not returned

- case 2: no mount points on C:
  - mounts in `C:/` - none
  - mount `D:/mnt3/` - detected/returned by psutil
  - mount `Z:/mnt4/` - not returned

Expectation is that all mountpoints from all drives are returned.

```
traceback message (if any)
```

```python
import psutil
psutil.disk_partitions(all=True)
```

**Comment by rankaiyx** [comment]
https://github.com/giampaolo/psutil/issues/1776
I meet the same trouble

**Comment by ajdurr** [comment]
Same issue I am seeing

**Comment by rankaiyx** [comment]
> Same issue I am seeing
You can try this the cmd command:
diskperf -y

**Comment by ajdurr** [comment]
I reviewed #1776 and it does not appear related to this one.
