### ISSUE TITLE
Windows 10 `virtual_memory()` giving inaccurate information title

### ISSUE THREAD

**Issue by Legorooj** [giampaolo/psutil#1608]
OS and psutil version
* Windows 10
* psutil version 5.6.3

## Error
Running `virtual_memory()` is giving me a total of `17080635392` bytes of memory capacity, (17.08 GB), but I know that I have only 16 gb of memory;

![Task Manager 20_10_2019 21_27_25](https://user-images.githubusercontent.com/50370070/67158834-9e608580-f380-11e9-99f9-478f76c62c08.png)

**Comment by giampaolo** [comment]
Bytes to giga bytes conversion:

```python
>>> 17080635392 / 1024 / 1024 / 1024
15.907581329345703
```

All good here.

**Comment by Legorooj** [comment]
@giampaolo apologies Bing gave me the wrong formula...

**Comment by schwaerz** [comment]
Just curious: Shouldn't it be 17196646400 for 16 GB?

At least this is what I'd expect. On Linux, `free` exactly returns the physical memory available - in contrast to `virtual_memory().total`.

On Windows `virtual_memory().total` returns little bit less than the actual amount of total memory, too. Is this expected?

**Comment by giampaolo** [comment]
>  On Linux, free exactly returns the physical memory available - in contrast to virtual_memory().total.

Weird. We have a test case which makes sure psutil's `total` vmem is equal to the value reported by `free` CLI utility:
https://github.com/giampaolo/psutil/blob/2d880c8a3bf9c239318bb283c52ce177f37244a7/psutil/tests/test_linux.py#L270-L273
Does this test fail for you? You can run tests with `python3 -m psutil.tests`.
