### ISSUE TITLE
module 'psutil' has no attribute 'sensors_temperatures'

### ISSUE THREAD

**Issue by flypigarmy** [giampaolo/psutil#1622]
* Dell R730xd
* Windows Server 2019 1809
* Python 3.7.4
* psutil version 5.6.5

>>> psutil.sensors_temperatures
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'psutil' has no attribute 'sensors_temperatures'

**Comment by giampaolo** [comment]
It's not available on Windows. RTFM. ;)
