### ISSUE TITLE
[OS] docs of psutil.virtual_memory()

### ISSUE THREAD

**Issue by guettli** [giampaolo/psutil#1633]
Please add a note to the docs:

> psutil.virtual_memory()
> Return statistics about system memory usage as a named tuple including the following fields, 
> expressed in bytes. Main metrics:
> total: total physical memory.

Source: https://psutil.readthedocs.io/en/latest/index.html#psutil.virtual_memory

Is `total` inclusive or exclusive swap?

**Comment by giampaolo** [comment]
Exclusive
