### ISSUE TITLE
[Linux] ppid_map fails if proc/stat/ is not accessible 

### ISSUE THREAD

**Issue by FabianHofmann** [giampaolo/psutil#1641]
If restrict cluster policies do not allow access to `proc/stat/`, the open_binary in [ppid_map](https://github.com/giampaolo/psutil/blob/0e1c78671b0ea0328bc87ea77081ef52e30b1d06/psutil/_pslinux.py#L1488) fails with an PermissionError which according to #1334 is correct. 

However is it possible to cover this case? A naive solution which worked for me is adding a PermissionError to the [exceptions](https://github.com/giampaolo/psutil/blob/0e1c78671b0ea0328bc87ea77081ef52e30b1d06/psutil/_pslinux.py#L1498). But I can imagine that this collides with other assumptions made here (as to see from the comments in the lines below)

**Comment by giampaolo** [comment]
If it's not accessible it should fail. Why should you expect a different outcome?

**Comment by FabianHofmann** [comment]
Then it is like that. It was rather a question whether it would make sense at all to allow a different setup if these files are not accessible. Then I have to talk to the managers of the clusters :)
