### ISSUE TITLE
Windows Server 2008 R2

### ISSUE THREAD

**Issue by snowdcwinter** [giampaolo/psutil#1651]
**Platform**
* { Windows Server 2008 R2 }     (also add appropriate OS issue label (linux, windows, ...))
* { psutil 5.6.7}  (use "pip show psutil")

**Bug description**
{ 
subdisk = psutil.disk_usage(disk_info[i][0])
PermissionError：[WinError21] 设备未就绪。
 }

```
traceback message (if any)
```

```python
def disknew ():
	diskstr = ''
	disk_info = psutil.disk_partitions()
	for i in range(len(disk_info)):
		subdisk = psutil.disk_usage(disk_info[i][0])
		diskstr += ''' 盘符：%s, 总空间：%s G, 剩余空间：%s G, 使用率:%s'''%(disk_info[i][0],int(subdisk.total/pow(1024,3)),int(subdisk.free/pow(1024,3)),subdisk.percent)+'\r\n'
	return diskstr

**Test results**
```
output of `python -c psutil.tests` (failures only, not full result)
```
{ you may want to do this in order to discover other issues affecting your platform }
{ if failures look unrelated with the issue at hand open another ticket }

**Comment by giampaolo** [comment]
`PermissionError` is legitimate. If you don't have the permission to query that path you should get an exception.
