### ISSUE TITLE
PyPy 2.7 unable to handle 3.X exceptions

### ISSUE THREAD

**Issue by graingert** [giampaolo/psutil#1659]
**Platform**
* { Linux2 }     (also add appropriate OS issue label (linux, windows, ...))
* { psutil==5.6.7 }  (use "pip show psutil") 

**Bug description**
`child_proc.wait(3)` raising OSError.errno = errno.ECHILD
even though it should be caught here:
https://github.com/giampaolo/psutil/blob/78c8669f9c11fc4d4105925e2fb5e13963abd4a5/psutil/_psposix.py#L87

```
t/unit/test_spawn.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.tox/pypy/site-packages/psutil/__init__.py:1383: in wait
    return self._proc.wait(timeout)
.tox/pypy/site-packages/psutil/_pslinux.py:1517: in wrapper
    return fun(self, *args, **kwargs)
.tox/pypy/site-packages/psutil/_pslinux.py:1725: in wait
    return _psposix.wait_pid(self.pid, timeout, self._name)
.tox/pypy/site-packages/psutil/_psposix.py:84: in wait_pid
    retpid, status = waitcall()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    def waitcall():
>       return os.waitpid(pid, os.WNOHANG)
E       OSError: [Errno 10] No child processes
```
https://github.com/graingert/billiard/blob/351a7d5546841e7a34ec78076a6bf5d41ba7faac/t/unit/test_spawn.py#L29

**Comment by graingert** [comment]
here's a standalone repro: https://github.com/graingert/psutil-pypy-echild

**Comment by graingert** [comment]
```
import errno

from psutil._compat import ChildProcessError

class MyPretendChildProcessError(EnvironmentError):
    errno = errno.ECHILD


try:
    raise MyPretendChildProcessError
except ChildProcessError:
    pass
```
an even smaller repro

I think reverting https://github.com/giampaolo/psutil/pull/1544/files will fix it

**Comment by graingert** [comment]
@giampaolo here's the error in pypy: https://bitbucket.org/pypy/pypy/issues/3149/compatability-excpeptions-using-a

**Comment by graingert** [comment]
@giampaolo the fix is now in pypy waiting a release

**Comment by giampaolo** [comment]
Another repo:

 ```python
from psutil._compat import FileNotFoundError
try:
    raise os.listdir('???')
except FileNotFoundError:
    pass
```

> the fix is now in pypy waiting a release

What do you mean?

**Comment by giampaolo** [comment]
May be related to this: https://doc.pypy.org/en/latest/cpython_differences.html#subclasses-of-built-in-types

**Comment by graingert** [comment]
> Another repo:
> 
> ```python
> import os
> from psutil._compat import FileNotFoundError
> try:
>    raise os.listdir('???')
> except FileNotFoundError:
>    pass
> ```
> 
> > the fix is now in pypy waiting a release
> 
> What do you mean?

The fix is here: https://bitbucket.org/pypy/pypy/commits/11a00b95fd59

**Comment by giampaolo** [comment]
Does this mean current psutil code will work with next version of pypy? If not, do you know a workaround (in psutil) to make it work with current/older pypy versions? If option 2 is not possible I'm keen on going with option 1 (wait for new pypy release) and return error in `setup.py` telling to upgrade pypy.

**Comment by graingert** [comment]
> Does this mean current psutil code will work with next version of pypy?

There will be a future release of pypy2 with the fix in it

> do you know a workaround (in psutil) to make it work with current/older pypy versions?
use:
```
except EnvironmentError as e:
    if e.errno == errno...:
        ...
    ...
```

> If option 2 is not possible I'm keen on going with option 1 (wait for new pypy release) and return error in `setup.py` telling to upgrade pypy.

Tbh I think the subclasshook is a rather ugly hack and the fact that it was removed intentionally in cpython3 makes me think it should not be used. I'd prefer it if you revert to using `e.errno==errno...` in psutil

**Comment by giampaolo** [comment]
This change was introduced not long ago: 
https://github.com/giampaolo/psutil/pull/1544
Latest working version is psutil 5.6.3. Sorry but I prefer to leave things as is. cPython 2 is deprecated and so should be pypy2. Also, soon this can be fixed via a pypy2 upgrade (once they release the next version). I can add a more detailed error message though.

**Comment by graingert** [comment]
> cPython 2 is deprecated and so should be pypy2

pypy2 isn't going anywhere

**Comment by giampaolo** [comment]
> pypy2 isn't going anywhere

Also Python 2. BTW, I don't plan on dropping Python 2 support any time soon (will happen years from now). I'm just giving up on a specific broken PyPy2 version which hopefully will be fixed soon.

**Comment by kashirin-alex** [comment]
one thing for sure, The exception subclass FileExistsError throw for OSError is only for PY3
without arguing py2 is going nowhere and just staying

so, it will be appropriate to have `PY3  and platform.python_implementation()` for the platform sanity check at

https://github.com/giampaolo/psutil/blob/4d6a086411c77b7909cce8f4f141bbdecfc0d354/psutil/_compat.py#L113

meanwhile work around is:
```bash
wget https://github.com/giampaolo/psutil/archive/release-5.7.0.tar.gz; 
tar -xf release-5.7.0.tar.gz;
sed -i 's/platform.python_implementation()/PY3 and platform.python_implementation()/g' \
 psutil-release-5.7.0/psutil/_compat.py;
pypy -m pip install psutil-release-5.7.0/
```
