### ISSUE TITLE
[Linux] disk_io_counters with NVME resulting in errors

### ISSUE THREAD

**Issue by J-StrY** [giampaolo/psutil#1692]
**Linux**
* { Archlinux 5.5.2 }
* { psutil version: 5.6.5 }
* { python 3.8.1-4 }

**Bug description**
Running disk_io_counters in the new kernel with an nvme drive results in the following error:

> File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1098, in read_procfs
>     raise ValueError("not sure how to interpret line %r" % line)
> ValueError: not sure how to interpret line ' 259       0 nvme0n1 109916 11636 7124076 550966 115172 4137 9296402 219723 0 51641 694795 0 0 0 0 4958 2319\n'

**Test results**
{ output of `python -c psutil.tests` (failures only, not full result) }

**Comment by aristocratos** [comment]
Found this on https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats

> 	Kernel 5.5+ appends two more fields for flush requests:
> 
> 		19 - flush requests completed successfully
> 		20 - time spent flushing

I'm guessing this is the reason, since the that value error is raised when there are more than 18 fields in /proc/diskstats.
