### ISSUE TITLE
TypeError: hilite() got an unexpected keyword argument 'ok'

### ISSUE THREAD

**Issue by glandium** [giampaolo/psutil#1714]
When running setup.py without the python development files or C compiler, this is what happens:
```
Traceback (most recent call last):
  File "/builds/worker/checkouts/gecko/third_party/python/psutil/setup.py", line 426, in <module>
    main()
  File "/builds/worker/checkouts/gecko/third_party/python/psutil/setup.py", line 400, in main
    missdeps("sudo apt-get install gcc python%s-dev" % py3)
  File "/builds/worker/checkouts/gecko/third_party/python/psutil/setup.py", line 116, in missdeps
    s = hilite("C compiler or Python headers are not installed ", ok=False)
```

The reason is that a8c9e878d5b43cbb729187ae6e1304eebd09b8dc changed the `hilite` function signature, but the callers from `setup.py` were left unchanged.

**Comment by ccarterlandis** [comment]
I was not aware that referencing an issue in another repo would tag it here...oops! @glandium I have the same issue as you. I needed to install it in the Docker image for our project; as a temporary workaround running `apt-get install gcc python3-dev` got everything to build for me.

**Comment by herrypio** [comment]
+1 I'm experiencing a similar problem when building a docker image.

@ccarterlandis Your workaround is working. Thanks!

**Comment by giampaolo** [comment]
This is already fixed in the master branch (just need a new release).

**Comment by herrypio** [comment]
When is the next release?

**Comment by ludjac** [comment]
+1 Also waiting for this to be released. Thanks

**Comment by waydegg** [comment]
New version (5.7.2 as of posting) has been released and this issue has been fixed now.
