### ISSUE TITLE
Please provide proper documentation for status constants of Process class

### ISSUE THREAD

**Issue by dhatraknilam** [giampaolo/psutil#1729]
I need detail description of status constants of psutil Process class. I need to define whether process is up or down based on the status returned by psutil Process. I am able to get information for some of normal states in process lifecycle such as running or defunct or stopped.

No proper documentation provided for the status constants (in psutil documentation). There is only two word explanation, such as for STATUS_WAKEKILL, information given is "wake kill".

**Comment by giampaolo** [comment]
>  I need to define whether process is up or down based on the status returned by psutil Process

You can use `psutil.STATUS_RUNNING` for that. If the process is not running it means it's in an "idle" state of some sort, either it's waiting for keybord input, disk access, it's blocked in a sleep() call or whatever.

As for the particular meaning of wake kill, "parked" etc. that is a sort of information/concept which is related to the kernel, and may vary depending on the OS, a low level detail, so the kernel/OS doc or source code should be used instead.

**Comment by dhatraknilam** [comment]
> > I need to define whether process is up or down based on the status returned by psutil Process
> 
> You can use `psutil.STATUS_RUNNING` for that. If the process is not running it means it's in an "idle" state of some sort, either it's waiting for keybord input, disk access, it's blocked in a sleep() call or whatever.
> 
> As for the particular meaning of wake kill, "parked" etc. that is a sort of information/concept which is related to the kernel, and may vary depending on the OS, a low level detail, so the kernel/OS doc or source code should be used instead.

Thank you for your help.I digged for the rest of the status constants , as you suggested. I found very intuitive link for process states
 https://www.ibm.com/developerworks/linux/library/l-task-killable/
I am just not clear about STATUS_WAKING. Does that mean process will be up after making any waking call(signal), otherwise sleeping?

**Comment by mithundiddi** [comment]
Above link is broken, adding new link to doc for ref

[https://wiki.deimos.fr/images/8/8a/L-task-killable-pdf.pdf](https://wiki.deimos.fr/images/8/8a/L-task-killable-pdf.pdf)
