### ISSUE TITLE
[Windows] parents() method somtimes occure hang (high cpu)

### ISSUE THREAD

**Issue by revermaru** [giampaolo/psutil#1735]
**Platform**
* { OS version } windows10
* { psutil version: python3 -c "import psutil; print(psutil.__version__)" } 5.6
* { python version } 2.7.14

**Bug description**
Hello
I made an agent that collects window information using psutil and distributed it to my organization.(about 1000 units)
However, we found that the agent cpu usage rate was over 20 percent at random and did not run normally.
So I checked the location of the code where the problem occurred and found that the problem was occurring on the line using the parents() function .
This issue disappears when the user reboots the pc, but seems to be occurring at random in any pc.
I want to use the parent() function as a very useful function, so is there a solution?
Please check it out
thank you

**Test results**
{ output of `python -c psutil.tests` (failures only, not full result) }

**Comment by giampaolo** [comment]
Not sure what you mean but I am sure this is not a bug report.
