### ISSUE TITLE
[windows] subprocesses and signals

### ISSUE THREAD

**Issue by dothebart** [giampaolo/psutil#1737]
If one spawns several processes, using signals with them isn't directly possible. 

Please either directly add `kwargs['creationflags'] - subprocess.CREATE_NEW_PROCESS_GROUP` to the code, or indicate in the documentation, that one should do this. 
Else signalling subprocesses is only possible for *all* subprocesses at once. 

https://stefan.sofa-rockers.org/2013/08/15/handling-sub-process-hierarchies-python-linux-os-x/

**Comment by giampaolo** [comment]
You mean in the test suite? `get_test_subprocess()` function?

**Comment by dothebart** [comment]
it seems that this combination does the right thing; Launch the process like this:
```
ON_WINDOWS = (sys.platform == 'win32')
...
kwargs = {}
if ON_WINDOWS:
       kwargs['creationflags'] = subprocess.CREATE_NEW_PROCESS_GROUP
self.proc = subprocess.Popen(self.arguments, **kwargs)
```
and then in terminate instead of redirecting to kill dodge the self signal by temporarily setting a signal handler: 
```
def dodge_sigint_handler(signum, frame):
    if signum != signal.SIGINT:
        exit(1)
    pass

original_sigint_handler = signal.getsignal(signal.SIGINT)
signal.signal(signal.SIGINT, dodge_sigint_handler)
self.proc.send_signal(signal.CTRL_BREAK_EVENT)
self.proc.wait()
# restore original handler
signal.signal(signal.SIGINT, original_sigint_handler)
```

This will result in terminating *only* the intended process, as would sending SIG_TERM on linux.

**Comment by giampaolo** [comment]
In the test suite it's not too important to kill a specific process only 'cause on `tearDown` we simply want to terminate them all, so I don't think it's worth it to add complexity. 
Signal handling is complex even without putting Windows in the mix: =)
http://grodola.blogspot.com/2016/02/how-to-always-execute-exit-functions-in-py.html

**Comment by dothebart** [comment]
Please have a look at my PR. 
I think its not as complicated, as one may think ;-P

**Comment by dothebart** [comment]
Please. We want to have a portable way. 
psutils should behave as similar on all available targets as possible. 
This patch will make it behave on the wintendo more like on a real OS.

**Comment by giampaolo** [comment]
Closing after discussion in https://github.com/giampaolo/psutil/pull/1740.

**Comment by ObiWahn** [comment]
I disagree with @dothebart on many things, but when operating systems behave differently it sucks! Most people expect python code to be somewhat portable.
