### ISSUE TITLE
[Windows] Process.username()  AccessDenied

### ISSUE THREAD

**Issue by hapasa** [giampaolo/psutil#1742]
** Windows 2012 Server **
* { psutil version: 5.4.8" }
* { python 3.7.1 }

**Bug description**

Even when running as an administrator, for some reason psutil.AccessDenied is thrown when trying to get username of a process.

I kludged around this with:

        user4pid = {}  # psutils 5.4.8 does not get the username reliably, even when run as admin. Workaround that
        plist = subprocess.getoutput(r'TASKLIST /FI "USERNAME ne NT AUTHORITY\SYSTEM" /V').split('\n')
        for pl in plist:
            if pl.strip():
                pid = pl[26:34].strip()
                if pid != 'PID' and pid != '========':
                    user4pid[int(pid)] = pl[93:144].strip()

**Test results**
{ output of `python -c psutil.tests`:  NameError: name 'psutil' is not defined }

**Comment by giampaolo** [comment]
It's expected. For certain processes the only way to avoid that is running the Python process as a kernel driver, like ProcessHacker does.
