### ISSUE TITLE
psmerge fails with the following two documents

### ISSUE THREAD

**Issue by rodolfo-medina** [giampaolo/psutil#1756]
Hi...

please help understanding why psmerge gets error over the attached examples...

Error: /stackoverflow in /--%setdevicecolor_cont--
Operand stack:
   --nostringval--
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1992   2   3   %oparray_pop   1991   2   3   %oparray_pop   1979   2   3   %oparray_pop   1833   2   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   1   0
Dictionary stack:
   --dict:732/1123(ro)(G)--   --dict:0/20(G)--   --dict:81/200(L)--   --dict:86/300(L)--
Current allocation mode is local
Current file position is 24997
GPL Ghostscript 9.27: Unrecoverable error, exit code 1

I renamed them with .txt extension but they're .ps files...

thank you

rodolfo
[test2.txt](https://github.com/giampaolo/psutil/files/4611755/test2.txt)
[test3.txt](https://github.com/giampaolo/psutil/files/4611757/test3.txt)

**Comment by giampaolo** [comment]
I don't know what's psmerge. This is psutil.

**Comment by rodolfo-medina** [comment]
sorry...  psmerge is part of psutils package...
