### ISSUE TITLE
Temperature and FAN sensors for Mac OSX

### ISSUE THREAD

**Issue by TechPeng** [giampaolo/psutil#1759]
#### Description
Use [istats](https://github.com/Chris911/iStats) to make [glances](https://github.com/nicolargo/glances) on MacOS can display CPU temperature and fan speed.

#### Versions

* Glances v3.1.4.1 with PsUtil v5.7.0
* MacOS Catalina 10.15.4

#### Logs

[_psosx.py.zip](https://github.com/giampaolo/psutil/files/4625176/_psosx.py.zip)
<img width="318" alt="a" src="https://user-images.githubusercontent.com/24990123/81875658-af6d2000-9578-11ea-88cd-6cb13c7480fc.png">

**Comment by giampaolo** [comment]
This is for glances project, not psutil.
