### ISSUE TITLE
Provide CPU or mainboard ID

### ISSUE THREAD

**Issue by cheak1974** [giampaolo/psutil#1771]
Hi, 
lovely and really useful library. Should be moved somewhen into python standard lib :-) 

I would love to see if psutil could retrieve the cpu or mainboard id (its possible, I can provide examples for win and linux). It would be useful for very safe identification of a client. While mac addresses can be changed the id will always stay the same. 

If you don't like the idea just drop the issue. 

regards
Chris

**Comment by giampaolo** [comment]
I considered this but it's something not well standardized and hard to expose in a reliable fashion (especially across different OSes, but also on Linux alone it would probably be messy). I prefer to keep this out.
