### ISSUE TITLE
[macOS] Reopen issue

### ISSUE THREAD

**Issue by jamilraichouni** [giampaolo/psutil#1775]
**OSX**
* { macOS Catalina 10.15.5 }
* { psutil version: 5.7.0 }
* { python version: 3.7.7 }

**Bug description**
...

See my comment [here](https://github.com/giampaolo/psutil/issues/1447#issuecomment-646294879)

Please reopen [the issue](https://github.com/giampaolo/psutil/issues/1447).

**Test results**

Producing test results seems not to work like described in the issue template here:

```bash

user@jarmac ~/repos/jar
$ python -c psutil.tests
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'psutil' is not defined

user@jarmac ~/repos/jar
$ python -c 'psutil.tests'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'psutil' is not defined

user@jarmac ~/repos/jar
$ python -c 'import psutil; psutil.tests'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'psutil' has no attribute 'tests'

user@jarmac ~/repos/jar
$ 
```

**Comment by giampaolo** [comment]
Fixed as of https://github.com/giampaolo/psutil/issues/1447.
