### ISSUE TITLE
[Windows/Others?] Relative import of PYDs not working in embedded zip

### ISSUE THREAD

**Issue by eblaudy** [giampaolo/psutil#1780]
Hi,
For the project I'm working (WAPT) we want to use psutil in a site-packages zip (because we deploy agents and the deployment can be faster with only one zip than multiple copy of files). Python can't loads DLLs/PYDs directly from the zip so I moved them in a DLLs directory which is in the path (he is declared in a python3X._pth). The problem is that you use relative imports for the PYD _psutil_windows.cp3X-win32.pyd if I change them to absolute imports it works (for ex : "from ._psutil_windows import ABOVE_NORMAL_PRIORITY_CLASS" --> from _psutil_windows import ABOVE_NORMAL_PRIORITY_CLASS). I think there is the same problem in others platforms :) 

Would it be possible to integrate this changes in the next release? I you want I can make a PR

Concerned lines for Windows : 
https://github.com/giampaolo/psutil/blob/2a44280b2e4a6bcb3ccc0b622acea3305807e175/psutil/_pswindows.py#L35:L40
https://github.com/giampaolo/psutil/blob/2a44280b2e4a6bcb3ccc0b622acea3305807e175/psutil/_pswindows.py#L43
https://github.com/giampaolo/psutil/blob/2a44280b2e4a6bcb3ccc0b622acea3305807e175/psutil/__init__.py#L146:151

**Comment by giampaolo** [comment]
Mmm... how are you producing the zip?

**Comment by eblaudy** [comment]
I produce the zip with a script :) 
For example in python 3.6 : 
 - I download the python embedded zip https://www.python.org/ftp/python/3.6.8/python-3.6.8-embed-win32.zip
 - I extract it 
 - I download the same python version and install it https://www.python.org/ftp/python/3.6.8/python-3.6.8-amd64.exe
 - With the python system I just downloaded I do a pip with '-t path_to_my_future_zip' params for my requirements
 - I search for all the pyds/dlls in path_to_my_future_zip and move them to a directory DLLs
 - I zip the lib  (path_to_my_future_zip) in site-packages.zip for example
 - I modify the python36._pth to add the line for site-packages.zip and the line for the directory DLLs

**Comment by giampaolo** [comment]
I never did something like that, and am not sure I understand your procedure, but I think psutil's dll file and py/pyc files should be in the same directory. Are they? This looks like something which should be fixed in how you produce the zip, not in psutil, as relative imports are a legitimate, old python future. 
I suspect there may even be tools out there that does this so. Quick google search:
https://docs.python.org/3/library/zipapp.html

**Comment by eblaudy** [comment]
If I let them in the same directory (in the zip) the problem is that python can't load DLL/pyd files directly from a zip. So it can't works :( And we have to keep the python interpreter because we do package deployment in python so when the adminsys do some packages he have to test it. So we only want to zip libs of the requirements. Yeah I read docs, it's not a good thing to replace by absolute imports. Thanks for your answers ! I close ;)
