### ISSUE TITLE
[Windows] Windows wheel for Python 27 not available anymore for 5.7.1

### ISSUE THREAD

**Issue by AlexandreYang** [giampaolo/psutil#1790]
Hi, first, thanks for creating/maintaining psutil.

Since `5.7.1` it seems that there is no windows py27 wheels anymore.

Is it possible to make them available like previous versions ?

**Platform**
* Windows

**Bug description**

Windows wheel for Python 27 seem not available anymore for 5.7.1 : https://pypi.org/project/psutil/5.7.1/#files

There were available before for 5.7.0:

https://pypi.org/project/psutil/5.7.0/#files
![image](https://user-images.githubusercontent.com/49917914/87546142-5a00dc80-c6a9-11ea-82c1-f0a9e5df145a.png)

**Comment by giampaolo** [comment]
Ouch! OK, I made a new release (5.7.2).
