### ISSUE TITLE
[macOS] cannot install from pip (using python 2.7)

### ISSUE THREAD

**Issue by nicoabie** [giampaolo/psutil#1797]
**Platform**
* { Catalina 10.15.16 }
* { 5.7.0 & 5.7.2 }
* { python 2.7.16 }

**Bug description**
```
psutil/_psutil_posix.c:36:14: fatal error: 'net/if_media.h' file not found
        #include <net/if_media.h>
                 ^~~~~~~~~~~~~~~~
```
Installing version 5.7.1 is possible. Am I missing some needed dependency?

**Comment by doneria-anjali** [comment]
Try:

echo "#include <net/if_media.h>" > /tmp/test.h
CFLAGS="-include /tmp/test.h" pip install psutil

**Comment by nicoabie** [comment]
Thanks @doneria-anjali! Rebooting the system seems to have fixed the issue.
