### ISSUE TITLE
[macOS] Unable to run psutil using py2.7

### ISSUE THREAD

**Issue by doneria-anjali** [giampaolo/psutil#1798]
**Platform**
* { 11.0 Beta }
* { psutil version: 5.7.2 }
* { python version: 2.7.16 }

**Bug description**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/psutil/__init__.py", line 159, in <module>
    from . import _psosx as _psplatform
  File "/Library/Python/2.7/site-packages/psutil/_psosx.py", line 15, in <module>
    from . import _psutil_osx as cext
ImportError: dynamic module does not define init function (init_psutil_osx)

I am installing psutil library using pip2 (pip2 install psutil) which should be building the library using py2, instead of py3 but when I try to import psutil in python2 script, above error is thrown. What would be the correct way to use this library in a py2 script?

**Comment by giampaolo** [comment]
Python wheels for macOS (including for py 2.7) are now uploaded on PYPI, so this should be solved.
