### ISSUE TITLE
linux　Build and compile errors during installation and execution

### ISSUE THREAD

**Issue by WangSongsen** [giampaolo/psutil#1806]
**Platform**
* { OS version }
* { psutil version: python3 -c "import psutil; print(psutil.__version__)" }
* { python version }

**Bug description**
...
![image](https://user-images.githubusercontent.com/66193944/89760398-d2599280-dadb-11ea-84e8-c2e9efbfcd7d.png)

　Wrote a test file to understand the library　but I seem to have some trouble and don't know how to solve it

**Test results**
{ output of `python -c psutil.tests` (failures only, not full result) }

**Comment by giampaolo** [comment]
The import is wrong. It should be "import psutil".
