### ISSUE TITLE
[Windows] nullptr exception in psutil_get_open_files()

### ISSUE THREAD

**Issue by ydder007** [giampaolo/psutil#1823]
**Windows**
* { Windows 10/Server 2016/Server 2019 }
* { 5.7.2 }
* { 2.7.18 }

**file: process_handles.c:250 -> exception: "globalFileName" was "nullptr"**
We recently upgraded from an older version of psutil (5.2.2) to the latest package. 
Since then we encountered numerous crashes. I traced the crash dumps down to one culprit:

process_handles.c lines 246ff.:
![image](https://user-images.githubusercontent.com/9085138/92595818-3ae78b00-f2a5-11ea-9f2a-49abc872c3ec.png)

It seems like globalFileName can be NULL here.

**Comment by BoboTiG** [comment]
Could this be the culprit for #1763?

**Comment by giampaolo** [comment]
Good catch. I should have fixed this. Please reopen if I didn't.
