### ISSUE TITLE
[Linux] Long delays in psutil result returns

### ISSUE THREAD

**Issue by RedBearAK** [giampaolo/psutil#1825]
psutil version: 5.7.2
Platform: MacBook3,1 with 6GB RAM and SATA3 SSD. Core2 Duo T7500 64-bit CPU. 
OS: Linux Mint 20, 64-bit, XFCE

**Bug description**
While using BpyTOP (https://github.com/aristocratos/bpytop) I experienced very long pauses or freezing in the BpyTOP interface. BpyTOP is a "top" utility like Htop and others. It's the successor to BashTOP, ported from Bash to Python. It's becoming very popular due to having a very nice UI and intuitive controls. 

The dev of BpyTOP suggests that the source of the freezing I experienced is psutil having a problem returning a result quickly. 

The closest I have come to determining the ultimate cause of the delay is that it seems to happen during a TimeShift backup. It is difficult to replicate since most TimeShift backups are incremental backups that only copy a small amount of data. But the longest pauses (up to 20 seconds of BpyTOP being completely frozen was observed) seemed to occur shortly after a fresh install of Linux Mint 20 on my system, during the period when I would have been installing a lot of new applications. That's when TimeShift would have been copying the largest amount of data to its backup destination folder. 

The TimeShift backup is on the same physical drive. It is a good quality SATA3 SSD drive, but the TimeShift (rsync) process appears to be creating enough disk latency (or some other system delay) that it keeps psutil from being able to return some results back to BpyTOP in a reasonable amount of time, thus creating the long "freezing" episodes in BpyTOP. 

I've discussed some possible mitigation solutions with the BpyTOP developer, but at the moment he thinks that the solution lies mainly with psutil. He had me run some speed tests with the psutil test scripts. Here is a long file of test results run during a system update involving a kernel upgrade, and then a TimeShift run: 

[run_results.txt](https://github.com/giampaolo/psutil/files/5213285/run_results.txt)

If you cat this file and grep for "elapsed", you'll just see the resulting total time calculations for each run. 

```
Time elapsed: 2070 milliseconds
Time elapsed: 1821 milliseconds
Time elapsed: 1988 milliseconds
Time elapsed: 1882 milliseconds
Time elapsed: 1892 milliseconds
Time elapsed: 1841 milliseconds
Time elapsed: 1791 milliseconds
Time elapsed: 1835 milliseconds
Time elapsed: 1749 milliseconds
Time elapsed: 1719 milliseconds
Time elapsed: 1682 milliseconds
Time elapsed: 1785 milliseconds
Time elapsed: 2577 milliseconds
Time elapsed: 1863 milliseconds
Time elapsed: 1650 milliseconds
Time elapsed: 1782 milliseconds
Time elapsed: 1767 milliseconds
Time elapsed: 3972 milliseconds
Time elapsed: 1812 milliseconds
Time elapsed: 1866 milliseconds
Time elapsed: 1791 milliseconds
Time elapsed: 1629 milliseconds
Time elapsed: 2614 milliseconds
Time elapsed: 1890 milliseconds
Time elapsed: 2297 milliseconds
Time elapsed: 1797 milliseconds
Time elapsed: 1795 milliseconds
Time elapsed: 1681 milliseconds
Time elapsed: 1698 milliseconds
Time elapsed: 1702 milliseconds
Time elapsed: 1874 milliseconds
Time elapsed: 1800 milliseconds
Time elapsed: 1783 milliseconds
Time elapsed: 1784 milliseconds
Time elapsed: 1738 milliseconds
Time elapsed: 1775 milliseconds
Time elapsed: 1647 milliseconds
Time elapsed: 1701 milliseconds
Time elapsed: 1668 milliseconds
Time elapsed: 1819 milliseconds
Time elapsed: 1784 milliseconds
Time elapsed: 1752 milliseconds
Time elapsed: 1837 milliseconds
Time elapsed: 1808 milliseconds
Time elapsed: 1676 milliseconds
Time elapsed: 1646 milliseconds
Time elapsed: 1700 milliseconds
Time elapsed: 1808 milliseconds
Time elapsed: 1829 milliseconds
Time elapsed: 1815 milliseconds
Time elapsed: 1884 milliseconds
Time elapsed: 1763 milliseconds
Time elapsed: 1754 milliseconds
Time elapsed: 1898 milliseconds
Time elapsed: 1691 milliseconds
Time elapsed: 1867 milliseconds
Time elapsed: 1811 milliseconds
Time elapsed: 1826 milliseconds
Time elapsed: 1912 milliseconds
Time elapsed: 1937 milliseconds
Time elapsed: 1762 milliseconds
Time elapsed: 1761 milliseconds
Time elapsed: 1980 milliseconds
Time elapsed: 1838 milliseconds
Time elapsed: 2133 milliseconds
Time elapsed: 2197 milliseconds
Time elapsed: 2144 milliseconds
Time elapsed: 1924 milliseconds
Time elapsed: 2299 milliseconds
Time elapsed: 2112 milliseconds
Time elapsed: 2352 milliseconds
Time elapsed: 2072 milliseconds
Time elapsed: 1668 milliseconds
```

The default refresh rate of BpyTOP is 2000ms. Many of the elapsed times above are longer than that, up to almost 4 seconds. Obviously the times above are the result of the psutil test scripts, but any result like this that happens during a BpyTOP refresh cycle results in BpyTOP freezing. 

A previous run where I was just outputting the total elapsed time resulted in almost up to 6 seconds of delay. I did this while experiencing freezes (delays in UI updating) in BpyTOP, and that's when I finally noticed that this seems to happen during a TimeShift backup cycle. 

```
Time elapsed: 2245 milliseconds
Time elapsed: 2261 milliseconds
Time elapsed: 2297 milliseconds
Time elapsed: 2354 milliseconds
Time elapsed: 2090 milliseconds
Time elapsed: 2580 milliseconds
Time elapsed: 2071 milliseconds
Time elapsed: 2646 milliseconds
Time elapsed: 2699 milliseconds
Time elapsed: 2596 milliseconds
Time elapsed: 2536 milliseconds
Time elapsed: 1729 milliseconds
Time elapsed: 2597 milliseconds
Time elapsed: 2310 milliseconds
Time elapsed: 2631 milliseconds
Time elapsed: 3984 milliseconds
Time elapsed: 4052 milliseconds
**Time elapsed: 5796 milliseconds**
**Time elapsed: 5361 milliseconds**
**Time elapsed: 5044 milliseconds**
Time elapsed: 2696 milliseconds
Time elapsed: 1979 milliseconds
Time elapsed: 1867 milliseconds
Time elapsed: 1890 milliseconds
Time elapsed: 1857 milliseconds
Time elapsed: 1946 milliseconds
Time elapsed: 2471 milliseconds
Time elapsed: 2124 milliseconds
Time elapsed: 1935 milliseconds
Time elapsed: 1860 milliseconds
Time elapsed: 1986 milliseconds
Time elapsed: 2084 milliseconds
```

And as stated earlier, I have personally observed up to around 20 seconds of total delay. 

So the question is, is there anything that psutil can do to mitigate this issue? Is the rsync process TimeShift is using running with too high a priority? Is psutil or BpyTOP running with too low a priority? 

Can psutil be modified to "time out" if a non-reasonable amount of time is elapsing before a specific result comes back? 

Am I experiencing some strange quirk specific to the MacBook3,1 hardware? How would I know? 

Here's the whole test result from the cycle when the total elapsed time was 3972 ms: 

```
SYSTEM APIS               SECONDS
----------------------------------
cpu_count                 0.000043
disk_usage                0.000077
cpu_times                 0.000092
cpu_stats                 0.000102
pid_exists                0.000124
users                     0.000131
cpu_percent               0.000144
cpu_times_percent         0.000158
virtual_memory            0.000192
swap_memory               0.000242
net_if_stats              0.000613
net_io_counters           0.000624
cpu_count (cores)         0.000884
pids                      0.001078
net_if_addrs              0.001719
boot_time                 0.001885
disk_io_counters          0.002168
disk_partitions           0.002993
sensors_battery           0.005289
sensors_fans              0.024085
cpu_freq                  0.037375
net_connections           0.052726
process_iter (all)        0.156321
sensors_temperatures      0.186860

PROCESS APIS              SECONDS
----------------------------------
create_time               0.000004
nice                      0.000013
cpu_affinity              0.000029
ionice                    0.000043
cwd                       0.000052
num_fds                   0.000052
exe                       0.000063
status                    0.000064
cpu_times                 0.000076
io_counters               0.000077
num_threads               0.000077
ppid                      0.000080
name                      0.000091
memory_info               0.000104
is_running                0.000110
cmdline                   0.000113
uids                      0.000115
cpu_num                   0.000119
gids                      0.000139
open_files                0.000154
memory_percent            0.000156
threads                   0.000179
username                  0.000458
num_ctx_switches          0.002362
cpu_percent               0.002574
memory_full_info          0.003733
terminal                  0.005182
connections               0.005868
environ                   0.010576
memory_maps               0.027303
children                  0.079814
15 methods involved on platform 'linux' (1000 iterations, psutil 5.7.2):
    cpu_num
    cpu_percent
    cpu_times
    gids
    memory_info
    memory_percent
    name
    num_ctx_switches
    num_threads
    parent
    ppid
    status
    terminal
    uids
    username
normal:  2.210 secs
onshot:  0.667 secs
speedup: +3.31x

+++++++++++++++++++++++++++
Time elapsed: 3972 milliseconds
+++++++++++++++++++++++++++
```

Is there anything here that appears highly abnormal?

**Comment by giampaolo** [comment]
Hello. It is hard to tell without profiling or looking at the source code. In general, psutil is "as fast as possible", as most information on Linux is collected by reading /proc directory, but it depends on how you collect information, see:
* https://github.com/giampaolo/psutil/issues/1772#issuecomment-641634925
* https://gmpy.dev/blog/2016/psutil-550-is-twice-as-fast
For example, there are some APIs which, if misused, can introduce a slow down, lilke `psutil.cpu_percent(interval=1)` executed in a loop. Perhaps BpyTOP is using one of them?

**Comment by RedBearAK** [comment]
Since in most cases BpyTOP is quite responsive even when reducing the refresh interval to the minimum allowed value of 100ms, I doubt the developer is making a mistake like that. 

Is it possible that the rsync process or some other process used by TimeShift could be temporarily tying up /proc in some way that would introduce a delay in psutil's ability to read from /proc quickly? 

If that idea is too crazy I'm not sure where else to go with trying to troubleshoot exactly what is causing the delays.

**Comment by giampaolo** [comment]
I cannot know but the API timings pasted above look normal, so if this happens only when you run the backup process I suppose the machine is simply being overloaded. To figure out the slowest BpyTOP / psutil API calls are the slowest you may try running BpyTOP under a profiler:
https://docs.python.org/3/library/profile.html#module-cProfile
