### ISSUE TITLE
[MACOS] Process object has no attribute 'cpu_affinity'

### ISSUE THREAD

**Issue by aouinizied** [giampaolo/psutil#1826]
**Platform**
* { MacOS 10.14 }
* { 5.7.2 }
* { 3.0 }

Hi,

psutil.Process.cpu_affinity() not working on macos.
Do you have any clue how to fix it?

BR,

**Test results**
https://github.com/nfstream/nfstream/runs/1109832012?check_suite_focus=true

**Comment by giampaolo** [comment]
`cpu_affinity` is not implemented on OSX

**Comment by aouinizied** [comment]
Thanks for you quick reply.

BR
