### ISSUE TITLE
[Linux] Projects using psutil

### ISSUE THREAD

**Issue by fredcox** [giampaolo/psutil#1829]
Hi, 

I would like you include my project in "Projects using psutil" section of psutil README.md

My Project is [GonhaNG](https://github.com/fredcox/gonhang), one light weight system monitor to Linux. 

See: [https://github.com/fredcox/gonhang](https://github.com/fredcox/gonhang)

Thank you. 

Follow one screenshot:
![shot](https://user-images.githubusercontent.com/65084421/93394161-26c5ff80-f84a-11ea-858e-df191ec4b1c0.png)

**Comment by giampaolo** [comment]
No, sorry.
