### ISSUE TITLE
Get supported CPU instructions using psutil

### ISSUE THREAD

**Issue by PedanticHacker** [giampaolo/psutil#1836]
As I read the documentation of `psutil`, I wasn't able to find how to get the instructions that a CPU supports (you know, like `popcnt`, `bmi2`, `ssse3`, `avx2`, and so on). I know there's [py-cpuinfo](https://github.com/workhorsy/py-cpuinfo) for that, but it'd be so cool is `psutil` had this functionality, especially since [py-cpuinfo](https://github.com/workhorsy/py-cpuinfo) is kinda slow at pulling that information.

So, is there such functionality in `psutil` or isn't there? And if not, will there ever be?

**Comment by giampaolo** [comment]
See #1894. Closing as duplicate.
