### ISSUE TITLE
[windows] process.cpu_affinity will have some problems on a 72-core machine

### ISSUE THREAD

**Issue by tomatome** [giampaolo/psutil#1848]
psutil version: 5.4.6
python version: 3.7.5

When the number of cpu cores of the system is greater than 64, cpu_affinity will have problems

**Comment by nuukedo29** [comment]
Same issue https://github.com/giampaolo/psutil/issues/1809

**Comment by giampaolo** [comment]
My mistake, didn't realize this is about CPU affinity, so I'm reopening.
@tomatome what problem do you have exactly?

**Comment by tomatome** [comment]
> My mistake, didn't realize this is about CPU affinity, not CPU times (#1809), so I'm reopening.
> @tomatome what problem do you have exactly?

cpus = [0, 1, 2, 3, ......69, 70, 71]
psutil.Process().cpu_affinity(cpus)

The cpu affinity setting failed which caused my program to quit， so how can the setting succeed?
and there are many threads in my process, I want to find a simple way to solve this problem

**Comment by giampaolo** [comment]
> The cpu affinity setting failed which caused my program to quit

Failed how? Please, post the traceback.
Also, how many CPUs are on your system (`psutil.cpu_count()`)?
