### ISSUE TITLE
[Windows] Release cpython wheels for Python 3.9 on PyPI

### ISSUE THREAD

**Issue by ntouran** [giampaolo/psutil#1850]
**Platform**
* Windows 64-bit
* Python 3.9

**Bug description**
Python 3.9 was released on Oct 5th and getting some wheels up on PyPI will make installation easier.

**Comment by giampaolo** [comment]
Depends on https://github.com/appveyor/ci/issues/3541.

**Comment by MrGreenTea** [comment]
> Depends on [appveyor/ci#3541](https://github.com/appveyor/ci/issues/3541).

This issue has been fixed. Is it possible now to release cpython wheel for `psutil-5.7.3-cp39-cp39-win_amd64.whl` ?.

**Comment by giampaolo** [comment]
Appveyor added support, but it turns out Python 3.9 depends on Visual Studio 2019, and unfortunately that breaks some stuff:
https://ci.appveyor.com/project/giampaolo/psutil/build/job/ewqdw2tpt19h86rf
Somebody with VS 2019 should give it a try.

**Comment by giampaolo** [comment]
Related: https://github.com/giampaolo/psutil/pull/1866.

**Comment by 1337THUG** [comment]
> 
> 
> **Platform**
> 
>     * Windows 64-bit
> 
>     * Python 3.9
> 
> 
> **Bug description**
> Python 3.9 was released on Oct 5th and getting some wheels up on PyPI will make installation easier.

https://pypi.bartbroe.re/psutil/

**Comment by giampaolo** [comment]
New 5.8.0 release and it includes wheels for Python 3.9 on Windows (see https://github.com/giampaolo/psutil/issues/1864#issuecomment-748399946).

**Comment by giampaolo** [comment]
New 5.8.0 release and it includes wheels for Python 3.9 on Windows (see https://github.com/giampaolo/psutil/issues/1550#issuecomment-748401967).
