### ISSUE TITLE
[Win] Installation failure on Cygwin

### ISSUE THREAD

**Issue by eabase** [giampaolo/psutil#1856]
**Win**
* { OS 8/10 }
* { psutil version: python3 -c "import psutil; print(psutil.__version__)" }
* { python version }

**Bug description**

Installation fails on Py3.8 under Cygwin. This is POSIX compatible and should work just as well as under WSL or any other *nix. 

...
```bash
$ pip install psutil
Collecting psutil
  Downloading psutil-5.7.2.tar.gz (460 kB)
     |████████████████████████████████| 460 kB 528 kB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.8.exe -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-geen0hz1/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-geen0hz1/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-9xffagwt
         cwd: /tmp/pip-install-geen0hz1/psutil/
    Complete output (1 lines):
    platform cygwin is not supported
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Test results**
{ output of `python -c psutil.tests` (failures only, not full result) }

---

**UPDATE** 2020-11-07

Apparently Cygwin is not supported as 'posix' nor 'nt', according to these related Issues: 
* #82  (Bump @embray )
* #1755 
* https://github.com/giampaolo/psutil/issues?q=is%3Aissue+cygwin+is%3Aclosed

However, there were already some suggested PRs that was (never?) submitted.

**Comment by eabase** [comment]
Because in Cygwin: 
```bash
# python -c "import os; print('\n'.join([os.name, os.sys.platform]));"
posix
cygwin

# python -c "import sys,os; print(os.uname()[0].split('-')[1]);"
6.3
```

Looks like some initial support could be given by changing, replacing these lines: 

* https://github.com/giampaolo/psutil/blob/241f8ed0cd5c0c792a28e4e6479586a70587177c/psutil/_common.py#L81-L82
```python
CYGWIN = os.sys.platform == "cygwin"
```
* https://github.com/giampaolo/psutil/blob/ecdaac33f5945be19090531be892791ac99fc597/scripts/winservices.py#L40

```python
if os.name != 'nt' and os.sys.platform != 'cygwin':
```

Then, in
* https://github.com/giampaolo/psutil/blob/241f8ed0cd5c0c792a28e4e6479586a70587177c/setup.py#L140-L142

these lines could be added/replaced with:
```python
def get_winver():
	return os.uname()[0].split('-')[1]
```

**Comment by giampaolo** [comment]
Cygwin is currently not supported. It's tracked in ticket 82 already.
