### ISSUE TITLE
Can't install psutil using pip on python 3.9 64bit windows having Visual C++ 14.0.23026

### ISSUE THREAD

**Issue by vinoddobhal** [giampaolo/psutil#1865]
I am using python 3.9.0 (x64) on a Windows server. Microsoft Visual C++ 2015 ver 14.0.23036 is also installed but getting the following error:

`C:\Windows\system32>pip install psutil
Collecting psutil
  Using cached psutil-5.7.3.tar.gz (465 kB)
Building wheels for collected packages: psutil
  Building wheel for psutil (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\program files\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\acroperf-local\\AppData\\Local\\Temp\\pip-install-_9do2h4n\\psutil\\setup.py'"'"'; __file__='"'"'C:\\Users\\acroperf-local\\AppData\\Local\\Temp\\pip-install-_9do2h4n\\psutil\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\acroperf-local\AppData\Local\Temp\pip-wheel-5nikd1ax'
       cwd: C:\Users\acroperf-local\AppData\Local\Temp\pip-install-_9do2h4n\psutil\
  Complete output (39 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\psutil
  copying psutil\_common.py -> build\lib.win-amd64-3.9\psutil
  copying psutil\_compat.py -> build\lib.win-amd64-3.9\psutil
  copying psutil\_psaix.py -> build\lib.win-amd64-3.9\psutil
  copying psutil\_psbsd.py -> build\lib.win-amd64-3.9\psutil
  copying psutil\_pslinux.py -> build\lib.win-amd64-3.9\psutil
  copying psutil\_psosx.py -> build\lib.win-amd64-3.9\psutil
  copying psutil\_psposix.py -> build\lib.win-amd64-3.9\psutil
  copying psutil\_pssunos.py -> build\lib.win-amd64-3.9\psutil
  copying psutil\_pswindows.py -> build\lib.win-amd64-3.9\psutil
  copying psutil\__init__.py -> build\lib.win-amd64-3.9\psutil
  creating build\lib.win-amd64-3.9\psutil\tests
  copying psutil\tests\runner.py -> build\lib.win-amd64-3.9\psutil\tests
  copying psutil\tests\test_aix.py -> build\lib.win-amd64-3.9\psutil\tests
  copying psutil\tests\test_bsd.py -> build\lib.win-amd64-3.9\psutil\tests
  copying psutil\tests\test_connections.py -> build\lib.win-amd64-3.9\psutil\tests
  copying psutil\tests\test_contracts.py -> build\lib.win-amd64-3.9\psutil\tests
  copying psutil\tests\test_linux.py -> build\lib.win-amd64-3.9\psutil\tests
  copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-3.9\psutil\tests
  copying psutil\tests\test_misc.py -> build\lib.win-amd64-3.9\psutil\tests
  copying psutil\tests\test_osx.py -> build\lib.win-amd64-3.9\psutil\tests
  copying psutil\tests\test_posix.py -> build\lib.win-amd64-3.9\psutil\tests
  copying psutil\tests\test_process.py -> build\lib.win-amd64-3.9\psutil\tests
  copying psutil\tests\test_sunos.py -> build\lib.win-amd64-3.9\psutil\tests
  copying psutil\tests\test_system.py -> build\lib.win-amd64-3.9\psutil\tests
  copying psutil\tests\test_testutils.py -> build\lib.win-amd64-3.9\psutil\tests
  copying psutil\tests\test_unicode.py -> build\lib.win-amd64-3.9\psutil\tests
  copying psutil\tests\test_windows.py -> build\lib.win-amd64-3.9\psutil\tests
  copying psutil\tests\__init__.py -> build\lib.win-amd64-3.9\psutil\tests
  copying psutil\tests\__main__.py -> build\lib.win-amd64-3.9\psutil\tests
  running build_ext
  building 'psutil._psutil_windows' extension
  VisualStudio is not installed; get it from http://www.visualstudio.com/en-au/news/vs2015-preview-vs
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for psutil
  Running setup.py clean for psutil
Failed to build psutil
Installing collected packages: psutil
    Running setup.py install for psutil ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\acroperf-local\\AppData\\Local\\Temp\\pip-install-_9do2h4n\\psutil\\setup.py'"'"'; __file__='"'"'C:\\Users\\acroperf-local\\AppData\\Local\\Temp\\pip-install-_9do2h4n\\psutil\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\acroperf-local\AppData\Local\Temp\pip-record-fszhv7kr\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files\python39\Include\psutil'
         cwd: C:\Users\acroperf-local\AppData\Local\Temp\pip-install-_9do2h4n\psutil\
    Complete output (39 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\psutil
    copying psutil\_common.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_compat.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psaix.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psbsd.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_pslinux.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psosx.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_psposix.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_pssunos.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\_pswindows.py -> build\lib.win-amd64-3.9\psutil
    copying psutil\__init__.py -> build\lib.win-amd64-3.9\psutil
    creating build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\runner.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_aix.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_bsd.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_connections.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_contracts.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_linux.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_misc.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_osx.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_posix.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_process.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_sunos.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_system.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_testutils.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_unicode.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\test_windows.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\__init__.py -> build\lib.win-amd64-3.9\psutil\tests
    copying psutil\tests\__main__.py -> build\lib.win-amd64-3.9\psutil\tests
    running build_ext
    building 'psutil._psutil_windows' extension
    VisualStudio is not installed; get it from http://www.visualstudio.com/en-au/news/vs2015-preview-vs
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\acroperf-local\\AppData\\Local\\Temp\\pip-install-_9do2h4n\\psutil\\setup.py'"'"'; __file__='"'"'C:\\Users\\acroperf-local\\AppData\\Local\\Temp\\pip-install-_9do2h4n\\psutil\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\acroperf-local\AppData\Local\Temp\pip-record-fszhv7kr\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files\python39\Include\psutil' Check the logs for full command output.
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the 'c:\program files\python39\python.exe -m pip install --upgrade pip' command.`

**Comment by giampaolo** [comment]
#1850.
