### ISSUE TITLE
[Linux] Process.open_files() sometimes hangs

### ISSUE THREAD

**Issue by ericaltendorf** [giampaolo/psutil#1867]
**Platform**
* Ubuntu 20.04 Linux 5.4.0-52-generic
* psutil version: 5.7.3
* 3.8.5

**Bug description**

Intermittently, Process.open_files() seems to hang, badly, as though it's deadlocked (the python process becomes unkillable).  Sometimes it works fine, though.  The processes I'm inspecting have a couple hundred open files, and I find with a psutil.process_iter() which picks out the relevant processes by name.

Roughly:

```
jobs = []
for proc in psutil.process_iter(['pid', 'name']):
    if (condition):
         jobs += [ MyJob(proc) ]
```

where MyJob's constructor is roughly:

```
__init__(self, proc):
    self.proc = proc
    with self.proc.oneshot():
        # read some proc fields, set some fields on self
        for f in self.proc.open_files():
             # never get here!
```

Are there any guidelines around general use of this library to avoid deadlocks?  I could be using it in error.

**Test results**
{ wasn't able to get test suite to run }

**Comment by ericaltendorf** [comment]
I did a little more research, perhaps it is inaccessible NFS hosts (I do have filesystems served by an NFS host): http://manpages.ubuntu.com/manpages/bionic/man8/lsof.8.html#blocks%20and%20timeouts

**Comment by giampaolo** [comment]
Most likely it's because you're interacting with a network filesystem. `open_files`'s Linux implementation is very simple and it's unlikely to be the cause.
