### ISSUE TITLE
[Windows] Intermittent AccessDenied errors trying to kill processes

### ISSUE THREAD

**Issue by rockobonaparte** [giampaolo/psutil#1924]
## Summary

* OS: Windows 10
* Architecture: 64bit
* Psutil version: 3.8.0
* Python version: 3.6.8 and 3.8.3
* Type: core

## Description

I think this is basically a re-open of #1774. I am noticing intermittent (inconsistent) AccessDenied errors when killing some processes I had launched. I had the requisite permissions. I had it happen repeatedly (for awhile) running a Python script as Administrator that was trying to launch another Python process.

I have an older log from May 7th:
```
    File [my glorious project], line 143, in proc_kill
      process.kill()
    File "C:\Python36\lib\site-packages\psutil\__init__.py", line 292, in wrapper
      return fun(self, *args, **kwargs)
    File "C:\Python36\lib\site-packages\psutil\__init__.py", line 1257, in kill
      self._proc.kill()
    File "C:\Python36\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
      raise convert_oserror(err, pid=self.pid, name=self._name)
  psutil.AccessDenied: psutil.AccessDenied (pid=428)
```

(scraping some newer logs to make sure I have more recent runs to show this)

The #1774 issue just caught the exception and suppressed it as a "workaround" but I'd prefer to not do that categorically. The message field just has the pid in it; I guess there was no message to go with it, so I can't really make judgments on the exception that might end with my suppressing exceptions that might actually be important.

**Comment by rockobonaparte** [comment]
I found some other logs that were different and perhaps more interesting.

```
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Python36\lib\site-packages\psutil\_pswindows.py", line 863, in kill
    return cext.proc_kill(self.pid)
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File [my glorious project], line 144, in proc_kill
    process.kill()
  File "C:\Python36\lib\site-packages\psutil\__init__.py", line 272, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Python36\lib\site-packages\psutil\__init__.py", line 1241, in kill
    self._proc.kill()
  File "C:\Python36\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=428)
```
I can try to involve an instrumented build or something. I don't have a procedure that will cause this in one place at any one particular time, but I can expect it to happen across my CI/CD run at some point.

**Comment by giampaolo** [comment]
There's not much we can do in case of AD. Even as Administrator there are different processes which result in ERROR_ACCESS_DENIED, which is then translated into `AccessDenied` exception. AFAICT, in the logs you pasted I can't see anything inherently wrong with psutil.

**Comment by yo-wotop** [comment]
My friend is running into this issue as well FWIW with processes that should not fail. Guild Wars 2, in this instance.  

Win10 (Home) x64. Yes she's running the script as Admin. We actually disabled UAC to be absolutely certain.  

I (2 different machines, running Win10 Enterprise on each) never face this problem. Like others have reported in this and the other closed thread, this is an intermittent issue. Sometimes it closes, sometimes it doesn't.

As a developer myself, I know that these aren't helpful repro steps. Just want to point out that there _does_ appear to be some intermittent bug here causing `kill` to fail and it isn't simply due to the target process having elevated privileges.
