### ISSUE TITLE
[Windows] status() of a terminated process raises exception

### ISSUE THREAD

**Issue by Zabolekar** [giampaolo/psutil#1928]
## Summary

* OS: Windows 10
* Architecture: 64bit
* Psutil version: 5.8.0
* Python version: 3.8 and 3.9
* Type: (not sure)

## Description

The following code raises an exception on Windows, but not on Ubuntu (same architecture, Python 3.9 in both cases):

```python
import multiprocessing
import psutil
import time
import os

def f():
    this = psutil.Process(os.getpid())

    old_parent = this.parent()
    old_parent.terminate()
    while this.parent() is not None:
        time.sleep(0.1)
    print(old_parent) # the printed string contains "status='terminated'"
    print(old_parent.status()) # raises ProcessLookupError on Windows, prints "Terminated" on Linux

if __name__ == '__main__':
    child = multiprocessing.Process(target=f)
    child.start()
```

Full traceback:

```
Process Process-1:
Traceback (most recent call last):
  File "...\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "...\lib\site-packages\psutil\_pswindows.py", line 1054, in status
    suspended = cext.proc_is_suspended(self.pid)
ProcessLookupError: [Errno 3] assume no such process (originated from NtQuerySystemInformation (no PID found))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "...\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\psutil_bug.py", line 14, in f
    print(old_parent.status())
  File "...\lib\site-packages\psutil\__init__.py", line 682, in status
    return self._proc.status()
  File "...\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=23508, name='python.exe')
```

**Comment by giampaolo** [comment]
```
    child = multiprocessing.Process(target=f)
    child.start()
```

...I think you need `child.join()` here. 
To my understanding, the problem occurs because after `child.start()` there is nothing, so the parent process quietly exits / terminates. 
That is reflected in the child process, which sees the parent as terminated. Yes, the outcome is different on Linux and Windows (status() -> "terminated" vs. NoSuchProcess) but we can't do anything about that. Adding `join()` should solve your issue.

**Comment by Zabolekar** [comment]
But that was the point of the example: to demonstate what happens if the child outlives the parent but still has a variable that references it. In this particular case, `join()` would solve the issue, but generally, it would not (e.g. if the child process runs an event loop that should be capable of being terminated by the parent).
