### ISSUE TITLE
[Linux] ps.util_freq() takes more than 5 seconds on AMD Epyc 7742

### ISSUE THREAD

**Issue by lbhm** [giampaolo/psutil#1933]
## Summary

* OS: Ubuntu 20.04.1 LTS
* Architecture: x86_64
* Psutil version: 5.8.0
* Python version: 3.8.5
* Type: performance

## Description

I recently got access to a dual-socket AMD Epyc 7742 machine with a total of 256 logical cores. One of the first things I did was to install [bpytop](https://github.com/aristocratos/bpytop) to monitor system behavior. However, I noticed that bpytop reacts very slowly on this machine. When I reached out to the bpytop community, they asked me to run `scripts/internal/print_api_speed.py` from the psutil repo and it showed that cpu_freq takes 5.11 seconds. 

Could this issue be related to the core count of the CPUs or to their relative novelty? I'd appreciate any help on how I can improve the performance of cpu_freq() on the system.

**Comment by giampaolo** [comment]
This was addressed in #1851, which is still unreleased. You can get it by using latest GIT master.
