### ISSUE TITLE
[Ubuntu 20.04] cpu_freq() returns None on aarch64

### ISSUE THREAD

**Issue by arslancharyev31** [giampaolo/psutil#1939]
## Summary

* OS: Ubuntu 20.04
* Architecture: aarch64
* Psutil version:  5.5.1
* Python version: Python 3.8.5
* Type: core

## Description

`psutil.cpu_freq()` returns `None` on AWS EC2 Ubuntu 20.04 instance that runs under ARM64 architecture.

I have checked the `/sys/devices/system/cpu/cpu*/` directories, and they are all missing the `cpufreq` file. 

Furthermore, `/sys/devices/system/cpu/cpufreq/` is empty.

Running `sudo apt install python3-psutil` didn't help either.

> P.S. I'm not sure if this issue needs to be addressed on psutil layer, so feel free to point to me in the appropriate direction.

**Comment by giampaolo** [comment]
What's the output of `cat /proc/cpuinfo`?

**Comment by arslancharyev31** [comment]
```
processor       : 0
BogoMIPS        : 243.75
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x3
CPU part        : 0xd0c
CPU revision    : 1

processor       : 1
BogoMIPS        : 243.75
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x3
CPU part        : 0xd0c
CPU revision    : 1
```

**Comment by giampaolo** [comment]
Mmmm... no CPU frequency info in there either. There have been changes re. `cpu_freq()` on Linux that are committed on master. Can you try latest master version? Command line should be:

```
python3 -m pip install --upgrade git+https://github.com/giampaolo/psutil.git@master
```

**Comment by arslancharyev31** [comment]
> Mmmm... no CPU frequency info in there either. There have been changes re. `cpu_freq()` on Linux that are committed on master. Can you try latest master version? Command line should be:
> 
> ```
> python3 -m pip install --upgrade git+https://github.com/giampaolo/psutil.git@master
> ```

Still `None` :(

**Comment by arslancharyev31** [comment]
Output of `lscpu`:
```
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       ARM
Model:                           1
Model name:                      Neoverse-N1
Stepping:                        r3p1
BogoMIPS:                        243.75
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        2 MiB
L3 cache:                        32 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dc
                                 pop asimddp ssbs
```
It's also weird, since it's supposed to show CPU frequency.

**Comment by giampaolo** [comment]
Then it's not implemented by the kernel. FWIW, I have access to a ARM / aarch64 platform and it's implemented.
