### ISSUE TITLE
[OS] process_iter() cached item ignored the killed process

### ISSUE THREAD

**Issue by rsik88** [giampaolo/psutil#1951]
## Summary

* OS: { Centos 8 }
* Architecture: { 64bit, 3 }
* Psutil version: { 5.8.0 }
* Python version: { 3.6.8 }
* Type: { core }

## Description

{{{
  psutil.process_iter() call caches pid etc. When a process restarted, it didn't update and still keeps the old pid. It would be nice to have a function to allow refresh the process list when needed.
}}}

**Comment by giampaolo** [comment]
`process_iter()` is already supposed to handle PIDs being reused, see:
https://github.com/giampaolo/psutil/blob/5d39cc9c8d8dc04862786abba0307ed9350144ce/psutil/__init__.py#L1444-L1453
