### ISSUE TITLE
[Win10] Call to disk_partitions() crashes if even a single volume is mounted as readonly

### ISSUE THREAD

**Issue by MaWe2019** [giampaolo/psutil#1953]
## Summary

* OS: { Win10 }
* Architecture: { 64bit }
* Psutil version: { 5.8.0 }
* Python version: { 3.9.4 }
* Type: { core }

## Description

Calls to disk_partitions() cause the surrounding python script to crash with exit code -1073740791 (0xC0000409) whenever a volume is mounted as readonly.

For a quick test, plugin a usb drive, and then:

1. Start prompt with admin priviliges.
2. Run diskpart
3. Enter "list disk" (look for the volume number of the usb drive)
4. Enter "select disk x" (x = volume number of usb drive)
5. Enter "attributes disk set readonly"
6. Call psutil.disk_partitions()

**Comment by MaWe2019** [comment]
I think I might have found the source of the error.

The size of the "opts" array (currently set to 20 characters) in psutil/disk.c might be too small for some circumstances.

I.e. consider a volume that's removable and readonly.

psutil_disk_partitions() will then try to store "ro,readonly,removable" in opts, which is >20 characters. Btw. why do both "ro" and "readonly" get stored in opts? Aren't they basically the same thing?

**Comment by MaWe2019** [comment]
I would like to once again underline the importance of this issue. **As of now, disk_partitions is virtually unusable.**

**Comment by giampaolo** [comment]
Since you identified the cause can't you just make a PR?

**Comment by MaWe2019** [comment]
Thanks. I'll do just that.
