### ISSUE TITLE
[Linux] Wrong cpu_count

### ISSUE THREAD

**Issue by orenbenkiki** [giampaolo/psutil#1969]
## Summary

* OS: Linux
* Architecture: X84
* Psutil version: 5.7.2
* Python version: 3.7.5
* Type: core

## Description

On a server with dual-socket. where each socket has 14 cores, then `cpu_count()` returns the expected 56 (number of logical processirs), but `cpu_count(logical=False)` returns 14 (per-socket value) instead of the expected 28 (actual total number of available physical cores in the system).

**Comment by jandrovins** [comment]
@orenbenkiki Do you still have this problem with latest version? I am running version 5.8.0 on Python 3.5.2 and printing `cpu_count` with and without `logical=False` works fine on my dual-socket Linux server.

**Comment by orenbenkiki** [comment]
I just tested and version 5.8.0 indeed seems to solve the problem (at least on my machine). Thanks!
