### ISSUE TITLE
Process Crashed On Windows Machines!!!

### ISSUE THREAD

**Issue by adhamelia** [giampaolo/psutil#1988]
* OS: Windows 10/2019/2016 
* Architecture:  64bit
* Psutil version: 5.8.0
* Python version: Python 3.7.4

  We are using psutil one of our project which collects server metrics using psutil package. after 8-9 hours, our process gets crashed on Windows machine while the same code works fine on all Linux/Unix based machines...  Is it OS problem or psutil problem ??? Attaching the windows eventlog for ref...

 We have tried multiple psutil version (5.6/5.7/5.8) but not luck :(

Log Name:      Application
Source:        Application Error
Date:          9/7/2021 10:22:13 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-VINHN6V
Description:
Faulting application name: python3.exe, version: 3.7.4150.1013, time stamp: 0x5d23a93f
Faulting module name: _psutil_windows.cp37-win_amd64.pyd, version: 0.0.0.0, time stamp: 0x5e4c25a3
Exception code: 0xc0000005
Fault offset: 0x00000000000092b4
Faulting process id: 0xbb48
Faulting application start time: 0x01d7a3d5e2e454c2
Faulting application path: C:\Program Files\Motadata\Motadata Agent\Python3\python3.exe
Faulting module path: C:\Program Files\Motadata\Motadata Agent\Python3\lib\site-packages\psutil\_psutil_windows.cp37-win_amd64.pyd
Report Id: b69606ea-2fce-4cde-9b7b-a1480424d7cd
Faulting package full name:
Faulting package-relative application ID:
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-09-07T16:52:13.668996100Z" />
    <EventRecordID>155072</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-VINHN6V</Computer>
    <Security />
  </System>
  <EventData>
    <Data>python3.exe</Data>
    <Data>3.7.4150.1013</Data>
    <Data>5d23a93f</Data>
    <Data>_psutil_windows.cp37-win_amd64.pyd</Data>
    <Data>0.0.0.0</Data>
    <Data>5e4c25a3</Data>
    <Data>c0000005</Data>
    <Data>00000000000092b4</Data>
    <Data>bb48</Data>
    <Data>01d7a3d5e2e454c2</Data>
    <Data>C:\Program Files\Motadata\Motadata Agent\Python3\python3.exe</Data>
    <Data>C:\Program Files\Motadata\Motadata Agent\Python3\lib\site-packages\psutil\_psutil_windows.cp37-win_amd64.pyd</Data>
    <Data>b69606ea-2fce-4cde-9b7b-a1480424d7cd</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by adhamelia** [comment]
Guys any clue ??? It's show stopper bug for us... Plz throw some light on this.

**Comment by Czaki** [comment]
It looks like a memory access violation error. The only thing that I could suggest is to compile code in debug mode and run it under the debugger to identify where the problem occurs. Without a minimal reproducible example, developers cannot perform any action.
