### ISSUE TITLE
Building Wheels for psutil with Python 3.10.0 raising Errors

### ISSUE THREAD

**Issue by Yuvaraja28** [giampaolo/psutil#2008]
## Summary

* OS: Windows-10-10.0.19042-SP0
* Architecture: 64bit
* Python version: 3.10.0
* Type: wheels, installation

## Description

When trying to Pip install shows error in Building wheels

**Comment by Ashtacore** [comment]
I was having an issue building the wheel as well on Windows Server 2019. I installed the MS build tools but got the error: C:\Program Files\Python310\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory

I found this answer on SO https://stackoverflow.com/a/50210015/13443483 and added the windows SDK through the Visual Studio installer. I meant to click on the latest version of the Windows 10 SDK, but accidentally selected the Windows 11 SDK. However after it finished installing I reran `pip install psutil` and it was able to successfully build the wheel.

Hope this helps in your debugging.

**Comment by Yuvaraja28** [comment]
Is there anyother way instead of downloading Visual Studio Installer in Windows??

**Comment by Ashtacore** [comment]
You can download the Windows SDK here: https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/ and the MS 2015 build tools can be installed here: https://www.microsoft.com/en-us/download/details.aspx?id=48159

Hope that works for you.
