### ISSUE TITLE
[Platform independent] Drop Python 2.x support 

### ISSUE THREAD

**Issue by auvipy** [giampaolo/psutil#2014]
## Summary

* OS: { type-or-version }
* Type: { Code }

## Description
Python 2.6 & 2.7 is EOL for long. lets drop support for python 2.x and modernize the codebase with 3.6/3.7+ only.

**Comment by giampaolo** [comment]
2.6 can probably go. 2.7... not a chance, for many years to come. It currently represents 7-10% of total downloads, aka around 70k /100k downloads per day: https://pypistats.org/packages/psutil

**Comment by auvipy** [comment]
ok then python 2.6
