### ISSUE TITLE
Please support GNU/kFreeBSD

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#202]
_From [matrixhasu](https://code.google.com/u/matrixhasu/) on August 29, 2011 01:22:41_

```
Hi,
in debian we have 2 flavors of GNU/kFreeBSD (amd64 and i386) and currently 
psutil is unable to detect those OSes since the check is too restrictive.

With the attached patch I'm able to build psutil and start the test suite, but 
I currently have 2 hangs:

- test_psutil.py - it hangs at "test_cmdline (__main__.TestCase) ..."
- test/test_memory_leaks.py - it hangs at "test_get_pid_list 
(__main__.TestModuleFunctionsLeaks) ..."

I'll see if I'll be able to debug it further in the coming days.

Regards,
Sandro
```

_Original issue: http://code.google.com/p/psutil/issues/detail?id=202_

**Comment by giampaolo** [comment]
From https://en.wikipedia.org/wiki/Debian_GNU/kFreeBSD and https://lists.debian.org/debian-devel-announce/2014/11/msg00005.html:

> Debian GNU/kFreeBSD was discontinued as an officially supported platform as of Debian 8.0.

> We discussed kfreebsd at length, but are not satisfied that a release with Jessie will be of sufficient quality. We are dropping it as an official release architecture, though we do hope that the porters will be able to make a simultaneous unofficial release.

As such, I'm closing this out as outdated.

**Comment by mr-c** [comment]
There is a new patchset for kfreebsd at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918884#5
