### ISSUE TITLE
No wheels for python 3.10 on PyPI

### ISSUE THREAD

**Issue by rikardn** [giampaolo/psutil#2028]
## Summary

* OS: all
* Architecture: all
* Psutil version: latest
* Python version: all
* Type: wheels

## Description

Difficult installing psutil for python 3.10 because wheels on pypi are missing. I guess this affects all packages having psutil as a dependency. I saw that built wheels are available as psutils-wheels, but using this is not an option if you have dependencies that depends on psutils.

**Comment by fenchu** [comment]
use psutil-wheels==5.8.0 util it is fixed

**Comment by giampaolo** [comment]
New psutil 5.9.0 is out, and it includes Python 3.10 wheels.

**Comment by rikardn** [comment]
Thanks!
