### ISSUE TITLE
[Any] Missing py36 wheels for v5.9.0

### ISSUE THREAD

**Issue by AntoineD** [giampaolo/psutil#2045]
See on [pypi](https://pypi.org/project/psutil/#files).

**Comment by isidroas** [comment]
I get an error installing psutil using python3.6. I don't know if it is related to this:
```
  copying psutil\tests\__main__.py -> build\lib.win-amd64-3.6\psutil\tests
  running build_ext
  building 'psutil._psutil_windows' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for psutil
```

**Comment by AntoineD** [comment]
@isidroas Yes it is.

**Comment by giampaolo** [comment]
Dropping wheel support for Python 3.6 was an explicit decision to ease up maintenance. We already support 4 versions (3.7, 3.8, 3.9, 3.10) + 1 (2.7).

**Comment by AntoineD** [comment]
@giampaolo This does not seem to be an explicit enough decision, just look at the README.rst or the INSTALL.rst.

**Comment by giampaolo** [comment]
3.6 is still supported. There simply are no pre-compiled wheels for it.

**Comment by isidroas** [comment]
Python 3.6 users can no longer use it, unless they remember to specify the version:
![image](https://user-images.githubusercontent.com/10489506/148550577-cbb8152f-1d96-43f3-98bd-e80b7f84e51c.png)
![image](https://user-images.githubusercontent.com/10489506/148550631-36cd0899-6a3a-4866-b823-697385c8867a.png)

In addition, the error message does not tell you clearly that is a problem related to the python version

**Comment by giampaolo** [comment]
I looked at dowload stats of Python 3.6, and realized they're still quite high:

 ```
### Python versions

| Python version                 |       Downloads |
|:------------------------------ | ---------------:|
| 3.7                            |      17,572,931 |
| 3.8                            |       4,920,216 |
| 3.6                            |       3,878,423 |
| 2.7                            |       2,421,810 |
| 3.9                            |       2,266,283 |
| 3.5                            |         528,630 |
| 3.10                           |         267,088 |
| 3.4                            |           5,323 |
| 3.11                           |             406 |
| 2.6                            |              49 |
```

...so I uploaded wheels for Python 3.6:

```
$ ls dist/
psutil-5.9.0-cp36-cp36m-macosx_10_9_x86_64.whl
psutil-5.9.0-cp36-cp36m-manylinux_2_12_i686.manylinux2010_i686.manylinux_2_17_i686.manylinux2014_i686.whl
psutil-5.9.0-cp36-cp36m-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
psutil-5.9.0-cp36-cp36m-win32.whl
psutil-5.9.0-cp36-cp36m-win_amd64.whl
```
