### ISSUE TITLE
[Linux] cpu_freq returns current value in GHz but min/max in MHz

### ISSUE THREAD

**Issue by grobie** [giampaolo/psutil#2049]
## Summary

* OS: Linux 5.15.12-arch1-1
* Architecture: 64bit
* Psutil version: 5.9.0
* Python version: Python 3.10.1
* Type: core

## Description

The current value of cpu_freq() seems to return the frequency in Gigahertz, but min+max are returned in Megahertz. I assume https://github.com/giampaolo/psutil/pull/1852 might have changed that?

```python
>>> import psutil
>>> psutil.cpu_freq(True)
[scpufreq(current=3.0, min=400.0, max=4800.0), scpufreq(current=3.0, min=400.0, max=4800.0), scpufreq(current=3.0, min=400.0, max=4800.0), scpufreq(current=3.0, min=400.0, max=4800.0), scpufreq(current=1.084, min=400.0, max=4800.0), scpufreq(current=3.0, min=400.0, max=4800.0), scpufreq(current=3.0, min=400.0, max=4800.0), scpufreq(current=1.695, min=400.0, max=4800.0)]
```

**Comment by giampaolo** [comment]
83d7067d7568f09ad95f094d17731e643a4a7ce6 should have fixed but please try and confirm it worked.

**Comment by Zorrototo** [comment]
Any ETA for 5.9.1 release? I would like to know so I can stop holding back 5.8.0 pack for issue in `s-tui` which should now be fixed for almost two months with [this patch](https://github.com/giampaolo/psutil/commit/83d7067d7568f09ad95f094d17731e643a4a7ce6). Thanks in advance for reply.
