### ISSUE TITLE
Real time disk IO counters

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#206]
_From [g.rodola](https://code.google.com/u/g.rodola/) on September 15, 2011 00:18:13_

```
Similarly to network_io_counters (see issue 150 ) it would be good for psutil 
to provide a disk_io_counters() function returning the number of bytes read and 
written from/to disk.
With this we'd have the possibility to write tools such as iotop [1].

>>> psutil.disk_io_counters()
iostat(read_bytes=2334342, write_bytes=12353453)

As an extra, if the OS provides the necessary hooks, it might be good to 
provide also the number of read()/write() calls, as per Process.get_io_counters 
method (see issue 64 ).

I haven't looked into any implementation yet so I'm still not sure what the 
implications are and whether this can be done on all platforms.

[1] http://guichaz.free.fr/iotop/
```

_Original issue: http://code.google.com/p/psutil/issues/detail?id=206_

**Comment by talestsp** [comment]
I have read that **read/write time** are _"the total amount of time (in nanoseconds) reading/writing to disk"_ Ok, but when it starts counting?
I have collected these metrics  (in a 15 seconds interval) and the values are, for example, 20, 28, 17, 23... I can't understand when this counter is reset to 0.

**Comment by giampaolo** [comment]
I suppose it starts counting since boot. With newer versions of psutil the counter will never reset to 0.
Please next time do not comment on such an old and closed thread.
