### ISSUE TITLE
[Windows] getloadavg() returns (0.0, 0.0, 0.0)

### ISSUE THREAD

**Issue by Ankitr19** [giampaolo/psutil#2063]
## Summary

* OS: { Windows 10 20h2 }
* Architecture: { 64bit }
* Psutil version: { 5.9.0 }
* Python version: { 3.10.2 }
* Type: { core}

## Description

{{{
I am trying to get the average load for my windows device using psutil, but it always keeps returning (0.0, 0.0, 0.0)
}}}

**Comment by dbwiddis** [comment]
Load average is a *nix thing.  It looks like psutil initializes its own counter on Windows to calculate this but would need to remain in execution long enough to collect useful data.

**Comment by giampaolo** [comment]
@dbwiddis is correct. The values on Windows are updated every 5 secs, so after the first call you'll keep seeing `(0.0, 0.0, 0.0)` for the next 5 secs.
