### ISSUE TITLE
[Linux] Does psutil report container-level metrics?

### ISSUE THREAD

**Issue by mrichman** [giampaolo/psutil#2076]
Looking for confirmation (or a workaround) to see if psutil reports container-level metrics, or if CPU and memory reported are from the host.

My containers report memory usage via `/sys/fs/cgroup/memory/memory.usage_in_bytes` for example. Just looking for guidance on whether to use this metric or psutil's `virtual.used` metric.

I just need to be sure that I'm reporting metrics from the container, not the host. Thanks!

**Comment by giampaolo** [comment]
Also see discussion in https://github.com/giampaolo/psutil/issues/2100.

**Comment by giampaolo** [comment]
Closing this one as a duplicate in favor of https://github.com/giampaolo/psutil/issues/2100 which has more discussion.
