### ISSUE TITLE
[OS] Why the function of cpu_freq() always getting the cpu default freq?

### ISSUE THREAD

**Issue by RosterMouch** [giampaolo/psutil#2083]
## Summary

* OS: Windows11 Home
* Architecture: 64bit
* Psutil version: 5.8.0
* Python version: 3.9.7(Base on Conda)
* Type: BugIssuses

## Description

Yeah,pretty confusing that i wanna using Flask and Psutil to make a monitor system,and yet the cpu_freq() functions seems doesnt work to detect freq?
![image](https://user-images.githubusercontent.com/75596885/157582506-60107f50-ae30-470e-b80c-482c61768893.png)

But in fact is:my cpu turboing very well.
![image](https://user-images.githubusercontent.com/75596885/157582541-1dd4d518-ca3f-4402-903c-b8977fb06b71.png)
So how should i fix that or otherwise is bottom layer issuses?

**Comment by dbwiddis** [comment]
Seems it's hardcoded that way:
```c
def cpu_freq():
    """Return CPU frequency.
    On Windows per-cpu frequency is not supported.
    """
    curr, max_ = cext.cpu_freq()
    min_ = 0.0
    return [_common.scpufreq(float(curr), min_, float(max_))]
```
In [the implementation](https://github.com/giampaolo/psutil/blob/b490b5d51af6ed29709c357a00fcdb6bda26df78/psutil/arch/windows/cpu.c#L403) the call to `GetNTPowerInformation()` returns a `ncpu`-sized array of `PROCESSOR_POWER_INFORMATION` structures but only the first one is fetched.  (Note: on systems with more than 64 logical processor groups this only returns the values for one group.)

I recall going down this road and think perhaps I saw that the frequencies were all the same here so this code may be acknowledging the API limitation.

A better source of processor frequency information is the performance counters:  `Processor Information\% of Maximum Frequency` returns a value 0 to 100 that can be multiplied by max freq (and divided by 100) to calculate it.

**Comment by RosterMouch** [comment]
Close this issuse due to unknow reasons
