### ISSUE TITLE
[macOS] Process.environ() often returns empty result

### ISSUE THREAD

**Issue by gaborcsardi** [giampaolo/psutil#2084]
## Summary

* OS: macOS Big Sur or later
* Architecture: all
* Psutil version: NA
* Python version: all
* Type: I wish it was core, but probably doc

## Description

On macOS Big Sur or later, `Process.environ()` often returns an empty dict. E.g.

```
❯ sleep 1000 &
[2] 70869

❯ python3
Python 3.9.10 (main, Jan 15 2022, 11:40:53)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> p = psutil.Process(70869)
>>> p.environ()
{}
```

The reason is that since Big Sur the `sysctl()` call that psutil uses only returns the env vars in these circumstances:

* kernel is DEVELOPMENT || DEBUG
* target process is same as current_proc()
* target process is not cs_restricted
* SIP is off
* caller has an entitlement

(From https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/bsd/kern/kern_sysctl.c#L1315-L1321)

It would be great to learn that there is another API to get the env vars, but I am afraid that there isn't, in which case psutil could document this.

**Comment by giampaolo** [comment]
Good catch. Documented in 2b57f24.
