### ISSUE TITLE
Generate Wheels for CPython 3.11 (or Use Limited API)

### ISSUE THREAD

**Issue by ericsnowcurrently** [giampaolo/psutil#2089]
The faster-cpython project uses pyperformance to run benchmarks, which in turn uses pyperf, which optionally uses psutil.  We run into problems when we try to benchmark CPython's main branch, since there are no corresponding wheels on PyPI.  See https://github.com/python/pyperformance/issues/148.

So it would be helpful to have wheels available on PyPI for the CPython 3.11 releases.  Furthermore, it would likewise help to have a wheel built for the main branch.

One alternative would be to release a build using CPython's limited API.  The resulting extension would be automatically compatible with the newer CPython.

**Comment by giampaolo** [comment]
Discussion at https://github.com/giampaolo/psutil/pull/2102 contains some progress on this topic.

**Comment by ericsnowcurrently** [comment]
Thanks!

CC @mdboom

**Comment by hroncok** [comment]
Do you plan to release a new version with the abi3 wheels before the final Python 3.11 release?  If not, would you consider publishing cp311 manylinux wheels for the recently released 5.9.3?

**Comment by hroncok** [comment]
psutil 5.9.4 was released. thanks.
