### ISSUE TITLE
Invalid values received for swap_memory()

### ISSUE THREAD

**Issue by rose112** [giampaolo/psutil#2091]
## Summary

* OS:  Windows 11 pro 64Bit (Version 21H2)
* Architecture:  64bit, Ryzen 5 (AMD64)
* Psutil version:  Version: 5.9.0
* Python version: 3.10.4 64Bit

## Description

{{{
Executing 
   "psutil.swap_memory()" 
on my system, the following result is received;
   "sswap(total=4091871232, used=4315365376, free=-223494144, percent=105.5, sin=0, sout=0)"
As you can see, the value of the used SWAP is greater than the total amount of the SWAP.
The value of the free SWAP is correctly calculated as negative and the percentage of use is
greater than 100% - also correctly calculated out of the values for total and available SWAP.

}}}

**Comment by dbwiddis** [comment]
Looks like a duplicate of #2074

**Comment by rose112** [comment]
Duplicate of https://github.com/giampaolo/psutil/issues/2074

so I close it
