### ISSUE TITLE
[FreeBSD] psutil.pids() fails with `[Errno 12] Cannot allocate memory (originated from sysctl)`

### ISSUE THREAD

**Issue by pilot513** [giampaolo/psutil#2093]
## Summary

* OS: { FreeBSD 13.0 P2 }
* OS Core: 13.0-RELEASE-p2 FreeBSD 13.0-RELEASE-p2 #2 releng/13.0-n244746-b74cdf1ecea
* Architecture: { 64bit, Intel(R) Xeon(R) CPU           E5630  @ 2.53GHz }
* Psutil version: { py38-psutil-5.9.0 }
* Python version: { Python 3.8.13 }
* Type: core
* 
## Description

```
04/04/22 (23:39:26) | ERROR: Data collection thread failed with exception: [Errno 12] Cannot allocate memory (originated from sysctl)
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 2958, in _runner
    collector._collect()
  File "/usr/local/bin/bpytop", line 3728, in _collect
    for p in sorted(psutil.process_iter(cls.p_values + (["memory_info"] if CONFIG.proc_mem_bytes else []), err), key=lambda p: eval(sort_cmd), reverse=reverse):
  File "/usr/local/lib/python3.8/site-packages/psutil/__init__.py", line 1432, in process_iter
    a = set(pids())
  File "/usr/local/lib/python3.8/site-packages/psutil/__init__.py", line 1372, in pids
    ret = sorted(_psplatform.pids())
  File "/usr/local/lib/python3.8/site-packages/psutil/_psbsd.py", line 512, in pids
    ret = cext.pids()
OSError: [Errno 12] Cannot allocate memory (originated from sysctl)
04/04/22 (23:39:28) | WARNING: Exiting with errorcode (1). Runtime 13:47:42
```

**Comment by giampaolo** [comment]
Ouch! This is bad. The error originates from [here](https://github.com/giampaolo/psutil/blob/f716afc81d4c9ded08b23d376612e1491d3ea5da/psutil/arch/freebsd/proc.c#L106-L112).

The fix should consist of calling the first `sysctl()` in a loop, and enlarge the buffer size it returns `ENOMEM`. There are similar constructs elsewhere in psutil. I'm CCing @glebius and @kostikbel just in case they have some comments about this.

Since I've never seen this happening here's a question: how many processes are running on this machine? `ps aux | wc -l` should tell.

**Comment by giampaolo** [comment]
Also how often does this happen? Can you reproduce it reliably?

**Comment by pilot513** [comment]
![image](https://user-images.githubusercontent.com/28645933/161813171-52ad1b7e-e3ae-454f-9017-25a964173c4b.png)

It's show working bashtop now. Not many processes. Basically it's a few virtual servers in VirtualBox

**Comment by pilot513** [comment]
$ uptime
20:17  up 2 days,  1:37, 4 users, load averages: 0,32 0,38 0,34

**Comment by pilot513** [comment]
This happened for the second time in two days. Therefore, I decided to write, because thought it would be important.
Yes, I can run both applications in parallel: bpytop / bashtop
Let's see what happens.

**Comment by pilot513** [comment]
Ok. I'm run that:
![image](https://user-images.githubusercontent.com/28645933/161814128-c7afcc6b-9a87-41ae-ba6f-bdf70ca2afcc.png)
Waiting now some time

**Comment by frikilax** [comment]
Hello there!
Just wanted to say that this also happens on HardenedBSD 12.3 (FreeBSD variant)!

uname -a : `FreeBSD hostname 12.3-STABLE-HBSD FreeBSD 12.3-STABLE-HBSD #0 : Mon Apr 18 00:48:16 UTC 2022     root@ci-12.md.hardenedbsd.lan:/usr/obj/usr/src/amd64.amd64/sys/HARDENEDBSD  amd64`
python version : 3.8.13
psutil version : 5.9.1

I rollbacked to psutil 5.8.0 and the error doesn't seem to happen anymore

**Comment by giampaolo** [comment]
This should now be fixed by https://github.com/giampaolo/psutil/commit/c7c7bbcfc762d73a50d3cb2ad6f277dad7bb9a6b which dynamically increase the buffer size instead of immediately giving up with `ENOMEM`.
Please confirm if you have the chance.

**Comment by frikilax** [comment]
I can confirm this resolved my issue, thanks!
