### ISSUE TITLE
[Linux] occasional deadlock in CI for `psutil.tests.test_contracts.TestFetchAllProcesses.test_all`

### ISSUE THREAD

**Issue by mayeut** [giampaolo/psutil#2104]
## Summary

* OS: Linux
* Architecture: at least x86_64, i686
* Psutil version: master
* Python version: at least 3.8/3.9/3.10
* Type: tests

## Description
`psutil.tests.test_contracts.TestFetchAllProcesses.test_all` deadlocks randomly in CI on Linux.
The job is then cancelled on timeout.
This has been seen on multiple occasions:
https://github.com/giampaolo/psutil/runs/6038584184?check_suite_focus=true (python 3.10 x86_64)
https://github.com/giampaolo/psutil/runs/5853723369?check_suite_focus=true (python 3.8 x86_64)
https://github.com/giampaolo/psutil/actions/runs/1705485233
https://github.com/mayeut/psutil/runs/6335366674?check_suite_focus=true (python 3.9 i686)

It seems to be linked to the `multiprocessing.Pool`. Switching to a "spawn" context as suggested [here](https://pythonspeed.com/articles/python-multiprocessing/) also deadlocks on my machine (docker, through cibuildwheel) but after all tests are ran (i.e. on python shutdown). I might have missed something in this implementation.

**Comment by giampaolo** [comment]
[735de78](https://github.com/giampaolo/psutil/commit/735de787b84a1c8410d97ce402847bfc0c535487) disables process pool usage if running in a CI env. Closing.
