### ISSUE TITLE
[Linux] Performance optimization for Process.memory_full_info()

### ISSUE THREAD

**Issue by itamarst** [giampaolo/psutil#2107]
## Summary

* OS: Linux
* Type: performance

## Description

Current `Process().memory_full_info()` reads `/proc/<pid>/smaps`, and then sums across maps. This can be slow if there are many maps. 

Linux provides a `/proc/<pid>/smaps_rollup` that is the information in `smaps` summarized across the whole process: exactly what this function is calculating. For processes with large number of mmaps, using this file directly would reduce the cost of `memory_full_info()` significantly.

This was apparently added to Linux sometime in 2017 or 2018.

It's the same format, so you could the exact same code, even, just open that file instead if it exists.

**Comment by giampaolo** [comment]
Well, this is awesome.

**Comment by giampaolo** [comment]
I've just implemented this in https://github.com/giampaolo/psutil/pull/2108.

Without patch:
```
~/svn/psutil {linux-smaps-rollup}$ python3 -m timeit -s "import psutil; p = psutil.Process()" "p.memory_full_info()"
500 loops, best of 5: 518 usec per loop
```

With patch (5 times faster):
```
~/svn/psutil {linux-smaps-rollup}$ python3 -m timeit -s "import psutil; p = psutil.Process()" "p.memory_full_info()"
2000 loops, best of 5: 111 usec per loop
```
