### ISSUE TITLE
[macOS/Docker] Current process stats are sanitized

### ISSUE THREAD

**Issue by lnguyenPHI** [giampaolo/psutil#2112]
## Summary

* OS: macOS Monterey 12.4
* Architecture: ARM64
* Psutil version: 5.9.1
* Python version: 3.8.9
* Type: core

## Description

In a linux/amd64 container on macOS, psutil reports wrong stats because output from /proc/pid/stat is sanitized. This only applies to the current process. 

```
>>> import psutil
>>> psutil.Process()
psutil.Process(pid=94005, name='python', status='?', started='21:31:57')
>>> with open("/proc/94005/stats", "rb") as f:
        f.read()
b'94005 (python) 0 36803 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 274903095072 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n'
```

**Comment by giampaolo** [comment]
What do you mean by "sanitized"?
`Process.status()` is taken from the third element of /proc/pid/stat. For some reason on your machine it's `0`, which is why psutil reports the status as a question mark `?`:
```
b'94005 (python) 0  <--- this
```

Usually it's a capital letter.

**Comment by lnguyenPHI** [comment]
Thanks for the quick reply! I mean a lot of these stats were replaced with 0 somehow:
```
>>> import psutil
>>> psutil.Process()
psutil.Process(pid=11871, name='python', status='?', started='21:31:57')
>>> with open("/proc/11871/stat", "rb") as f:
        f.read()
b'11871 (python) 0 36803 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 274903095072 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n'
>>> import subprocess
>>> subprocess.run("cat /proc/11871/stat", shell=True, capture_output=True)
CompletedProcess(args='cat /proc/11871/stat', returncode=0, stdout=b'11871 (python) S 36803 11871 36803 34819 11871 4194560 6591 3080 2 2 63 9 31 10 20 0 2 0 5692122 167149568 8871 18446744073709551615 2900224 4590696 281474773579888 0 0 0 0 16781312 1988161279 0 0 0 17 1 0 0 0 0 0 4959640 5038760 502562816 281474773584335 281474773584385 281474773584385 281474773585890 0\n', stderr=b'')
```

And it only happens to the current process. In another python REPL:
```
>>> import psutil
>>> psutil.Process(11871)
psutil.Process(pid=11871, name='python', status='sleeping', started='13:20:38')
```
`create_time` for example defaulted to `boot_time` in the first shell because `starttime` was masked with 0.

**Comment by roryschadler** [comment]
Have you found any workaround for this @lnguyenPHI? Followed you here from the ray issue, having the same `ray.init` failure.

**Comment by giampaolo** [comment]
I'm going to close this as won't fix. It's an oddity of the (emulated) kernel to return that content filled with 0 / null values. psutil cannot do anything about it.
