### ISSUE TITLE
[Linux] Adding CPU numbers to thread objects

### ISSUE THREAD

**Issue by georgechustz-embark** [giampaolo/psutil#2117]
## Summary
[My fork](https://github.com/georgechustz-embark/psutil) simply reads in the CPU/core number from the stat file  when reading in thread information in the same way as it does for the processes object.

* OS: Linux
* Type: core

## Description

[Link to changes](https://github.com/giampaolo/psutil/commit/0bec29b7e80ba645b240a1ef28f219ed6b5b552d)
The changes simply add a cpu_num value to the pthread named tuple, and fills it with item at index 36 from the thread's stat file in the same way that the process does.

**Comment by giampaolo** [comment]
This can only be supported on Linux. Also, you can achieve the same thing by iterating over thread IDs as in:

```python
import psutil

proc = psutil.Process()
while 1:
    for t in proc.threads():
         print(psutil.Process(t.id).cpu_num())
```

Closing as won't fix.
