### ISSUE TITLE
 AttributeError: psutil has no attribute 'dirty'

### ISSUE THREAD

**Issue by manjhi-amit** [giampaolo/psutil#2122]
## Summary

* OS:  Ubuntu1804
* Architecture: 64bit, 32bit, ARM, PowerPC, s390 
* Psutil version: 5.9.0
* Python version: python3.6.8 
* Type: scripts

## Description

Hello guys I am working on a python3 migration project in which I have upgraded psutil version to 5.9.0
here is a snippet of my code

`import psutil

mem = psutil.virtual_memory()

x.add_metric(schema.yy_MEMORY_DIRTY, mem.dirty)`
![Screenshot 2022-07-13 at 2 23 44 PM](https://user-images.githubusercontent.com/108260421/178693212-d20fcb60-c294-4f55-971a-7bc29c0db5b4.png)

Attaching screenshots for your reference

**Comment by giampaolo** [comment]
https://psutil.readthedocs.io/en/latest/#psutil.virtual_memory is not supposed to return any `dirty` mem info. That's `psutil.Process.memory_info()`.
