### ISSUE TITLE
How to convert these two data into total CPU utilization?

### ISSUE THREAD

**Issue by LRF520** [giampaolo/psutil#2129]
I open a Google browser, which has many independent processes. If I use the method "psutil. Process(). Cpu_percent()" to calculate the CPU utilization of multiple chrome.exe processes, how can I convert these independent CPU utilization into the total CPU utilization? Let me give an example (my CPU is 8 logical cores):

psutil.Process(16196).cpu_ percent()=30%

psutil.Process(4740).cpu_ percent()=10%

How to convert these two data into total CPU utilization:

psutil.Process(16196).cpu_ percent()+psutil.Process(4740).cpu_ percent()=???

![20220810_143303](https://user-images.githubusercontent.com/58470642/183832796-71a8f114-7643-49c1-bc61-58a16651c174.jpg)

**Comment by LRF520** [comment]
In fact, my puzzle is how to calculate the total CPU utilization rate of the whole Google browser. Because there are many processes in Google browser, I want to get the total CPU utilization rate of Google browser. A lot of software runs and there are many independent processes, just like Google browser. Is there any way to calculate the total CPU utilization of such multi process software?

**Comment by giampaolo** [comment]
Assuming you collect info for all processes **at the same time/interval**, I suppose you can just add percentages together. Not tested:

```python
import psutil, time

procs = [psutil.Process(123), psutil.Process(456), psutil.Process(789)]
while 1:
    tot = sum([x.cpu_percent() for x in procs])
    print(tot)
    time.sleep(1)
```

**Comment by LRF520** [comment]
Thanks,i will try it.
