### ISSUE TITLE
[QNX] QNX support

### ISSUE THREAD

**Issue by large-cat** [giampaolo/psutil#2143]
## Summary

* OS: QNX 7.0 
* Type: core

## Description
  Whether psutil can be supported on qnx.
  I want to use psutil on "qnx 7.0". Could you help me complete the adaptation?
  Looking forward to your reply. 
  Thank you so much.

**Comment by giampaolo** [comment]
It looks like this is a proprietary platforms, with very few potential downloads. More or less, the same considerations for rejecting [IBM i](https://github.com/giampaolo/psutil/pull/1564#issuecomment-748328481) support apply here as well.
