### ISSUE TITLE
Centos 7 armv8 and pypy issue

### ISSUE THREAD

**Issue by mixmind** [giampaolo/psutil#2144]
## Summary

* OS: Centos 7
* Architecture: ARM 64
* Psutil version: 5.6.7
* Python version: Python 3.9.12
* Pypy version: [PyPy 7.3.9 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
* Type: core
## Description

I'm trying to use plutil on Centos 7 with arm architecture, and its fails on import with strange error. See error attached

 ```
pypy3.9 
Python 3.9.12 (05fbe3aa5b0845e6c37239768aa455451aa5faba, Mar 29 2022, 13:45:01)
[PyPy 7.3.9 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import psutil
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/pypy3.9/site-packages/psutil/__init__.py", line 96, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib/pypy3.9/site-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: /usr/lib/pypy3.9/site-packages/psutil/_psutil_linux.pypy39-pp73-aarch64-linux-gnu.so: undefined symbol: PyExc_RuntimeError
```

**Comment by giampaolo** [comment]
You have to install `python-dev` or `python-devel` package, depending on the distro. Closing.

**Comment by mixmind** [comment]
Have you tried to reproduce it?
I can’t install psutil without packages that you are saying. Because it asks for it during pip install

**Comment by giampaolo** [comment]
You have to install them with the system package manager (eg apt)

**Comment by mixmind** [comment]
oh, interesting. If there is no python3.9 for centos 7 with arm, and I had to compile it. 
There is still a chance to use psutil??

**Comment by mixmind** [comment]
If someone has same issue , just use —no-binary during pip install
