### ISSUE TITLE
[OS] process name truncated when it ends with "k"

### ISSUE THREAD

**Issue by Alex-Izquierdo** [giampaolo/psutil#2159]
## Summary

* OS: fedora 34 / fedora 36
* Architecture: 64bit
* Psutil version: Version: 5.8.0 / 5.9.3
* Python version: 3.9.13 / 3.10.7

## Description
process.name() returns a truncated process name when ends with "k". 
(Verified with multple (python) programs ended in "k")

## How to reproduce:
Install ansible and run a simple playbook
```sh
pip install ansible
ansible-playbook play.yml
``` 
play.yml:
```yml
- hosts: localhost
  connection: local
  tasks:
    - shell: sleep 1000
```

Actual result: 

python shell:
```python
>>> import psutil
>>> p = next(proc for proc in psutil.process_iter() if "playboo" in proc.name())
>>> p.name()
'ansible-playboo'
```
Expected result:
`ansible-playbook` not `ansible-playboo`

**Comment by giampaolo** [comment]
This is known. It's a limitation we have on different POSIX system. Process name can be truncated to the 15th character. When this happens we try to infer the full name() from the cmdline():
https://github.com/giampaolo/psutil/blob/1da9f7928e79ecc127768e7a5bc4eb7f785f4513/psutil/__init__.py#L622-L635

```python
>>> len('ansible-playboo')
15
```

**Comment by Alex-Izquierdo** [comment]
ok, thanks.
