### ISSUE TITLE
Python 3.11 wheels are missing on PYPI

### ISSUE THREAD

**Issue by XJTLUmedia** [giampaolo/psutil#2163]
## Summary

* OS: { Windows}
* Architecture: { 64bit, }
* Psutil version: { No package yet }
* Python version: { python3.11 }
* Type: {  installation }

## Description

**Works well on python 3.10, but not in python 3.11**

pip install ipykernel

`Collecting ipykernel
  Downloading ipykernel-6.16.1-py3-none-any.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.5/138.5 kB 411.2 kB/s eta 0:00:00
Collecting debugpy>=1.0
  Downloading debugpy-1.6.3-py2.py3-none-any.whl (4.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 482.2 kB/s eta 0:00:00
Collecting ipython>=7.23.1
  Downloading ipython-8.5.0-py3-none-any.whl (752 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 752.0/752.0 kB 461.0 kB/s eta 0:00:00
Collecting jupyter-client>=6.1.12
  Downloading jupyter_client-7.4.3-py3-none-any.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.2/132.2 kB 487.8 kB/s eta 0:00:00
Collecting matplotlib-inline>=0.1
  Downloading matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting nest-asyncio
  Downloading nest_asyncio-1.5.6-py3-none-any.whl (5.2 kB)
Collecting packaging
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 kB 984.2 kB/s eta 0:00:00
Collecting psutil
  Downloading psutil-5.9.3.tar.gz (483 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 483.6/483.6 kB 541.0 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyzmq>=17
  Downloading pyzmq-24.0.1-cp311-cp311-win_amd64.whl (990 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 990.3/990.3 kB 471.6 kB/s eta 0:00:00
Collecting tornado>=6.1
  Downloading tornado-6.2-cp37-abi3-win_amd64.whl (425 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.3/425.3 kB 474.4 kB/s eta 0:00:00
Collecting traitlets>=5.1.0
  Downloading traitlets-5.5.0-py3-none-any.whl (107 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.4/107.4 kB 478.5 kB/s eta 0:00:00
Collecting backcall
  Downloading backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting decorator
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting jedi>=0.16
  Downloading jedi-0.18.1-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 511.0 kB/s eta 0:00:00
Collecting pickleshare
  Downloading pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting prompt-toolkit<3.1.0,>3.0.1
  Downloading prompt_toolkit-3.0.31-py3-none-any.whl (382 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 382.3/382.3 kB 553.7 kB/s eta 0:00:00
Collecting pygments>=2.4.0
  Downloading Pygments-2.13.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 497.5 kB/s eta 0:00:00
Collecting stack-data
  Downloading stack_data-0.5.1-py3-none-any.whl (24 kB)
Collecting colorama
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting entrypoints
  Downloading entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting jupyter-core>=4.9.2
  Downloading jupyter_core-4.11.2-py3-none-any.whl (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.5/88.5 kB 416.1 kB/s eta 0:00:00
Collecting python-dateutil>=2.8.2
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 422.5 kB/s eta 0:00:00
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 471.1 kB/s eta 0:00:00
Collecting parso<0.9.0,>=0.8.0
  Downloading parso-0.8.3-py2.py3-none-any.whl (100 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 576.7 kB/s eta 0:00:00
Collecting pywin32>=1.0
  Downloading pywin32-304-cp311-cp311-win_amd64.whl (12.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 511.6 kB/s eta 0:00:00
Collecting wcwidth
  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting executing
  Downloading executing-1.1.1-py2.py3-none-any.whl (22 kB)
Collecting asttokens
  Downloading asttokens-2.0.8-py2.py3-none-any.whl (23 kB)
Collecting pure-eval
  Downloading pure_eval-0.2.2-py3-none-any.whl (11 kB)
Building wheels for collected packages: psutil
  Building wheel for psutil (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for psutil (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\psutil
      copying psutil\_common.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_compat.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psaix.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psbsd.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_pslinux.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psosx.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psposix.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_pssunos.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_pswindows.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\__init__.py -> build\lib.win-amd64-cpython-311\psutil
      creating build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\runner.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_aix.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_bsd.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_connections.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_contracts.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_linux.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_misc.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_osx.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_posix.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_process.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_sunos.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_system.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_testutils.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_unicode.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_windows.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\__init__.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\__main__.py -> build\lib.win-amd64-cpython-311\psutil\tests
      running build_ext
      building 'psutil._psutil_windows' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/    
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psutil
Failed to build psutil
ERROR: Could not build wheels for psutil, which is required to install pyproject.toml-based projects`

**Comment by gleatd01** [comment]
Also, having this issue python 3.11.0 fresh venv.

**Comment by gleatd01** [comment]
I successfully installed psutil following the instructions here https://stackoverflow.com/a/73715493, it essentially says download the psutil's wheel file from https://www.lfd.uci.edu/~gohlke/pythonlibs/#_psutil then install it. pip install psutil-5.9.0-cp311-cp311-win_amd64.whl in my case. I am sure a better way can be figured out.

**Comment by gleatd01** [comment]
Also, the same method does not work with the latest wheel from https://pypi.org/project/psutil/#files

**Comment by Martal24** [comment]
> I successfully installed psutil following the instructions here https://stackoverflow.com/a/73715493, it essentially says download the psutil's wheel file from https://www.lfd.uci.edu/~gohlke/pythonlibs/#_psutil then install it. pip install psutil-5.9.0-cp311-cp311-win_amd64.whl in my case. I am sure a better way can be figured out.

Worked for me, thanks a lot !

**Comment by nNoidea** [comment]
Installing the build tools (via: https://visualstudio.microsoft.com/visual-cpp-build-tools/) solved my problem.

![image](https://user-images.githubusercontent.com/58337790/199821834-097e4059-1919-44da-b081-c87bb0ca63fe.png)

**Comment by SKardar** [comment]
> 

There is no such file "psutil-5.9.0-cp311-cp311-win_amd64.whl" in the link!

**Comment by ImpatientTurtle** [comment]
> > 
> 
> There is no such file "psutil-5.9.0-cp311-cp311-win_amd64.whl" in the link!

https://download.lfd.uci.edu/pythonlibs/archived/psutil-5.9.0-cp311-cp311-win_amd64.whl

**Comment by SKardar** [comment]
> > > 
> > 
> > 
> > There is no such file "psutil-5.9.0-cp311-cp311-win_amd64.whl" in the link!
> 
> https://download.lfd.uci.edu/pythonlibs/archived/psutil-5.9.0-cp311-cp311-win_amd64.whl

Thank you, where should I copy the file? I mean which directory on my pc?

**Comment by ImpatientTurtle** [comment]
> > > > 
> > > 
> > > 
> > > There is no such file "psutil-5.9.0-cp311-cp311-win_amd64.whl" in the link!
> > 
> > 
> > https://download.lfd.uci.edu/pythonlibs/archived/psutil-5.9.0-cp311-cp311-win_amd64.whl
> 
> Thank you, where should I copy the file? I mean which directory on my pc?

I've just been keeping it in my downloads directory and running `py.exe -3.11 -m pip install ~\psutil-5.9.0-cp311-cp311-win_amd64.whl` until we get a new psutil release that works with Python 3.11 without installing the build tools.

**Comment by Defcon404** [comment]
Unable to update psutil. I get the following error.

"C:\Users\anura>pip install --upgrade psutil
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psutil in c:\users\anura\appdata\roaming\python\python311\site-packages (5.9.0)
Collecting psutil
  Using cached psutil-5.9.3.tar.gz (483 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: psutil
  Building wheel for psutil (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for psutil (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\psutil
      copying psutil\_common.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_compat.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psaix.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psbsd.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_pslinux.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psosx.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psposix.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_pssunos.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_pswindows.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\__init__.py -> build\lib.win-amd64-cpython-311\psutil
      creating build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\runner.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_aix.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_bsd.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_connections.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_contracts.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_linux.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_misc.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_osx.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_posix.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_process.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_sunos.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_system.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_testutils.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_unicode.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_windows.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\__init__.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\__main__.py -> build\lib.win-amd64-cpython-311\psutil\tests
      running build_ext
      building 'psutil._psutil_windows' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psutil
Failed to build psutil
ERROR: Could not build wheels for psutil, which is required to install pyproject.toml-based projects"

**Comment by giampaolo** [comment]
To fix this I will have to upload wheels for Python 3.11. Locking discussion since the problem is clear.

**Comment by giampaolo** [comment]
New psutil 5.9.4 wheels supporting ABI3 / limited C API were uploaded so this should fixed.

**Comment by MEDIYouTube** [comment]
HOW TO FIX IT? 
Building wheel for psutil (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for psutil (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\psutil
      copying psutil\_common.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_compat.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psaix.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psbsd.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_pslinux.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psosx.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psposix.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_pssunos.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_pswindows.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\__init__.py -> build\lib.win-amd64-cpython-311\psutil
      creating build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\foo.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\runner.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_aix.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_bsd.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_connections.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_contracts.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_linux.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_misc.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_osx.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_posix.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_process.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_sunos.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_system.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_testutils.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_unicode.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_windows.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\__init__.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\__main__.py -> build\lib.win-amd64-cpython-311\psutil\tests
      running build_ext
      building 'psutil._psutil_windows' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psutil
Failed to build psutil
ERROR: Could not build wheels for psutil, which is required to install pyproject.toml-based projects
