### ISSUE TITLE
ERROR: Failed building wheel for psutil

### ISSUE THREAD

**Issue by Defcon404** [giampaolo/psutil#2166]
## Summary

Win 11 22h2
64bit
not able to install pustil
3.11.0
none

unable to install pustil

{{{
  I upgraded to python 3.11.0. Then i tried to run jupyter notebook cell via vs code and the ide said i need to install ipkernal within quotations. 

"Running cells with 'Python 3.11.0 64-bit' requires ipykernel package.
Run the following command to install 'ipykernel' into the Python environment.
Command: 'c:/Users/anura/AppData/Local/Programs/Python/Python311/python.exe -m pip install ipykernel -U --user --force-reinstall".

 Via elevated cmd I tried installing the same but encountered error within quotations.

"note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psutil
Failed to build psutil
ERROR: Could not build wheels for psutil, which is required to install pyproject.toml-based projects
"
After this I submitted an issue request with vs code github page and I was informed that vs code was fine and that it was an issue with ipkernel . Then I submitted the same issue with ipkernal github page, there I was again told that this was not an issue with ipkernal and it was issue with psutil. So now I am finally submitting an issue request to you.
Belo are the github links to my issues posted earlier.
https://github.com/microsoft/vscode-jupyter/issues/11820
https://github.com/ipython/ipykernel/issues/1011

Please help in this regard. Also I am attaching screenshot of the error messages.
Please help.
Thank You
![error](https://user-images.githubusercontent.com/83384787/199247981-7d618187-a024-43a2-900e-a8e6be6548f5.jpg)

}}}

**Comment by ReneDussault** [comment]
same thing over here.

```
running build_ext
      building 'psutil._psutil_windows' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psutil
Failed to build psutil
ERROR: Could not build wheels for psutil, which is required to install pyproject.toml-based projects

```
ive tried to install visual c++ build tools. does not change anything.

**Comment by Carreau** [comment]
Please have a minimal decency and search for other similar issues. #2165 the issue just before this one is the same issue – it was the one at the top of the bug tracker when this issue was opened. Same as #2163 which is 3 issues before this one.

You've also been suggested to avoid screenshot and provide text.
