### ISSUE TITLE
[Linux] New psutil version (5.9.4) fails to install

### ISSUE THREAD

**Issue by ofirbit** [giampaolo/psutil#2169]
## Summary

* OS: Linux
* Architecture:  64bit
* Psutil version: 5.9.4
* Python version: 3.9.7
* Type: installation 

## Description

Hello,
The new released version (5.9.4) seems to not install correctly. Getting this in our pipelines:
```
E   ImportError: version conflict: '/opt/conda/lib/python3.9/site-packages/psutil/_psutil_linux.cpython-39-x86_64-linux-gnu.so' C extension module was built for another version of psutil (5.9.0 instead of 5.9.4); you may try to 'pip uninstall psutil', manually remove /opt/conda/lib/python3.9/site-packages/psutil/_psutil_linux.cpython-39-x86_64-linux-gnu.so or clean the virtual env somehow, then reinstall
```

**Comment by giampaolo** [comment]
That should mean that your previously installed version conflicts with the new one for some reason (perhaps because you installed the first from sources?).

You should be able to fix that by getting psutil sources from git and then:

```
make clean
make uninstall
python3 -m pip install psutil
```

**Comment by ofirbit** [comment]
Hey @giampaolo. Thanks for the prompt response. In fact, the failure happens on a Gitlab pipeline that creates a new virtual environment every time and installs everything from scratch. I cleared Gitlab cache and it still happens.

**Comment by giampaolo** [comment]
That looks like a problem with your setup / environment. Closing.

**Comment by nurettin** [comment]
This happened to me as well. 
Steps to resolve:
```
rm your_virtual_environment_dir/psutil/*.so 
pip uninstall psutil
pip install -U psutil
```
