### ISSUE TITLE
[ALL] cpu_percent() (and/or similar functions):  Add pid=N argument

### ISSUE THREAD

**Issue by L3337** [giampaolo/psutil#2176]
## Summary

* OS: All
* Type: performance

## Description

In it's current form, cpu_percent() is useful, for example, creating a system monitoring application.  I am interested in monitoring the CPU usage of my own application only, regardless of what the overall system is doing.  Likely I would want to aggregate the percent into a single number (percpu=False), but I could eventually also create a multi-core CPU usage widget.

For example, for the application to monitor itself:
```
cpu_percent = psutil.cpu_percent(percpu=False, pid=os.getpid())
```
Or in my case, I actually want to measure the performance of my child process that does all of the hard work, so something like:
```
child = subprocess.Popen(...)
cpu_percent = psutil.cpu_percent(percpu=False, pid=child.pid)
```

I'm fairly confident that every platform has APIs that support this

**Comment by giampaolo** [comment]
What you're describing already exist since... forever. It's called `psutil.Process.cpu_percent()`.

**Comment by L3337** [comment]
Thanks, was not aware that existed.
