### ISSUE TITLE
[Windows WSL2 Docker] Getting wrong metrics

### ISSUE THREAD

**Issue by Nollknolle** [giampaolo/psutil#2183]
## Summary

* OS: Windows WSL2 Docker
* Architecture: 64bit
* Psutil version: 5.9.4
* Python version: 3.11
* Type: core

## Description

When I am using docker i cant get any metrics from my host. Is there a way i can get the windows metrics?

**Comment by giampaolo** [comment]
psutil can only be used locally (meaning not remotely on another host / VM)
