### ISSUE TITLE
[RPi OS] Invalid CPU percentage values

### ISSUE THREAD

**Issue by hex-developer** [giampaolo/psutil#2193]
## Summary

* OS: Raspberry Pi OS Lite
* Architecture: ARM
* Psutil version: 5.8.0
* Python version: Python 3.9.2
* Type: not sure

## Description

I am using psutil to return cpu usage for each core. From the python interpreter this works correctly, however from a script it does not.
Both are using the same python version.
The code I run is 
```
import psutil
print(psutil.cpu_percent(percpu=True))
```
In both cases, this returns no errors.
When executing the script, I get values such as `[0.0, 0.0, 0.0, 0.0]` and `[0.0, 0.0, 100.0, 0.0]`
Running htop proves that cpu usage is different and that all cores are used.
Even rebooting failed to help.

**Comment by hex-developer** [comment]
I upgraded to psutil version 5.9.4 and I still have the same results

**Comment by giampaolo** [comment]
From doc:

> Warning: the first time this function (psutil.cpu_percent()) is called with interval = 0.0 or None it will return a meaningless 0.0 value which you are supposed to ignore.

Translated: to get meaningful values you have to call `psutil.cpu_percent()` in a loop with an interval:

```
while 1:
    print(psutil.cpu_percent())
    time.sleep(1)
```

**Comment by hex-developer** [comment]
I am sorry, I did not mention that I was actually calling the function in a loop. I have attached a screenshot of the terminal output after my function converting the values to a format I would like to use, but also original values from the cpu_percent function
![Screenshot_20230124_162310_com.viber.voip_edit_681986326979.jpg](https://user-images.githubusercontent.com/77530549/214319964-3a594caa-a7fc-444e-9265-2af529a0c779.jpg)

Here is the screenshot of the code I run:

![Screenshot_20230124_162813_org.mozilla.firefox_edit_958593908707.jpg](https://user-images.githubusercontent.com/77530549/214321191-b02b95a9-c860-4c11-80ce-3731a9631593.jpg)

**Comment by hex-developer** [comment]
I wrote the same code in a different way and it worked. Thank you!
