### ISSUE TITLE
[Termux] PermissionError: [Errno 13] Permission denied: '/proc/stat'

### ISSUE THREAD

**Issue by babaric-dev** [giampaolo/psutil#2195]
## Summary

* OS: Android 10
* Architecture: aarch64
* Psutil version: 5.9.4
* Python version: 3.11.1
* Type: core

## Description
```
>>> import psutil
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_common.py", line 399, in wrapper
    return cache[key]
           ~~~~~^^^^^
KeyError: (('/proc',), frozenset())
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_pslinux.py", line 285, in <module>
    set_scputimes_ntuple("/proc")
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_common.py", line 401, in wrapper
    ret = cache[key] = fun(*args, **kwargs)                                       ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_pslinux.py", line 268, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_common.py", line 728, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/proc/stat'
>>>
```

From the error message above, 2 errors occured:
1. `KeyError` (IDK why this appears)
2. `PermissionError` (because of SeLinux restrictions on Android)

I want to focus on more about the second error. Because we never know which files are readable and which are not, we should handle exceptions raised by `open()`. We should add an `try-except` clause catching `PermissionError`. Another solution that I propose is to check whether the file is readable first before actually reading it. Both have their pros and cons, but I prefer the latter solution.

**Comment by giampaolo** [comment]
Paste the full error here instead of opening two tickets.

**Comment by giampaolo** [comment]
The error originates from [here](https://github.com/giampaolo/psutil/blob/2da99502238852f18f74db05304e67a01ee77005/psutil/_pslinux.py#L284-L289) and occurs at import time. It's just printed, meaning it does not crash the app.

`KeyError` before `PermissionError` is legitimate, although a bit confusing: it just means caching didn't happen yet. We may want to improve that though.

As for `PermissionError`, I don't think there's anything we can do. If a basic file like `/proc/stat` cannot be read, I imagine tools like `htop` or `ps` won't work as well (unless they have SUID permissions).

**Comment by giampaolo** [comment]
> KeyError before PermissionError is legitimate, although a bit confusing: it just means caching didn't happen yet. We may want to improve that though.

This part is now solved by https://github.com/giampaolo/psutil/pull/2196. The `KeyError` part is no longer shown in traceback messages.

**Comment by babaric-dev** [comment]
A bit off-topic, but when will 5.9.5 be released?

**Comment by thewhiteh4t** [comment]
@giampaolo in version `5.9.5` specifically in `termux`, we cannot catch `PermissionError` ?

**Comment by thewhiteh4t** [comment]
![Screenshot_20230822-233034.png](https://github.com/giampaolo/psutil/assets/36354846/e0fc41a8-5725-4d14-bf41-f700a8014d20)

**Comment by Ammar-Husain** [comment]
So How to get rid of this annoying error each time i run the code ?

**Comment by romanovj** [comment]
@Ammar-Husain you can copy /proc/stat with adb and then read it

/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_pslinux.py

function def set_scputimes_ntuple(procfs_path):

replace

with open_binary('%s/stat' ...



with

os.system('adb shell cp /proc/stat /sdcard/stat')
with open_binary('%s/stat' % "/sdcard" ) as f:

**Comment by giampaolo** [comment]
I have fixed this in https://github.com/giampaolo/psutil/commit/becbe86f6e5b686ad3cfaee3ea6afddffae82170. The error/exception is no longer printed on screen. It is only shown by using `PSUTIL_DEBUG` env var.

**Comment by thewhiteh4t** [comment]
works now, thanks a lot!!

**Comment by ishanyoshitha03-art** [comment]
Pleace tell
