### ISSUE TITLE
[Linux] offline cpus raise NotImplementedError in cpu_freq

### ISSUE THREAD

**Issue by ohsix** [giampaolo/psutil#2254]
python3-psutil (5.9.2) on fedora 38

turn cpu1 off:
`echo 0 > /sys/devices/system/cpu/cpu1/online`

or every cpu but cpu0:
`for i in $(seq 1 $(nproc --ignore=1)); do echo 0 > /sys/devices/system/cpu/cpu$i/online; done
`
cpu_freq needs one more case to skip offline cpus (or ones without the sysfs files for frequency, which means the same thing)

https://github.com/giampaolo/psutil/blob/7eadee31db2f038763a3a6f978db1ea76bbc4674/psutil/_pslinux.py#L749

**Comment by singingtelegram** [comment]
Experienced the same issue after turning some cores off.

```
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 1864, in cpu_freq
    ret = _psplatform.cpu_freq()
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 742, in cpu_freq
    raise NotImplementedError(
NotImplementedError: can't find current frequency file
```
