### ISSUE TITLE
[Linux] Allow Process() to take an existing Process as argument

### ISSUE THREAD

**Issue by smprather** [giampaolo/psutil#2262]
Would be nice if Process() could take an existing Process as an argument and just return it. This is similar to how pathlib.Path() works.

The workaround to check in the input type is trivial, so this is a very soft ask. Take/leave. Thanks!

```python
# Example, take an int or Process as input. Default self pid.
def foo(proc: int | Process | None):
    proc = Process(proc) if proc else Process()
```

**Comment by giampaolo** [comment]
I don't see how this would be useful in practice. Why would you pass a `Process` instance to `Process`?

**Comment by smprather** [comment]
So that I can write a proc that takes a PID as an integer or a Process() object. Why do you suppose pathlib.Path supports it? Do you think they made a mistake?

```python
# Example, take an int or Process as input.
def foo(proc: int | Process):
    proc = Process(proc)
```
