### ISSUE TITLE
cpu_percent return 0.0 for single process, but it was okay for system-wild CPU utilization

### ISSUE THREAD

**Issue by mozz85** [giampaolo/psutil#2278]
## Summary

psutil 5.9.2
windows

## Description

here is the test code
```
import subprocess
import psutil
import time

os_process = subprocess.Popen('notepad', stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
psutil_process = psutil.Process(os_process.pid)
time.sleep(1)
print(psutil_process.cpu_percent(interval=None))
time.sleep(1)
print(psutil_process.cpu_percent(interval=None))
time.sleep(1)
print(psutil_process.cpu_percent(interval=None))
time.sleep(1)
print(psutil_process.cpu_percent(interval=None))
```
here is the output
![image](https://github.com/giampaolo/psutil/assets/59696028/a1f6c5ec-addc-469a-9f84-681c7c7cc31c)
 if the image load failed
0.0
0.0
0.0
0.0

**Comment by mozz85** [comment]
i also tried for the current process. and i can get the vaild value by this way
```
time.sleep(1)
print(psutil.cpu_percent(interval=None))
time.sleep(1)
print(psutil.cpu_percent(interval=None))
time.sleep(1)
print(psutil.cpu_percent(interval=None))
time.sleep(1)
print(psutil.cpu_percent(interval=None))
```
output goes like
4.7
2.5
5.5
3.6

but if i do this, i failed
```
p = psutil.Process()
time.sleep(1)
print(p.cpu_percent(interval=None))
time.sleep(1)
print(p.cpu_percent(interval=None))
time.sleep(1)
print(p.cpu_percent(interval=None))
time.sleep(1)
print(p.cpu_percent(interval=None))
```
output goes like
0.0
0.0
0.0
0.0

**Comment by mozz85** [comment]
![image](https://github.com/giampaolo/psutil/assets/59696028/8e7f0f3e-f29a-44f6-9cea-55cd4201aafd)
don't know why i couldn't upload the pic before

**Comment by mozz85** [comment]
![image](https://github.com/giampaolo/psutil/assets/59696028/ff2cc1e0-8ba5-4d0a-86c9-153e429fd192)
![image](https://github.com/giampaolo/psutil/assets/59696028/ede18341-633e-4c01-b072-85e9005810f2)

**Comment by giampaolo** [comment]
I guess it's because the process does basically nothing.

**Comment by mozz85** [comment]
You are right. Althought the process that i want to check out did something, when i print out the os_process.pid, i found out that's not it. The code that i copied from chatgpt set the shell=True when calling the Popen. and i know nothing about it.  That opens a shell, and that shell opens the intended process.
