### ISSUE TITLE
[Win] "\" as line ending character in __init__.py throws an syntax error

### ISSUE THREAD

**Issue by jho101** [giampaolo/psutil#2328]
## Summary

* OS: Windows 10
* Architecture: 64bit 
* Psutil version: 5.9.6
* Python version: 3.9
* Type: installation 

## Description

We are synchronizing our python packages with the version control tool Perforce. In Perforce the user can decide between several line ending styles like (local, system, shared(UNIX and local).
So the result of it is that the whitespaces in the files are different depending on what line ending style we are using.

The problem here is that every time a "\\" is used, script fails. I have attached the correspond file with the not working line endings. If you ressolve the "\\" it should work:

[__init__.py.txt](https://github.com/giampaolo/psutil/files/13294996/__init__.py.txt)

**Comment by giampaolo** [comment]
I'm not sure what you're trying to say here. psutil uses UNIX line endings (\n) in all files (.py, .rst, etc.).

**Comment by jho101** [comment]
Hi,
thanks for the quick reply. I wanted to say that if someone changes the line endings to a non Unix style, when psutil is not working anymore because of using the "\\" to forwarding the code line to the next line. I think my initial description is misleading. I have added another images.
E.g.: If I remove the "\\" from the fun variable, when it is working.

![image](https://github.com/giampaolo/psutil/assets/16503256/cbe41bbe-5e80-444a-94a0-6f494174af3f)

![image](https://github.com/giampaolo/psutil/assets/16503256/a206bacc-f17b-4700-8e88-7025f7b3a4a8)

**Comment by giampaolo** [comment]
A problem with your editor perhaps? I'm not sure. Anyway, if you want to modify psutil source code I recommend configuring your editor to use the UNIX style. You don't want to mix \n and \r\n anyway. Just stick to one (\n).
