### ISSUE TITLE
[Linux] Failing to compile latest version on on lder compiler

### ISSUE THREAD

**Issue by arossert** [giampaolo/psutil#2345]
## Summary

* OS: Ubuntu
* Architecture: 64bit
* Psutil version: 5.9.7
* Python version: 3.8.10
* Type: Installation

## Description
Trying to build the latest version on an older compiler fails on this error
```
      psutil/_psutil_linux.c: In function 'PyInit__psutil_linux':
      psutil/_psutil_linux.c:79:56: error: 'DUPLEX_UNKNOWN' undeclared (first use in this function)
           if (PyModule_AddIntConstant(mod, "DUPLEX_UNKNOWN", DUPLEX_UNKNOWN)) INITERR;
                                                              ^
      psutil/_psutil_linux.c:79:56: note: each undeclared identifier is reported only once for each function it appears in
      psutil could not be installed from sources. Perhaps Python header files are not installed. Try running:
        sudo apt-get install gcc python3-dev
      error: command '/usr/bin/gcc' failed with exit code 1
```

Looking at the diff it seems that this [commit](https://github.com/giampaolo/psutil/commit/a7205fc9d77b13a161da1502bd0988db8b9b5971) removed the needed DUPLEX_UNKNOWN in `psutil/_psutil_linux.c`
```
#ifndef DUPLEX_UNKNOWN
    #define DUPLEX_UNKNOWN 0xff
#endif
```

Found an older ticket on the same issue https://github.com/giampaolo/psutil/issues/2156

**Comment by arossert** [comment]
Created a PR for this issue https://github.com/giampaolo/psutil/pull/2346

**Comment by giampaolo** [comment]
Thank you. Merged.

**Comment by arossert** [comment]
Thanks, any estimation on new release?
