### ISSUE TITLE
[Enhancement] Refactoring of test

### ISSUE THREAD

**Issue by antoninoLorenzo** [giampaolo/psutil#2377]
I am using `psutil` for a personal project for which I need to compile a Python script; during the compilation process I get prompted a warning that there are tests inside the code of `psutil`, for this reason, I propose to refactor `psutil/tests` out of `psutil` folder.

However, if there are any specific reasons to have tests inside of the `psutil` folder I specify that this isn't a problem but an enhancement.
PS: I am using Nuitka for compilation.

**Comment by giampaolo** [comment]
The reason why psutil tests are under psutil/tests is because you can test psutil installation with "python3 -m psutil.tests". Basically they are installed along side psutil on purpose.
