### ISSUE TITLE
[Linux] Distribute linux wheels for python versions > 3.6 on x86 and arm64

### ISSUE THREAD

**Issue by kapilt** [giampaolo/psutil#2389]
Per latest pypi release
https://pypi.org/project/psutil/#files

psutil is not distributing wheels for any linux version of python other than 3.6 and 2.7 which are ancient and way past end of life.

Instead it should target wheel building for modern versions ideally across x86 and aarch64.

**Comment by giampaolo** [comment]
This is incorrect. These 2 files support any Python versions from 3.6 onward:
![image](https://github.com/giampaolo/psutil/assets/681260/2b1e900e-a671-4cb6-8572-44806b2fcb7a)

**Comment by giampaolo** [comment]
This is incorrect. These 2 files support any Python versions from 3.6 onward:
![image](https://github.com/giampaolo/psutil/assets/681260/f6e8d39e-b885-4958-9763-97f87667b712)
