### ISSUE TITLE
[Linux] cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import)

### ISSUE THREAD

**Issue by mattthhh** [giampaolo/psutil#2419]
## Summary

* OS: RedHat8
* Architecture: 64bit
* Psutil version: 5.9.8 (cloned today)
* Python version: python3.11 
* Type: import locally

## Description

Hi, when I try to import the the lib that I cloned to `modules/libs/` with these lines :
```python
sys.path.insert(0, "modules/libs/")
import psutil
```

I got this error :
`ImportError: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import)`

Any ideas ? (I don't want to use pip or venv to get the library, because it needs to be flexible)

**Comment by giampaolo** [comment]
psutil needs to be compiled, so you can't get away with `sys.path.insert`.

**Comment by mattthhh** [comment]
Okay, do you have any ideas to import this lib without pip and venv and compile it from the source code ?

**Comment by mattthhh** [comment]
Okay I found, just compile it locally with a simple python interpreter, and add the result of the compilation in `sys.path`
