### ISSUE TITLE
[Windows] win_service_get by PID and not by name

### ISSUE THREAD

**Issue by arossert** [giampaolo/psutil#2423]
## Summary

* OS: Windows
* Type: new-api

## Description
I have a use case where I have a PID and I want to know what service it is, the process name for this PID is `svchost.exe` but I want to get the service name.

The only option that I have now is to iterate the full list using `win_service_iter()` and look for the service with this PID, can you add a new function that will retrieve the service by the PID?

**Comment by giampaolo** [comment]
Mmm I don't think it's worth it. Services are inherently bound to a `name`. Such a function would basically be a one-liner which you can easily implement in your own code. 

Each new API you add makes the project and doc bigger / more complex, thus it has a cost. As such it makes sense to only add utility functions which solve a either complex or very common problem (like `process_iter()`).

**Comment by giampaolo** [comment]
I doubt it exists because the Windows API which returns a service handler accepts the service name (aka a string):
https://github.com/giampaolo/psutil/blob/89b6096f2a026ec85f2a188920877371d4515b60/psutil/arch/windows/services.c#L30
