### ISSUE TITLE
[Windows] error

### ISSUE THREAD

**Issue by CraftolokCode2024** [giampaolo/psutil#2432]
## Summary

* OS: { Windows 11 }
* Architecture: { 64bit, }
* Psutil version: { pip3 show psutil }
* Python version: { python3 -latest }
* Type: { core, doc, performance, scripts, tests, wheels, new-api, installation }

## Description

{{{
  Requirement already satisfied: psutil in c:\users\levi\appdata\local\programs\python\python312\lib\site-packages (6.0.0)
but....

--------------------------------------------------------
Temperature Info Error: module 'psutil' has no attribute 'sensors_temperatures'
Fan Speed Info Error: module 'psutil' has no attribute 'sensors_fans'

-------------------------------------------------------
}}}

**Comment by giampaolo** [comment]
Both APIs are not available on Windows.

**Comment by gvanem** [comment]
> Temperature Info Error: module 'psutil' has no attribute 'sensors_temperatures'

I have done a private patch to make this work. Needs the [CoreTemp](https://www.alcpu.com/CoreTemp/) program.
With this, running `scripts/temperatures.py`, shows:
```
coretemp
    Core 0               56 °C (high = 95 °C, critical = %95 °C)
    Core 1               56 °C (high = 95 °C, critical = %95 °C)
    Core 2               56 °C (high = 95 °C, critical = %95 °C)
    Core 3               56 °C (high = 95 °C, critical = %95 °C)
    Core 4               56 °C (high = 95 °C, critical = %95 °C)
    Core 5               56 °C (high = 95 °C, critical = %95 °C)
    Core 6               56 °C (high = 95 °C, critical = %95 °C)
    Core 7               56 °C (high = 95 °C, critical = %95 °C)
    Core 8               56 °C (high = 95 °C, critical = %95 °C)
    Core 9               56 °C (high = 95 °C, critical = %95 °C)
    Core 10              56 °C (high = 95 °C, critical = %95 °C)
    Core 11              56 °C (high = 95 °C, critical = %95 °C)
```

I tried to commit this patch before, w/o any response. So I'm not keen to do it again.
