### ISSUE TITLE
[ Windows-11] Add Option to do .net_io_counters on a Process object

### ISSUE THREAD

**Issue by GHERMAN99** [giampaolo/psutil#2464]
## Summary

* OS: {Windows-11}
* Type: { core }

## Description

  Add Option to do .net_io_counters on a Process object

```
import psutil
p = psutil.Process(psutil.pids()[0])
p.net_io_counters()
```

**Comment by giampaolo** [comment]
This was discussed in the past, but long story short is that there was no operating system offering this functionality.
