### ISSUE TITLE
/asset/python/psutil/tests/test_system.py:518: SyntaxWarning: "is not" with 'float' literal. Did you mean "!="?

### ISSUE THREAD

**Issue by jrobbins-LiveData** [giampaolo/psutil#2468]
https://github.com/giampaolo/psutil/blob/fb68f9fae3b398899d87161746884ebb2a2613c0/psutil/tests/test_system.py#L518 raises a SyntaxWarning in Python 3.12.

**Comment by mtelka** [comment]
It raises the warning even with Python 3.9.

**Comment by giampaolo** [comment]
Fixed, thanks.
