### ISSUE TITLE
(chore) macOS 12 build fails due to deprecation

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#2478]
See:
https://github.com/giampaolo/psutil/actions/runs/12397041381/job/34607795665

Quote:

> The macOS-12 environment is deprecated, consider switching to macOS-13, macOS-14 (macos-latest) or macOS-15. For more details, see https://github.com/actions/runner-images/issues/10721

@mayeut would you mind to take a look?

**Comment by mayeut** [comment]
https://github.com/giampaolo/psutil/pull/2479 should fix this.

**Comment by giampaolo** [comment]
Thank you!
