### ISSUE TITLE
Add network interface speed information

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#250]
_From [nicolash...@gmail.com](https://code.google.com/u/115069581463621203225/) on January 30, 2012 15:14:15_
    
    Proposal: add the network interface spped (100 Mbps, 1000 Mbps...) in the 
    structure returned by the psutil.network_io_counters(True) function 
    
        # python
        # import statgrab
        # statgrab.sg_get_network_iface_stats()
        [{'duplex': 2, 'interface_name': 'lo', 'speed': 0, 'up': 1}, {'duplex': 0, 
    'interface_name': 'eth0', 'speed': 100, 'up': 1}, {'duplex': 2, 
    'interface_name': 'wlan0', 'speed': 0, 'up': 1}, {'duplex': 2, 
    'interface_name': 'virbr0', 'speed': 0, 'up': 1}] 
    
    Please provide any additional information below.  
    -
    
_Original issue: http://code.google.com/p/psutil/issues/detail?id=250_

**Comment by giampaolo** [comment]
Merged into master as of PR #592.

**Comment by tevaum** [comment]
Thanks! :]
