### ISSUE TITLE
Support GNU/Hurd

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#276]
_From [sandro.tosi](https://code.google.com/u/sandro.tosi/) on June 08, 2012 00:06:35_

```
Hello,
i'm reporting here the Debian bug: http://bugs.debian.org/676450 >>>
Currently python-psutil fails to build on Debian GNU/Hurd. (Doesn't recognize 
gnu system).

Attached is a patch for building on Hurd.
<<<

Cheers,
Sandro
```

**Attachment:** [pypsutil-hurd.diff](http://code.google.com/p/psutil/issues/detail?id=276)

_Original issue: http://code.google.com/p/psutil/issues/detail?id=276_

**Comment by giampaolo** [comment]
Closing out as outdated.

**Comment by sandrotosi** [comment]
hey @giampaolo this still happens with 5.4.1:

https://buildd.debian.org/status/fetch.php?pkg=python-psutil&arch=hurd-i386&ver=5.4.1-1&stamp=1511665962&raw=0
```
for python in python2.7 python3.6; do \
	$python setup.py build; \
	$python-dbg setup.py build; \
done
platform gnu0 is not supported
/<<PKGBUILDDIR>>/debian/rules:10: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
/<<PKGBUILDDIR>>/debian/rules:7: recipe for target 'build-arch' failed
make: *** [build-arch] Error 2
dpkg-buildpackage: error: debian/rules build-arch subprocess returned exit status 2
```

should this issue be re-opened?

**Comment by sthibaul** [comment]
Well, yes this is still happening :) and blocking the availability of a hundred packages in Debian.
Hurd's /proc implementation is mostly following Linux' shape, so probably much of the Linux code can be just called as such.

**Comment by giampaolo** [comment]
What happens if you fix setup.py and run tests?
