### ISSUE TITLE
Support getting information of remote host

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#336]
_From [sebasma...@gmail.com](https://code.google.com/u/106015684066365608417/) on October 09, 2012 13:57:50_

```
It would be neat to be able to monitor a remote process with psutil. Several 
utilities already do this on windows, I guess by using RPC.

On UNIX, one could thing on using SSH to do this. I don't know if there are 
other options.

Regards.
```

_Original issue: http://code.google.com/p/psutil/issues/detail?id=336_

**Comment by fruch** [comment]
I think this one actually doable 
it's proven that RpyC can be use to connect the remote machine
http://stackoverflow.com/questions/10036981/python-rpyc-can-not-run-a-psutil-command-remotely

and zero deploy can be used:
http://rpyc.readthedocs.org/en/latest/docs/zerodeploy.html#zerodeploy

the only requirement is for psutil to be installed on the remote machine.

(and useful in lots of cases, my case is an embedded system which it's filesystem is read-only, and installing a package on the other end might take a while to get right )

**Comment by weswam** [comment]
Why would it ever make sense to bake this into psutil? If you need this functionality then write it into your application layer.

**Comment by fruch** [comment]
Sounded like a common enough case.
I.e. monitoring a remote machine.

But you are right, that can be built into its own package, that depends on
psutil.

**Comment by weswam** [comment]
I can understand there being potential use cases for this type of functionality. I just agree with @giampaolo that this makes no sense to be built into psutil. psutil is not intended to be a full stack monitoring solution. It is an amazingly awesome library that gives your application logic access to all the monitoring metrics. If someone needs to use the data from psutil remotely then its fairly basic stuff to write a layer in the application to handle this using existing communication protocols, RPC is an option but for remote systems with low power and low bandwidth availability something like MQTT, ZeroMQ, or even Websockets would work as well.

**Comment by giampaolo** [comment]
Exactly: it just doesn't make sense to add any level of complexity in that sense, mainly because there's not a "blessed" protocol which can be chosen (SSH? HTTP? Whatever...?), and any solution you can think of will never be generic enough to satisfy all the possible use cases. All the types returned by psutil functions and methods are standard python types (int, list, dict, str, set, nameduple) which can be easily serialized (e.g. via JSON), transmitted over a certain protocol (e.g. HTTP) and recomposed on the remote endpoint in order to recreate the original Python type(s) and deal with them. How to transmit and handle that stream of data/information is entirely up to the user, not the library per se. To say one, Process.as_dict() was explicitly designed to be used in such a case (#282 and #408 comes to mind). In summary this is one of those cases where the KISS (keep it simple stupid) principle applies. =)

**Comment by mrjefftang** [comment]
Microsoft already builds this functionality into WMI.  There's a WMI library for Python.

I would recommend whoever needs this to actually build a remote monitoring solution using such.

**Comment by fruch** [comment]
And what about poor us, which actually work with Linux ecosystems ?,  but
anyhow I've got it, remote monitoring a feature not for psutil.

**Comment by giampaolo** [comment]
On Linux it's a lot easier than on Windows which sucks for these kind of things. To say one, you can simply use SSH to send commands to the remote host which will have a python script which collects some metrics via psutil, serialize them by using JSON and print the serialized string to stdout. The stdout will be piped through, returned back to you, you deserialize it and you're done.
For example, something like this will print the content of remote /tmp directory:

    ssh -o "StrictHostKeyChecking no" user@192.168.1.7 "ls /tmp"

Replace "ls /tmp" with "python /path/to/your/script.py" and you're done.
If you don't want to type the password every time simply use authentication based on SSH keys.
Reimplementing something like this (SSH) which provides transport, authentication, encryption and a tons of other things into psutil is out of question: it's a totally different project.
Let's have the SSH guys take care of those things and psutil take care of its things. =)

**Comment by birbalsain** [comment]
Alternate way is  ssh hostname "ps command" . means use the ps command with ssh hostname.
