### ISSUE TITLE
get_open_files might hang forever

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#340]
_From [amo...@google.com](https://code.google.com/u/101252647480125095856/) on November 24, 2012 15:39:51_
    
    What steps will reproduce the problem?  
    
    
    1. Create a process_iter()
    2. Call get_open_files on each of the processes 
    
    
    
    What is the expected output?  
    The list of open files for each process. 
    
    
    
    What do you see instead?  
    The program hangs forever.
    
    This has already been encountered, there are some exception in the code for 
    exactly this problem. I have found on more access mask where the problem arises 
    - please add it to the list of exceptions. Patch is attached.
    
**Attachment:** [patch](http://code.google.com/p/psutil/issues/detail?id=340)
    
_Original issue: http://code.google.com/p/psutil/issues/detail?id=340_

**Comment by giampaolo** [comment]
This is now supposed to be fixed by PR #597 which spawns a thread.

**Comment by daveajones** [comment]
thanks @giampaolo @mrjefftang .  much appreciated.

**Comment by giampaolo** [comment]
From [original comment](https://github.com/giampaolo/psutil/issues/340#issuecomment-59365752):

> This blog post (http://0memory.blogspot.com/2008/08/getfinalpathnamebyhandle-api-hungs.html) suggests using GetFileInformationByHandleEx (http://msdn.microsoft.com/en-us/library/aa364953(VS.85).aspx) which is introduced in WIndows Vista+

...here's an archived copy in case that blog disappears:
https://web.archive.org/web/20201023075814/https://0memory.blogspot.com/2008/08/getfinalpathnamebyhandle-api-hungs.html

**Comment by PolarGoose** [comment]
> From [original comment](https://github.com/giampaolo/psutil/issues/340#issuecomment-59365752):
> 
> > This blog post (http://0memory.blogspot.com/2008/08/getfinalpathnamebyhandle-api-hungs.html) suggests using GetFileInformationByHandleEx (http://msdn.microsoft.com/en-us/library/aa364953(VS.85).aspx) which is introduced in WIndows Vista+
> 
> ...here's an archived copy in case that blog disappears: https://web.archive.org/web/20201023075814/https://0memory.blogspot.com/2008/08/getfinalpathnamebyhandle-api-hungs.html

I have tried [GetFileInformationByHandleEx](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getfileinformationbyhandleex):
* It hangs the same way `NtQueryObject(ObjectNameInformation)` does.
* The information in the blog post you mentioned is incorrect. `GetFileInformationByHandleEx` doesn't use a driver. It uses `NtQueryObject` under the hood, like `GetFileInformationByHandle`.
* The file name it returns doesn't contain a drive name: `\Windows\System32\en-US\mswsock.dll.mui`
