### ISSUE TITLE
Import of psutil errors with "import _psutil_mswindows .. DLL load failed"

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#348]
_From [Drydercs...@gmail.com](https://code.google.com/u/110073261854132591011/) on January 02, 2013 02:56:28_

```
What steps will reproduce the problem?  
1. Install python-3.3.0 and psutil 0.6.1.win32 on windows-XP, 32bit
2. start python cli
3. import psutil 

What is the expected output?  
succesful import of psutil 

What do you see instead?  
>python
Python 3.3.0 (v3.3.0:bd8afb90ebf2, Sep 29 2012, 10:55:48) [MSC v.1600 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python33\lib\site-packages\psutil\__init__.py", line 76, in <module>
    import psutil._psmswindows as _psplatform
  File "c:\Python33\lib\site-packages\psutil\_psmswindows.py", line 16, in <modu
le>
    import _psutil_mswindows
ImportError: DLL load failed: The specified procedure could not be found.
>>> 

What version of psutil are you using? What Python version?  
psutil 0.6.1
python 3.3 

On what operating system? Is it 32bit or 64bit version?  
Windows XP, 32bit, SP-3 

Please provide any additional information below.  
I have installed same python 3.3 and psutil 0.6.1 on a windows 7 systems and it works.
```

_Original issue: http://code.google.com/p/psutil/issues/detail?id=348_

**Comment by pac2000** [comment]
Sorry to bring this up ... yet again
but this is working on win 2003 ... also tried python 3.4 ... no joy
any chance that this is an easy fix ??? sigh
(and no, I cant compile patches)

windows server 2003 R2
enterprise x64 - SP2

psutil  4.1.0
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
========= RESTART: Z:\common\scheduled tasks\kill stuff\kill_this.py =========

Traceback (most recent call last):
  File "Z:\common\scheduled tasks\kill stuff\kill_this.py", line 1, in <module>
    import psutil
  File "C:\Python27\lib\site-packages\psutil\__init__.py", line 124, in <module>
    from . import _pswindows as _psplatform
  File "C:\Python27\lib\site-packages\psutil\_pswindows.py", line 14, in <module>
    from . import _psutil_windows as cext
ImportError: DLL load failed: The specified procedure could not be found.
>>>

**Comment by bitranox** [comment]
same here - can not load psutil 4.1.0 on Windows XP, SP3, Python 3.4.3 : 

Microsoft Windows XP [Version 5.1.2600]
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32
>>> import psutil
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\psutil\__init__.py", line 124, in <module>

    from . import _pswindows as _psplatform
  File "C:\Python34\lib\site-packages\psutil\_pswindows.py", line 14, in <module>
    from . import _psutil_windows as cext
ImportError: DLL load failed: The specified procedure could not be found.
>>>

And I can not update that particular machine, because it is a gateway for an ancient database.
Please Help !

**Comment by maatthc** [comment]
Guys,
I was having the same issue with a Windows 2003 Server and I solved it temporarily downgrading the PsUtil version to 2.2.0 - it is now running with Python 3.4 . 
The file I used to install it can be found here: https://pypi.python.org/simple/psutil/

Cheers,
Alexandre

**Comment by giampaolo** [comment]
Duplicate of #810
