### ISSUE TITLE
disk_io_counters fail to find physical disk on Windows

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#351]
_From [m.maly...@gmail.com](https://code.google.com/u/105683034376530868826/) on February 13, 2013 17:25:14_

```
What steps will reproduce the problem?  
1. import psutil
2. psutil.disk_io_counters(perdisk=True) 

What is the expected output?  
{'PhysicalDrive0': iostat(read_count=122927, write_count=200599, 
read_bytes=2346739200L, write_bytes=1753369088L, read_time=28560720L, 
write_time=9023350L)} 

What do you see instead?  
Traceback (most recent call last):
  File "<pyshell#19>", line 1, in <module>
    psutil.disk_io_counters()
  File "C:\TestEnv\Python26\lib\site-packages\psutil\__init__.py", line 1041, 
in disk_io_counters
    raise RuntimeError("couldn't find any physical disk")
RuntimeError: couldn't find any physical disk 

What version of psutil are you using? What Python version?  
psutil 0.6.1
Python 2.6.6 

On what operating system? Is it 32bit or 64bit version?  
Windows Server 2008 32-bit 

Please provide any additional information below.  
I have run some additional commands:
>>> psutil.disk_partitions()
[partition(device='C:\\', mountpoint='C:\\', fstype='NTFS', opts='rw,fixed'), 
partition(device='D:\\', mountpoint='D:\\', fstype='', opts='cdrom')]
>>> psutil.disk_usage('c:\\')
usage(total=146774487040L, used=93277802496L, free=53496684544L, 
percent=63.600000000000001)
>>> psutil._psmswindows.disk_io_counters()
{}

I also checked WinObj from sysinternals suite. It shows PhysicalDrive0 being 
symbolic link to \Device\Harddisk0\DR0, which exists and has type Device. 

I have similar machine hardware-wise, but with 64-bit Windows Server and 
additional iSCSI disk. On this machine psutil works without any issue.
```

_Original issue: http://code.google.com/p/psutil/issues/detail?id=351_

**Comment by LeoCavaille** [comment]
Hey @giampaolo  I am experiencing this issue with win server 2012 R2 64 bits, python 2.7.8, psutil 2.2.1.
Can we reopen this issue ?

```
  File "psutil\__init__.pyc", line 1726, in disk_io_counters
RuntimeError: couldn't find any physical disk
```

I'll try to get the bottom of it but you might have ideas?
Thanks

**Comment by giampaolo** [comment]
Not at the moment no, I'll have to investigate the original issue and code changes. Reopening for now.

**Comment by giampaolo** [comment]
@LeoCavaille not sure if you're still into it but the issue is old so I wonder whether it still exists. Care to try?

**Comment by goofballtech** [comment]
Been working on getting influxDB working and just realized i am getting these as well on Windows Server 2016. Managed to stumble on your thread here. if you still need a fix tested (assumption since issue is still open) i am will to give it a shot. 

Thanks. 

![capture](https://user-images.githubusercontent.com/8220165/35078499-2546eab0-fbc8-11e7-8aa7-58bc30865760.JPG)

**Comment by ofek** [comment]
@giampaolo Hi there!

Any progress on this? We're hitting the same issue https://ci.appveyor.com/project/Datadog/integrations-core/builds/19775520#L342

**Comment by ofek** [comment]
Sorry for the noise, `diskperf -y` actually does make AppVeyor work.

**Comment by giampaolo** [comment]
It is necessary to issue `diskperf -y` command in order to make `disk_io_counters()` work? If so I will add it to the doc.

**Comment by ofek** [comment]
I think that is correct yes, at least on some newer versions of Windows Server.

**Comment by giampaolo** [comment]
Closing out as fixed (`diskperf -y` was documented).
