### ISSUE TITLE
Several test failures with 0.7.0 on Debian amd64

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#369]
_From [sandro.tosi](https://code.google.com/u/sandro.tosi/) on April 13, 2013 19:27:11_
    
    Hello,
    while preparing 0.7.0 version for Debian, I'm seeing a lot of unittest 
    failures; I'm attaching the whole unittest running log, I'm executing 
    test_memory_leaks.py test_psutil.py on 2.6 2.7 and 3.2.
    
    Regards,
    Sandro
    
**Attachment:** [psutil_0.7.0_unittest_failures.txt](http://code.google.com/p/psutil/issues/detail?id=369)
    
_Original issue: http://code.google.com/p/psutil/issues/detail?id=369_

**Comment by sandrotosi** [comment]
Let's close this, I will open a new report for 4.1.2
