### ISSUE TITLE
Getting of peak rss memory on Linux

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#383]
_From [grds...@gmail.com](https://code.google.com/u/111531056625488550956/) on May 21, 2013 14:28:45_

```
Now get_ext_memory_info() on Windows returns peak working set but doesn't 
return peak rss on Linux.

It is possible to get peak rss on Linux reading VmHWM field from 
/proc/pid/status.
```

_Original issue: http://code.google.com/p/psutil/issues/detail?id=383_

**Comment by tijko** [comment]
On Linux systems this could be exposed under `/proc/$PID/status` under `VmHWM`.  Adding an extra field under `pmem` tuple and using a `re.compile` with `_read_status_file`.

**Comment by NotSqrt** [comment]
Or a separate method, something like this, in `_pslinux`:

```python
    @wrap_exceptions
    def peak_rss(self, _hwm_re=re.compile(br'VmHWM:\s+(\d+)\s+kB')):
        # Returns Peak resident set size in bytes
        data = self._read_status_file()
        val, = _hwm_re.findall(data)[0]
        return int(val) * 1024
```
