### ISSUE TITLE
Implement linux load average

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#384]
_From [skolpat...@gmail.com](https://code.google.com/u/107207551280828561988/) on May 22, 2013 22:56:57_

```
Proposal  
Implement linux load average in psutil 

On what platforms would this be available?  
Linux 

Proposed API  
Use getloadavg() perhaps? 

Are there existent implementations we can use as an example?  


Please provide any additional information below.  
If you guys think its feasible to present linux load average in psutil, I'd be 
interested in working on making this happen.
```

_Original issue: http://code.google.com/p/psutil/issues/detail?id=384_

**Comment by Smankusors** [comment]
hmm what if stdlib/libc doesn't have getloadavg? For example some libc on Android doesn't implement this.

You can easily reproduce this using Termux app (available on Google Play).

**Comment by giampaolo** [comment]
> what if stdlib/libc doesn't have getloadavg? 

In that case `psutil.getloadavg()` is not available. From source code:

```python
if hasattr(os, "getloadavg") or hasattr(_psplatform, "getloadavg"):
    # Perform this hasattr check once on import time to either use the
    # platform based code or proxy straight from the os module.
    if hasattr(os, "getloadavg"):
        getloadavg = os.getloadavg
    else:
        getloadavg = _psplatform.getloadavg

    __all__.append("getloadavg")
```

**Comment by Smankusors** [comment]
And yeah that's error I got... 😅

But there's some alternative without root, that you can get load average from `/system/bin/uptime` instead 🤔

**Comment by giampaolo** [comment]
> For example some libc on Android doesn't implement this.

Does psutil work on Android^

**Comment by Smankusors** [comment]
> > For example some libc on Android doesn't implement this.
> 
> Does psutil work on Android?

Hmm how to test it all? I just do `import psutil` and it's working, not throwing any exception. But when I need `getloadavg` and I got this :

```
AttributeError: module 'psutil' has no attribute 'getloadavg'
```

(This is expected from psutil code you mentioned before)

**Comment by giampaolo** [comment]
`python3 -m psutil.tests`

**Comment by Smankusors** [comment]
Ok I run it on my 2 devices (both non-root and root shell), but the errors seems incosistent across devices. Both of this two devices are custom ROM too.

[psutil_tab.txt](https://github.com/giampaolo/psutil/files/4893260/psutil_tab.txt)
[psutil_xsp.txt](https://github.com/giampaolo/psutil/files/4893261/psutil_xsp.txt)
[psutil_root_tab.txt](https://github.com/giampaolo/psutil/files/4893288/psutil_root_tab.txt)
[psutil_root_xsp.txt](https://github.com/giampaolo/psutil/files/4893289/psutil_root_xsp.txt)

**Comment by giampaolo** [comment]
Considering psutil was never developed on Android I'd say that's not bad at all.

**Comment by giampaolo** [comment]
Does androind have `/proc/loadavg`?

**Comment by Smankusors** [comment]
> Considering psutil was never developed on Android I'd say that's not bad at all.

it could be worse if it's on OEM/non-custom ROM 😉

> Does androind have `/proc/loadavg`?

It looks like android have? I don't know in non custom ROM because of SELinux being enforced 😅

But 2 of my devices which is custom ROM does have that `/proc/loadavg`

**Comment by Smankusors** [comment]
I could do PR for this though. But I will get the loadavg by getting output of `uptime` command. 🤔

**Comment by giampaolo** [comment]
`cat /proc/loadavg`, it's weird the file is there but glibc does not expose the syscall. Can you determine what glibc version is installed? Manual says 2.19 is required.

**Comment by Smankusors** [comment]
> `cat /proc/loadavg`, it's weird the file is there but glibc does not expose the syscall. Can you determine what glibc version is installed? Manual says 2.19 is required.

huh? no. Android doesn't use glibc, but Bionic. It's a different implementation, that's why sometimes there's libc function that's missing on Android. 😥

Even though you can read /proc/loadavg on Android, it still needs root access (or SELinux permissive/disabled). But using uptime works without root. 🤔

**Comment by giampaolo** [comment]
I don't think parsing uptime is worth it. I prefer to keep things simple. You can easily do it in your own code though.

**Comment by Smankusors** [comment]
that's fine. Thanks for the response 😉

hmm.... is there possibility that uptime have output variation/inconsistent output across devices and operating system? 🤔

**Comment by giampaolo** [comment]
I don't know. =)
