### ISSUE TITLE
there is a small integer overflow bug in _psutil_linux.c

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#455]
_From [amo...@google.com](https://code.google.com/u/101252647480125095856/) on December 10, 2013 11:05:31_
    
    What I get:
    
    In [2]: psutil.RLIM_INFINITY
    Out[2]: -1 
    
    
    
    What is the expected output?  
    
    
    In [2]: psutil.RLIM_INFINITY
    Out[2]: 18446744073709551615L 
    
    It's a simple integer overflow. The constant is an unsigned long, 
    PyModule_AddIntConstant accepts a signed one. I fixed it for me, patch is attached.
    
**Attachment:** [overflow.patch](http://code.google.com/p/psutil/issues/detail?id=455)
    
_Original issue: http://code.google.com/p/psutil/issues/detail?id=455_

**Comment by giampaolo** [comment]
It doesn't matter what the actual value of RLIM_INFINITY is as long as it remains the same (as it is the case). I don't think this should be fixed.

**Comment by grrrrrrrrr** [comment]
I wasn't really worried about the value of RLIM_INFINITY but my compiler complained about the overflow and would refuse to build. I tried to reproduce this now and I don't get that error anymore so I guess closing is ok...
