### ISSUE TITLE
incorrect per-process CPU usage reported [Windows]

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#474]
_From [francois...@gmail.com](https://code.google.com/u/116472837397792107220/) on February 11, 2014 00:42:48_

```
What steps will reproduce the problem?  
1.Create a psutil.Process object for an existing PID
2.Call get_cpu_percent() on the Process object
3.Value returned is capped at 100 

What is the expected output?  
The value returned fits the per-process CPU &#37; from Windows Performance 
monitor (perfmon.exe) "Process/&#37; Processor Time" counter, which is not 
capped at 100 (the max is 100 * NB_CORES) 

What do you see instead?  
It is capped at 100 

What version of psutil are you using? What Python version?  
psutil 1.2.1
python 2.7.6 

On what operating system? Is it 32bit or 64bit version?  
Windows 8 Enterprise, 64-bit 

Please provide any additional information below.  
I already saw bug 194 that has been closed where it is seen as an error to 
report values higher than 100 on Unix platforms. I would not have any 
particular issue with that on Windows either, as long as the reported values 
are scaled accurately, which they are not.

I am currently running performance tests on a multithreaded program of mine, 
and I was surprised to see that the values reported by your tool did not 
correspond at all to the values I read in the task manager. I then investigated 
the issue and found that they rather correspond to the values reported by the 
aforementioned counter in Performance monitor (procmon.exe). The problem is, as 
soon as the value raises above 100 (which happens frequently on a multicore 
system), they are clipped to 100, which gives wrong values. 

In its current state, I cannot use this library for the intent I planned for it.

Thank you for looking into this. I can help solve the bug if it is approved.
```

_Original issue: http://code.google.com/p/psutil/issues/detail?id=474_

**Comment by fx86** [comment]
How does one normalize the cpu percent consumed if it goes above 100% ?

**Comment by giampaolo** [comment]
What do you mean?

**Comment by fx86** [comment]
Meaning, should we divide the CPU % given with percpu=False by the number of cores OR should it be average of values given by percpu=True ?

**Comment by giampaolo** [comment]
From psutil doc: https://pythonhosted.org/psutil/#psutil.Process.cpu_percent

<<Note the returned value is explicitly not split evenly between all available CPUs (differently from psutil.cpu_percent()). This means that a busy loop process running on a system with 2 logical CPUs will be reported as having 100% CPU utilization instead of 50%. This was done in order to be consistent with top UNIX utility and also to make it easier to identify processes hogging CPU resources independently from the number of CPUs. It must be noted that taskmgr.exe on Windows does not behave like this (it would report 50% usage instead). To emulate Windows taskmgr.exe behavior you can do: p.cpu_percent() / psutil.cpu_count().>>

**Comment by fx86** [comment]
Thanks much!
Had missed that line.
