### ISSUE TITLE
Segfault with psutil.net_connections()

### ISSUE THREAD

**Issue by wowi42** [giampaolo/psutil#512]
Hi
I have a little segfault with psutil on FreeBSD 10 :
```
wowi@wowi.io:/root# uname -a
FreeBSD wowi.io 10.0-RELEASE-p3 FreeBSD 10.0-RELEASE-p3 #0: Tue May 13 18:31:10 UTC 2014     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
wowi@wowi.io:/root# python
Python 2.7.6 (default, May 15 2014, 18:58:42)
[GCC 4.2.1 Compatible FreeBSD Clang 3.3 (tags/RELEASE_33/final 183502)] on freebsd10
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.net_connections()
Segmentation fault (core dumped)
```
Python come directly from pkg, and psutil version is 2.1.1
Peace

**Comment by giampaolo** [comment]
Sorry for replying so late. I've never bumped into this issue. As such the only thing I can suggest is to try to debug the problem yourself and post here in case you collect some useful information.

**Comment by lucien2k** [comment]
I've run into the same problem myself with python2.7.9 on freebsd 10.

It threw these warnings while installing via pip:
Collecting psutil
  Using cached psutil-2.2.1.tar.gz
Installing collected packages: psutil
  Running setup.py install for psutil
    building '_psutil_bsd' extension
    cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -DPSUTIL_VERSION=221 -I/usr/local/include/python2.7 -c psutil/_psutil_bsd.c -o build/temp.freebsd-10.1-RELEASE-p5-amd64-2.7/psutil/_psutil_bsd.o
    psutil/_psutil_bsd.c:106:1: warning: control reaches end of non-void function [-Wreturn-type]
    }
    ^
    psutil/_psutil_bsd.c:1160:44: warning: field precision should have type 'int', but argument has type 'unsigned long' [-Wformat]
                        path, sizeof(path), "%.*s",
                                             ~~^~
    psutil/_psutil_bsd.c:2004:41: warning: field precision should have type 'int', but argument has type 'unsigned long' [-Wformat]
            snprintf(path, sizeof(path), "%.*s",
                                          ~~^~
    3 warnings generated.
    cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -DPSUTIL_VERSION=221 -I/usr/local/include/python2.7 -c psutil/_psutil_common.c -o build/temp.freebsd-10.1-RELEASE-p5-amd64-2.7/psutil/_psutil_common.o
    cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -DPSUTIL_VERSION=221 -I/usr/local/include/python2.7 -c psutil/arch/bsd/process_info.c -o build/temp.freebsd-10.1-RELEASE-p5-amd64-2.7/psutil/arch/bsd/process_info.o
    cc -shared -pthread -Wl,-rpath,/usr/lib:/usr/local/lib -Wl,-rpath=/usr/lib:/usr/local/lib -fstack-protector build/temp.freebsd-10.1-RELEASE-p5-amd64-2.7/psutil/_psutil_bsd.o build/temp.freebsd-10.1-RELEASE-p5-amd64-2.7/psutil/_psutil_common.o build/temp.freebsd-10.1-RELEASE-p5-amd64-2.7/psutil/arch/bsd/process_info.o -L/usr/local/lib -ldevstat -lpython2.7 -o build/lib.freebsd-10.1-RELEASE-p5-amd64-2.7/_psutil_bsd.so
    building '_psutil_posix' extension
    cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -I/usr/local/include/python2.7 -c psutil/_psutil_posix.c -o build/temp.freebsd-10.1-RELEASE-p5-amd64-2.7/psutil/_psutil_posix.o
    cc -shared -pthread -Wl,-rpath,/usr/lib:/usr/local/lib -Wl,-rpath=/usr/lib:/usr/local/lib -fstack-protector build/temp.freebsd-10.1-RELEASE-p5-amd64-2.7/psutil/_psutil_posix.o -L/usr/local/lib -lpython2.7 -o build/lib.freebsd-10.1-RELEASE-p5-amd64-2.7/_psutil_posix.so
Successfully installed psutil-2.2.1



Python 2.7.9 (default, Jan 28 2015, 05:37:45)
[GCC 4.2.1 Compatible FreeBSD Clang 3.3 (tags/RELEASE_33/final 183502)] on freebsd10
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.net_connections()
Segmentation fault (core dumped)

**Comment by lucien2k** [comment]
Ok I did some more testing this morning.

The good news seems to be that its fixed in the master version. I tried 2.2.1 from pip and from source and both had the same seg fault issue, but using the master version I was able to use it correctly.

Based on the history of commits to the bsd files (and from glancing at the code), I suspect its this one fix: https://github.com/giampaolo/psutil/commit/5feb9367551431c88165f9502d116ca98f6ca041

Thanks Giampaolo, and lets hope its fixed in 2.2.2!

**Comment by giampaolo** [comment]
Mmmm no, unfortunately I think it's unlikely that commit has anything to do with this.

**Comment by lucien2k** [comment]
Hmm, well the good news is it definitely seems better. I've played around quite a lot now and no more seg faults with the master version.

**Comment by giampaolo** [comment]
OK, I'm going to close this out then.

**Comment by giampaolo** [comment]
I've just bumped into this myself. Reopening.

**Comment by giampaolo** [comment]
OK I think I've fixed this in https://github.com/giampaolo/psutil/commit/f37b720f6fe27ae579acca9a8ca523b1492c320b
