### ISSUE TITLE
Error building psutil-2.1.3 from pip on MSYS2 python3

### ISSUE THREAD

**Issue by mappu** [giampaolo/psutil#543]
It seems like maybe some win32-specific `#define`'s don't play nice with MSYS2 environment?

Full error log from pip is at https://gist.github.com/mappu/d3b617487d2768a2987b , seems like the issue may be in `psutil/_psutil_windows.c`.

**Comment by giampaolo** [comment]
I'm going to close this out for now as it's not something which is top priority for me at the moment.
