### ISSUE TITLE
cmdline of cmd.exe is empty on windows

### ISSUE THREAD

**Issue by fyrestone** [giampaolo/psutil#549]
ProcessExplorer:
![image](https://cloud.githubusercontent.com/assets/6308809/5101008/cd835d74-6feb-11e4-9e39-3f53e1cb2bec.png)
psutil:
![img](https://cloud.githubusercontent.com/assets/6308809/5101081/bb75a0fa-6fec-11e4-853d-aa38bd1d90b2.png)
![image](https://cloud.githubusercontent.com/assets/6308809/5101114/5a56bc90-6fed-11e4-91df-cbe16ce92b40.png)

**Comment by giampaolo** [comment]
It looks like this was already tracked as of (very old) https://github.com/giampaolo/psutil/issues/56.

**Comment by giampaolo** [comment]
Note: this may have been fixed recently with the introduction of `Process.environ` as that part of the code has been rewritten. I would like to know what happens when 4.0.0 is out (unless you can compile psutil).

**Comment by giampaolo** [comment]
OK, I confirm it looks the old logic ignoring the error and returning an empty list is gone, see:
https://github.com/giampaolo/psutil/blob/d4a07172e41bcba258dcc1a4d1f6d7cf67a5400c/psutil/arch/windows/process_info.c#L703
Closing this out.
