### ISSUE TITLE
psutil.net_io_counters() return same value every time on some machines

### ISSUE THREAD

**Issue by EvinceMoi** [giampaolo/psutil#551]
It's weird that the same code `psutil.net_io_counters()` works on my dev machines(win7 x64) but doesn't work on some other machines that has the same OS as the title says.
I've done some investigation that the NIC on the failed system seems to be nothing abnormly, and it has about 20Mbps network io though one NIC. 
Is it something relates to runtime?

----
Python version: 3.4.2

**Comment by EvinceMoi** [comment]
Tried but couldn't work it out, failed to build psutil just like what you mentioned in [INSTALL.rst](https://github.com/giampaolo/psutil/blob/master/INSTALL.rst), using win7 64 bit, vs2013, python 3.4 64bit

**Comment by giampaolo** [comment]
If you give me your email I can send you a pre-compiled exe installer for Python 3.4 64 bit.

**Comment by EvinceMoi** [comment]
baneyue#gmail.com, just came back from Spring Festival and happy new year

**Comment by giampaolo** [comment]
New releases/installers were released in the meantime. I think this should have already been fixed by now. Closing.
