### ISSUE TITLE
Lots of file handles left open due to return before closing

### ISSUE THREAD

**Issue by sandrotosi** [giampaolo/psutil#556]
Hello,
as reported in Debian bug bugs.debian.org/772543 here are several file handles left opened due to the use of return before the handle closure; some have been fixed in https://github.com/giampaolo/psutil/commit/3760d9593524e553e9e012c6b63cd802e3b25a46 but several others are still around (even in that very same commit, the first hunk leave the fd opened.

for programs meant to keep running, leaving fd opened will hit linux limits, like the reported described

Regards,
Sandro

**Comment by giampaolo** [comment]
It will happen very soon. Closing this out for now.

**Comment by sandrotosi** [comment]
@giampaolo hi! dont know if you had a look at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=772543#27 but it seems there are more fd leaks to address?

**Comment by giampaolo** [comment]
Ciao Sandro. What is the method leaking file handles? Process.threads()? I can't see anything wrong with it. Note: I'm talking about the current latest repo version which is not released yet.

**Comment by sandrotosi** [comment]
the user attached a patch in the next message, this: https://bugs.debian.org/cgi-bin/bugreport.cgi?msg=32;filename=psutil-filehandle-leaks-more-fixes.patch;att=1;bug=772543 which he mention was under test (still with the version released in debian, 2.1.1) but not come back, but you might still want to give it a look

**Comment by giampaolo** [comment]
Why don't you guys just make a patch for psutil instead? What are the methods leaking fds?

**Comment by sandrotosi** [comment]
i'm not making any patch, i'm just passing by the information the reporter wrote on the bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=772543 maybe you can contact him (the email is in the bug report)?

**Comment by giampaolo** [comment]
OK, I took a look at the patch and guessed where the problem might be. https://github.com/giampaolo/psutil/commit/ad2624ae1679e884087f448df8c1aedbaf3d346d is the result of it: now every open() call uses the 'with' context manager. I suppose all the issues described in that bug report should be addressed now. Could you report back to them asking if they can try latest GIT version and see if the problem still occurs?

**Comment by giampaolo** [comment]
Fixed in 2.2.0. Closing.
