### ISSUE TITLE
NoSuchProcess to check if process is really dead

### ISSUE THREAD

**Issue by wojons** [giampaolo/psutil#559]
In the case that there is an error getting one of the elements of a process  from the /pid it returns the exception  nosuchprocess but the process is there. For example it cant read the /proc/<pid>/cwd or the nice value and a few other things. It also happens in psutil.Process(pid).as_dict() i think in this use case it should return the exception like permission denied or something and or fill in the value as None or False.

**Comment by giampaolo** [comment]
I'm going to close this as I believe it's a non-issue. Feel free to reopen it if you have further insights.
