### ISSUE TITLE
Support CPU affinity on FreeBSD

### ISSUE THREAD

**Issue by oberstet** [giampaolo/psutil#566]
It seems, [getting/setting CPU affinity](http://pythonhosted.org/psutil/#psutil.Process.cpu_affinity) is not supported on FreeBSD:

```
Python 2.7.8 (a980ebb26592ed26706cd33a4e05eb45b5d3ea09, Dec 13 2014, 07:55:06)
[PyPy 2.4.0 with GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)] on freebsd10
Type "help", "copyright", "credits" or "license" for more information.
>>>> import psutil
>>>> psutil.__version__
'2.1.3'
>>>> p = psutil.Process()
>>>> p.cpu_affinity()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Process' object has no attribute 'cpu_affinity'
>>>>
```

**Comment by giampaolo** [comment]
Implemented in https://github.com/giampaolo/psutil/commit/cd37f6425e2e15f87778ae18b7bc7774d114ad2f

**Comment by oberstet** [comment]
Fantastic! I've tested trunk: works as expected .. cool. We are using psutil in https://github.com/crossbario/crossbar .. and this feature is highly appreciated.

Test system: FreeBSD 10.1 amd64 PyPy 2.4

* Building spits out some minor warnings: https://gist.github.com/oberstet/de48b9a7effa4a0754ad
* API works: https://gist.github.com/oberstet/78971b18970c5b1d8744
* And finally, running a TCP echo server with and without affinity set actually shows it *does* work http://picpaste.com/pics/Clipboard01-sgocv9h8.1420126580.png

Thank you very much! Ah, and happy new year;)

**Comment by giampaolo** [comment]
Glad you appreciated it and crossbar.io looks like a very interesting project.
I fixed some (not all) warnings in https://github.com/giampaolo/psutil/commit/842e4fb5afecd9458eb40a4d0be54a2d9358f054.
Happy new year to you too. =)

**Comment by oberstet** [comment]
Warnings .. thx! Nearly gone now .. here, just for the record:

```
cc -O2 -fPIC -Wimplicit -I/usr/local/include -O3 -march=native -I/home/oberstet/pypy1/include -c psutil/_psutil_bsd.c -o build/temp.freebsd-10.1-RELEASE-amd64-2.7/psutil/_psutil_bsd.o
psutil/_psutil_bsd.c:106:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
psutil/_psutil_bsd.c:1160:44: warning: field precision should have type 'int', but argument has type 'unsigned long' [-Wformat]
                    path, sizeof(path), "%.*s",
                                         ~~^~
psutil/_psutil_bsd.c:2004:41: warning: field precision should have type 'int', but argument has type 'unsigned long' [-Wformat]
        snprintf(path, sizeof(path), "%.*s",
                                      ~~^~
3 warnings generated.
```
