### ISSUE TITLE
ValueError: ambiguos inode with multiple PIDs references

### ISSUE THREAD

**Issue by bbinet** [giampaolo/psutil#572]
I get the following exception when I use the `psutil.net_connections(kind='tcp')` method:
```
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python2.7/dist-packages/rsm/server.py", line 84, in check
    db[uuid].update(netstat(db[uuid]['port']))
  File "/usr/local/lib/python2.7/dist-packages/rsm/server.py", line 37, in netstat
    for c in psutil.net_connections(kind='tcp'):
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 1816, in net_connections
    return _psplatform.net_connections(kind)
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 530, in net_connections
    return _connections.retrieve(kind)
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 514, in retrieve
    for fd, family, type_, laddr, raddr, status, bound_pid in ls:
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 453, in process_inet
    raise ValueError("ambiguos inode with multiple "
ValueError: ambiguos inode with multiple PIDs references
```

I've found that the #497 issue is similar, but I'm using psutil latest 2.2.0 version which should not be affected.
Anyway, #497 patch prevent to throw the exception when family is `socket.AF_UNIX` but in my case family is `socket.AF_INET`, so the exception is raised. My question is why do you consider having multiple references to the same inode is abnormal?

If this is actually abnormal I don't know why I reach this point... May be this is due to my code living in a docker container? I don't know. Any other idea?

**Comment by bbinet** [comment]
do you think it would be safe to just remove these offending lines: https://github.com/giampaolo/psutil/blob/master/psutil/_pslinux.py#L449-454

**Comment by bbinet** [comment]
note that when I manually comment out these lines https://github.com/giampaolo/psutil/blob/master/psutil/_pslinux.py#L449-454 it fixes my issue and everything then work as expected for me.

**Comment by giampaolo** [comment]
What if you comment out those lines then run tests?

**Comment by bbinet** [comment]
It looks like tests still pass: https://travis-ci.org/giampaolo/psutil/builds/46975016

**Comment by bbinet** [comment]
@giampaolo do you think #575 could be merged?

**Comment by giampaolo** [comment]
Hey, sorry for the delay but I've been busy. Yes, I think it should be merged. I'd only ask to comment everything out (as opposed to remove those lines) then we can merge it.

**Comment by bbinet** [comment]
Ok, I've just updated the pull request as requested.

**Comment by bbinet** [comment]
Do you think you can now merge #575 so that the fix will be included in the next release?
By the way, when do you think you will release v2.2.1?

**Comment by giampaolo** [comment]
2.2.1 is out

**Comment by bbinet** [comment]
Thanks!
