### ISSUE TITLE
drop mingw32 support on Windows

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#591]
Not sure in which release exactly but mingw32 support has been broken for a while now, to the point that I'm not sure if I'll manage to fix it because it's too messy. Plus, I'd really like to get rid of the tons of shitty workarounds all over the place, https://github.com/giampaolo/psutil/blob/08d490d0d8fa60ee1d689cca30738ceb599298d0/psutil/arch/windows/ntextapi.h above all.

**Comment by techtonik** [comment]
Do  you want to get rid of C compilation step.

**Comment by giampaolo** [comment]
What do you mean?

**Comment by techtonik** [comment]
Use ctypes of CFFI to access core API and implement necessary logic in Python.

**Comment by giampaolo** [comment]
I don't think it's a good idea:
 - converting all the C extensions to ctypes is huge work 
- C extension code is huge and mature (years old); translating it to ctypes means introducing instability; it basically means losing years of bug fixes
- CFFI is a third party dep which would be required; psutil as it stands right now does not require any dep except a C compiler; the only advantage I see is that with your proposal we would get rid of the C compiler dependency but the cost is too high
- psutil has been proposed for inclusion into stdlib: stdlib is known for avoiding ctypes and third-party deps

**Comment by giampaolo** [comment]
I guess all mingw related hacks have been removed by now. Closing this out.
