### ISSUE TITLE
open_files() on BSD reports null paths

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#595]
```
======================================================================
FAIL: test_open_files (__main__.TestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_psutil.py", line 1656, in test_open_files
    self.assertIn(TESTFN, filenames)
AssertionError: '/usr/home/user/psutil/$testfile' not found in ['/usr/local/bin/python2.7', '']

======================================================================
FAIL: test_open_files2 (__main__.TestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_psutil.py", line 1684, in test_open_files2
    self.assertEqual(path, fileobj.name)
AssertionError: '' != '/usr/home/user/psutil/$testfile'
```

This comes straight from kinfo_getfile(). The open file is there (you can tell from the fd) but the path is an empty string. Also procstat utility (`procstat -f {PID}`) which internally uses kinfo_getfile() has the same problem (also when running as root). Apparently the only tool which doesn't have this problem is lsof (but the code is a mess).

**Comment by giampaolo** [comment]
Test disabled as of https://github.com/giampaolo/psutil/commit/b8f444d03f42f8b32f6743de36543326833c244a

**Comment by giampaolo** [comment]
Note: OpenBSD has the same problem.

**Comment by giampaolo** [comment]
@glebius is this something you may wanna look at?

**Comment by giampaolo** [comment]
Actually I think this may be a kernel bug. Maybe we should report this to freebsd-dev.

**Comment by glebius** [comment]
test_open_files2 no longer exists. What is the modern name of this test?

**Comment by glebius** [comment]
Found it. It works :)

**Comment by giampaolo** [comment]
Closing out as outdated.
