### ISSUE TITLE
Compatibility matrix?

### ISSUE THREAD

**Issue by mumrah** [giampaolo/psutil#601]
Would be sweet if you could quickly glance at a table to see what features were supported on what platforms.

**Comment by giampaolo** [comment]
You mean in the doc? Currently almost all features are cross-platform and when they're not it's specified in the doc (e.g. "Availability: Linux").

**Comment by mumrah** [comment]
Ah great! It still might be nice to invert that so you could see what is and isn't supported in a condensed manner.

**Comment by giampaolo** [comment]
Honestly I don't think it's worth it. You can just search for "Availability".

**Comment by giampaolo** [comment]
I'm gonna close this out as rejected.
