### ISSUE TITLE
Average system load metrics on Windows

### ISSUE THREAD

**Issue by techtonik** [giampaolo/psutil#604]
Is there a way to query some kind of load average for Windows?
https://github.com/nicolargo/glances/issues/344

**Comment by giampaolo** [comment]
Interesting, I will look into this. And no, right now this is not exposed.

**Comment by techtonik** [comment]
Yea, I know. I stumbled upon this while trying to port https://github.com/Jahaja/psdash to Windows.

**Comment by giampaolo** [comment]
Some other references:
- https://www.zabbix.com/forum/showthread.php?t=14297
- https://technet.microsoft.com/en-us/library/cc940375.aspx

@wj32 Do you know how to retrieve the processor queue length on Windows (possibly without using WMI)?

**Comment by giampaolo** [comment]
This is implemented in a fork of sigar by using WMI:
https://github.com/boundary/sigar/blob/86613fe75578f8e09453866bc11741cc6dca6a60/src/os/win32/win32_sigar.c#L1084
Other ref:
https://github.com/hyperic/sigar/issues/72#issuecomment-241228024

**Comment by giampaolo** [comment]
http://serverfault.com/a/328406

**Comment by giampaolo** [comment]
Recent related BPO tickets:
https://bugs.python.org/issue34060
https://bugs.python.org/issue30263#msg296311
