### ISSUE TITLE
test_cpu_count fails on SunOS: no such file /proc/cpuinfo

### ISSUE THREAD

**Issue by grobian** [giampaolo/psutil#620]
The test obviously fails, could try to use nproc from gnu-coreutils, but more likely on Solaris /usr/sbin/psrinfo (-pv) should be used to get the number of physical and virtual processors.

**Comment by grobian** [comment]
https://github.com/Infinidat/psutil/commit/5c28b2b16f3a1fcc4683d21d762504d85dfa79e7
I thought about the alternative if LINUX: but I wonder what the intention of the test was, it looks like it tries to avoid a false positive, question is if that can happen on non-Linux systems (and how to detect it).

**Comment by giampaolo** [comment]
Yeah, the real intent of that test should be to run on Linux only so the `if` condition should be:

    if LINUX and os.path.exists("/proc/cpuinfo"):
         ...

**Comment by giampaolo** [comment]
This is supposed to have been fixed by #610.
