### ISSUE TITLE
hangs up on Process.open_files()

### ISSUE THREAD

**Issue by nsobiratel** [giampaolo/psutil#622]
version 2.2.1, python 
on process_iter cause hang on two processes: spoolsv.exe and python.exe. 
system : windows 7 professional x32, as admin
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (In
tel)] on win32
installed kaspersky av

    for proc in psutil.process_iter():
        try:
            # temporary hack
            #if proc.name() == 'spoolsv.exe' or proc.name() == 'python.exe':
            #    continue

            print(proc.name())
            opened_files = proc.open_files() # <- hang
        except:
             continue

if walk with debugger:

    def open_files(self):
        if self.pid in (0, 4):
            return []
        retlist = []
        # Filenames come in in native format like:
        # "\Device\HarddiskVolume1\Windows\systemew\file.txt"
        # Convert the first part in the corresponding drive letter
        # (e.g. "C:\") by using Windows's QueryDosDevice()
        raw_file_names = cext.proc_open_files(self.pid) # <--------------------------- HANG
        for file in raw_file_names:
            file = _convert_raw_path(file)
            if isfile_strict(file) and file not in retlist:
                ntuple = _common.popenfile(file, -1)
                retlist.append(ntuple)
        return retlist

**Comment by mrjefftang** [comment]
@nsobiratel Can you tryusing the patch here: https://github.com/giampaolo/psutil/pull/597 ?

**Comment by nsobiratel** [comment]
excuse me, I was not able to compile psutil from source with this patch...with migw, with VS - result - various compilation errors, spent more than 4 hours attempts compile... which simplest way install 2.2.1 with this patch? can you build some installer with patch?

**Comment by giampaolo** [comment]
Unfortunately MinGW is no longer supported. Here's some instructions on how to compile using VS:
https://github.com/giampaolo/psutil/blob/master/INSTALL.rst#compiling-on-windows-using-visual-studio
If you can't maybe @mrjefftang can send you the exe?
@mrjefftang to build an exe you have to:

     C:\Python27\python.exe setup.py build bdist_wininst

The exe will be in the `dist` directory.

**Comment by mrjefftang** [comment]
@nsobiratel Installer available here: https://github.com/mrjefftang/psutil/releases/tag/nsobiratel

https://github.com/mrjefftang/psutil/releases/download/nsobiratel/psutil-3.0.0-test.win32-py3.4.zip

**Comment by giampaolo** [comment]
Boy, that was fast!

**Comment by nsobiratel** [comment]
i'm have 2012 VS only at workplace and with this instruction get error..
after install psutil by @mrjefftang build:

  File "D:\OEInstances\Python\process_util.py", line 12, in <module>
    import psutil
  File "C:\Python\lib\site-packages\psutil-2.2.1-py3.4-win32.egg\psutil\__init__.py", line 139, in <module>
    import psutil._pswindows as _psplatform
  File "C:\Python\lib\site-packages\psutil-2.2.1-py3.4-win32.egg\psutil\_pswindows.py", line 17, in <module>
    import _psutil_windows as cext
ImportError: DLL load failed: Не найден указанный модуль. (translate - cannot find module)

**Comment by mrjefftang** [comment]
It looks like you have the old psutil still installed, your error is loading 2.2.1, the temp build I gave you registers as 3.0.0.  There will be some weird error where the old python library tries to load the new DLL and vice versa.

Remove all versions of psutil and try reinstalling.

**Comment by nsobiratel** [comment]
make reinstall - get same error...

**Comment by giampaolo** [comment]
Remove all `C:\Python\lib\site-packages\psutil*` occurrences (files and dirs).

**Comment by nsobiratel** [comment]
deinstall by pip, after install all works. thaaaaanks

**Comment by nsobiratel** [comment]
and about VS 2012:

E:\psutil-2.2.1>E:\psutil-2.2.1\setup.py build
running build
running build_py
creating build
creating build\lib.win32-3.4
creating build\lib.win32-3.4\psutil
copying psutil\_common.py -> build\lib.win32-3.4\psutil
copying psutil\_compat.py -> build\lib.win32-3.4\psutil
copying psutil\_psbsd.py -> build\lib.win32-3.4\psutil
copying psutil\_pslinux.py -> build\lib.win32-3.4\psutil
copying psutil\_psosx.py -> build\lib.win32-3.4\psutil
copying psutil\_psposix.py -> build\lib.win32-3.4\psutil
copying psutil\_pssunos.py -> build\lib.win32-3.4\psutil
copying psutil\_pswindows.py -> build\lib.win32-3.4\psutil
copying psutil\__init__.py -> build\lib.win32-3.4\psutil
running build_ext
building '_psutil_windows' extension
error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).

**Comment by mrjefftang** [comment]
You can use VS2012 to build, you just have to set up your environment variables correctly.

```
set VS100COMNTOOLS=%VS110COMNTOOLS%
```

**Comment by nsobiratel** [comment]
excuse me, but #597 fully merged into master? or no? i'm build last master (3.0.2) and get hang on open_files()...

**Comment by giampaolo** [comment]
No, it's not merged yet. I believe @mrjefftang is still dealing with some unsolved issues.

**Comment by mrjefftang** [comment]
It's about as complete as I can get it to work around the limitations of WinXP.

There's a balance between not hanging a process vs successfully enumerating all file handles.

In my testing I haven't seen any hangs and it grabs most of the file handles.  There are definitely ones being missed but that's a fact we have to live with given our limitations to the Windows API.

**Comment by giampaolo** [comment]
What are the differences between Windows XP and other Windows variants?

**Comment by mrjefftang** [comment]
WinXP uses GetMappedFileName to enumerate file handles, a method documented in MSDN.  It will miss some files (issues we've seen filed by other users) but it will not hang.

Vista+ uses threads and kills it off if the thread hangs.  I have not seen any issues of it missing file handles.  Though it's really hard to find what you are missing because replicating the different file handles is tough.

**Comment by giampaolo** [comment]
This was fixed by Jeff in https://github.com/giampaolo/psutil/pull/597. Closing.
