### ISSUE TITLE
psutil net_if_stats() and net_if_addrs() returning Attribute Error

### ISSUE THREAD

**Issue by vemkiran** [giampaolo/psutil#626]
>>> psutil.net_if_addrs()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ModuleWrapper' object has no attribute 'net_if_addrs'
>>> psutil.net_if_stats()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ModuleWrapper' object has no attribute 'net_if_stats'

**Comment by giampaolo** [comment]
`net_if_stats()` is not available in any release yet, it's just on GIT. I (erroneously) updated the README so if you look at the home page it seems the function is already available but it's not (my fault).

**Comment by vemkiran** [comment]
ok! Thanks!

**Comment by gunslingor** [comment]
Hows this code coming?

**Comment by edurc** [comment]
Hello giampaolo, how are you doing?

I'm trying to use psutil net_if_stats() in my project to measure network traffic on OpenSimulator. But I'm getting the same error as kiran-vemuri described. Well, not exactly the same, I'm using this:

speed = psutil.net_if_stats().speed

To save that informatiion into the speed variable, like I'm already doing on "psutil.net_io_counters().bytes_sent" and "psutil.net_io_counters().bytes_recv". These two work, but the psutil.net_if_stats() doesn't.

I am using psutil version 3.4.2 on Windows x64.

Can you help me?

**Comment by giampaolo** [comment]
Hello there. I'm fine thanks.
That doesn't work because net_if_stats() return a Python dict. Every dict's value contain the info you're looking for. Try this:

```
for name, stats in psutil.net_if_stats().items():
  print "%s: %s" % (name, stats.speed)
```

**Comment by edurc** [comment]
Thank you! It worked.

But I have another issue that I hope you could help me:

I was thinking in a way to capture NIC usage, e.g. how much bytes NIC is using. Do you know if it is possible to accomplish with psutil?
We have the total number of bytes received and sent, as well as NIC maximum speed, but not the actual usage.

Thanks again.
