### ISSUE TITLE
IntEnum import error in Python 2.7 while using custom enum.

### ISSUE THREAD

**Issue by lukeweber** [giampaolo/psutil#635]
Changes made in #582 to change connection types to enum broke my code. I'm running python 2.7 and was using https://pypi.python.org/pypi/enum/. The fix would be to more specifically check for IntEnum in the import.

The failure is basically where enum.IntEnum is used in https://github.com/giampaolo/psutil/blob/master/psutil/_common.py it fails as the code assumes the existence of enum means the existence of python 3.4 and thus IntEnum.

**Comment by giampaolo** [comment]
Mmm I see what's going on (and it sucks).
I suppose you `pip install enum`, which is not the right backport of python 3.4 enum module (that is: https://pypi.python.org/pypi/enum34/). I will provide a fix for this and make a new release ASAP.
