### ISSUE TITLE
Can not get name, memory on windows (3.0.1)

### ISSUE THREAD

**Issue by eight04** [giampaolo/psutil#636]
In 2.2.1, I only get `AccessDenied` from `process.name()`. After updating to 3.0.1, `process.memory_percent()` will also raise `AccessDenied` error.

Also, although 3.0.0 should use the second method to get process name on windows, it always raises `AccessDenied` from `self.exe()`.

https://github.com/giampaolo/psutil/blob/master/psutil/_pswindows.py#L291-L294

I guess it should change to:
```python
except AccessDenied:
    return cext.proc_name(self.pid)
```

**Comment by giampaolo** [comment]
I checked the differences of memory related functions with `git diff release-2.2.1 release-3.0.1` and they are basically the same: I can't see why we would get AD on 3.0.1 but not on 2.2.1. If you're sure about that then please provide a test script or more debugging info.

> I guess it should change to:

no, it should not

**Comment by eight04** [comment]
Test script:
https://gist.github.com/eight04/fe6dd335e264a6a74e7d

2.2.1 result:
https://gist.github.com/eight04/cf5e5e4a163cb7bb2f9a

3.0.1 result:
https://gist.github.com/eight04/bbaf79c93e49889bbbd4

**Comment by giampaolo** [comment]
This was a silly error (a typo). :-\
Fixed now.
