### ISSUE TITLE
DLL load failed - cx_freeze

### ISSUE THREAD

**Issue by JonasR-** [giampaolo/psutil#638]
I get the following stacktrace when I try to start a program using the 3.0.1 psutil library.
The program is packed using cx_freeze on a Windows 7 machine and gets executed on a Windows XP machine.
The problem does not occur on psutil 2.2.1

    Traceback (most recent call last):
      File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
      File "main.py", line 6, in <module>
      File "C:\Python27\lib\site-packages\psutil\__init__.py", line 110, in <module>
      File "C:\Python27\lib\site-packages\psutil\_pswindows.py", line 16, in <module>
      File "ExtensionLoader_psutil__psutil_windows.py", line 22, in <module>
      File "ExtensionLoader_psutil__psutil_windows.py", line 14, in __bootstrap__
    ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.

**Comment by giampaolo** [comment]
Not sure how to reproduce this. Does the problem occur if you install psutil from scratch on Windows XP (either via pip or by installing the exe)?

**Comment by JonasR-** [comment]
Thanks for your response
Yes this also happens on my freshly installed Python 2.7.10 with psutil 3.0.1. Its the same Windows XP system and psutil was installed with "psutil-3.0.1.win32-py2.7.exe".
The traceback looks a bit different but I think it cohere

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Python27\lib\site-packages\psutil\__init__.py", line 110, in <module>

        from . import _pswindows as _psplatform
      File "C:\Python27\lib\site-packages\psutil\_pswindows.py", line 16, in <module
    >
        from . import _psutil_windows as cext
    ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.

By the way the translation for "Die angegebene Prozedur wurde nicht gefunden." is "The specified procedure could not be found"

**Comment by JonasR-** [comment]
Looks like msvcr90.dll is missing. Thats strange because Microsoft Visual C++ 2008 Redist and SP1 of it are installed.
![2015-07-09_13_44_24_001](https://cloud.githubusercontent.com/assets/4939798/8594419/ca08ba48-2640-11e5-9180-7e2647825acb.png)
![2015-07-09_13_43_52_001](https://cloud.githubusercontent.com/assets/4939798/8594421/cca65cb0-2640-11e5-9b4f-e22944f4928b.png)

**Comment by mrjefftang** [comment]
I haven't tried 3.0.1 yet but it might be related to the inet_ntop issue I saw earlier.

@JonasR- Have you tried copying the msvcr90.dll to the same directory as the python app?

**Comment by JonasR-** [comment]
Sorry for the late response.
Also with the dll copied to the working dir I got no change. 
"Dependency Walker" sayes it gets found

![2015-07-14_10_12_25_001](https://cloud.githubusercontent.com/assets/4939798/8669049/6ba252f0-2a11-11e5-9461-5a199e888326.png)

**Comment by mrjefftang** [comment]
I can confirm the same error on WinXP with Python 2.7.10 and psutil 3.0.1 and psutil 3.0.0.

**Comment by mrjefftang** [comment]
I just did some testing with the zipped release of 3.0.1 and it's definitely due to the issue identified in #616  .  I'll work on that patch to get it working across WinXP / Win 7.
