### ISSUE TITLE
nginx not displayed fully in p.cmdline

### ISSUE THREAD

**Issue by ccsalway** [giampaolo/psutil#639]
This is what it looks like in `ps aux`

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root     21475  0.0  0.0  96104  1404 ?        Ss   Jun23   0:00 nginx: master process /usr/sbin/nginx
```

but this is what it looks like in psutil.Process

```
>>> import psutil
>>> p = psutil.Process(21475)
>>> p.cmdline()
['nginx: master process /usr/sbin/ngin']
```

It has chopped the x of the end. I'm guessing it's because the amount of characters per list item isnt enough.

**Comment by giampaolo** [comment]
This was introduced in #634. I should have fixed it in https://github.com/giampaolo/psutil/commit/3a620d94b347a7044e1bd6c6aabcf5528c3089c3. Can you please confirm it works as expected?

**Comment by giampaolo** [comment]
I'm assuming this is fixed. Closing.
