### ISSUE TITLE
Add continuous test integration for OSX

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#648]
Similarly to #646 but for OSX. Still have to investigate whether there are public free services providing this.

**Comment by giampaolo** [comment]
http://www.yegor256.com/2014/10/05/ten-hosted-continuous-integration-services.html
Apparently the only solution is https://hosted-ci.com/ but it's not free. https://ship.io/ does not seem to support OSX, only IOS.

**Comment by mrjefftang** [comment]
Travis CI supports it but they are full currently.  You may want to get in contact with them for since psutil is an open source project.

**Comment by giampaolo** [comment]
from http://docs.travis-ci.com/user/multi-os/

> We are at capacity with Mac workers in both .org and .com environments. Consequently, we are not 
> accepting requests for the multi-OS feature at this time. As more capacity is added, we will resume 
> accepting requests.

I'm gonna try to send them an email anyway.

**Comment by giampaolo** [comment]
See comments in: https://github.com/travis-ci/travis-ci/issues/2312#issuecomment-122850231

**Comment by giampaolo** [comment]
It seems this project is using Travis + OSX by using `language: generic`. AFAIU the trick should be not using `language: python`, then use `os: osx` and for that install python separately.

**Comment by mrjefftang** [comment]
Figuring out the correct Travis settings will be a matter of trial and error as long as we can get it access to Travis's OSX builders.

**Comment by giampaolo** [comment]
Fixed by @mrjefftang. Closing.
