### ISSUE TITLE
Cannot from psutil import * 

### ISSUE THREAD

**Issue by Redpoint1** [giampaolo/psutil#656]
commit: cea400070302dc69d3f92d9b11d5ec6bb2307246 likely introduced a bug with the \__all\__ list of the \__init\__ module by wrongly renaming \__version\__ to \__3n\__:

```python
from psutil import *  # pylint: disable=wildcard-import
AttributeError: 'module' object has no attribute '__3n__'
```

**Comment by giampaolo** [comment]
...what the? I must have committed that by accident.
Also tells we should have a test case for it.
Sign... I shouldn't make releases at 4.00 AM in the morning.

**Comment by giampaolo** [comment]
The actual issue:

```
>>> from psutil import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__3n__'
>>> 
```
