### ISSUE TITLE
compilation error in psutil/_psutil_linux.c when including ethtool.h

### ISSUE THREAD

**Issue by maozguttman** [giampaolo/psutil#659]
Hi,

I was trying to build psutil 3.1.1 and got compilation errors from psutil/_psutil_linux.c:
  /usr/include/linux/ethtool.h:18:2: error: expected specifier-qualifier-list before 'u32'
The problem is that u32 is undefined in /usr/include/linux/ethtool.h.
ethtool.h looks like: https://www.kernel.org/pub/linux/kernel/people/marcelo/linux-2.4/include/linux/ethtool.h
It has no #include statements in it.

I am using: SUSE 10, Kernel 2.6.16.60

Thanks,
Maoz

**Comment by giampaolo** [comment]
can you provide a patch / PR?

**Comment by maozguttman** [comment]
Adding following code to psutil/_psutil_linux.c before #include <linux/ethtool.h> will work for me (hoping it will not break things on other Unix platforms)

// hack, so we may include kernel's ethtool.h
#include <linux/types.h>
typedef __u64 u64;
typedef __u32 u32;
typedef __u16 u16;
typedef __u8 u8;

**Comment by giampaolo** [comment]
It seems https://www.kernel.org/pub/linux/kernel/people/marcelo/linux-2.4/include/linux/types.h should define those types.
I tried to fix it in 9503109725f4bac2d087e9fdcd547cadbcffd0a0.
Please let me know it it works.

**Comment by maozguttman** [comment]
Hi,

Your suggested fix doesn't work in my environment. Getting the same error.

In my environment /usr/include/linux/types.h includes /usr/include/asm/types.h which includes /usr/include/asm-x86_64/types.h or /usr/include/asm-i386/types.h based on the platform.
u8/u16/u32 u3/u16/u32 types defined in asm-x86_64/types.h and asm-i386/types.h.
However, they are wrapped with ifdef with the following comment above them: "These aren't exported outside the kernel to avoid name space clashes"
Please take a look in: https://www.kernel.org/pub/linux/kernel/people/marcelo/linux-2.4/include/asm-i386/types.h

Another way it to workaround asm-x86_64/types.h by adding the following code to _psutil_linux.c before the first #include in that file:

#ifdef __KERNEL__
    #include < asm/types.h >
#else
    #define __KERNEL__
    #include < asm/types.h >
    #undef __KERNEL__
#endif

But I don't really like it. I think that my first suggestion is the most generic.

Thanks,
Maoz

**Comment by maozguttman** [comment]
I found the first workaround (with the typedefs) in the web.
For example:
http://net-snmp.sourcearchive.com/documentation/5.4.1~dfsg-12ubuntu3/interface__linux_8c-source.html

Maoz

**Comment by mrjefftang** [comment]
I took a look at that net-snmp fix and it looks like they are relying on a compile time flag.

**Comment by giampaolo** [comment]
@mrjefftang can you please make a PR based on https://github.com/mrjefftang/psutil/commit/b82b8bec6463a90d708a922e36b98d3896e850a1? Or you can also commit it directly.

**Comment by mrjefftang** [comment]
I haven't made a PR because that commit didn't work.  It relies on a compiler time flag.

**Comment by maozguttman** [comment]
Maybe you can do like ./configure does when building a C++ applications.
Meaning, check if can include linux/ethtool.h with or without any workaround.

psutil/_psutil_linux.c will look like:
```
#ifdef ETHTOOL_MISSING_TYPES
#include <linux/types.h>
typedef __u64 u64;
typedef __u32 u32;
typedef __u16 u16;
typedef __u8 u8;
#endif
#include <linux/ethtool.h>
```

And in setup.py, you will check if to define ETHTOOL_MISSING_TYPES. Something like:
```
...

import os
import sys
try:
    from setuptools import setup, Extension, UnixCCompiler, CompileError
except ImportError:
    from distutils.core import setup, Extension
    from distutils.unixccompiler import UnixCCompiler
    from distutils.errors import CompileError

...

elif sys.platform.startswith("linux"):
    compiler = UnixCCompiler()
    ETHTOOL_MACRO = ()
    try:
        compiler.compile( ('psutil/_test_ethtool.c', ))
    except CompileError:
        ETHTOOL_MACRO = ( "ETHTOOL_MISSING_TYPES", 1 )
    extensions = [Extension(
        'psutil._psutil_linux',
        sources=['psutil/_psutil_linux.c'],
        define_macros=[VERSION_MACRO, ETHTOOL_MACRO]),
        posix_extension,
    ]
```
Where psutil/_test_ethtool.c looks like:
```
#include <linux/ethtool.h>
```

* I don't know if the change in the import of setuptools  is correct. If it has UnixCCompiler  and CompileError classes
* I know how to set an output area for compiler.compile. But I don't know how to get it in setup.py

**Comment by giampaolo** [comment]
I don't particularly like the solution of compiling a separate C file in setup.py buy I've extensively searched for a solution and couldn't find any. I committed a variant of your patch as of https://github.com/giampaolo/psutil/commit/b8adcd733d35d4e2351aee2cb7e6ac120c835825. Can you please confirm it works?

**Comment by maozguttman** [comment]
It works!

There is one cosmetic fix that you might want to do.
Many errors (from gcc) are printed because the compilation of temporary c-file that includes "linux/ethtool.h" fails in my environment.
These errors might be confusing and people will not be aware that they should ignore them.

**Comment by giampaolo** [comment]
Done in https://github.com/giampaolo/psutil/commit/8d66475bbeaa04aa6c4064ceadf0f4f176f5e03d.
Closing.
