### ISSUE TITLE
Add detection for Windows 10

### ISSUE THREAD

**Issue by KamranMackey** [giampaolo/psutil#661]
Apparently if you're on Windows 10 psutil detects it as Windows 8. Please add detection for WIndows 10.

**Comment by giampaolo** [comment]
What do you mean?

**Comment by KamranMackey** [comment]
@giampaolo: It displays this when you're on Windows 10: "OS: Windows-8-6.2.9200"

**Comment by giampaolo** [comment]
When? During install? Is that an error popping up as a dialog? Or a Python exception (with traceback)? Assuming psutil erroneously detects Windows 8 instead of 10 what exactly is the issue? That psutil cannot be installed on Windows 10? Or it can be installed but it does work (how?)? You need to be more specific.

**Comment by KamranMackey** [comment]
It works, but on my IRC bot and I do the bot's 'system command it displays
the operating system as Windows 8.

On Mon, Aug 3, 2015 at 8:37 AM, giampaolo <notifications@github.com> wrote:

> When? During install? Is that an error popping up as a dialog? Or a Python
> exception (with traceback)? Assuming psutil erroneously detects Windows 8
> instead of 10 what exactly is the issue? That psutil cannot be installed on
> Windows 10? Or it can be installed but it does work (how?)? You need to be
> more specific.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/giampaolo/psutil/issues/661#issuecomment-127263206>.
>



-- 
- Kamran Mackey

**Comment by giampaolo** [comment]
**what** displays the operating system? psutli does not provide any API to detect and distinguish different Windows (or any other OS) versions.

**Comment by KamranMackey** [comment]
Nevermind. It might just be a Python 3.4.3 issue.

On Mon, Aug 3, 2015 at 8:44 AM, giampaolo <notifications@github.com> wrote:

> *what* displays the operating system? psutli does not provide any API to
> detect and distinguish different Windows (or any other OS) versions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/giampaolo/psutil/issues/661#issuecomment-127265134>.
>



-- 
- Kamran Mackey

**Comment by mrjefftang** [comment]
@KamranMackey This is a Python issue with the Platform module.

>>> platform.platform()
'Windows-8-6.2.9200'

**Comment by giampaolo** [comment]
Thanks Jeff.
