### ISSUE TITLE
psutil don't make difference between broadcast and point to point interfaces

### ISSUE THREAD

**Issue by mffrench** [giampaolo/psutil#663]
Hello,

just found this little issue on snic tuple returned by psutil.net_if_addrs(). 

I've currently a tun0 interfaces linked to a VPN : 

```
tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet adr:10.8.0.10  P-t-P:10.8.0.9  Masque:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:20358 errors:0 dropped:0 overruns:0 frame:0
          TX packets:21988 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:100 
          RX bytes:7265126 (6.9 MiB)  TX bytes:6695863 (6.3 MiB)
```

As you can see the P-t-P target address is considered as the broadcast address on the psutil snic tuple : 

```
snic(family=<AddressFamily.AF_INET: 2>, address='10.8.0.10', netmask='255.255.255.255', broadcast='10.8.0.9')
```

I guess best way to make the diff and keep retro compatibility would be to add a ptp field with '10.8.0.9' and leave the broadcast field with None.

Cheers,

Mathilde

**Comment by giampaolo** [comment]
Mmm interesting. I took a look at netifaces lib and it seems it has the same problem because the only fields it provides are `broadcast`, `netmask` and `addr`, similarly as psutil.
In order to retrieve NIC info we use `getifaddrs`: http://man7.org/linux/man-pages/man3/getifaddrs.3.html I suppose the returned structure must have some flag to identify when the broadcast refers to a P2P address but that opens a pandora's box: what other flags should we take into account and are they portable across UNIX platforms? For this reason adding a new `ptp` field looks like a bad a idea to me.
What is your use case exactly? Identifying NICs linked to a VPN?

**Comment by giampaolo** [comment]
Nevermind. I should read man pages before assuming anything too soon. =)
According to man getifaddrs it seems ptp is the only exception:

```
       Depending on whether the bit IFF_BROADCAST or IFF_POINTOPOINT is set
       in ifa_flags (only one can be set at a time), either ifa_broadaddr
       will contain the broadcast address associated with ifa_addr (if
       applicable for the address family) or ifa_dstaddr will contain the
       destination address of the point-to-point interface.
```

...so after all it looks like adding a separate 'ptp' could make sense.

**Comment by giampaolo** [comment]
Note to self. 
Linux uses IFF_BROADCAST and IFF_POINTOPOINT flags to distinguish the meaning of `ifa_broadaddr` struct:
http://man7.org/linux/man-pages/man3/getifaddrs.3.html
FreeBSD has two (less confusing) separate `ifa_broadaddr` and `ifa_dstaddr` structs:
https://www.freebsd.org/cgi/man.cgi?query=getifaddrs
OSX uses `ifa_dstaddr`:
https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man3/getifaddrs.3.html
Solaris uses `ifa_broadaddr` and `ifa_dstaddr` structs similarly to FreeBSD:
http://docs.oracle.com/cd/E26502_01/html/E29035/getifaddrs-3socket.html

**Comment by giampaolo** [comment]
This is now implemented as of https://github.com/giampaolo/psutil/pull/668/files

**Comment by mffrench** [comment]
Hello Giampalo,

very quick reaction and implementation ! thank you :)

to answer your question (why I need to identify NIC identified on VPN). I'm currently working on an OS mapping plugin linked to the Ariane project. Our target is ability to map all processes and their connections in the OS.  https://github.com/echinopsii/net.echinopsii.ariane.community.plugin.procos

You can get more information here : http://ariane.echinopsii.net/

Cheers
