### ISSUE TITLE
CPU usage for short lived processes

### ISSUE THREAD

**Issue by johnmudd** [giampaolo/psutil#671]
I recently had to diagnose a problem with high CPU usage. Running top, htop and glances was not helpful because the problem processes were too short lived to appear in the output.

A sys admin found the problem by running ````ps aux | sort -rk 3,3 | head -n 30````. This showed a number of ````ls```` commands running. Each was taking up about 8% of a CPU. Our application was spawning about 400 ````ls```` commands per second. Each was an ````ls```` on an empty directory so each process didn't run long.

I was able to find some of these commands with psutil but I only got 0% when calling the cpu_percent() method. How could the ````ps```` command get the CPU percentage for these processes but psutil can't?

**Comment by giampaolo** [comment]
The first call to `cpu_percent` (with interval == 0) is expected to return 0% because it has no previous data to compare against. In order to get a meaningful result you should wait some time (0.1 secs or something) between one call and another. I am not sure how ps determines that 8%.
