### ISSUE TITLE
Emulating ps STAT output

### ISSUE THREAD

**Issue by siavashaslanbeigi** [giampaolo/psutil#674]
Can I access the "STAT" attribute of the "ps" command for a specific process using psutil? (http://askubuntu.com/questions/360252/what-do-the-stat-column-values-in-ps-mean). More specifically, I would like to know if the question asked in http://unix.stackexchange.com/questions/152140/find-out-which-process-is-in-foreground-on-bash can be answered by psutil, instead of having to parse the output of "ps".

**Comment by giampaolo** [comment]
Yes you can use psutil.Process.status() method.
Il 28/ago/2015 15:31, "siavashaslanbeigi" <notifications@github.com> ha
scritto:

**Comment by siavashaslanbeigi** [comment]
psutil.Process.status() is not able to distinguish between background and foreground processes, is it ?

**Comment by giampaolo** [comment]
What do you mean by that? Define background / foreground.
Il 28/ago/2015 21:49, "siavashaslanbeigi" <notifications@github.com> ha
scritto:

**Comment by siavashaslanbeigi** [comment]
Say I have some Python script test.py. If I execute "$ python test.py" and then look at the output of "ps", I see:
PID STAT TTY      COMMAND
23887 S    ttys008  bash
25920 S+   ttys008  python test.py
Note the "+" in the STAT value of test.py.

However, if I execute the same script via "$ nohup python -u test.py &" and look at the output of "ps":
PID STAT TTY      COMMAND
23887 S+   ttys008  bash
25941 S    ttys008  python test.py
You see that the "+" now appears for the bash process, because test.py is running in the background.

It is the "+" in STAT that I am after.

**Comment by giampaolo** [comment]
I see, then what you're looking for is determining whether the process is
attached to a terminal.
You can do that via psutil.Process.terminal() method (which must return
something != None). Use it in conjunction with psutil.Process.state() and
you can replicate the same ps behavior.

On Sat, Aug 29, 2015 at 5:03 PM, siavashaslanbeigi <notifications@github.com
> wrote:

> Say I have some Python script test.py. If I execute "$ python test.py" and
> then look at the output of "ps", I see:
> PID STAT TTY COMMAND
> 23887 S ttys008 bash
> 25920 S+ ttys008 python test.py
> Note the "+" in the STAT value of test.py.
>
> However, if I execute the same script via "$ nohup python -u test.py &"
> and look at the output of "ps":
> PID STAT TTY COMMAND
> 23887 S+ ttys008 bash
> 25941 S ttys008 python test.py
> You see that the "+" now appears for the bash process, because test.py is
> running in the background.
>
> It is the "+" in STAT that I am after.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/giampaolo/psutil/issues/674#issuecomment-135996301>.
>



-- 
Giampaolo - http://grodola.blogspot.com

**Comment by siavashaslanbeigi** [comment]
For the two scenarios above, I get the exact same output : p.terminal() = '/dev/ttys008' and p.status() = 'running', so what you're suggesting does not seem to work for me.

**Comment by giampaolo** [comment]
On Sat, Aug 29, 2015 at 6:07 PM, siavashaslanbeigi <notifications@github.com
> wrote:

> p.terminal() = '/dev/ttys008' and p.status() = 'running'


To my understanding status() == "running" and terminal() != None is the
logic used by "ps" when "S+" is shown.
With that said, I may be wrong, as I didn't write "ps" ...and I don't
understand why you do care, honestly. =)


-- 
Giampaolo - http://grodola.blogspot.com

**Comment by siavashaslanbeigi** [comment]
>> To my understanding status() == "running" and terminal() != None is the
logic used by "ps" when "S+" is shown.
This cannot be true, since for the process 25941 in my example above "ps" shows "S" while status() == "running" and terminal() != None.

Why do I care? Good question. In OS X Terminal, I have a bunch of tabs open. I would like to know which ones are currently busy (i.e. one cannot enter commands and see their results). "ps" lets me do this because (i) there's a one-to-one correspondence between tabs and TTYs, (ii) if there is a non-shell process whose STAT has "+" in it, I can conclude that the tab is busy.

I know this is more of a GUI question for OS X Terminal, but I am doing this in Python and making osascript AppleScript calls is just too damn slow. psutil is super fast, so I thought if I can get my hands at the "+" in STAT, I would use the logic described above.

**Comment by giampaolo** [comment]
You should first make sure about what "+" and "S+" means exactly and with
that check if the Process class provides the necessary info:
http://pythonhosted.org/psutil/#process-class.
If that has to do with a process GUI / window then psutil cannot be of any
help.

On Sat, Aug 29, 2015 at 6:31 PM, siavashaslanbeigi <notifications@github.com
> wrote:

> To my understanding status() == "running" and terminal() != None is the
> logic used by "ps" when "S+" is shown.
> This cannot be true, since for the process 25941 in my example above "ps"
> shows "S" while status() == "running" and terminal() != None.
>
> Why do I care? Good question. In OS X Terminal, I have a bunch of tabs
> open. I would like to know which ones are currently busy (i.e. one cannot
> enter commands and see their results). "ps" lets me do this because (i)
> there's a one-to-one correspondence between tabs and TTYs, (ii) if there is
> a non-shell process whose STAT has "+" in it, I can conclude that the tab
> is busy.
>
> I know this is more of a GUI question for OS X Terminal, but I am doing
> this in Python and making osascript AppleScript calls is just too damn
> slow. psutil is super fast, so I thought if I can get my hands at the "+"
> in STAT, I would use the logic described above.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/giampaolo/psutil/issues/674#issuecomment-136007584>.
>



-- 
Giampaolo - http://grodola.blogspot.com

**Comment by siavashaslanbeigi** [comment]
I thought this would be the place to ask whether or not the Process class provides the necessary info regarding "+". I don't think it does. Regarding what "+" means *exactly*, it depends what level of rigour you're after here. I thought my example above was illustrative enough, though. Below is what "man ps" provides:

PROCESS STATE CODES Here are the different values that the s, stat and state output specifiers (header "STAT" or "S") will display to describe the state of a process:

           D    uninterruptible sleep (usually IO)
           R    running or runnable (on run queue)
           S    interruptible sleep (waiting for an event to complete)
           T    stopped, either by a job control signal or because it is being traced
           W    paging (not valid since the 2.6.xx kernel)
           X    dead (should never be seen)
           Z    defunct ("zombie") process, terminated but not reaped by its parent

   For BSD formats and when the stat keyword is used, additional characters may be displayed:

           <    high-priority (not nice to other users)
           N    low-priority (nice to other users)
           L    has pages locked into memory (for real-time and custom IO)
           s    is a session leader
           l    is multi-threaded (using CLONE_THREAD, like NPTL pthreads do)
           +    is in the foreground process group

**Comment by giampaolo** [comment]
In this case I'm not sure what to suggest, I'm sorry. Closing this out.
