### ISSUE TITLE
Decoding error on child.connections(kind='unix')

### ISSUE THREAD

**Issue by teto** [giampaolo/psutil#675]
Here is a log of my small python script that tries to find the unix socket associated with the neovim application running in the currently focused terminal:
```
NVIM detected
Retreived terminal pid 13109, nvim should be one of its children
proc name rxvt-unicode with 5 children
child name & pid rxvt-unicode/13110
child name & pid zsh/13111
child name & pid nvim/13272
Could not find neovim socket 'utf-8' codec can't decode byte 0xd7 in position 469: invalid continuation byte
Traceback (most recent call last):
  File "/home/teto/.i3/i3nvim.py", line 56, in get_nvim_socket
    unix_sockets = child.connections(kind="unix")
  File "/home/teto/.local/lib/python3.4/site-packages/psutil/__init__.py", line 1010, in connections
    return self._proc.connections(kind)
  File "/home/teto/.local/lib/python3.4/site-packages/psutil/_pslinux.py", line 709, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/teto/.local/lib/python3.4/site-packages/psutil/_pslinux.py", line 1169, in connections
    ret = _connections.retrieve(kind, self.pid)
  File "/home/teto/.local/lib/python3.4/site-packages/psutil/_pslinux.py", line 555, in retrieve
    for fd, family, type_, laddr, raddr, status, bound_pid in ls:
  File "/home/teto/.local/lib/python3.4/site-packages/psutil/_pslinux.py", line 508, in process_unix
    f.readline()  # skip the first line
  File "/usr/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 469: invalid continuation byte

```
The exception seem to start with the child.connections(kind="unix") call. On another computer with configuration nearly identical (same $HOME, ubuntu on both etc...) the script works perfectly. I've tried with the latest master and still the same error.

**Comment by giampaolo** [comment]
Mmm this is gonna be hard to debug. What's the output of `sys.getfilesystemencoding()` and `sys.getdefaultencoding()`? Do you have the same problem by using python 2? Also, what's the output of `echo $LANG`?

**Comment by teto** [comment]
```$echo $LANG
fr_FR.UTF-8
$ python3
>>> import sys
>>> sys.getfilesystemencoding()
'utf-8'
```
It works with python2. The typical neovim socket name is "/tmp/nvimeArb4h/0"

**Comment by teto** [comment]
let me know if psutil embeds a logging system I could enable to help debugging

**Comment by giampaolo** [comment]
What about `sys.getdefaultencoding()`?

**Comment by teto** [comment]
Oops sorry:  sys.getdefaultencoding() gives 'utf-8'

**Comment by giampaolo** [comment]
Please try https://github.com/giampaolo/psutil/commit/e229dbe546cb87e9aa4579fa83b79065ef8ab26f

**Comment by giampaolo** [comment]
Actually please try https://github.com/giampaolo/psutil/commit/77119ebe737b2ab562e20aa4980faba4d7624fbb

**Comment by teto** [comment]
Apparently the commit fixed it. Hope it's not because the random socket name was ok. Anyway I close this and will reopen if the bug arises again.
thanks

**Comment by teto** [comment]
Sorry, it was working because I had left python2 in the shebang. When using python3 I still have the same mistake

**Comment by giampaolo** [comment]
Can you paste the content of the file (with `cat` or something)?

**Comment by giampaolo** [comment]
Actually it would be great if you can attach the file itself. Can you mail it to me at g.rodola@gmail.com?

**Comment by giampaolo** [comment]
Please try now.

**Comment by teto** [comment]
Great that solved it. Thanks again ! Closing this (Hopefully definitely :) )
