### ISSUE TITLE
the result of net_if_stats() on windows server2008 seems incorrect

### ISSUE THREAD

**Issue by skysider** [giampaolo/psutil#682]
psutil 3.2.1
the result of psutil.net_if_stats() on my machine is 
{"\x01": .....}
, which is very strange, while the result of psutil.net_if_addrs() is 
{"Teredo Tunneling Pseudo-Interface": .....}, which is consistent with my machine

**Comment by giampaolo** [comment]
This is python 2 right? What happens on python 3?

**Comment by shenyuan123** [comment]
python 3.4.3

**Comment by giampaolo** [comment]
Now that #1040 is fixed there may be chances this was fixed.

**Comment by giampaolo** [comment]
Assuming it's fixed. Closing.
