### ISSUE TITLE
psutil.disk_usage returning same values for all partitions

### ISSUE THREAD

**Issue by vitorluis** [giampaolo/psutil#686]
Hi all,

i'm writing a application, that read some hardware data, and one of them is the partitions data.

So, when i execute the `psutil.disk_partitions` i get all the partitions, and that's OK.

But when i execute the `psutil.disk_usage('mount_point')`, all partitions return the same free, used and total values.

Follow, two screenshots to show this situation:
![home](https://cloud.githubusercontent.com/assets/1554800/10031442/8e85e434-6153-11e5-9687-d44c87de13ed.png)

And 

![usr](https://cloud.githubusercontent.com/assets/1554800/10031444/8fa47be6-6153-11e5-85f9-df2b6c05ed68.png)

Both partitions are XFS filesystem, but my '/' partition are EXT4 and also return this values. And i don't if is a problem, i running the psutil function in a new Thread.

To complement, i'm using Ubuntu 15.04.

**Comment by giampaolo** [comment]
I'm not sure I understand. Are you complaining that 2 different paths return the same values?
That is expected behavior in case the 2 paths belong to the same **mountpoint**.
For example on my Linux box `/` and `/tmp`  return the same values because `/tmp` is mounted under `/`.

**Comment by vitorluis** [comment]
Yes, 2 different paths are returning the same values.

But, as you can see on the screenshot, the mount point /home is pointing to /dev/sda3. And the other mount point /usr is pointing to /dev/sda6.

So, does not have 2 mount points, pointing to the same partition.

**Comment by vitorluis** [comment]
Oh man, i'm realized that i passing the device path, not the mounting point. So sorry about that :(
