### ISSUE TITLE
cpu percent of process always 0.0 

### ISSUE THREAD

**Issue by qingzhoutest** [giampaolo/psutil#691]
Hi,

I am using psutil in python 2.7 to get the cpu percent of the process, however, it always get 0.0 for current process. The system cpu percent is correct, and the cpu_time per process is also increased.

here is the test code which I am using:

```
def test_monitor():
    while True:
    	cpu_times = psutil.cpu_times()
    	print(cpu_times)
    	cpu_percent = psutil.cpu_percent()
    	print(cpu_percent)
    	p = psutil.Process()
    	p_cpu_times = p.cpu_times()
        print(p_cpu_times)
        cpu_percent = p.cpu_percent(1)
        print(cpu_percent)
    	for i in range(10000000):
    		j = i * i
        time.sleep(0.1)
```

Here is  the output of the test code:

```
scputimes(user=3659.16, nice=36.96, system=971.1, idle=45878.04, iowait=1802.11, irq=1.34, softirq=18.26, steal=0.0, guest=0.0, guest_nice=0.0)
0.0
pcputimes(user=0.06, system=0.01)
0.0
scputimes(user=3661.55, nice=36.96, system=971.24, idle=45882.6, iowait=1802.11, irq=1.34, softirq=18.26, steal=0.0, guest=0.0, guest_nice=0.0)
35.6
pcputimes(user=2.39, system=0.12)
0.0
scputimes(user=3663.96, nice=36.96, system=971.33, idle=45886.99, iowait=1802.16, irq=1.34, softirq=18.26, steal=0.0, guest=0.0, guest_nice=0.0)
36.8
pcputimes(user=4.72, system=0.17)
0.0
....
```

Can anybody help to check where's the problem? thank you.

Best Regards,
Qing

**Comment by giampaolo** [comment]
Try this:

```
def test_monitor():
    p = psutil.Process()
    while True:
         print(p.cpu_percent(interval=1))
```

**Comment by mattthhh** [comment]
Is it possible to write a async function to get all cpu_percent for all processes returned by `psutil.process_iter` ?

**Comment by mattthhh** [comment]
> Is it possible to write a async function to get all cpu_percent for all processes returned by `psutil.process_iter` ?

I guess I found it :
```python
list_proc = []
for proc in psutil.process_iter():
    list_proc.append(proc)
tasks = []
for i in range(len(list_proc):
    tasks.append(asyncio.create_task(update_process_cpu_percent(i, list_proc)))
await asyncio.gather(*tasks)

def update_process_cpu_percent(index, lst):
    percent = lst[index].cpu_percent()
    await asyncio.sleep(1)
    percent = lst[index].cpu_percent()
    # process return as you want
    return percent
```

**Comment by giampaolo** [comment]
> Is it possible to write a async function to get all cpu_percent for all processes returned by psutil.process_iter ?

`cpu_percent()` functions are non-blocking when you pass `interval=None` as an arg. 
As such you don't need to run then in a separate thread e.g. when you use asyncio. You can call `cpu_percent(interval=0)` directly. You probably just want to do `await asyncio.sleep(1)` between one call and another.
