### ISSUE TITLE
Process.name() cache may be outdated

### ISSUE THREAD

**Issue by PierreF** [giampaolo/psutil#692]
psutil cache the process name based on (pid, creation_time), but in case of exec it could change.

I can reproduce this issue with:
* start bash in one terminal. Use "echo $$" to find PID of this shell (e.g. 1626)
* Run a psutil.process_iter() loop => process.name() return "bash" when I'm on pid == 1626
* run "exec sh" on the bash terminal
* Re-run the same psutil.process_iter() loop, process.name() is still "bash"

The loop used is : 
```
for p in psutil.process_iter():
    if p.pid == 1626:
        print(p.name(), p.cmdline())
```

Note: the cmdline() - which is not cached - show the new name.

A way to request name without using cache may be valuable.

**Comment by adrianreber** [comment]
I have the same problem with checkpointing and restarting processes. During restart the process name is the name of the checkpoint/restart tool (CRIU) and once the process has been restored it changes to the program being restarted. So sometimes I get 'criu' as process name and sometimes the actual process name after the restore. It depends on the point in time at which the loop over psutil.process_iter() is run.

**Comment by giampaolo** [comment]
This is now fixed in latest GIT version.
