### ISSUE TITLE
Unable install psutil with python 3.5 on Windows 10 enterprise

### ISSUE THREAD

**Issue by andriyankov** [giampaolo/psutil#706]
python --version : Python 3.5.0
System : Windows 10 Enterprise 64-bit

To reproduce:
0. Start `cmd.exe`
1. Run `python.exe -m venv pyenv`
2. `pyenv\scripts\activate.bat`
3. `pip install psutil`

```
(pyenv) d:\dmitry-projects\python-workspace\myproject-test>pip install psutil
Collecting psutil
  Using cached psutil-3.2.2.tar.gz
Installing collected packages: psutil
  Running setup.py install for psutil
    Complete output from command d:\dmitry-projects\python-workspace\myproject-test\pyenv\scripts\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\Dmitry\\AppData\\Local\\Temp\\pip-build-30f7xgce\\psutil\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Dmitry\AppData\Local\Temp\pip-9o2vuh2s-record\install-record.txt --single-version-externally-managed --compile --install-headers d:\dmitry-projects\python-workspace\myproject-test\pyenv\include\site\python3.5\psutil:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.5
    creating build\lib.win32-3.5\psutil
    copying psutil\_common.py -> build\lib.win32-3.5\psutil
    copying psutil\_compat.py -> build\lib.win32-3.5\psutil
    copying psutil\_psbsd.py -> build\lib.win32-3.5\psutil
    copying psutil\_pslinux.py -> build\lib.win32-3.5\psutil
    copying psutil\_psosx.py -> build\lib.win32-3.5\psutil
    copying psutil\_psposix.py -> build\lib.win32-3.5\psutil
    copying psutil\_pssunos.py -> build\lib.win32-3.5\psutil
    copying psutil\_pswindows.py -> build\lib.win32-3.5\psutil
    copying psutil\__init__.py -> build\lib.win32-3.5\psutil
    running build_ext
    building 'psutil._psutil_windows' extension
    error: Unable to find vcvarsall.bat

    ----------------------------------------
Command "d:\dmitry-projects\python-workspace\myproject-test\pyenv\scripts\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\Dmitry\\AppData\\Local\\Temp\\pip-build-30f7xgce\\psutil\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Dmitry\AppData\Local\Temp\pip-9o2vuh2s-record\install-record.txt --single-version-externally-managed --compile --install-headers d:\dmitry-projects\python-workspace\myproject-test\pyenv\include\site\python3.5\psutil" failed with error code 1 in C:\Users\Dmitry\AppData\Local\Temp\pip-build-30f7xgce\psutil
```

**Comment by ibigpapa** [comment]
I'm also having this issue

**Comment by mrjefftang** [comment]
You need Visual Studio 2015 installed and the correct environment variables set so pip can find vcvarsall.bat.  It's easier if you just launch ```Developer Command Prompt for VS2015``` since these are automatically set for you.

```VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\```

**Comment by andriyankov** [comment]
Excuse me, but why python-developer have to install MS Visual Studio?

**Comment by mrjefftang** [comment]
Until @giampaolo releases a 3.5 wheel release, pip will build the extension from source which is why you need MS Visual Studio.

psutil requires a compiled library in order to interact with the operating system, it is not a simple python only module.

**Comment by giampaolo** [comment]
I didn't provide binaries/wheels for Python 3.5 because Python 3.5
installer gives me a weird error on install. I will try to take a look at
that once I find some time (someday next week or during the weekend).
Sorry. :-(

On Thu, Oct 29, 2015 at 7:45 PM, Jeff Tang <notifications@github.com> wrote:

> Until @giampaolo <https://github.com/giampaolo> releases a 3.5 wheel
> release, pip will build the extension from source which is why you need MS
> Visual Studio.
>
> psutil requires a compiled library in order to interact with the operating
> system, it is not a simple python only module.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/giampaolo/psutil/issues/706#issuecomment-152283968>.
>



-- 
Giampaolo - http://grodola.blogspot.com

**Comment by giampaolo** [comment]
This is the bug I've bumped into: http://bugs.python.org/issue25157
It seems related to system updates (which I currently have disabled).

**Comment by giampaolo** [comment]
OK, 3.5 installers are now available.

**Comment by bassplayer12** [comment]
Hi,

I encountered the same error:

raceback (most recent call last):
  File "C:\wptagent\wptagent.py", line 110, in run_testing
    self.run_single_test()
  File "C:\wptagent\wptagent.py", line 189, in run_single_test
    browser.stop(self.job, self.task)
  File "C:\wptagent\internal\chrome_desktop.py", line 136, in stop
    DesktopBrowser.stop(self, job, task)
  File "C:\wptagent\internal\desktop_browser.py", line 284, in stop
    kill_all(os.path.basename(self.path), False)
  File "C:\wptagent\internal\os_util.py", line 24, in kill_all
    wait_for_all(exe, timeout)
  File "C:\wptagent\internal\os_util.py", line 32, in wait_for_all
    pinfo = proc.as_dict(attrs=['pid', 'name', 'exe'])
  File "C:\Python27\lib\site-packages\psutil\__init__.py", line 638, in as_dict
    ret = meth()
  File "C:\Python27\lib\site-packages\psutil\__init__.py", line 775, in exe
    return guess_it(fallback=err)
  File "C:\Python27\lib\site-packages\psutil\__init__.py", line 757, in guess_it
    cmdline = self.cmdline()
  File "C:\Python27\lib\site-packages\psutil\__init__.py", line 790, in cmdline
    return self._proc.cmdline()
  File "C:\Python27\lib\site-packages\psutil\_pswindows.py", line 718, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
  File "C:\Python27\lib\site-packages\psutil\_pswindows.py", line 708, in convert_oserror
    raise exc
WindowsError: [Error 1168] Element not found: '(originated from NtQueryInformationProcess(ProcessBasicInformation))'

I just want to ask about the resolution or workaround about this.

Thank you
