### ISSUE TITLE
Graceful handling of missing /proc/vmstat

### ISSUE THREAD

**Issue by dpavlenkov** [giampaolo/psutil#722]
Joyent's LX brand zones don't have /proc/vmstat https://github.com/joyent/illumos-joyent/issues/33 and I don't think they will in near future. Would like to not throw error on https://github.com/giampaolo/psutil/blob/master/psutil/_pslinux.py#L260 but try alternative ways of getting swap page in/out values.

**Comment by giampaolo** [comment]
On what linux kernel is this missing? It is reasonable to catch `IOError` if the file is not there and set swap in/out values to `0`. Feel free to provide a PR if you want.
