### ISSUE TITLE
redundant check in WinXp implementation of psutil_get_open_files

### ISSUE THREAD

**Issue by Mezrin** [giampaolo/psutil#725]
https://github.com/giampaolo/psutil/blob/master/psutil/arch/windows/process_handles.c#L356

__NtQueryObject does not used by WinXP implementation of psutil_get_open_files
So check __NtQueryObject == NULL is redundant and should be deleted

**Comment by giampaolo** [comment]
Are you saying that the check is there only for Windows XP and since Windows XP is no longer supported it should be removed?

**Comment by giampaolo** [comment]
Closing this out because of inactivity and because it doesn't look too important.
