### ISSUE TITLE
non unicode data not correctly handled in Python 3

### ISSUE THREAD

**Issue by fbenkstein** [giampaolo/psutil#734]
Filenames and command line arguments can include (non-unicode) binary data on most operating systems.  This is more difficult to handle on Python 3 because these are generally expressed as the str type.  I've created pull request https://github.com/giampaolo/psutil/pull/733 with a test case that highlights the issue but do not have a solution at this point.

**Comment by giampaolo** [comment]
Fixed in https://github.com/giampaolo/psutil/pull/733

**Comment by giampaolo** [comment]
...also on OSX (https://github.com/giampaolo/psutil/commit/818ef90fdcfc6749786ba9ff38a1314910d92ca2 and https://github.com/giampaolo/psutil/commit/ba838832f03365587191b2e1849278d3eb414ee1).

**Comment by giampaolo** [comment]
It turns out this problem exists on pretty much all platforms and it affects `name()`, `exe()`, `cmdline()`, `cwd()` and `open_files()` methods on Python 3 only.
