### ISSUE TITLE
Add command line utility

### ISSUE THREAD

**Issue by techtonik** [giampaolo/psutil#750]
Add `python -m psutil` that list the most frequent data that are requested from users while troubleshooting:

    RAM:  419/3029 MB
    CPU:  Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz
    GPU:  Mobile Intel(R) GMA 4500MHD

GPU string for Intel is got from Adapter String, not from Adapter Type, which is "Mobile Intel(R) 4 Series Express Chipset Family".

**Comment by giampaolo** [comment]
I see little value in returning an arbitrary string which is not easily parse-able. If the user wants to do so he/she can simply do, for example:

```
python -c "import json, psutil; print(json.dumps(psutil.virtual_memory()))"
[10367352832, 4556836864, 56.0, 7951433728, 2415919104, 3891007488, 1778888704, 229965824, 1910951936]
```

...and decide what info to retried and what serialization format to use.
Also, psutil does not provide those stats about CPU and GPU.

**Comment by techtonik** [comment]
> I see little value in returning an arbitrary string which is not easily parse-able.

Is is not return - it is just a small helper for user space convenience. See https://github.com/godotengine/godot/issues/3546 for an example how it should be used.
