### ISSUE TITLE
OSError: [Errno 111] Connection refused when calling psutil.net_if_addrs().values()

### ISSUE THREAD

**Issue by thestick613** [giampaolo/psutil#784]
i'm running this code with gevent monkey patch so that may be a cause.

        for interface in psutil.net_if_addrs().values():
      File "/root/venv_smtpout/local/lib/python2.7/site-packages/psutil/__init__.py", line 1766, in net_if_addrs
        rawlist = _psplatform.net_if_addrs()
    OSError: [Errno 111] Connection refused

**Comment by giampaolo** [comment]
Well... I would say they first thing you should do is to run that **without** gevent monkey patch and see what happens.

**Comment by thestick613** [comment]
It only happens from time to time, like once every a few days. I've upgraded to 4.0.0 and i'll wait to see if it happens again.

**Comment by giampaolo** [comment]
`net_if_addrs` code in 4.0.0 is the same so that won't make any difference.

**Comment by giampaolo** [comment]
Have you ever bumped into this again?

**Comment by thestick613** [comment]
No, i just run the python script with larger ulimit settings
```
ulimit -n 65000;
python script.py
```
