### ISSUE TITLE
Mac address reporting is probably wrong on Linux

### ISSUE THREAD

**Issue by grrrrrrrrr** [giampaolo/psutil#786]
Hey,

I'm trying to update to v4.0.0 and I get test failures for the test_net_if_addrs_ips test. This is the assertion error:

FAIL: test_net_if_addrs_ips (psutil.tests.test_linux.TestSystemNetwork)

Traceback (most recent call last):
  File "psutil/tests/test_linux.py", line 334, in test_net_if_addrs_ips
    self.assertEqual(addr.address, get_mac_address(name))
AssertionError: '0b:6a:f2:c2' != '0b:6a:f2:c2:00:00'

In ifconfig, the offending HWaddr looks like this:

Link encap:UNSPEC  HWaddr 0B-6A-F2-C2-00-00-00-00-00-00-00-00-00-00-00-00  

I'm not sure what the value should be but to me it seems that the test function returning "0b:6a:f2:c2:00:00" might be correct? In any case, it would be good if the two functions agreed :)

**Comment by giampaolo** [comment]
Mmm I don't know much about IPv6 addresses but perhaps '0b:6a:f2:c2' and '0b:6a:f2:c2:00:00' are the same? In that case this would be a test issue.

**Comment by grrrrrrrrr** [comment]
Note that this is a HW address, not IPv6. It's probably not a MAC address either (sorry, I'm not an expert here) - it has link encap: unspec, not ethernet, so it's a different class.

It's still a hardware address but the assumption that it's exactly 6 bytes is not valid.

Maybe the correct solution here is to ignore encap unspec addresses entirely?

**Comment by giampaolo** [comment]
Ah right sorry, it's a MAC address (I got confused). What about `ifconfig -a`? Does it fill the missing pieces with null bytes? Can you paste the output?

**Comment by giampaolo** [comment]
I should have fixed this. Can you try latest GIT version?

**Comment by grrrrrrrrr** [comment]
Thanks, impressively fast response!

Your commit fixed that one issue, I have another one though. Sorry, some of our machines have weird network setup:

psutil mac output:

eth0:00:1a:11:40:3a:e6
gre0:0a:6b:9b:d4:00:00
gretap0:00:00:00:00:00:00
ip6gre0:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
ip6tnl0:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
sixdecap0:0a:6b:9b:d4:00:00

ifconfig -a:

eth0      Link encap:Ethernet  HWaddr 00:1a:11:40:3a:e6
gre0      Link encap:UNSPEC  HWaddr 0A-6B-9B-D4-36-00-32-30-00-00-00-00-00-00-00-00
gretap0   Link encap:Ethernet  HWaddr 00:00:00:00:00:00
ip6gre0   Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
ip6tnl0   Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
sixdecap0 Link encap:UNSPEC HWaddr 0A-6B-9B-D4-00-00-32-30-00-00-00-00-00-00-00-00

so it seems like psutil loses information on gre0 and sixdecap0? in any case, the test function always gets exactly 6 bytes so the test passes for gre0 and sixdecap0 (even though psutil is probably wrong) but fails for ip6gre0 and ip6tnl0 where psutil agrees with ipconfig.

The other bug was much more important than this small issue here now, thanks for fixing that one!

**Comment by giampaolo** [comment]
Mmmm... but is that the actual `ifconfig -a` output? Please past that one.

**Comment by grrrrrrrrr** [comment]
Sent you a mail with more debugging info. Thanks for investigating this!

**Comment by giampaolo** [comment]
Attaching here.

name : psutil output : test function output

```
eth0 : 00:1a:11:3d:10:7e : 00:1a:11:3d:10:7e
eth1 : 00:1a:11:3d:10:7e : 00:1a:11:3d:10:7e
eth2 : 00:1a:11:3d:10:7e : 00:1a:11:3d:10:7e
gre0 : 0a:6a:23:d5:00:00 : 0a:6a:23:d5:00:00
gretap0 : 00:00:00:00:00:00 : 00:00:00:00:00:00
ip6gre0 : 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 : 00:00:00:00:00:00
ip6tnl0 : 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 : 00:00:00:00:00:00
lo : 00:00:00:00:00:00 : 00:00:00:00:00:00
sit0 : 00:00:00:00:00:00 : 00:00:00:00:00:00
sixdecap0 : 0a:6a:23:d5:00:00 : 0a:6a:23:d5:00:00
sixtofour0 : 0a:6a:23:d5:00:00 : 0a:6a:23:d5:00:00
```

ifconfig -a:

```
eth0      Link encap:Ethernet  HWaddr 00:1a:11:3d:10:7e  
          inet addr:10.106.35.213  Bcast:10.106.35.255  Mask:255.255.255.192
          inet6 addr: fe80::21a:11ff:fe3d:107e/64 Scope:Link
          UP BROADCAST RUNNING MASTER MULTICAST  MTU:1500  Metric:1
          RX packets:265673646736 errors:0 dropped:285601 overruns:0 frame:0
          TX packets:166156715785 errors:0 dropped:10 overruns:0 carrier:0
          collisions:0 txqueuelen:16000 
          RX bytes:328579112914742 (328.5 TB)  TX bytes:167113018921683 (167.1 TB)

eth1      Link encap:Ethernet  HWaddr 00:1a:11:3d:10:7e  
          UP BROADCAST RUNNING SLAVE MULTICAST  MTU:1500  Metric:1
          RX packets:131343215103 errors:0 dropped:157999 overruns:0 frame:0
          TX packets:81612377398 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:16000 
          RX bytes:163414882141800 (163.4 TB)  TX bytes:81191689373065 (81.1 TB)

eth2      Link encap:Ethernet  HWaddr 00:1a:11:3d:10:7e  
          inet6 addr: fe80::1a:1100:13d:107e/64 Scope:Link
          UP BROADCAST RUNNING SLAVE MULTICAST  MTU:1500  Metric:1
          RX packets:134473520527 errors:0 dropped:127602 overruns:0 frame:0
          TX packets:84656951063 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:16000 
          RX bytes:165337821247077 (165.3 TB)  TX bytes:86032973938521 (86.0 TB)

gre0      Link encap:UNSPEC  HWaddr 0A-6A-23-D5-65-00-66-65-00-00-00-00-00-00-00-00  
          NOARP  MTU:1476  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

gretap0   Link encap:Ethernet  HWaddr 00:00:00:00:00:00  
          BROADCAST MULTICAST  MTU:1476  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:16000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

ip6gre0   Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          NOARP  MTU:1448  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

ip6tnl0   Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          NOARP  MTU:1452  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:4377324021 errors:0 dropped:31 overruns:0 frame:0
          TX packets:4377324021 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:61690980989260 (61.6 TB)  TX bytes:61690980989260 (61.6 TB)

sit0      Link encap:IPv6-in-IPv4  
          NOARP  MTU:1480  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

sixdecap0 Link encap:UNSPEC  HWaddr 0A-6A-23-D5-00-00-66-65-00-00-00-00-00-00-00-00  
          inet6 addr: fe80::5efe:a6a:23d5/64 Scope:Link
          UP POINTOPOINT RUNNING NOARP  MTU:1476  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:41301 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:4900900 (4.9 MB)

sixtofour0 Link encap:IPv6-in-IPv4  
          inet6 addr: 2002:a6a:23d5::1/128 Scope:Global
          inet6 addr: 2002:a6a:23d5::/128 Scope:Global
          UP RUNNING NOARP  MTU:1480  Metric:1
          RX packets:1071664 errors:0 dropped:0 overruns:0 frame:0
          TX packets:968859 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:267622912 (267.6 MB)  TX bytes:188416346 (188.4 MB)
```

**Comment by giampaolo** [comment]
Mmm.. it seems the problem only occurs with those `Link encap:UNSPEC` NICs, which I'm not sure what they are (it also says NOARP and POINTTOPOINT). I would say we can ignore them.

**Comment by mrjefftang** [comment]
Those look like virtual interfaces for tunneling (GRE, 6to4, etc).

**Comment by grrrrrrrrr** [comment]
Yes, they probably are. Do you know what the correct value would be to report for HWaddr in that case?

**Comment by mrjefftang** [comment]
Matching the system tool such as ifconfig is probably best.
