### ISSUE TITLE
Process.memory_maps() hangs when using it through a PyInstaller-compiled exe on Windows

### ISSUE THREAD

**Issue by qtfkwk** [giampaolo/psutil#787]
Test machine OS is Windows 7 with Python 2.7.11 and psutil 4.0.0. Goal is to enumerate all processes on a Windows machine.

The following script (process_iter.py) works fine when running it as `python process_iter.py`:

```
import psutil
i = psutil.process_iter()
for j in i:
    print j
    print j.as_dict()
    print
```

Then I compile it via PyInstaller: `pyinstaller -F process_iter.py` to produce process_iter.exe.

When the exe is run, it hangs on processes with the names: 'dwm.exe', 'explorer.exe', 'taskhost.exe', 'VBoxTray.exe', 'conhost.exe', 'cmd.exe', which I discovered via this version of the script (but I would prefer to not omit any processes):

```
import psutil
i = psutil.process_iter()
for j in i:
    print j
    n = j.name()
    print '"%s"' % n
    if not n in ('dwm.exe', 'explorer.exe', 'taskhost.exe', 'VBoxTray.exe', \
        'conhost.exe', 'cmd.exe'):
        print j.as_dict()
    print
```

Searching produced some older issues related to the open_files method, but it seems odd that it works perfectly as Python but hangs as an exe.

Any insight/assistance would be greatly appreciated.

My next steps are to avoid using the as_dict method and still obtain as much information as possible.

**Comment by giampaolo** [comment]
You should identify what method of `as_dict` hangs. As to why it hangs as an exe but not as a py file I have no idea.

**Comment by qtfkwk** [comment]
I'm not sure what you mean by "method of ``as_dict``"... ``as_dict`` is the method. I think that we are probably thinking the same thing, which is to identify what is the underlying cause and surgically avoid it. 

The main purpose in documenting this as an "issue" is to inform that there might be problems that only arise in this specific case: compiling via PyInstaller.

**Comment by giampaolo** [comment]
`as_dict` internally calls many `Process` methods such as `name()`, `cmdline()` etc. My suggestion was to first identify which ones of those methods hang exactly.

**Comment by giampaolo** [comment]
Note: I suppose you can also do that by simply pressing CTRL - C. The traceback should show you where it was hanging exactly.

**Comment by qtfkwk** [comment]
For some reason, the hung exe does not respond to a Ctrl+C, but adding a more surgical use of the underlying calls and print statements and/or logging should help. Thanks!

**Comment by mrjefftang** [comment]
You can try doing something like:

```python
import psutil

PROCESS_ATTRS = [
    'cmdline',
    'connections',
    'cpu_affinity',
    'cpu_percent',
    'cpu_times',
    'create_time',
    'cwd',
    'exe',
    'ext_memory_info',
    'gids',
    'io_counters',
    'io_nice',
    'memory_info',
    'memory_info_ex',
    'memory_maps',
    'memory_percent',
    'name',
    'nice',
    'num_ctx_switches',
    'num_fds',
    'num_handles',
    'num_threads',
    'open_files',
    'pid',
    'ppid',
    'rlimit',
    'status',
    'state',
    'terminal',
    'threads',
    'uids',
    'username'
]

curr_attrs = []
for attr in PROCESS_ATTRS:
    curr_attrs.append(attr)
    print("Current attributes: %s" % curr_attrs)
    for proc in psutil.process_iter():
        print("Querying process: %s [%s]" % (proc.name(), proc.pid))
        proc.as_dict(attrs=curr_attrs)
```

**Comment by giampaolo** [comment]
+1, good idea. `memory_full_info` is missing though.

On Wed, Mar 2, 2016 at 8:20 PM, Jeff Tang <notifications@github.com> wrote:

> You can try doing something like:
>
> import psutil
> PROCESS_ATTRS = [
>     'cmdline',
>     'connections',
>     'cpu_affinity',
>     'cpu_percent',
>     'cpu_times',
>     'create_time',
>     'cwd',
>     'exe',
>     'ext_memory_info',
>     'gids',
>     'io_counters',
>     'io_nice',
>     'memory_info',
>     'memory_info_ex',
>     'memory_maps',
>     'memory_percent',
>     'name',
>     'nice',
>     'num_ctx_switches',
>     'num_fds',
>     'num_handles',
>     'num_threads',
>     'open_files',
>     'pid',
>     'ppid',
>     'rlimit',
>     'status',
>     'state',
>     'terminal',
>     'threads',
>     'uids',
>     'username'
> ]
>
> curr_attrs = []for attr in PROCESS_ATTRS:
>     curr_attrs.append(attr)
>     print("Current attributes: %s" % curr_attrs)
>     for proc in psutil.process_iter():
>         print("Querying process: %s [%s]" % (proc.name(), proc.pid))
>         proc.as_dict(attrs=curr_attrs)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/giampaolo/psutil/issues/787#issuecomment-191382213>.
>



-- 
Giampaolo - http://grodola.blogspot.com

**Comment by mrjefftang** [comment]
Improved version:

```python
import psutil

EXCLUDE = ['send_signal', 'suspend', 'resume', 'terminate', 'kill', 'wait', 'is_running', 'as_dict', 'parent', 'children', 'rlimit']

PROCESS_ATTRS = set(x for x in dir(psutil.Process) if x not in EXCLUDE and not x.startswith('_'))

curr_attrs = []
for attr in PROCESS_ATTRS:
    curr_attrs.append(attr)
    print("Current attributes: %s" % curr_attrs)
    for proc in psutil.process_iter():
        print("Querying process: %s [%s]" % (proc.name(), proc.pid))
        proc.as_dict(attrs=curr_attrs)
```

**Comment by giampaolo** [comment]
Any news about this?

**Comment by giampaolo** [comment]
@qtfkwk I would really appreciate if you could identify what Process methods exactly causes the hanging as it looks like a high priority issue.

**Comment by qtfkwk** [comment]
@giampaolo Sorry, I am not working on this any more, at least for now. I believe I've provided everything necessary for someone to troubleshoot this issue.

**Comment by Nitiflor** [comment]
@giampaolo The Process method causing the hanging is `memory_maps`.
