### ISSUE TITLE
(3.3.0) Linux.rss ~= Windows.vms ?

### ISSUE THREAD

**Issue by drandreaskrueger** [giampaolo/psutil#791]
I have used psutil 3.3.0 to memory-benchmark the webframeworks (bottle, flask, cherrypy, web.py, tornado). 

To me it looks as if ``Linux.rss ~= Windows.vms`` ?
[Strange - but the numbers are too close to not notice that.](https://github.com/drandreaskrueger/pythonMicroframeworks#strange)

Compare these

* [results_windows.txt](https://github.com/drandreaskrueger/pythonMicroframeworks/blob/master/results_windows.txt)
* [results_linux.txt](https://github.com/drandreaskrueger/pythonMicroframeworks/blob/master/results_linux.txt)

Thanks!

**Comment by giampaolo** [comment]
Sorry for the huge delay, this totally slipped under my radar.
No, the two memory values represent different things, although kind of similar.
