### ISSUE TITLE
`psutil` has no attribute `cpu_stats`

### ISSUE THREAD

**Issue by MichaelCurrie** [giampaolo/psutil#794]
```
>>> import psutil
>>> psutil.cpu_stats()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'psutil' has no attribute 'cpu_stats'
```

However it is shown as an example on the [main page](https://github.com/giampaolo/psutil):

> ```
>>> psutil.cpu_stats()
scpustats(ctx_switches=20455687, interrupts=6598984, soft_interrupts=2134212)
```

I'm running 
```
>>> import sys
>>> sys.version
'3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'
>>> psutil.__version__
'4.0.0'
```
on
```
$ uname -a
Linux ip-172-31-9-94 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by giampaolo** [comment]
Hehe, that's because it's a feature I developed (see #https://github.com/giampaolo/psutil/issues/792) but I still have to package a new psutil release/tarball, so technically it's not available yet.
