### ISSUE TITLE
Windows: provide APIs to deal with Windows services

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#795]
Rationale
=======

People who want to deal with Windows services in Python are forced to rely either on pywin32 or WMI extensions but they're too low level (pywin32) and a bit confusing IMO. Some examples:

- list(): http://www.thecodingforums.com/threads/listing-existing-windows-services-with-python.715123/
- create():  http://code.activestate.com/recipes/576451-how-to-create-a-windows-service-in-python/
- remove(): https://bytes.com/topic/python/answers/32671-win32serviceutil-remove-service
- modify(): http://code.activestate.com/recipes/59872-manipulating-windows-services/

It would be nice if psutil could provide a compact API to deal with Windows services more easily.

API
===

I'm still not sure how to organize the API (classes? functions? namedtuple? etc.) yet, but roughly the underlying C extension module should expose these APIs:

- `list()`
- `create(name, exe_path, start_type='auto', description=None, ...)`
- `remove(name)`
- `modify(name, description=None, start_type=None, ...)`
- `start(name)`
- `stop(name)`
- `restart(name)`

psutil might wrap them by providing 3 higher-level functions + one class:

- `win_service_list()` -> return a list or `WindowsService` classes
- `win_service_install(name, exe_path, start_type='auto', description=None, ...)`
- `win_service_get(name)` -> return a `WindowsService` instance with the following attrs/methods:
      - `name`
      - `description`
      - `start_type`
      - `status`
      - `start()`
      - `stop()`
      - `restart()`
      - `modify()`
      - `remove()`

I think it's a good idea to stay as minimal as possible, meaning we should not provide all the features offered by pywin32. Instead we should cover the most common use cases only, which are list/create/modify/remove and start/stop/restart.

References
=========

- remove() and create(): http://web.mit.edu/source-8.1/third/xntp/scripts/wininstall/instsrv/instsrv.c
- pywin32 service utils: http://pyxr.sourceforge.net/PyXR/c/python24/lib/site-packages/win32/lib/win32serviceutil.py.html

**Comment by giampaolo** [comment]
Implemented and merged as of https://github.com/giampaolo/psutil/pull/803.
Ultimately, I decided to not provide start(), stop() and modify(). We only have iter() and get() for now.

**Comment by naggie** [comment]
This is great, thanks -- would you consider adding those methods? psutil has such a clean interface, it would be nice to use it for manipulating services too.

**Comment by giampaolo** [comment]
Here's the reasons why I didn't expose those methods back then:
https://github.com/giampaolo/psutil/blob/229fcd96fb69980f6db59e38c4a6752ccec3a285/psutil/_pswindows.py#L424-L440

**Comment by naggie** [comment]
Ok 👍
