### ISSUE TITLE
Windows - Process.open_files()  always return empty array

### ISSUE THREAD

**Issue by newdive** [giampaolo/psutil#798]
Using psutil ( 4.1.0 )
```
import psutil
proc = psutil.Process()
print proc.open_files()     # shows []
f = open('D:\ProgramSpace\python\test.txt','rb')
print proc.open_files()     # still []?
```
The second one does not print out the file that is opened. Am i missing something here?

**Comment by giampaolo** [comment]
What if you put a `time.sleep(.5)` before `open_files()`?

**Comment by newdive** [comment]
I tried the sleep function,still got no luck.
I also tried the process_iter() function to iterate all the process in my windows, and got empty array.
BTW, this piece of code works well on linux , without any delay

**Comment by giampaolo** [comment]
`open_files` on Windows has always had some problems due to limitations of the underlying Windows API (there's also a warning in the doc). The fact that it returns an empty list for **all** processes is weird though.

**Comment by YJesus** [comment]
open_files works well in Windows 7 but not in windows 8 or 10

**Comment by giampaolo** [comment]
I believe `open_files()` does not work properly on any Windows version. The C APIs provided by Windows are extremely low level, undocumented and apparently just broken (https://github.com/giampaolo/psutil/blob/master/psutil/arch/windows/process_handles.c), and AFAIK there's nothing out there which is able to do this reliably unless a Windows driver or service (not sure) is involved, which is a no-no for a Python lib. Running the Python process with the highest user privileges (NT/SYSTEM) may possibly alleviate the issue but I believe even in that case `open_files()` will keep being reliable. The only good news about it is that at some point we managed to solve the "hanging" issue by introducing a thread, but the fact that certain perfectly legitimate files are being skipped is still not solved. @wj32 (Process Hacker author) is way more expert than me on this. I am not sure whether PH is able to do this reliably without using a driver/service.

**Comment by YJesus** [comment]
The real alternative is handle from sysinternals that uses a driver but I don't understand why in Win7 works perfectly and not in 8-10  (same privileges, same code ...)

**Comment by giampaolo** [comment]
What's the problem? It skips files?

**Comment by giampaolo** [comment]
The thread PR: https://github.com/giampaolo/psutil/pull/597/files

**Comment by YJesus** [comment]
sorry, return nothing not None

**Comment by YJesus** [comment]
https://code.msdn.microsoft.com/windowsapps/CppFileHandle-03c8ea0b this example seems to work in Windows 8 (actualized in 2012)

**Comment by giampaolo** [comment]
That looks like a lot of good info, thanks. Unfortunately at a first glance it looks like it does pretty much the same things we're doing in psutil. I will take a better look at it later.

**Comment by YJesus** [comment]
What do you think about: 'Get system handle information. (NtQuerySystemInformation, SystemHandleInformation, SYSTEM_HANDLE_INFORMATION)NtQuerySystemInformation does not return the correct required buffer size if the buffer passed is too small. Instead you must call the function while increasing the buffer size until the function no longer returns STATUS_INFO_LENGTH_MISMATCH.'

--> DWORD nSize = 4096, nReturn;

And in your code:

 DWORD                               dwInfoSize = 0x10000;

**Comment by YJesus** [comment]
As I see you do:

while ((status = __NtQuerySystemInformation(
                           SystemExtendedHandleInformation,
                           pHandleInfo,
                            dwInfoSize,
                            &dwRet)) == STATUS_INFO_LENGTH_MISMATCH);

And in the example:

while (NtQuerySystemInformation(SystemHandleInformation, pSysHandleInfo,  
        nSize, &nReturn) == STATUS_INFO_LENGTH_MISMATCH) 
    { 
        HeapFree(GetProcessHeap(), 0, pSysHandleInfo); 
        nSize += 4096; 
        pSysHandleInfo = (SYSTEM_HANDLE_INFORMATION*)HeapAlloc( 
            GetProcessHeap(), 0, nSize); 
    } 

The example starts with 4096 and increments 4096 in each iteration

**Comment by YJesus** [comment]
Ok, I try the example from Microsoft and not works. But when I remove 

if (pHandle->ProcessId == pid && pHandle->ObjectTypeNumber == HANDLE_TYPE_FILE)

It works perfectly and lists all handles. So I suspect they fails because bad HANDLE_TYPE_FILE

**Comment by YJesus** [comment]
OK, I put a printf in pHandle->ObjectTypeNumber and I can say that the handle_type is random 

Probably you shoud changle

 if (hHandle->UniqueProcessId != (HANDLE)dwPid ||
            hHandle->ObjectTypeIndex != HANDLE_TYPE_FILE)

to

if (hHandle->UniqueProcessId != (HANDLE)dwPid)

**Comment by YJesus** [comment]
I have tested the patch and psutil open_files works very well in Windows 7 and Windows 10

**Comment by YJesus** [comment]
conclusions: HANDLE_TYPE_FILE is a fixed type in Windows XP and 7 but in 8 and 10 is a random type or at least it could be many values

**Comment by giampaolo** [comment]
Fixed in https://github.com/giampaolo/psutil/commit/c597ab3
