### ISSUE TITLE
Speedup Process methods

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#799]
This is something I've been thinking about for a while. Problem with current `Process` class implementation is that if you want to fetch multiple process info the underlying (C / Python) implementation may unnecessarily do the same thing more than once. 

For instance, on Linux we read `/proc/pid/stat` file to get `terminal`, `cpu_times`, and `create_time`, and each time we invoke those methods we `open` the file and `read` from it. We get the one info we're interested in and discard the rest.
A similar thing happens on basically every OS. For instance on BSD we use `kinfo_proc` syscall to get basically 80% of all process info (`uids`, `gids`, `create_time`, `ppid`, `io_counters`, `status` etc.). 
Again, all this info retrieved once (in C) and re-requested every time we call a `Process` method.

Since we typically get more than one info about the process (e.g. think about a top-like app) it appears clear that this could (and should) be done in a single operation. A possible solution would be to provide a context manager which temporarily puts the `Process` instance in a state so that internally the requested metrics are determined in a single shot and then "cached" / "stored" somewhere:

```
p = psutil.Process()
with p.oneshot():
    p.terminal()  # internally, this retrieves terminal, cpu_times and create time
    p.cpu_times()  # return the cached value
    p.create_time()  # return the cached value
```

Note: `Process.as_dict()` method would use this method implicitly.

=== EDITS AFTER COMMENTS BELOW ===
# Branch

https://github.com/giampaolo/psutil/compare/master...oneshot#files_bucket
# Benchmark scripts
- [bench_oneshot.py](https://github.com/giampaolo/psutil/blob/oneshot/scripts/internal/bench_oneshot.py) (quick, based on timeit module)
- [bench_oneshot_2.py](https://github.com/giampaolo/psutil/blob/oneshot/scripts/internal/bench_oneshot_2.py) (slower, more precise, using [perf](https://github.com/haypo/perf) module).
# Linux (+2.56x speedup)

```
$ python scripts/internal/bench_oneshot.py 
11 methods involved on platform 'linux2' (1000 iterations):
    cpu_percent
    cpu_times
    create_time
    gids
    name
    num_ctx_switches
    num_threads
    ppid
    status
    terminal
    uids
normal:  0.233 secs
oneshot: 0.091 secs
speedup: +2.56x
```
# Windows (+1.9x or +6.5x speedup)

user's process:

```
C:\Python27\python.exe scripts\internal\bench_oneshot.py
13 methods involved on platform 'win32' (1000 iterations, psutil 4.5.0)
    cpu_affinity
    cpu_percent
    cpu_times
    io_counters
    ionice
    memory_info
    memory_percentnice
    num_ctx_switches
    num_handles
    num_threads
    parent
    ppid
normal:  1.243 secs
onshot:  0.655 secs
speedup: +1.90x
```

other user's process:

```
C:\Python27\python.exe scripts\internal\bench_oneshot.py
11 methods involved on platform 'win32' (1000 iterations, psutil 4.4.2):
    cpu_percent
    cpu_times
    create_time
    io_counters
    memory_info
    memory_percent
    num_ctx_switches
    num_handles
    num_threads
    parent
    ppid
normal:  5.027 secs
onshot:  0.765 secs
speedup: +6.57x
```
# FreeBSD (+2.18x speedup)

```
$ python scripts/internal/bench_oneshot.py 
13 methods involved on platform 'freebsd10' (1000 iterations):
    cpu_percent
    cpu_times
    create_time
    gids
    io_counters
    memory_full_info
    memory_info
    memory_percent
    num_ctx_switches
    ppid
    status
    terminal
    uids
normal:  0.121 secs
oneshot: 0.056 secs
speedup: +2.18x
```
# OSX (+1.92x speedup)

```
$ python scripts/internal/bench_oneshot.py
13 methods involved on platform 'darwin' (1000 iterations):
    cpu_percent
    cpu_times
    create_time
    gids
    memory_info
    memory_percent
    name
    num_ctx_switches
    num_threads
    parent
    ppid
    terminal
    uids
    username
normal:  0.200 secs
onshot:  0.104 secs
speedup: +1.92x
```
# SunOS (+1.37x speedup)

```
$ python scripts/internal/bench_oneshot.py
12 methods involved on platform 'sunos5' (1000 iterations):
    cmdline
    create_time
    gids
    memory_full_info
    memory_info
    memory_percent
    name
    num_threads
    ppid
    status
    terminal
    uids
normal:  0.087 secs
oneshot: 0.064 secs
speedup: +1.37x
```

**Comment by nicolargo** [comment]
+1 for this enhancement request. It will be awesome for the Glances project.

**Comment by giampaolo** [comment]
I started working on this in a separate branch (https://github.com/giampaolo/psutil/compare/oneshot?expand=1) and completed the Linux implementation. The code below runs about twice as fast:

```
import psutil
import time

attrs = ['ppid', 'uids', 'gids', 'num_ctx_switches', 'num_threads', 'status',
         'name', 'cpu_times', 'terminal']
p = psutil.Process()
t = time.time()
for x in range(1000):
    for name in attrs:
        getattr(p, name)()
print(time.time() - t)
```

**Comment by nicolargo** [comment]
Any head up on this enhancement ?

**Comment by giampaolo** [comment]
I completed the linux implementation but I still have to benchmark it
properly. All other platform implementations are still missing. It's gonna
take a while.

**Comment by giampaolo** [comment]
Linux benchmark. With this I get a 2x speedup (twice as fast) if I involve all the "one shot" methods, meaning I am emulating the best possible scenario:

```
import psutil
import time


def doit(p):
    p.name()
    p.terminal()
    p.cpu_times()
    p.create_time()
    p.status()
    p.ppid()
    #
    p.num_ctx_switches()
    p.num_threads()
    p.uids()
    p.gids()


p = psutil.Process()

t = time.time()
for x in range(1000):
    doit(p)
print("normal:  %f" % (time.time() - t))

t = time.time()
for x in range(1000):
    with p.oneshot():
        doit(p)
print("oneshot: %f" % (time.time() - t))
```

Output:

```
normal:  0.189042
oneshot: 0.097632
```

**Comment by giampaolo** [comment]
FreeBSD impact deriving from getting multiple (14) info when only 1 is needed is negligible 0.46 secs vs. 0.43, so even when NOT using `oneshot()` and retrieving a single process info does not slow things down.

**Comment by giampaolo** [comment]
Linux speedup went from 1.9x to 2.6x after https://github.com/giampaolo/psutil/commit/f851be92d6e098a6e9355e93efb007711318f708.

**Comment by giampaolo** [comment]
BSD implementation is completed. On FreeBSD I get a +2.18 speedup.
I also added a benchmark script here: https://github.com/giampaolo/psutil/blob/oneshot/scripts/internal/bench_oneshot.py.

**Comment by nicolargo** [comment]
Nice! Are you also think that the new process method will speedup on
Windows Operating System?

**Comment by giampaolo** [comment]
Yes, this is intended for all OSes, even though Windows is probably gonna be the most difficult platform because it has less C APIs which can be used to retrieve multiple info in one shot.
For instance, BSD is the exact opposite, as in one shot you get a whole blob of stuff:
https://github.com/giampaolo/psutil/blob/50015c4073f741e89e29f67b74bded47a25a3a49/psutil/_psutil_bsd.c#L234
The only Windows C call I can think of that is being used basically all the time on Windows is `OpenProcess`.
We use a wrapper around it:
https://github.com/giampaolo/psutil/blob/50015c4073f741e89e29f67b74bded47a25a3a49/psutil/arch/windows/process_info.c#L21
...which is extensively used in the main C extension module:

```
grep psutil_handle  psutil/_psutil_windows.c | wc -l
16
```

What we can do is get the handle once, store it in Python (as an `int`), then pass it back to the C extension as an argument, and do this as long as we're in the `oneshot` context (then on `__exit__` we're gonna "`CloseHandle()` it"). The methods involved should be (at least): `cpu_times()`, `create_time()`, `memory_info()`, `nice()`, `io_counters()`, `cpu_affinity()`, `num_handles()` and `memory_maps()`. So yes, also on Windows there's a lot of space for speeding things up quite a bit.

**Comment by giampaolo** [comment]
Solaris implementation 630b40db322f2ca6a3de31b8679970ad3283cc52 +1.37x speedup.

**Comment by giampaolo** [comment]
It turns out storing `OpenProcess` handle in Python is slower than retrieving it in C every time. I experimented with this in here:
https://github.com/giampaolo/psutil/compare/oneshot...oneshot-win#files_bucket
...and I get a -1.5x slowdown. As such Windows is apparently the only platform which cannot take advantage of this.

**Comment by giampaolo** [comment]
OSX implemented as of https://github.com/giampaolo/psutil/commit/7b2a6b370d59f8c731aefb5f3c6e12d18e194ade and https://github.com/giampaolo/psutil/commit/cf21849a24a62ebecac13ba377bb90b243e06e0b. The speedup is 1.8x! Unless I'm missing something else, with this we should be done with all platforms.

**Comment by nicolargo** [comment]
Good news @giampaolo !

**Comment by giampaolo** [comment]
OSX: going from 1.8 to 1.9 speedup with https://github.com/giampaolo/psutil/commit/1e8cef9f124c881699853c26e79cd1e8a36bd03b.

**Comment by giampaolo** [comment]
It turns out the apparent slowdown occurring on Windows as per my previous message https://github.com/giampaolo/psutil/issues/799#issuecomment-238386787 was due to the benchmark script not being stable enough, so we're good also on Windows.
https://github.com/giampaolo/psutil/blob/7f51f0074b6d727a01fea0290ed0988dd51ad288/scripts/internal/bench_oneshot_2.py script relying on perf module shows a 1.2x speedup. 
With 
https://github.com/giampaolo/psutil/commit/c10a7aa12f94151ba094f184faaaeec84d2af38e and https://github.com/giampaolo/psutil/commit/3efb6bf9e5acf3cf62df2854fd910c637a7209f9 I went from 1.2x to 1.8x.

**Comment by giampaolo** [comment]
The interesting thing about Windows is that because some Process methods use a dual implementation (see #304) we can get a way bigger speedup for PIDs owned by other users, for which the first "fast" implementation raises AccessDenied.
On a high-privileged PID by using `oneshot()` I am now getting an awesome +6.3x speedup!

**Comment by giampaolo** [comment]
OK, this is now merged into master.

**Comment by suzaku** [comment]
Great job!
