### ISSUE TITLE
cannot build psutil on mingw32

### ISSUE THREAD

**Issue by doomsplayer** [giampaolo/psutil#808]
psutil's `/psutil/arch/windows/ntextapi.h` is not compatible with new version of mingw32's `winternl.h` which is included by `ntextapi.h`, and there are lots of redeclaration errors and incompatible errors when building psutil on mingw32.

[error log](https://gist.github.com/ogrisel/e08d59f9c8ac500855bc)

**Comment by giampaolo** [comment]
mingw support has been removed long ago because it was unpractical to maintain and 64 bit version didn't work. Unfortunately you'll need Visual Studio (see https://github.com/giampaolo/psutil/blob/master/INSTALL.rst#windows).
