### ISSUE TITLE
Implement rlimit() on BSD

### ISSUE THREAD

**Issue by NicolasLM** [giampaolo/psutil#809]
In most cases a process running out of file descriptors is a sign that the software does not behave correctly. Psutil currently gives the number of fds opened by a process, but not how many can it open.

On Linux this information is available through `/proc/<pid>/limits`.

This metric per process would be complementary of system wide limits described in #720.

**Comment by giampaolo** [comment]
Actually that info is already retrievable via stdlib resource module:

```
>>> import resource
>>> resource.getrlimit(resource.RLIMIT_NOFILE)
(1024, 4096)
```

Doing the same via /proc/pid/limits would add the ability to do it for all processes in case the default value gets modified by a specific process, but I'm not sure how much that's valuable considering it would be linux only.

**Comment by NicolasLM** [comment]
I ended implementing something like https://github.com/NicolasLM/sauna/commit/f9a7a5240242882e32fdd5764910679afe621bc7#diff-4cdd796dc1ec5ac72502aab351c123a2R86

It would be surprising if other OSes than Linux do not provide a way to fetch this information as well.

**Comment by giampaolo** [comment]
Most (all?) UNIX systems provide a way to know the number of **default** maximum fds per-process and https://github.com/giampaolo/psutil/issues/720 is meant to expose that information. `/proc/<pid>/limits` differs in that it provides the updated information in case the user changes the default value, and that can be done for **all process**, not only `os.getpid()`, and AFAIK that is only possible on Linux (for all processes). Other UNIX flavors are able to do the same only for the current process (via `resource` module).

**Comment by NicolasLM** [comment]
I'm pretty sure other platforms provide this information as well, for instance on freebsd `procstat -l <pid>` gives the rlimits of the process of your choice.

**Comment by giampaolo** [comment]
What other platforms are you talking about? Are you sure it's update info and not the default system setting info being reported insted?

**Comment by NicolasLM** [comment]
I just tried on freebsd, indeed it is possible to fetch the actual limits of a process:

```
$ procstat -l 841
  PID COMM             RLIMIT                  SOFT             HARD      
  841 python2.7        openfiles              14049            14049
```

```
>>> import resource 
>>> resource.setrlimit(resource.RLIMIT_NOFILE, (512, 1024))
```

```
$ procstat -l 841
  PID COMM             RLIMIT                  SOFT             HARD         
  841 python2.7        openfiles                512             1024     
```

**Comment by giampaolo** [comment]
Getting back to this. Actually I totally forgot it is already possible to do this on Linux:
https://pythonhosted.org/psutil/#psutil.Process.rlimit
Doing the same on FreeBSD though would certainly be welcome though. I will try to `strace` `procstat` command and try to see what it relies on internally. Linux relies on "man 2 prlimit":
http://linux.die.net/man/2/prlimit
...and that looks like it's Linux only, hence why I am not sure how FreeBSD (or any other UNIX variant) provides this.

**Comment by giampaolo** [comment]
@glebius just in case you want to give it a try. ;-)
