### ISSUE TITLE
Installation documentation should mention setup instructions for Python 3

### ISSUE THREAD

**Issue by danielmitterdorfer** [giampaolo/psutil#814]
The [installation instructions](https://github.com/giampaolo/psutil/blob/master/INSTALL.rst) mention that users need to install `python-devel` / `python-dev` on Linux. This is correct for Python 2 but it would be nice to also document that for Python 3, `python3-devel` / `python3-dev` is needed instead.

**Comment by giampaolo** [comment]
Fixed.
