### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by b3mb4m** [giampaolo/psutil#821]
`import psutil`

- Traceback (most recent call last):
- File "C:\Documents and Settings\r00t\Desktop\qwee.py", line 1, in <module>
-     import psutil
-   File "C:\Python27\lib\site-packages\psutil\__init__.py", line 124, in <module>
-     from . import _pswindows as _psplatform
-   File "C:\Python27\lib\site-packages\psutil\_pswindows.py", line 15, in <module>
-     from . import _psutil_windows as cext
-    ImportError : DLL load failed

Tested on : XP SP3, python 2.x & 3.x

Problem is about me ? ..

**Comment by giampaolo** [comment]
It's likely you're using an old pip version. `pip install -U pip` should fix this issue. Closing as a duplicate of #810.
