### ISSUE TITLE
virtual_memory() on NetBSD

### ISSUE THREAD

**Issue by FarhansCode** [giampaolo/psutil#823]
virtual_memory() opened the /proc/meminfo file as a binary. As such, each line was a binary, but lines 135 and 137 were checking against a string type. This caused str.startswith() to raise a TypeError and fail.

**Comment by giampaolo** [comment]
Please add something like "#XXX [NetBSD]: virtual_memory() raises TypeError on Python 3." in HISTORY.rst

**Comment by FarhansCode** [comment]
This item was resolved with commit e98db38f97c542042ab6edb662512c4092085562. Closing ticket.
