### ISSUE TITLE
Makefile setup-dev-env recipe import errors on Python 3.x

### ISSUE THREAD

**Issue by tijko** [giampaolo/psutil#827]
When running `make setup-dev-env` on Python 3.x the recipe attempts to import `urllib2`, which throws a `ImportError` on Python 3.x.

**Comment by giampaolo** [comment]
Please paste the whole output.

On Wed, May 25, 2016 at 5:37 PM, Timmy Konick <notifications@github.com>
wrote:

> When running make setup-dev-env on Python 3.x the recipe attempts to
> import urllib2, which throws a ImportError on Python 3.x.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/giampaolo/psutil/issues/827>
>



-- 
Giampaolo - http://grodola.blogspot.com

**Comment by tijko** [comment]
Traceback:

```
ln -sf ../../.git-pre-commit .git/hooks/pre-commit
chmod +x .git/hooks/pre-commit
python -c  "import urllib2, ssl; \
                        context = ssl._create_unverified_context() if hasattr(ssl, '_create_unverified_context') else None; \
                        kw = dict(context=context) if context else {}; \
                        r = urllib2.urlopen('https://bootstrap.pypa.io/get-pip.py', **kw); \
                        open('/tmp/get-pip.py', 'w').write(r.read());"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'urllib2'
Makefile:38: recipe for target 'setup-dev-env' failed
make: *** [setup-dev-env] Error 1
```

**Comment by tijko** [comment]
Is any more information needed regarding this issue?
