### ISSUE TITLE
Catch memory usage until process will be terminated

### ISSUE THREAD

**Issue by isaiasfrederick** [giampaolo/psutil#830]
Hello!

I'm using psutil for measure memory size in my programa where i'll insert a lot of workloads with different sizes. i cannot set a timeout cause i don't know the time and max memory necessary to process that workloads. I just wanna catch the max memory usage and stop only when the PID be released.

Thanks.

**Comment by giampaolo** [comment]
Do that in a loop calling `memory_info` and when it raises `NoSuchProcess` exit the loop:

```
p = psutil.Process(SOME_PID)
while True
     try:
           print p.memory_info()
     except NoSuchProcess:
           break
     else:
            time.sleep(1)
```
