### ISSUE TITLE
Memory Leak On Other Computers

### ISSUE THREAD

**Issue by root426** [giampaolo/psutil#848]
Hi, i have coded server-client application on python 3.4
i used cx_freeze for distrubate. When i open client app on other computer it will graudally eat memory
is this a bug or something ?

**Comment by root426** [comment]
actually i found solution.

theory I : if you use psutil.net_io_counters() alone, the garbage collector wont collect rest of the information.
exp.
`a=psutil.net_io_counters(pernic=True)
time.sleep(1)
b=psutil.net_io_counters(pernic=True)
downspeed = a[1]-b[1]
`
if i write the code above there will be memory leak

`    a1 = psutil.net_io_counters(pernic=False).bytes_recv
    b1 = psutil.net_io_counters(pernic=False).bytes_sent
    time.sleep(1)
    a2 = psutil.net_io_counters(pernic=False).bytes_recv
    b2 = psutil.net_io_counters(pernic=False).bytes_sent

downspeed = a2-a1
`
if i write like this then there will be no momory leak :)

**Comment by giampaolo** [comment]
I am not sure what you're talking about. What do you mean by memory leak? You're using a NET IO related API so that's why I'm not sure what you mean by that.

**Comment by root426** [comment]
i mean my program's ram usage always increase. like at start 7.2 MB after 10 min 30.3 MB and it's not stopping.
