### ISSUE TITLE
Checks on virtual_memory() and swap_memory() values

### ISSUE THREAD

**Issue by dmedri** [giampaolo/psutil#862]
On Linux (fedora23, i686), running psutil.cpu_memory() and `free` (on Py3), the results are wrong:
```
>>> psutil.virtual_memory()
svmem(total=2103410688, available=1315647488, percent=37.5, used=2044448768,
free=58961920, active=958812160, inactive=962322432, buffers=77824, cached=1256607744)

>>> psutil.swap_memory()
sswap(total=2148528128, used=48975872, free=2099552256, percent=2.3, sin=49152,
sout=48984064)
```
in console, results are differents:
```
> free
              total        used        free      shared  buff/cache   available
Mem:        2054112      682720       55752      190224     1315640     1132484
Swap:       2098172       47828     2050344
```
Let me know how can I run some tests to help you.

**Comment by giampaolo** [comment]
Some values of `free` and `psutil.virtual_memory()` refer to different things and cannot be compared.
E.g. `used` and `available` are calculated differently.
Secondly, psutil returns results in bytes. In order for free to do the same you should do ` free -b`.

**Comment by dmedri** [comment]
Ok, second try:
```
>>> psutil.virtual_memory()
svmem(total=2103410688, available=1310154752, percent=37.7, used=2012487680,
free=90923008, active=908922880, inactive=971247616, buffers=28672, cached=1219203072)

>>> psutil.swap_memory()
sswap(total=2148528128, used=38989824, free=2109538304, percent=1.8, sin=217088,
sout=39026688)
```
and `free -b` results:

```
$ free -b
              total        used        free      shared  buff/cache   available
Mem:     2103410688   703737856    76132352   182116352  1323540480  1166770176
Swap:    2148528128    38989824  2109538304
```
Please, sync your method with the 'free' developers for a final resolution.

**Comment by giampaolo** [comment]
Update about this: I update Linux tests and with Ubuntu 16.04 `free` column of "free" cmdline utility matches psutil. I suspect there are "free" versions where this is different, see:
https://github.com/giampaolo/psutil/issues/685#issuecomment-202914057
Anyway, I checked the output of `vmstat -s` and the two values (vmstat and psutil) matches so I think "free" value is fine.

What is not fine is "used" value.
Both vmstat and free CLI tools report different numbers but I'm not sure how they calculate that. I'll have to take a peek at the source code.

**Comment by giampaolo** [comment]
Fixed in https://github.com/giampaolo/psutil/issues/887
