### ISSUE TITLE
Process.memory_maps() does not return addresses above 32 bits on 64 bit builds

### ISSUE THREAD

**Issue by jhumble** [giampaolo/psutil#863]
Using the distributed x64 version of psutil and running against a 64 bit process with memory regions higher than 0xffffffff, all bits higher than 32 are truncated. 

Example:
Running a 64 bit process under x64dbg, I have msctf.dll mapped in at  0x000007FEFF020000.

If I get the memory map for this process using memory_map, the entry corresponding to msctf.dll is shown with base address 0xFF020000, cutting off the highest 32 bits of the address.

**Comment by giampaolo** [comment]
What platform are we talking about? Windows?

**Comment by jhumble** [comment]
Sorry about that, don't know how I left that off.  Yes, Windows. I'm submitting a pull request now which has fixed the issue for me.

**Comment by giampaolo** [comment]
Fine, looking forward to it.

**Comment by jhumble** [comment]
Here's the pull request: https://github.com/giampaolo/psutil/pull/864

**Comment by giampaolo** [comment]
Cool. I added comments to it.

**Comment by jhumble** [comment]
Closed out #864 since I messed it all up and managed to base it off some branch other than master. 

This new one should be much cleaner: https://github.com/giampaolo/psutil/pull/865
