### ISSUE TITLE
UnicodeDecodeError    psutil.win_service_iter()

### ISSUE THREAD

**Issue by FabioBaroni** [giampaolo/psutil#866]
I have this function for retrieving and displaying info about all the Windows services.

```
def enum_service():
    for service in psutil.win_service_iter():
        sinfo = service.as_dict()
        print("[*] Name: {} Display name: {} Status: {} Type: {} Path: ".format(sinfo["name"], sinfo["display_name"], sinfo["status"], sinfo["start_type"], sinfo["binpath"]))
```
I get an error at line 342 of psutil\\_pswindows.py, in win_service_iter
**for name, display_name in cext.winservice_enumerate():
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 7: invalid continuation byte**

It seems that one or more values aren't encoded in utf-8 so it throws an error.
Is it a known issue? Can it be fixed?

**Comment by giampaolo** [comment]
Does the error occur on `print()`? If so then it's cmd.exe's fault, not psutil's. 
You should be able to print that by `repr()`ing it first.

**Comment by FabioBaroni** [comment]
I'm not sure I'm doing right but I tried this:

```
def enum_service():
    for service in psutil.win_service_iter():
        sinfo = service.as_dict()
        print("[*] Name: {} Display name: {} Status: {} Type: {} Path: ".format(repr(sinfo["name"]), repr(sinfo["display_name"]), repr(sinfo["status"]), repr(sinfo["start_type"]), repr(sinfo["binpath"])))
```

I simply added repr() to each item that I want to display but I get the same error as above.
Since it's just a few lines of code, I'd be grateful if you could run it on your pc and try to debug it in order to rule out any issue on psutil side.

**Comment by giampaolo** [comment]
If you remove the `print()` and only do `service.as_dict()` do you still get the unicode error?
If you do then it's a psutil issue, if you don't then it's the cmd.exe encoding which is not able to print that unicode string.

**Comment by FabioBaroni** [comment]
I tried again with the following code:

```
import psutil

for service in psutil.win_service_iter():
    service.as_dict()
```
I get the same error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\Fabio\AppData\Local\Programs\Python\Python35\lib\site-packages\psutil\_pswindows.py", line 342, in win_service_iter
    for name, display_name in cext.winservice_enumerate():
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 7: invalid continuation byte
```
I'm testing this code on Windows 10 with python 3.5.2 . I tried to run the script from the IDE (I'm using PyCharm anyway it shouldn't be important mentioning that) and also using the Python Console. The same error is displayed.

**Comment by giampaolo** [comment]
OK, then it's a psutil problem.

**Comment by giampaolo** [comment]
OK I should have fixed it. Can you compile from sources and verify it is fixed? If not I can attach a .exe pre-compiled version for you to test (Python version? 32 or 64 bit?).
