### ISSUE TITLE
Raised psutil.TimeoutExpired using wrong timeout unit - seconds vs. milliseconds

### ISSUE THREAD

**Issue by manuel-koch** [giampaolo/psutil#869]
Using
`Process.wait(timeout=0.1)`
with a process that is still running during the timeout duration results in exception being thrown with wrong text, e.g. the timeout should be noted as "milliseconds" and not "seconds".

`File "C:\Python34_64\lib\site-packages\psutil\_pswindows.py", line 665, in wait
    raise TimeoutExpired(timeout, self.pid, self._name)
psutil.TimeoutExpired: psutil.TimeoutExpired timeout after 100 seconds (pid=72124, name='cmd.exe')
`

**Comment by giampaolo** [comment]
Fixed, thanks for the report.
