### ISSUE TITLE
Install XcodeTools first

### ISSUE THREAD

**Issue by 2achary** [giampaolo/psutil#873]
For OS X 10.11.6

I'm following your install instructions for Mac and it says to install XcodeTools first then pip install. However there is nothing at the given link called XcodeTools. There is a package from 2006 call "Xcode Tools" but I get a warning:

> This package is incompatible with this version of OS X and may fail to install.

What is the name of the tools package I need?

**Comment by giampaolo** [comment]
I changed "XcodeTools" to "Xcode", which is the correct name of the download(s).
