### ISSUE TITLE
Call Method When New Process Started/Ended

### ISSUE THREAD

**Issue by developeralp** [giampaolo/psutil#899]
Hello all,

How can i detect to new process start ? 

i.e : 

-my application running.
-firefox.exe started 
-my.application prints a new line "firefox.exe started !"
-firefox.exe closed
-my.application prints another new line "firefox.exe closed."

I was detecting a process start with that code in c# ;

`new ManagementEventWatcher("SELECT * FROM Win32_ProcessStartTrace");`

How can i do that in python with psutil ?

**Comment by giampaolo** [comment]
You could iterate over all processes, looking for process name:

```
import psutil

PROCNAME = "firefox.exe"

for proc in psutil.process_iter():
    if proc.name() == PROCNAME:
         print "found"
```

To check when it's closed you could call `is_running` ever X secs:

```
while 1:
        if not proc.is_running():
              print "it's gone"
              break
        time.sleep(1)
```
