### ISSUE TITLE
BSD: disk_partitions(all=False) always return an empty list

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#906]
On BSD systems there is no difference between `df` and `df -a`. The same partitions are always returned. As such psutil should ignore the `all` argument passed to `disk_partitions` as there simply is no way to distinguish between physical partitions and "others". We'll just always return them all.

**Comment by Loney1** [comment]
Hi shirou, I am a student.  I have one question is that can I get the disk SN in gopsutil. I can't find this function in the source code
