### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by hujiaweibujidao** [giampaolo/psutil#913]
Hi all, thank you for making this wonderful tool! 

Since psutil supports Windows, Linux, OS X, etc. is there any plan to make it work for Android device? Or how should I start if I wanna make it support for Android platform?

Thank you for all.

**Comment by hujiaweibujidao** [comment]
Maybe we don't support all the functionalities of psutil for Android, just support the main features of psutil with the help of adb command, is it possible, right?

**Comment by giampaolo** [comment]
This is tracked in #843 but I won't have time to look into it any time soon.
