### ISSUE TITLE
Can't get environment for 64-bit processes on Windows 10

### ISSUE THREAD

**Issue by rajdevsharma** [giampaolo/psutil#915]
I am trying to use psutil on Windows 10, with 32-bit Python.

If I try to get the environment of any 64-bit process, it raises an error. It looks like the problem is that the NtWow64QueryVirtualMemory64 function no longer available from ntdll.dll.

Here is an example of trying to grab an explorer.exe process (which is 64-bit), and then calling environ() on it to get the environment.

```
>>> [ps for ps in psutil.process_iter() if ps.name() == 'explorer.exe'][0].environ()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\temp\testpsutil\venv\lib\site-packages\psutil\__init__.py", line 772, in environ
    return self._proc.environ()
  File "c:\temp\testpsutil\venv\lib\site-packages\psutil\_pswindows.py", line 536, in wrapper
    return fun(self, *args, **kwargs)
  File "c:\temp\testpsutil\venv\lib\site-packages\psutil\_pswindows.py", line 597, in environ
    return parse_environ_block(cext.proc_environ(self.pid))
NotImplementedError: NtWow64QueryVirtualMemory64 missing
```

Any help or insight would be greatly appreciated!

**Comment by giampaolo** [comment]
@fbenkstein any idea dude?

**Comment by fbenkstein** [comment]
There's nothing that can be done on the psutil side of things as far as I can tell.  If Microsoft releases an update with NtWow64QueryVirtualMemory64 exposed again it will work again - other people have complained about that.  As a workaround I suggest using 64bit Python which should be able to query both 32bit and 64bit processes.

**Comment by rajdevsharma** [comment]
Thank you so much both of you for the responses, I really appreciate your taking the time to help me out with this! I'll see if I am able to switch to Python 32-bit or if not then maybe find some other workaround.

Thanks again!

**Comment by giampaolo** [comment]
@fbenkstein sorry to bother you but there's a test which has been failing for a long time and which bothers me. It fails on my win 10 (not on appveyor for some reason) and **only with python 2.7**. 27-64 and Python 3 (e.g. 35, 35-64) are all fine so I'm really not sure what to make of it. The failure:

```
======================================================================
ERROR: psutil.tests.test_windows.RemoteProcessTestCase.test_environ_64
----------------------------------------------------------------------
Traceback (most recent call last):
  File "psutil\tests\test_windows.py", line 716, in test_environ_64
    e = p.environ()
  File "psutil\__init__.py", line 872, in environ
    return self._proc.environ()
  File "psutil\_pswindows.py", line 620, in wrapper
    return fun(self, *args, **kwargs)
  File "psutil\_pswindows.py", line 698, in environ
    ustr = cext.proc_environ(self.pid)
NotImplementedError: NtWow64QueryVirtualMemory64 missing
```

The error originates from here: https://github.com/giampaolo/psutil/blob/c2702117881eaff7bdd3dc3357db11107458e4de/psutil/arch/windows/process_info.c#L319-L330

So for some reason on python 2.7 32 bit only "ntdll.dll" has no `NtWow64QueryVirtualMemory64` which doesn't make sense to me. Any idea?

**Comment by fbenkstein** [comment]
@giampaolo Maybe there's a separate ntdll.dll that's being pulled for that particular version of Python?
