### ISSUE TITLE
Feature Request: Named tuples for result of laddr in net_connections()

### ISSUE THREAD

**Issue by guettli** [giampaolo/psutil#928]
Up to now you need ugly index numbers to access the port in laddr tuple.
Example:

`('10.0.0.1', 48776)
`
It would be nice to have a named tuple.

Is there a good reason against it?

**Comment by giampaolo** [comment]
Sounds reasonable.

**Comment by giampaolo** [comment]
Actually hang on: addresses my either been a tuple in case of AF_INET sockets (TCP/UDP) or a string in case of AF_INET6 (IPv6) sockets, so that's why back then I opted for a raw tuple.

**Comment by guettli** [comment]
That is new to me. I have not worked with ipv6 before. Is there no integer port number?

**Comment by giampaolo** [comment]
I'm sorry, I meant AF_UNIX sockets, not IPv6. With those, the address is a string, not a tuple.

**Comment by giampaolo** [comment]
I think I'm gonna reject this for consistency with `socket.getsockname()` and `socket.getpeername()` which both return a raw tuple.

**Comment by guettli** [comment]
Yes, you are right. Symmetry would be nice. 

I think socket.getsockname() should return a named tuple. I asked at the python-ideas mailing list.

But nobody seems to care: https://mail.python.org/pipermail/python-ideas/2017-June/046028.html

Up to now there is no reply.

Maybe this is the wrong mailing list ...

**Comment by guettli** [comment]
.... Great, Guido V R is open for pull requests if someone wants to implement named tuples for the socket library. There were +1 votes, too (and some concern about python startup time).

See https://mail.python.org/pipermail/python-ideas/2017-June/046086.html

I stopped coding in spare time, since my children are more important at the moment .. if some wants to try it ... go ahead and implement named tuples for the socket standard library - would be great.

**Comment by giampaolo** [comment]
OK this is now fixed.
