### ISSUE TITLE
No module named psutil

### ISSUE THREAD

**Issue by lookcat** [giampaolo/psutil#943]
I using the tool of pip that innstall the psutil on the centOS6.5. I using the python2.7.3 and the django1.9.6.
I run the project , I found the error . but I using the python shell, It' true. 
so, I make a test, use the os to run the django's project with different host's port (python manage.py runserver 127.0.0.1:8001  or 127.0.0.1:8002), the one is ok, the other is error.
can you give me some advice?  Help me .

                                                                                                                    Thanks

**Comment by giampaolo** [comment]
I didn't understand much of what you said but it looks like an installation problem.
Perhaps you use django via a virtualenv which has psutil installed, but then when you switch to plain python interpreter (!= virtualenv) psutil is not installed.
Anyway, it's too hard to tell given the information you provided.
