### ISSUE TITLE
psutil.net_if_stats return operation not permitted

### ISSUE THREAD

**Issue by zackshen** [giampaolo/psutil#945]
@bbinet 
i have two operation system, one is CentOS6 release 6.7 Final, another is CentOS6 release 6.8 Final
CentOS6.7 kernel is `2.6.32-573.el6.x86_64` in vmware
CentOS6.8 kernel is `2.6.32-642.11.1.el6.x86_64` in vagrant
 
i install `psutil==5.0.0` and add a user named `test01` in default group `test01`. 
then switch to user `test01` , go into python shell,  call `psutil.net_if_stats()`, 

CentOS6.7 raise 
``` shell
duplex, speed = cext.net_if_duplex_speed(name)
OSError: [Errno 1] Operation not permitted
```

CentOS6.8 passed

error happened when call `ret = ioctl(sock, SIOCETHTOOL, &ifr);` 
strace: 
`ioctl(3, SIOCETHTOOL, 0x7ffcc8a19840)   = -1 EPERM (Operation not permitted)`

it's so weired, why ?

**Comment by giampaolo** [comment]
Well, it's that particular centos version which does that. There is nothing you can do except elevate privileges of the python process.
