### ISSUE TITLE
psutil: pip will not install it on windows 10, 64bit, python 3.6

### ISSUE THREAD

**Issue by ddmee** [giampaolo/psutil#949]
Using python 3.6 (see from the README on Git that psutil is compatible up to python 3.5. Is this still true?)

Failing to install with pip. Perhaps the solution is obvious (to install visual c++)? 

[I saw from a previous issue that is now closed](https://github.com/giampaolo/psutil/issues/882) there might have been an issue with the upload made to PIP because no wheels file was included. Could it be the same here again?

Here's the output from the failed pip install.

```shell 
PS C:\Users\USER\DIR> pip install psutil
Collecting psutil
  Using cached psutil-5.0.1.tar.gz
Building wheels for collected packages: psutil
  Running setup.py bdist_wheel for psutil ... error
  Complete output from command c:\users\USER\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\USER\\AppData\\Local\\Temp\\pip-build-w0e9_g3z\\psutil\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\dmee\AppData\Local\Temp\tmpy12ws8ecpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.6
  creating build\lib.win32-3.6\psutil
  copying psutil\_common.py -> build\lib.win32-3.6\psutil
  copying psutil\_compat.py -> build\lib.win32-3.6\psutil
  copying psutil\_psbsd.py -> build\lib.win32-3.6\psutil
  copying psutil\_pslinux.py -> build\lib.win32-3.6\psutil
  copying psutil\_psosx.py -> build\lib.win32-3.6\psutil
  copying psutil\_psposix.py -> build\lib.win32-3.6\psutil
  copying psutil\_pssunos.py -> build\lib.win32-3.6\psutil
  copying psutil\_pswindows.py -> build\lib.win32-3.6\psutil
  copying psutil\__init__.py -> build\lib.win32-3.6\psutil
  creating build\lib.win32-3.6\psutil\tests
  copying psutil\tests\runner.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_bsd.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_linux.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_memory_leaks.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_misc.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_osx.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_posix.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_process.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_sunos.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_system.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_windows.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\__init__.py -> build\lib.win32-3.6\psutil\tests
  running build_ext
  building 'psutil._psutil_windows' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

  ----------------------------------------
  Failed building wheel for psutil
  Running setup.py clean for psutil
Failed to build psutil
Installing collected packages: psutil
  Running setup.py install for psutil ... error
    Complete output from command c:\users\USER\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\dmee\\AppData\\Local\\Temp\\pip-build-w0e9_g3z\\psutil\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\USER\AppData\Local\Temp\pip-437r43sy-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\psutil
    copying psutil\_common.py -> build\lib.win32-3.6\psutil
    copying psutil\_compat.py -> build\lib.win32-3.6\psutil
    copying psutil\_psbsd.py -> build\lib.win32-3.6\psutil
    copying psutil\_pslinux.py -> build\lib.win32-3.6\psutil
    copying psutil\_psosx.py -> build\lib.win32-3.6\psutil
    copying psutil\_psposix.py -> build\lib.win32-3.6\psutil
    copying psutil\_pssunos.py -> build\lib.win32-3.6\psutil
    copying psutil\_pswindows.py -> build\lib.win32-3.6\psutil
    copying psutil\__init__.py -> build\lib.win32-3.6\psutil
    creating build\lib.win32-3.6\psutil\tests
    copying psutil\tests\runner.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_bsd.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_linux.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_memory_leaks.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_misc.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_osx.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_posix.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_process.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_sunos.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_system.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_windows.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\__init__.py -> build\lib.win32-3.6\psutil\tests
    running build_ext
    building 'psutil._psutil_windows' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
```

**Comment by giampaolo** [comment]
I've just upload exe and wheel files so this issue should be fixed now.

**Comment by ddmee** [comment]
Thanks, that's great.

Cheers.

**Comment by alterego25** [comment]
import os
import sys

popisdirektorija=list()
fajl=open('popis.lst','w')
imedirektorija='.'
ekstenzija=sys.argv[1]
fajl.writelines('Velicina za ekstenziju: '+ekstenzija+'\n')
for datoteka in os.listdir(imedirektorija):
   if datoteka[datoteka.rfind('.')+1:]==ekstenzija:
       fajl.writelines(datoteka+' '+str(os.path.getsize(datoteka))+'\n')
fajl.close()





import webbrowser

webbrowser.open('https://www.algebra.hr/naslovnica/kontakt/')



yum install python-devel
yum install epel-release
yum install python-pip
pip install psutil

import psutil
import os

a=psutil.pids()
b=os.getlogin()

for pid in a:
   process=psutil.Process(pid)
   if process.username() == b:
       print (process.name()+' '+str(process.cpu_percent()))


yum install tkinter *

from Tkinter import *
import random
import string

r=Tk()
r.geometry("200x200")

r.title('GUI')

def pritisak():
   niz=string.ascii_letters
   znak.config(text=niz[random.randint(1,len(niz))])

def pritisak1():
   znak2.config(text=str(random.randint(10,99)))

tekst=' '

znak=Label(r)
znak2=Label(r)
gumb=Button(r)
gumb2=Button(r)

znak.config(width=20)
znak.config(text='prazno')
znak2.config(width=20)
znak2.config(text='prazno')
gumb.config(text="Pritisni za nasumicni znak")
gumb.config(command=pritisak)
gumb2.config(text="Pritisni za nasumicni broj")
gumb2.config(command=pritisak1)

znak.grid(row=0)
znak2.grid(row=0,column=1)
gumb.grid(row=1)
gumb2.grid(row=1,column=1)

mainloop()


import os
pids = [pid for pid in os.listdir('/proc') if pid.isdigit()]

for pid in pids:
try:
print open(os.path.join('/proc', pid, 'cmdline'), 'rb').read()
except IOError:
continue

**Comment by YashThenuan** [comment]
Complete output from command c:\users\admin\documents\github\ct-workflows\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-xi0lxpdn\\psutil\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Admin\AppData\Local\Temp\pip-wheel-0_opornd --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.6
  creating build\lib.win32-3.6\psutil
  copying psutil\_common.py -> build\lib.win32-3.6\psutil
  copying psutil\_compat.py -> build\lib.win32-3.6\psutil
  copying psutil\_psbsd.py -> build\lib.win32-3.6\psutil
  copying psutil\_pslinux.py -> build\lib.win32-3.6\psutil
  copying psutil\_psosx.py -> build\lib.win32-3.6\psutil
  copying psutil\_psposix.py -> build\lib.win32-3.6\psutil
  copying psutil\_pssunos.py -> build\lib.win32-3.6\psutil
  copying psutil\_pswindows.py -> build\lib.win32-3.6\psutil
  copying psutil\__init__.py -> build\lib.win32-3.6\psutil
  creating build\lib.win32-3.6\psutil\tests
  copying psutil\tests\runner.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_bsd.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_linux.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_memory_leaks.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_misc.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_osx.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_posix.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_process.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_sunos.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_system.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\test_windows.py -> build\lib.win32-3.6\psutil\tests
  copying psutil\tests\__init__.py -> build\lib.win32-3.6\psutil\tests
  running build_ext
  building 'psutil._psutil_windows' extension
  creating build\temp.win32-3.6
  creating build\temp.win32-3.6\Release
  creating build\temp.win32-3.6\Release\psutil
  creating build\temp.win32-3.6\Release\psutil\arch
  creating build\temp.win32-3.6\Release\psutil\arch\windows
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPSUTIL_WINDOWS=1 -DPSUTIL_VERSION=442 -D_WIN32_WINNT=0x01000 -D_AVAIL_WINVER_=0x01000 -D_CRT_SECURE_NO_WARNINGS -DPSAPI_VERSION=1 -Ic:\users\admin\appdata\local\programs\python\python36-32\include -Ic:\users\admin\appdata\local\programs\python\python36-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tcpsutil/_psutil_windows.c /Fobuild\temp.win32-3.6\Release\psutil/_psutil_windows.obj
  _psutil_windows.c
  c:\users\admin\appdata\local\temp\pip-install-xi0lxpdn\psutil\psutil\arch\windows\ntextapi.h(166): error C2011: '_CLIENT_ID': 'struct' type redefinition
  C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\winternl.h(80): note: see declaration of '_CLIENT_ID'
  c:\users\admin\appdata\local\temp\pip-install-xi0lxpdn\psutil\psutil\arch\windows\ntextapi.h(172): error C2011: '_SYSTEM_THREAD_INFORMATION': 'struct' type redefinition
  C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\winternl.h(286): note: see declaration of '_SYSTEM_THREAD_INFORMATION'
  c:\users\admin\appdata\local\temp\pip-install-xi0lxpdn\psutil\psutil\arch/windows/inet_ntop.h(10): warning C4028: formal parameter 2 different from declaration
  psutil/_psutil_windows.c(246): warning C4244: '=': conversion from 'float' to 'ULONGLONG', possible loss of data
  psutil/_psutil_windows.c(2810): error C2039: 'ContextSwitches': is not a member of '_SYSTEM_THREAD_INFORMATION'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\winternl.h(286): note: see declaration of '_SYSTEM_THREAD_INFORMATION'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for psutil
  Running setup.py clean for psutil
Failed to build psutil
Installing collected packages: psutil, Unidecode, python-slugify, python-nvd3, pycparser, cffi, greenlet, gevent, enum-compat, eventlet, billiard, vine, amqp, kombu, celery, babel, tornado, flower, asn1crypto, cryptography, mysqlclient, bcrypt, Flask-Bcrypt, psycopg2, filechunkio, boto, apache-airflow, jmespath, botocore, s3transfer, boto3, protobuf, cachetools, browscap-python, msgpack, decorator, ipython-genutils, traitlets, backcall, pickleshare, parso, jedi, simplegeneric, wcwidth, prompt-toolkit, colorama, ipython, ipdb
  Found existing installation: psutil 5.4.6
    Uninstalling psutil-5.4.6:
      Successfully uninstalled psutil-5.4.6
  Running setup.py install for psutil ... error
    Complete output from command c:\users\admin\documents\github\ct-workflows\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-xi0lxpdn\\psutil\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Admin\AppData\Local\Temp\pip-record-znq068jg\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\admin\documents\github\ct-workflows\venv\include\site\python3.6\psutil:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\psutil
    copying psutil\_common.py -> build\lib.win32-3.6\psutil
    copying psutil\_compat.py -> build\lib.win32-3.6\psutil
    copying psutil\_psbsd.py -> build\lib.win32-3.6\psutil
    copying psutil\_pslinux.py -> build\lib.win32-3.6\psutil
    copying psutil\_psosx.py -> build\lib.win32-3.6\psutil
    copying psutil\_psposix.py -> build\lib.win32-3.6\psutil
    copying psutil\_pssunos.py -> build\lib.win32-3.6\psutil
    copying psutil\_pswindows.py -> build\lib.win32-3.6\psutil
    copying psutil\__init__.py -> build\lib.win32-3.6\psutil
    creating build\lib.win32-3.6\psutil\tests
    copying psutil\tests\runner.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_bsd.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_linux.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_memory_leaks.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_misc.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_osx.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_posix.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_process.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_sunos.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_system.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\test_windows.py -> build\lib.win32-3.6\psutil\tests
    copying psutil\tests\__init__.py -> build\lib.win32-3.6\psutil\tests
    running build_ext
    building 'psutil._psutil_windows' extension
    creating build\temp.win32-3.6
    creating build\temp.win32-3.6\Release
    creating build\temp.win32-3.6\Release\psutil
    creating build\temp.win32-3.6\Release\psutil\arch
    creating build\temp.win32-3.6\Release\psutil\arch\windows
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPSUTIL_WINDOWS=1 -DPSUTIL_VERSION=442 -D_WIN32_WINNT=0x01000 -D_AVAIL_WINVER_=0x01000 -D_CRT_SECURE_NO_WARNINGS -DPSAPI_VERSION=1 -Ic:\users\admin\appdata\local\programs\python\python36-32\include -Ic:\users\admin\appdata\local\programs\python\python36-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tcpsutil/_psutil_windows.c /Fobuild\temp.win32-3.6\Release\psutil/_psutil_windows.obj
    _psutil_windows.c
    c:\users\admin\appdata\local\temp\pip-install-xi0lxpdn\psutil\psutil\arch\windows\ntextapi.h(166): error C2011: '_CLIENT_ID': 'struct' type redefinition
    C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\winternl.h(80): note: see declaration of '_CLIENT_ID'
    c:\users\admin\appdata\local\temp\pip-install-xi0lxpdn\psutil\psutil\arch\windows\ntextapi.h(172): error C2011: '_SYSTEM_THREAD_INFORMATION': 'struct' type redefinition
    C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\winternl.h(286): note: see declaration of '_SYSTEM_THREAD_INFORMATION'
    c:\users\admin\appdata\local\temp\pip-install-xi0lxpdn\psutil\psutil\arch/windows/inet_ntop.h(10): warning C4028: formal parameter 2 different from declaration
    psutil/_psutil_windows.c(246): warning C4244: '=': conversion from 'float' to 'ULONGLONG', possible loss of data
    psutil/_psutil_windows.c(2810): error C2039: 'ContextSwitches': is not a member of '_SYSTEM_THREAD_INFORMATION'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\winternl.h(286): note: see declaration of '_SYSTEM_THREAD_INFORMATION'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

    ----------------------------------------
  Rolling back uninstall of psutil
Command "c:\users\admin\documents\github\ct-workflows\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-xi0lxpdn\\psutil\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Admin\AppData\Local\Temp\pip-record-znq068jg\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\admin\documents\github\ct-workflows\venv\include\site\python3.6\psutil" failed with error code 1 in C:\Users\Admin\AppData\Local\Temp\pip-install-xi0lxpdn\psutil\

**Comment by YashThenuan** [comment]
Still getting the issue

**Comment by giampaolo** [comment]
This issue is unrelated. Please open a new ticket.
