### ISSUE TITLE
ImportError: version conflict for psutil-5.0.1-cp36-cp36m-win_amd64.whl

### ISSUE THREAD

**Issue by csarn** [giampaolo/psutil#951]
When pip-installing psutil on Python 3.6 on Windows 7 64-bit, the psutil package cannot be imported:

>  C:> python -c "import psutil"
>  Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "E:\Py36\lib\site-packages\psutil\\\_\_init\_\_.py", line 218, in <module>
>     raise ImportError(msg)
> ImportError: version conflict: 'E:\\Py36\\lib\\site-packages\\psutil\\_psutil_windows.cp36-win_amd64.pyd' C extension module was built for another version of psutil (5.0.2 instead of 5.0.1); you may try to 'pip uninstall psutil', manually remove E:\Py36\lib\site-packages\psutil\_psutil_windows.cp36-win_amd64.pyd or clean the virtual env somehow, then reinstall

**Comment by giampaolo** [comment]
"you may try to 'pip uninstall psutil', manually remove E:\Py36\lib\site-packages\psutil_psutil_windows.cp36-win_amd64.pyd or clean the virtual env somehow, then reinstall"

have you tried this?

**Comment by csarn** [comment]
Yes I have. I also cleaned out the pip cache, so it downloaded the file again. The problem persists.

**Comment by ymeine** [comment]
In the meantime, the build at [Python Extension Packages for Windows - Christoph Gohlke](http://www.lfd.uci.edu/~gohlke/pythonlibs/#psutil) works fine.

**Comment by giampaolo** [comment]
It looks like this is a problem with your past installation. If no psutil is installed that error message shouldn't occur. You can test this by installing another psutil version as in "pip install psutil==5.0.0" in which case I expect the same error message. 
Please try to search "psutil" inside your Python installation and remove any occurrence (either file or directory).

**Comment by prokher** [comment]
I have exactly the same issue. Installing previous version with `pip install psutil==5.0.0` works fine, which I am going to proceed with as a workaround.

**Comment by csarn** [comment]
I tried it on a completely fresh windows 7 install, fresh python3.6, nothing installed or copied except win7, servicepack1, firefox, python. Even there the problem is the same, so this must be a problem in the wheel.

**Comment by giampaolo** [comment]
I tried now and I could install psutil via pip both with 32bit and 64bit versions of python 3.6. Really not sure what to think. :-\

**Comment by xoviat** [comment]
This also [seems to be happening][1] for us as well.

[1]: https://ci.appveyor.com/project/xoviat/pyinstaller/build/1.0.296/job/oo60225mkevh79h9#L836

**Comment by giampaolo** [comment]
Can you please try these wheels? They are from upcoming 5.1.0 version:
32 bit: https://ci.appveyor.com/project/giampaolo/psutil/build/1050/job/j4iv1dp8ioj5mwxf/artifacts
64 bit: https://ci.appveyor.com/project/giampaolo/psutil/build/1050/job/dv7gcgp7j9v2mtqb/artifacts

**Comment by xoviat** [comment]
The error only occurs on py36-x64, which I happen to be running. I can confirm that:

1. The pip version of psutil doesn't work on py36-x64.
2. The wheel that you provided for py36-x64 does work. 

Not sure about the 32-bit wheel, but that one wasn't broken in the first place.

**Comment by csarn** [comment]
I can second that. 64bit wheel for 5.1.0 fixes the import error.

**Comment by giampaolo** [comment]
OK, then for some reason the 5.0.1 wasn't properly built or something. I will release a 5.1.0 wheel version soon (possibly today).

**Comment by giampaolo** [comment]
OK, new version is out.
