### ISSUE TITLE
Process().username() return badly decoding character

### ISSUE THREAD

**Issue by PierreF** [giampaolo/psutil#964]
On a Windows 10 using French locale, I have wrong character on my username:
```
> python.exe -c "import psutil;print(psutil.Process().username())
MSEDGEWIN10\D�mo
```
In reality the user is named "Démo".

Call to user is also affected:
```
> python.exe -c "import psutil;print(psutil.users())
[suser(name='D�mo', ...
```

Version tested:
* Python 3.6.0 - amd64 (using official Python webinstaller)
* Python 3.6.0 - 32 bits (using embedded Python)

psutil version 5.0.1 from pypi (wheel, not built locally).

My current guess is that from my understanding of documentation of Microsoft, result from API are using a Windows code page (cp1252 in my case) and psutil decode using [Py_FileSystemDefaultEncoding](https://github.com/giampaolo/psutil/blob/5dfb92a434ef97bdf39895e76fcfaee6400adf9b/psutil/_psutil_windows.c#L1422) (utf-8 in my case).

**Comment by giampaolo** [comment]
The same issue should affect at least also `psutil.users()`.
