### ISSUE TITLE
as_dict does not return pure dicts

### ISSUE THREAD

**Issue by nmaas87** [giampaolo/psutil#967]
Hi there,

I recently started to use psutil - and it is awesome 👍.
Especially the as_dict function is very useful. I try to benchmark some functions and I call the as_dict, bound on the process before and after the function to get my measurements. As the as_dict returns a dict, I wanted to store it via dataset [dataset.readthedocs.io/en/latest/] in a inmemory sqlite database, so that I can write it to disk after the benchmark and do not interfere with the disk I/O. However, dataset only accepts true dicts, while as_dict gives back a dict with named_tuples nested in it (i.e. io_counters, memory_info, memory_full_info, etc) and lists (connections, open_files).
At the moment I am thinking of converting these named_tuples and lists into json so that this degraded dict becomes one which can be handled with sqlite / dataset. Is there anything planed to change the behavior of as_dict or would there be an better way of getting it into some compatible format as I described? :)

Thanks a lot!

**Comment by giampaolo** [comment]
Hello and thanks. I'm not sure what you suggest to return instead of namedtuples and lists.
namedtuples may be converted to raw tuples but lists? They really can't be replaced with anything else.
If dataset does not support lists and nametuples I suppose your only option is to store that data as a  JSON string.

**Comment by nmaas87** [comment]
@giampaolo Thanks for your commenct, I think you're right. Seems like there is then no other way. However, it would be great if you could add the information to the Documentation that certain information will be given as namedtuples or lists :)! Have a nice day :)
