### ISSUE TITLE
Windows - psutil.test() cpu_percent = 0

### ISSUE THREAD

**Issue by ladislashornok** [giampaolo/psutil#983]
Hi,

When I use psutil.test() in a windows cmd :

python -c "import psutil; psutil.test()"

the cpu_percent is always equal to zero.

If a start python : 

>>> import psutil
>>> psutil.test()

Then the cpu_percent values are right.

Python 2.7.10 / psutil version 5.1.3 / tested on Windows 10 and Windows 2008 R2 Standard

Thanks.

**Comment by giampaolo** [comment]
Yes, the CPU column is irrelevant (always shows 0%) because in order to get a meaningful value `cpu_percent` method would need more time. I added it in order to emulate `ps` command, which also shows a CPU% column of 0%. It probably makes sense to remove it.
