### ISSUE TITLE
Crash in `Process.open_files` when it times out

### ISSUE THREAD

**Issue by maxbelanger** [giampaolo/psutil#985]
We've observed that psutil can crash in a call to `DeleteFiber` when trying to clean up the `NtQueryObject` thread if it takes too long. This is reproducing primarily on recent versions of Windows (8.1, 10) when building using the Windows 8.1 SDK and manually inducing the call to `psutil_NtQueryObject` to time out by adding a breakpoint on `NtQueryObject`.

**Comment by giampaolo** [comment]
Isn't this what you fixed in https://github.com/giampaolo/psutil/pull/984 PR?

**Comment by maxbelanger** [comment]
Yep, realized I hadn't opened an issue and just sent a PR. Leaving this here in case there's ever a need for discussion.
