### ISSUE TITLE
Unable to get cpu temperature on Ubuntu 16.04

### ISSUE THREAD

**Issue by wavic** [giampaolo/psutil#990]
I am on Ubuntu-MATE 16.04, kernel 4.4.0-59-generic.
psutil.sensors_remperatures() gives me this:

```
>>> psutil.sensors_temperatures()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/psutil/__init__.py", line 2212, in sensors_temperatures
    rawdict = _psplatform.sensors_temperatures()
  File "/usr/local/lib/python3.5/dist-packages/psutil/_pslinux.py", line 1110, in sensors_temperatures
    current = float(cat(base + '_input')) / 1000.0
  File "/usr/local/lib/python3.5/dist-packages/psutil/_pslinux.py", line 299, in cat
    return f.read().strip()
OSError: [Errno 19] No such device
[Errno 19] No such device
```

**Comment by giampaolo** [comment]
Did you `sudo apt-get install lm-sensors`?

**Comment by wavic** [comment]
Yes, I did?

**Comment by giampaolo** [comment]
What's the output of `sensors` command?

**Comment by StevenMapes** [comment]
Ubuntu 16.04lts
Python 3.5.2
psutil 5.2.2

```
>>> import psutil
>>> psutil.sensors_temperatures()
{}

```

**Comment by giampaolo** [comment]
No I mean `sensors` command in the Linux shell.

**Comment by giampaolo** [comment]
This should have been fixed by now.

**Comment by wavic** [comment]
Well, it's a bit late but I have reinstalled the system because of other issues. It works now. This is what I get:
`{'acpitz': [shwtemp(label='', current=0.0, high=127.0, critical=127.0)],
 'coretemp': [shwtemp(label='Package id 0', current=56.0, high=84.0, critical=100.0),
  shwtemp(label='Core 0', current=56.0, high=84.0, critical=100.0),
  shwtemp(label='Core 1', current=53.0, high=84.0, critical=100.0),
  shwtemp(label='Core 2', current=53.0, high=84.0, critical=100.0),
  shwtemp(label='Core 3', current=50.0, high=84.0, critical=100.0)]}`

The OS is Arch Linux. Python 3.6.2
