### ISSUE TITLE
Command line interface to all those nice methods?

### ISSUE THREAD

**Issue by guettli** [giampaolo/psutil#995]
AFAIK psutil does not provide console_scripts up to now.

I think it would be great to provide a command line interface to all those nice methods.

Why not provide some command line tools based on psutil?

My concrete example: We have usernames which are longer than 8 characters.

The default linux `ps` tool cuts those names. But I want to see the whole name ....

There are several other things I would like to have, and all of them would be quite easy to implement using psutil.

What do you think?

**Comment by giampaolo** [comment]
I've thought about this but it's not easy to come up with a generic enough solution which satisfies me. One may want plain text output, or JSON or XML (for which we may add cmdline options as --xml or --json). Also, process info are one thing, system thing are another. The output should be parsable and consistent and I've never properly thought on how to do that but I'm open to suggestions.

**Comment by guettli** [comment]
My use case was this: Replacement for the command line tools like `top` and `ps`.

This means json/xml/proto-buf output is not my current use case.

**Comment by giampaolo** [comment]
Well, you can already do that:

```
~$ python -c "import psutil; print(psutil.Process(2354).name())"
python
~$ python -c "import psutil; print(psutil.Process(2354)).as_dict(['name', 'pid', 'ppid'])"
{'ppid': 2164, 'pid': 2354, 'name': 'python'}
```

...and if you want to be creative with serialization formats:

```
~$ python -c "import psutil, json; print(json.dumps(psutil.Process().as_dict(['name', 'pid', 'ppid'])))"
{"ppid": 2564, "pid": 9627, "name": "python"}
```

**Comment by giampaolo** [comment]
On a second though, my examples probably show that any effort into building a consistent command line parser is probably not worth the effort as the user can already "script" such kind of things with one liners in pure bash and choose the output format they want pretty easily.

It's probably more easy to just do something like this yourself by using `python -c "..."` than figure out how the psutil CLI interface works (arguments accepted etc).

**Comment by SethMichaelLarson** [comment]
This might even be a good chance to someone to build a whole new project. :) `psutil-cli`"

**Comment by giampaolo** [comment]
A separate `psutil-cli` project is indeed more intriguing. We could have different separate CLI tools implementing the most popular UNIX ones such as `psutil-ps`, `psutil-netstat`, `psutil-lsof` etc. The advantage would be that they would be 100% cross-platform both in terms of CLI parsers and text output.

**Comment by SethMichaelLarson** [comment]
@giampaolo I'd be willing to contribute to a project like that just as I am to `psutil`. :)

**Comment by giampaolo** [comment]
I don't know where it will land but I just felt like creating a new repo =)
https://github.com/giampaolo/psutil-cli

**Comment by SethMichaelLarson** [comment]
Haha sounds good to me! :) I'll take a look when I get time and help if needed.

**Comment by guettli** [comment]
Thanks - the licence looks good :-)
